### ISSUE TITLE
A valid React element (or null) must be returned.

### ISSUE THREAD

**Issue by jaydreyer** [gregnb/mui-datatables#1]
## Config
```         
 <MUIDataTable
            title={'API Catalog'}
            data={tableData}
            columns={tableColumns}
            options={tableOptions}
          />
```

## Issue
I've got a bare bones example running and I keep getting an error saying `t.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

I've just got the data set up as an array of arrays, and options are basically nothing. Some of the table control appears for a few seconds before switching to a browser error page. No idea what's happening.

## Your Environment

| Tech         | Version |
|--------------|---------|
| mui-datatables  |    latest     |
| node        |   6.11      |
| OS      |   High Sierra      |
| react | 15.6 |

**Comment by gregnb** [comment]
Would you mind putting up a sandbox? For example:
https://codesandbox.io/s/wy2rl1nyzl

**Comment by jaydreyer** [comment]
That's going to be tough to do because it's part of a larger app. I can paste the page code in there if it would help. Basically, when I have 
```
            <MUIDataTable
              title={'API Catalog'}
              data={tableData}
              columns={tableColumns}
              options={tableOptions}
            />
```
in the code, I get the error. If I comment it out, things work fine (other than I have no data table).

**Comment by jaydreyer** [comment]
What I really don't get is the rest of the table component seems to show up. You can see the title, and if you click the download icon, it will download a csv with the dummy data I used. It also says '1-2 of 2', which is correct, as well.

<img width="1019" alt="screen shot 2018-01-25 at thursday january 25 2018 3 04 18 pm" src="https://user-images.githubusercontent.com/1815281/35412221-1a79b5d0-01e1-11e8-8db8-624f9d45af92.png">

**Comment by jaydreyer** [comment]
Last thing I can think of, we are using material-ui 1.0.0-beta.27. I don't know if that would cause an issue.

**Comment by gregnb** [comment]
Could you paste the data you use to populate the table ?  Feel free to remove any sensitive data

**Comment by jaydreyer** [comment]
```
const tableColumns = ['API', 'Lifecycle Status', 'API Type', 'Owner']

const tableData = [['loading', 'loading', 'loading', 'loading'], ['loading', 'loading', 'loading', 'loading']]
```

**Comment by gregnb** [comment]
Ok great,  thanks! I'll look into this tonight

**Comment by gregnb** [comment]
So I played around with this a bit tonight and I am able to replicate your error. A quick fix around this is to upgrade to react and react-dom 16 and above. Is that something you can change in your current project?

I'll still look into what causes issues for 15.6 but will need time

**Comment by jaydreyer** [comment]
Thanks for checking. I'm not sure about being able to upgrade. I'll have to investigate and see if that causes any other issues for us. Thanks!

**Comment by gregnb** [comment]
I tried working this out some more but it will not go. As a result I set the peerDependencies to be minimum 16 and above for React. Just does not work well otherwise. Sorry for the inconvenience

**Comment by jaydreyer** [comment]
OK. Bummer. We'll look into migrating to react 16 or I'll keep looking for a datagrid controller. Yours is good! Thanks for investigating.
