### ISSUE TITLE
How to disable 'Sort' tooltip / hint?

### ISSUE THREAD

**Issue by andygock** [gregnb/mui-datatables#1001]
Hi

Is there a way to disable the tool tip / hint on the column header which says 'Sort' without actually disabling sorting functionality.

When I use column option `{ hint: 'My Tooltip' }`, this tooltip in addition to the"Sort' tooltip is displayed in an overlapping fashion causing one of them to not be readable.

It would be good if I can make only the custom tooltip be shown without 'Sort' covering it up.

Thanks.

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.5.0      |
| MUI-datatables  |    2.12.0     |
| React        |   16.10.2      |
| browser      |   Firefox  69.0.2   |

**Comment by gabrielliwerant** [comment]
Hm, sounds like it might be a material-ui v4 bug. Can you confirm if this happens in material-ui v3? If not, I'd much rather fix the behavior than add a new option. They should ever overlap. The way it works for me now with material-ui v3 is that they show/hide based on where your cursor is so that they never overlap.

**Comment by andygock** [comment]
@gabrielliwerant 

Can verify overlaps in Material-UI 4.x but not in 3.x

Codesandboxes:

- [with Material-UI 3.9.0](https://codesandbox.io/s/mui-390mui-datatables-2120-rs4mi) - expected behaviour
- [with Material-UI 4.5.0](https://codesandbox.io/s/mui-450mui-datatables-2120-jlgf3) - overlapping tooltips

**Comment by gabrielliwerant** [comment]
@andygock Thanks for your help in reproducing this. I was able to confirm with your examples. I have a fix up as a PR.

**Comment by andygock** [comment]
Great, thanks @gabrielliwerant

**Comment by Way-U-Need** [comment]
any update?

**Comment by yeahoffline** [comment]
so any way to disable the sort tooltip?

**Comment by andygock** [comment]
Any updates on this?

This is still an issue [with latest releases Material-UI 4.7.0 and mui-datatables 2.13.1](https://codesandbox.io/s/mui-470mui-datatables-2131-wd4iq)

**Comment by yuriy-voypost** [comment]
Hi! Is there are some updates on this issue?

**Comment by gabrielliwerant** [comment]
Sorry for the delay. Fix should now be in `2.13.3`.

**Comment by Boultak** [comment]
Hi,
Is there a way to display a custom tooltip with { hint : "my tooltip" } instead of displaying "sort" even if sorting is enabled ?

**Comment by willym74** [comment]
Hi! Put the following to your MUIDataTable options:
```javascript
const options: MUIDataTableOptions = { 
    textLabels: {
        body: {
            columnHeaderTooltip: (column: MUIDataTableColumn) => functionThatGivesYouTheRightTooltip(column)
        }
    }
};
```
Best regards,
Willy
