### ISSUE TITLE
Add an option to set row header

### ISSUE THREAD

**Issue by supakitk** [gregnb/mui-datatables#1002]
We want to request a functionality to have an option to set a column to be a row header and render <th> instead of <td> for the row header column (please see https://www.w3.org/TR/2008/NOTE-WCAG20-TECHS-20081211/H51.html)

**Comment by gabrielliwerant** [comment]
Not totally sure I follow. If you're looking to have a specific feature that fundamentally alters the display of the table, you should be able to get most of what you need out of existing custom render functions like `customRowRender` and `customBodyRender`. But fundamentally, this library is built on material-ui and the material standards set forth by Google and I don't have any plans to support totally different table formats.

**Comment by supakitk** [comment]
Thank you for the quick response. I can probably use customRowRender as a workaround.
