### ISSUE TITLE
scrollFullHeight behavior (when scrolling down) of v2.10.0 is not preserve on newer versions

### ISSUE THREAD

**Issue by kenjoegolo** [gregnb/mui-datatables#1007]
I like the srolling behavior of `v2.10.0` with option `responsive: scrollFullHeight` - when you have more rows that overlaps the page height and when scrolling down, the header will become positioned fixed at the top of the page, see codesandbox: https://codesandbox.io/s/mutable-wildflower-wv99g

but on the newer versions or latest with option `responsive: scrollFullHeight` the scrolling behavior was removed, see codesandbox: https://codesandbox.io/s/sleepy-chatelet-8yqyy

Can you help me achieve the scrolling behavior of `v2.10.0` on latest version using option `responsive: scrollFullHeight`?

I know there is another option `responsive: scrollMaxHeight`, but it has an issue with printing - it doesn't print all rows of the current table page.

**Comment by gabrielliwerant** [comment]
You're right, that behavior should have remained in `scrollFullHeight` unless `fixedHeader` is set to `false`. Will add a fix.
