### ISSUE TITLE
Current page is remembered when data is changed

### ISSUE THREAD

**Issue by LusineGasparyan98** [gregnb/mui-datatables#1020]
## Expected Behavior
If data is changed in the table and it is too much that includes also current page, it should update the table instead of just changing inner data

## Current Behavior
   If we are not on the first page, data changes and the new one includes the current page as well, the table is not refreshed and we stay on the same page as we were before and only inner data is changing.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.4.0      |
| MUI-datatables  |   2,12,3 |
| React        |   16,9,0   |
| browser      |  Chrome       |

**Comment by gabrielliwerant** [comment]
I need a little help understanding this one. If you have 100 rows, 10 rows per page, are on page 1, and you increase the amount of data in the table, what are you looking to have happen to your current page exactly?

**Comment by LusineGasparyan98** [comment]
In that case, I am looking to see the first page with updated data. But if I am not on the first page, for example I am on the second or fourth page, and my data is updated I am looking to see the first page as the current page because maybe data is not only increasing but also is changing. For example, this can happen if we are not on the first page and are searching for something.

**Comment by gabrielliwerant** [comment]
I think this is behavior that you will need to customize for yourself, as it seems to fall under server side  behavior, for which the table can't predict the desired UX. For example, if you increase the data by enough that it would add multiple new pages of content, would you want to see the first new page or the last new page? Both could be valid answers depending on what you want.

 So, you have access to the `page` value in the table options, and you can change this value dynamically when you receive new data to determine which page should be showing.
