### ISSUE TITLE
Responsive width

### ISSUE THREAD

**Issue by joziahg** [gregnb/mui-datatables#1026]
Hey all, running into an issue with wide tables.

## Expected Behavior

I would expect wide tables to scroll within when the amount of columns surpasses the width of the visible screen area
## Current Behavior

Currently it just makes the table wider so the toolbar and pagination functions get hidden.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  | 4.5.1 |
| MUI-datatables  | 2.12.0         |
| React        | 16.10.2        |
| browser      |   firefox 69.0.3     |
| etc          |         |

**Comment by gabrielliwerant** [comment]
Can you provide the options you are using and the exact screen dimensions, etc, so that the issue can be reproduced?

**Comment by joziahg** [comment]
Here is my options, I am also going to update my package to see if that resolves the issue:
```javascript
  const options = {
    rowsPerPage: 10,
    rowsPerPageOptions: [5, 10, tableData.length],
    print: false,
    fixedHeader: true,
    selectableRows: 'none',
    downloadOptions: {
      filename: `${format(new Date(), 'P')}.csv`,
      separator: ','
    },
    responsive: 'scrollMaxHeight',
    onDownload: (buildHead, buildBody, columns, rows) => {
      return (
        buildHead(columns) +
        buildBody(rows.map((row, index) => ({ index, data: row.data.map(data => typeof (data) === 'object' ? data.alias : data) })))
      )
    }
  }
```

**Comment by gabrielliwerant** [comment]
It works on my end. Let me know if upgrading to the latest version helps.

**Comment by joziahg** [comment]
Upgraded version, didn't help. I am also having troubles reproducing the issue in codesandbox. All my tables that are super wide have this issue in my project. Ill pull together some screenshots.

**Comment by joziahg** [comment]
Here is some screenshots, the first is normal behaviour and the second is when there are many columns. Both were captured using the firefox screenshot feature which allows you to capture everything on the page, not just that which is visible, so you can see how the table goes behind the drawer component and seems to stretch the parent div.

![Screenshot_2019-10-22 BBQ - physics Seminar - Overview](https://user-images.githubusercontent.com/14083884/67331906-fa8fea80-f4e3-11e9-8141-c36835e0091a.png)
![Screenshot_2019-10-22 BBQ - English 11-12 Seminar - Overview](https://user-images.githubusercontent.com/14083884/67331948-0a0f3380-f4e4-11e9-943b-73246ed7a616.png)

**Comment by gabrielliwerant** [comment]
You've got a lot going on and I'm not exactly sure what you're trying to do, so it's really difficult to tell if this is a problem with the library, or just a complication due to all the customizations you've got.

Below is a gif I took of the `simple` table in the examples that I modified to use excess columns and the `scrollMaxHeight` responsive option:
![capture](https://user-images.githubusercontent.com/1779564/67336531-7fcecb80-f4f3-11e9-92d7-c3aeb2117a3e.gif)

I think what you've need to do is start from a simple example like that, and then add to it bit by bit until something breaks. As it stands, I'm not even sure there's a bug.

**Comment by gabrielliwerant** [comment]
Also, do you still have the same issue if you reduce material ui version to v3?

**Comment by joziahg** [comment]
When I was trying to reproduce the issue in code sandbox it had MUI 4.5.1 so that shouldn't be an issue, not to mention I'd have to refactor quite a bit of code to get it downgraded. The table itself is pretty simple, the columns are generated and have custom body renders if that changes anything.

**Comment by joziahg** [comment]
I figured it out, my app is wrapped in a div with display: 'flex' which allows the drawer to work, but breaks the table.
https://codesandbox.io/s/muidatatables-custom-component-example-mv8p0?fontsize=14

**Comment by gabrielliwerant** [comment]
Glad you got it sorted!

I wasn't suggesting you abandon material v4 permanently, just trying to determine if it's a breaking issue between the versions, as I'm trying to make sure I catch any of those for the next major version of this library.

All good to close this out?

**Comment by joziahg** [comment]
Well, I still need the flex div so the drawer works. Ill keep working on a workaround on my end, but it might be worth it to make MUI-datatables X overflow work inside a flex div. I haven't taken a look at the source code in regards to this yet so I can't say for sure what a fix might look like. I'd be willing to work on this but might need some guidance on where to look in the source. Let me know what you think.

**Comment by gabrielliwerant** [comment]
@joziahg I'm open to potential enhancements, but I'm not sure that flexbox plays nicely with table layouts. They are fundamentally different in what they're attempting to do as far as display. Also, drawers aren't typically used to hide table views. I'm a bit wary of potentially breaking layout to make something work in a situation that isn't recommended by material, given that this is a material-based project.

**Comment by joziahg** [comment]
The drawer is static, it isn't hiding anything. Either way thanks for the help.

**Comment by joziahg** [comment]
To be clear the Table is not the direct child of the flex div and the drawer is static and doesn't hide anything. The table resides in the content component and is set to display block.

This is the documentation for the drawer, anyone following this page would run into this issue.
https://material-ui.com/components/drawers/#full-height-navigation

**Comment by joziahg** [comment]
I've found a workaround, by using the same trick mui does on their persistent drawers example. I set the width of the content div to be 100% - the drawers width.
```javascript
style: {
  content: {
    width: `calc(100% - ${drawerWidth}px)`
  }
}
```

**Comment by gabrielliwerant** [comment]
I experimented briefly with nesting a large table inside a temporary drawer, and it appears to me that the main culprit is `position: fixed` in the main drawer container.

![capture](https://user-images.githubusercontent.com/1779564/67438985-056d7c80-f5c3-11e9-8f57-59e10ffe455a.gif)

So maybe that will also help you.

However, you might run into issues if you override that because I believe drawers are supposed to have fixed positions. So it seems like a problem outside of this library, but I can re-open if it proves to be otherwise.
