### ISSUE TITLE
searchPlaceholder option not working.

### ISSUE THREAD

**Issue by LavanyaRanganath** [gregnb/mui-datatables#1027]
searchPlaceholder option not working.

**Comment by gabrielliwerant** [comment]
It works on my end, and in the example in the library, so I'll need the exact steps to reproduce your issue, along with any relevant code and table options in order to look into this.

**Comment by LavanyaRanganath** [comment]
Below are the options I am using for MUIDataTable.All the options other than searchPlaceholder is working for me.
<MUIDataTable
              title="Install Base"
              columns={columns}
              data={dataForTable}
              options={{
                selectableRows: 'none',
                download: false,
                print: false,
                rowsPerPage: 100,
                filter: false,
                viewColumns: false,
                searchPlaceholder: 'This is a search placeholder',
}}

**Comment by LavanyaRanganath** [comment]
I tried checking if its working in the following sandbox link - https://codesandbox.io/s/muidatatables-custom-component-example-o8fl3. its not working

**Comment by gabrielliwerant** [comment]
Your versions of this library and the material-ui library are too low. If you use material ui >= v3 and the latest version of this library, it will work.

**Comment by LavanyaRanganath** [comment]
Got it fixed :) you were right with versions. Thank you so much!
