### ISSUE TITLE
Update to @material-ui/icons v2.0.0 

### ISSUE THREAD

**Issue by jkeruzec** [gregnb/mui-datatables#103]
Can you provide support for updated material-ui/icons V2.0.0 ?

`Module not found: Can't resolve '@material-ui/icons/FileDownload' `

**Comment by gregnb** [comment]
Resolved thanks to @terenced I will be doing a release later tonight

**Comment by kalyan542** [comment]
The same issue is coming in "@material-ui/icons": "^3.0.2"

**Comment by LeoLozes** [comment]
I don't really understand the release process of this project, because the releases and tags listed in github are not in line with the releases in npm. Anyway. I lost one hour trying to figure out this one. 
It seems that the last version released in npm is the `2.0.0-beta-55`, except it's not the source of the master branch, hence the FileDowload import that hasn't been there for months. So I recommend using the version `2.0.0-beta-54` which looks like the source matches the version.

Thanks for that.

**Comment by gregnb** [comment]
@LeoLozes First off, watch your tone. This is a free project if you don't like it you can totally leave Bud. 

As for this issue with FileDownload there is no import of it in either -54 or -55 release so what are you even talking about?

**Comment by LeoLozes** [comment]
You are right about my tone, I'm sorry, I spent way too much time on this one this morning. 

BTW something must have been wrong with the version 55 because it has been pulled out npm when I was trying to document this issue properly:

```
npm ERR! No compatible version found: mui-datatables@2.0.0-beta-55
npm ERR! Valid install targets:
npm ERR! 2.0.0-beta-9, 2.0.0-beta-8, 2.0.0-beta-7, 2.0.0-beta-6, 2.0.0-beta-54, 2.0.0-beta-53, 2.0.0-beta-52, 2.0.0-beta-51, 2.0.0-beta-50, 2.0.0-beta-5, 2.0.0-beta-49, 2.0.0-beta-48, 2.0.0-beta-47, 2.0.0-beta-46, 2.0.0-beta-45, 2.0.0-beta-44, 2.0.0-beta-43, 2.0.0-beta-42, 2.0.0-beta-41, 2.0.0-beta-40, 2.0.0-beta-4, 2.0.0-beta-39, 2.0.0-beta-38, 2.0.0-beta-37, 2.0.0-beta-36, 2.0.0-beta-35, 2.0.0-beta-34, 2.0.0-beta-33, 2.0.0-beta-32, 2.0.0-beta-31, 2.0.0-beta-30, 2.0.0-beta-3, 2.0.0-beta-29, 2.0.0-beta-28, 2.0.0-beta-27, 2.0.0-beta-26, 2.0.0-beta-25, 2.0.0-beta-24, 2.0.0-beta-23, 2.0.0-beta-22, 2.0.0-beta-21, 2.0.0-beta-20, 2.0.0-beta-2, 2.0.0-beta-19, 2.0.0-beta-18, 2.0.0-beta-17, 2.0.0-beta-16, 2.0.0-beta-15, 2.0.0-beta-14, 2.0.0-beta-13, 2.0.0-beta-12, 2.0.0-beta-11, 2.0.0-beta-1, 2.0.0-beta.55, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.9, 1.0.8, 1.0.7, 1.0.6, 1.0.5, 1.0.4, 1.0.2, 1.0.1, 1.0.0
```
I appreciate your work and thank you for it.

**Comment by gregnb** [comment]
I have made a change for it to properly follow semver after someone pointed out it was incorrect. Try this

```
npm install mui-datatables@2.0.0-beta.55
```

**Comment by lShinal** [comment]
I have the same problem after 
 : Can't resolve '@material-ui/icons/Check'
