### ISSUE TITLE
Render Filter with customBodyRender

### ISSUE THREAD

**Issue by svensq** [gregnb/mui-datatables#1030]
## Expected Behavior
Render Filter-Values with customBodyRender

## Current Behavior
If the column is a object the Filter shows [object Object] and not the customBodyRender return.

I have to try it with the custom filter option, but i do not get the filterdata to display the select options.

I think to a solution like that: 
```
{filterData[index].map((filterValue, filterIndex) => (
              <MenuItem value={filterValue} key={filterIndex + 1}>
{column.customBodyRender ? (column.customBodyRender(filterValue)): 
                (<React.Fragment>{filterValue != null ? filterValue.toString() : ''}</React.Fragment>)}
              </MenuItem>
            ))}
```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.5.1      |
| MUI-datatables  |    2.12.1     |
| React        |   16.11      |

**Comment by gabrielliwerant** [comment]
Hello @svensq. I think I need more information about what you're trying to accomplish on my end. Can you demonstrate the bug, if there is one, in a codesandbox?

**Comment by svensq** [comment]
Sorry, I have found my mistake now. I return a Component by customBodyRender. Thank you.
