### ISSUE TITLE
Wrong CSV values in columns which have `customBodyRender` option

### ISSUE THREAD

**Issue by bkiac** [gregnb/mui-datatables#1033]
Downloaded CSV file has wrong values in columns which have `customBodyRender` if the table is filtered.

## Expected Behavior

This table view
![image](https://user-images.githubusercontent.com/24522620/67559517-68712780-f719-11e9-83e2-4522f97a75fa.png)
should result in this CSV
```csv
"Name","Title","Location","Age","Salary"
"Gabby George","Business Analyst","Minneapolis","30","$100,000"
"Franky Rees","Business Analyst","St. Petersburg","22","$50,000"
"Robin Duncan","Business Analyst","Los Angeles","20","$77,000"
"Brynn Robbins","Business Analyst","Norfolk","22","$90,000"
"Jesse Hall","Business Analyst","Baltimore","44","$99,000"
```

## Current Behavior

but the actual CSV is
```csv
"Name","Title","Location","Age","Salary"
"Gabby George","Business Analyst","Minneapolis","30","$100,000"
"Aiden Lloyd","Business Analyst","St. Petersburg","22","$50,000"
"Jaden Collins","Business Analyst","Los Angeles","20","$77,000"
"Franky Rees","Business Analyst","Norfolk","22","$90,000"
"Aaren Rose","Business Analyst","Baltimore","44","$99,000"
```
These values correspond to the first 5 rows of the unfiltered table data.

## Steps to Reproduce (for bugs)

https://codesandbox.io/s/muidatatables-wrong-download-values-if-column-has-custombodyrender-3jtsx
1. Click "Download CSV"
1. Observe the invalid values in the downloaded file
2. Remove `customBodyRender` option by replacing this column definition
    ```javascript
    {
      name: "Name",
      options: { customBodyRender: value => <span>{value}</span> }
    },
    ```
    with
    ```javascript
    "Name"
    ```
3. Click "Download CSV"
1. Observe the correct values in the downloaded file

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  4.5.1       |
| MUI-datatables  |  2.12.3       |
| React        |   16.11.0      |

**Comment by gabrielliwerant** [comment]
Verified, thank you for the detailed report! I have a fix locally, will push soon and probably release a patch today.
