### ISSUE TITLE
How to change action icons

### ISSUE THREAD

**Issue by zilkenberg22** [gregnb/mui-datatables#1048]
How to change action icons 

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.3.3     |
| MUI-datatables  |   2.10.3      |
| React        |  16.9.0       |
| browser      |    google Chrome     |
| etc          |         |

**Comment by gabrielliwerant** [comment]
Unless you specify all your own actions via `customToolbar`, there isn't yet a way to do it. I'm open to proposals for how to do so here https://github.com/gregnb/mui-datatables/issues/198.

**Comment by BjoernRave** [comment]
@gabrielliwerant if I would create a custom toolbar, is there a way to get access to the download, filter etc. functionality ? Meaning can I create my own button and pass it an onClick handler to download the csv?

**Comment by gabrielliwerant** [comment]
@BjoernRave Unfortunately, individual functions and components aren't importable on their own at the moment, but I'm open to PRs that would provide this functionality.
