### ISSUE TITLE
Pagination row exceeds table bounds on mobile

### ISSUE THREAD

**Issue by joshwaiam** [gregnb/mui-datatables#1049]
On mobile devices, the pagination row in the footer of the table exceeds the bounds.  The left and right arrows in particular are what actually break out of the right edge of the table.

This appears to be happening because of a 24px padding applied to the last-child in MUIDataTablePagination.  I was able to fix this in my project by applying an override to the element, but it would be great to not need to create an override for this!

```typescript
              <ThemeProvider
                theme={{
                  overrides: {
                    MUIDataTablePagination: {
                      root: {
                        "&:last-child": {
                          padding: 0
                        }
                      }
                    }
                  }
                }}
              >
```

**Comment by joshwaiam** [comment]
I should have said thank you for you and your team's efforts and work on this project.  I have used it in many projects and thank you all for this wonderful tool and your continued commitment to refining and improving it!

**Comment by gabrielliwerant** [comment]
Haha, thanks @joshwaiam! Team of 1 at the moment, but much appreciated.

I would be open to a PR that addresses this at the proper responsive breakpoints. Let me know if you're interested and I can assign you!

**Comment by joshwaiam** [comment]
I would love to try and help with this!  I've been a coder/tinkerer half my life, but plagued by doubt.  I've been wanting to contribute to a project, but I'm been scared because I've never done it!  This seems like as good a time as any to take a swing!

**Comment by gabrielliwerant** [comment]
That's great @joshwaiam, and I agree I think this is a great opportunity to get your feet wet! Don't worry, we all start out that way, and I'm glad to help you through it if need be. Let me know if you'd like me to start you off by pointing you in the right direction, or if you wanted to tinker around on your own first; I'm good with either.

**Comment by joshwaiam** [comment]
I appreciate your willingness to help!  I'll take a crack at it and see what I can do before taking your time on it!

**Comment by joshwaiam** [comment]
Sorry for everyone's time on this.  I thought I did a good amount of testing before reporting this, but it must have been something on my end as two new projects do not replicate the issue.  Thank you for taking the time to respond and guide me, and apologies for any wasted effort on your part!
