### ISSUE TITLE
Hide Filter Icon

### ISSUE THREAD

**Issue by PratyushaTN** [gregnb/mui-datatables#1050]
Is there an option to hide/remove the Filter Icon on the top right of the MuiDatatable

## Expected Behavior
Would like to remove/hide the Filter icon from MUIDatatable options.

## Current Behavior
Currently I have 3 icons displayed on the MUIDatatable Filter, Search and Columns. I tried setting the option to false and also removing the option for the Filter Icon.

But the icon is still displayed.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     0.20.2    |
| MUI-datatables  | 2.0.0-beta.58        |
| React        |   16.8.2      |
| browser      |     any    |

**Comment by gabrielliwerant** [comment]
This should be the option you want

![image](https://user-images.githubusercontent.com/1779564/68163439-83694600-ff28-11e9-9adf-18fac9f5d2a5.png)

however, you will need to be on a version of the library that has support for this option, so check the release notes and/or tags to find out what version you need.

**Comment by PratyushaTN** [comment]
Thank you..This works.
