### ISSUE TITLE
Error to download CSV when change columns visibility

### ISSUE THREAD

**Issue by rubenp9** [gregnb/mui-datatables#1052]
Hi,
I think I found a bug.

Steps to reproduce it:
1. Hide one column.
2. Download the csv file. (first time it works without problem and csv file is ok)
3. Download the csv file again. (file downloaded has displayed header columns ok, but the body of the table has a column less).
4. Download the csv file again.  (file downloaded has displayed header columns ok, but the body of the table has two columns less).
5. Etc (if you repeat the last step you will have a column less every time)

Here you can see how it works:
https://codesandbox.io/s/priceless-lamarr-zfezb?fontsize=14

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.9.3     |
| MUI-datatables  |    2.9.0     |
| React        |    16.8.6     |

**Comment by gabrielliwerant** [comment]
Hello @rubenp9. I was unable to reproduce from the steps given. I will probably need to see what your options are, or the codesandbox example. The example you posted here just looks like this for me:

![image](https://user-images.githubusercontent.com/1779564/68229069-89ad0000-ffc4-11e9-9e23-6a1df754097c.png)

**Comment by rubenp9** [comment]
Ups, I think y shared a wrong link, sorry. It is fixed now.

**Comment by rubenp9** [comment]
> Hello @rubenp9. I was unable to reproduce from the steps given. I will probably need to see what your options are, or the codesandbox example. The example you posted here just looks like this for me:
> 
> ![image](https://user-images.githubusercontent.com/1779564/68229069-89ad0000-ffc4-11e9-9e23-6a1df754097c.png)

**Comment by gabrielliwerant** [comment]
@rubenp9 I can confirm now, thank you for updating the example!
