### ISSUE TITLE
SortDirection Type is missing 'none'

### ISSUE THREAD

**Issue by BjoernRave** [gregnb/mui-datatables#1061]
The type `SortDirection` , which you apply to `sortDirection` to the `options` object of every column does not accept the `'none'` option

**Comment by gabrielliwerant** [comment]
Hello @BjoernRave. Can you provide a codesandbox example that demonstrates the issue so that I can reproduce it?

**Comment by HumayounBaig** [comment]
![image](https://user-images.githubusercontent.com/32910163/72047015-6b70c280-32db-11ea-906e-810d67e48ca9.png)
this is the error i am getting when trying to use sortDirection on multiple columns to conditionally change sorting of data.

**Comment by gabrielliwerant** [comment]
@HumayounBaig, you can't have more than one sort direction set at a time, so you have to switch the others to 'none'. See the `serverside-sorting` example for demonstrations of how to change the sort directions dynamically.

I'm closing this issue as it has received no follow up and yours sounds like a separate thing. If you think you've found a bug after trying the method in `serverside-sorting`, feel free to open a new issue with steps to reproduce and codesandbox example.
