### ISSUE TITLE
onRowsSelect doesn't work with useState

### ISSUE THREAD

**Issue by W3ND31** [gregnb/mui-datatables#1070]
**Expected Behavior**
the selected rows should stay checked

**Current Behavior**
When useState is called, the checkboxes even don't keep checked

**Steps to Reproduce**
1- https://codesandbox.io/s/cool-surf-bqxg0
2-Click on checkbox

Tech | Version
-- | --
Material-UI | 4.6.1
MUI-datatables | 2.12.4
React | 16.12.0
browser | Chrome
etc

Similar issue on https://github.com/gregnb/mui-datatables/issues/191

**Comment by gabrielliwerant** [comment]
Hey @W3ND31 so there are a few problems with the approach. For one, it's difficult to override the existing selection behavior using `onRowsSelect`, assuming that's your goal, as this function only fires after the internal state that manages selections has already been updated. So what you'd need to do is use `rowsSelected` from the options to track which rows you want selected, update that array in `onRowsSelect`, and then make sure that the table re-renders with the new values. As it stands, even if you were using `rowsSelected`, I think the value would be re-initialized on re-render, so you might need to use lifecycle hooks to make sure side effects propagate.

**Comment by W3ND31** [comment]
> Hey @W3ND31 so there are a few problems with the approach. For one, it's difficult to override the existing selection behavior using `onRowsSelect`, assuming that's your goal, as this function only fires after the internal state that manages selections has already been updated. So what you'd need to do is use `rowsSelected` from the options to track which rows you want selected, update that array in `onRowsSelect`, and then make sure that the table re-renders with the new values. As it stands, even if you were using `rowsSelected`, I think the value would be re-initialized on re-render, so you might need to use lifecycle hooks to make sure side effects propagate.

Man, thx for the reply! I took the "rowsSelected" way and achieved my goal! 
Thx again!
