### ISSUE TITLE
without checkbox in table

### ISSUE THREAD

**Issue by venkatesh950** [gregnb/mui-datatables#1072]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by venkatesh950** [comment]
i want the table without checkbox

**Comment by ebadilla10** [comment]
Did you get any solution?
