### ISSUE TITLE
Custom Row/Footer

### ISSUE THREAD

**Issue by usotnyk** [gregnb/mui-datatables#108]
Question:

Is it possible to add a custom footer to a datatable? At the bottom of a datatable I need to add a row with "Totals" that needs to be fixed (always be visible on every page even when pagination is on), but not be filterable/sortable. I've tried creating a separate datatable component below the main table (and styling it to look as part of the main table), but there is a scrolling issue in responsive: when the main table is scrolled horizontally, last row is not scrolled with it - so not a good UI experience. Any suggestions on how it can be achieved?

This is what I need:
![image](https://user-images.githubusercontent.com/22330666/43293418-2d86659a-9108-11e8-886e-36a89f59a62e.png)

Thanks!

**Comment by jkeruzec** [comment]
Why not create a special row added at the end of data in which you will add some computation, maybe add some style to it also

**Comment by usotnyk** [comment]
@jkeruzec, that was my first solution and until a user starts interacting with the table, it looks as per the mockup. However, with this solution, when a user wants to filter or sort the table, it fails. Ex: a user wants to filter by "Site" -> in the dropdown of filters by site there will now be 3 options: "Red Apple", "The Bargain Shop" and... "Total", which makes no sense. Sorting columns presents similar issues. So I need to either disable  sorting and filtering in this table or make my totals a separate table all together (in this case, as I outlined above, I run into scrolling issue - two tables scroll separately on mobile).

Thank you for the suggestion though!

**Comment by gregnb** [comment]
I have a PR that should be merged shortly after some further testing that will allow you to override the current table footer (pagination) with a custom one.  This will obviously overwrite the pagination but should allow you to do anything.

**Comment by usotnyk** [comment]
That's awesome! I'm looking forward to using this enhancement in my project. Thank you!

**Comment by gregnb** [comment]
Ok published `2.0.0-beta-18` give it a shot

**Comment by gregnb** [comment]
@usotnyk DId it work out for you?

**Comment by usotnyk** [comment]
@gregnb, I did not have a chance to try it yet. We found a temporary work around for the existing datatable I had (disabled filtering and sorting) for the time being. I will however, use your enhancements for a few other tables I will start building next.

**Comment by gregnb** [comment]
Ok no worries. I will close the issue for now. Thanks

**Comment by ProjectCheshire** [comment]
@gregnb is it possible to access the table data from the footer? Because it is declared in the options,and it seems I dont have the rowData/tableMeta yet, i can't show/hide footer cells in correlation with their column indices, or take advantage of the responsive styles. My needs are exactly the same as usotnyk, essentially a fixed, non sortable, non filteralbe rowset, but that has the context of the current table state.

**Comment by iKrushYou** [comment]
I'm looking to do just this -- the footer row holding all the totals

The jquery datatable has this option (and the big thing is that it scrolls with the table if it overflows X) and it seems like this custom footer option might require a lot of custom coding in order to achieve the same

**Comment by jukakoski** [comment]
Hi! I started to fork this repo to get this feature. First idea was to get only the totals, but I decided to develop it further by adding d3.js to get more detailed stats. Also stats to select are optional for every column. There is still som todo's e.g checking if some stats are valid for string columns.

You can find preview video from this link.
https://www.youtube.com/watch?v=3XefVyYv784

I will PR this feature as finished. I had to modify some core features to be able to pass data and column width references to stats footer.

**Comment by estyh** [comment]
@jukakoski That's incredible, just what I need. Do you have code you are willing to share?
