### ISSUE TITLE
customFilterListOptions not working as expected

### ISSUE THREAD

**Issue by ertw** [gregnb/mui-datatables#1080]
Should the `customFilterListOptions` option transform both the checkbox label and the chip label when I use it with `filterType: 'checkbox'`?

I would like to use the `checkbox` filter, and rename both the checkbox and chip labels. I'm not finding much documentation on how this is supposed to work, so I could very well be doing it wrong. I am currently able to customize the chip labels with `customFilterListRender`, but am not able to customize the checkbox labels. [Per the documentation, `customFilterListRender` is deprecated for `customFilterListOptions`](https://github.com/gregnb/mui-datatables/blob/master/README.md), so I am trying to get this working with `customFilterListOptions`.

## Expected Behavior
I expect both the checkbox and chip labels to be tansformed, instead of printing the original string from data object.

## Current Behavior
The chip and checkbox labels are not transformed.

## Steps to Reproduce (for bugs)

1. Add `customFilterListOptions` object with function on render key that should transform the text: 

```
  const options = {
    filterType: "checkbox" as FilterType,
    customFilterListOptions: {
      render: (v: Title) => {
        return `Title: ${v}`;
      }
    }
  };
```

Reproduction example:
https://codesandbox.io/s/charming-raman-ro3d0

In this example, I would expect to see `Title: analyst` and `Title: attorney` instead of just `analyst` and `attorney`, respectively. Note that the chip label is transformed like this, but the checkbox label is not. 

## Your Environment
```
  "dependencies": {
    "@material-ui/core": "4.7.0",
    "@material-ui/icons": "4.5.1",
    "@types/mui-datatables": "2.12.2",
    "mui-datatables": "2.13.0",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-scripts": "3.2.0"
  },
  "devDependencies": {
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.2",
    "typescript": "3.3.3"
  },
```

**Comment by gabrielliwerant** [comment]
Hey @ertw, I apologize for the confusion. There are a lot of options related to filters, and it's difficult to tell what does what. I'll try to make this more clear in the documentation.

The `customFilterListOptions` only affect the display of the filter chips once filters are selected (as well as what happens when they are removed).

To customize the display of the filters themselves, you'll need to use `filterOptions: { display: function }` with `filterType` set to `custom`. You'll have to recreate the filter components entirely to get custom behavior. There isn't any granular approach to this at the moment, so you can't, say, just use checkboxes but alter the display of the labels. You have to rebuild the filters themselves. You get total control, but at the cost of effort.

**Comment by Legogris** [comment]
> Hey @ertw, I apologize for the confusion. There are a lot of options related to filters, and it's difficult to tell what does what. I'll try to make this more clear in the documentation.
> 
> The `customFilterListOptions` only affect the display of the filter chips once filters are selected (as well as what happens when they are removed).
> 
> To customize the display of the filters themselves, you'll need to use `filterOptions: { display: function }` with `filterType` set to `custom`. You'll have to recreate the filter components entirely to get custom behavior. There isn't any granular approach to this at the moment, so you can't, say, just use checkboxes but alter the display of the labels. You have to rebuild the filters themselves. You get total control, but at the cost of effort.

I think  in the default case, users would like the same rendering in selects/multiselects/checkboxes as in the chips. This means that the majority of users who want to override `customFilterListOptions.render` will have to reimplement the full controls most of the time.

Would you be open to a PR that adds a prop (say, `customFilterListOptions.renderOptions` that does the corresponding override for the actual options?

**Comment by Legogris** [comment]
See https://github.com/gregnb/mui-datatables/pull/1121
