### ISSUE TITLE
Table not refreshed on data updates

### ISSUE THREAD

**Issue by fuzunspm** [gregnb/mui-datatables#1082]
## Expected Behavior
On data change table should be refreshed

## Current Behavior
Table and rowData values are not reflecting new values

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.5.1    |
| MUI-datatables  |     2.12.4    |
| React        |     16.10.2    |
| browser      |     Firefox 70.0.1    |

I have a modal window that opens on row click. There are 3 buttons to edit row data (OK, NOT OK, PAUSE). The data is changing with setState but table is not refreshing with the new value.

```
const columns = [
  {
    name: "id"
  },
  {
    name: "name",
    options: {
      filter: true,
      sort: true
    }
  },
  {
    name: "ownerName",
    options: {
      filter: true,
      sort: true
    }
  },
  {
    name: "quantity",
  },
  {
    name: "unit",
  },
  {
    name: "department",
    options: {
      filter: true,
      sort: true
    }
  },
  {
    name: "verified",
    options: {
      filter: true,
      sort: true
    }
  }
];

export default class extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      loading: false,
      page: 1,
      pageSize: 5,
      data: [],
      totalRows: 0,
      showModal: false,
      clicked: []
    };
    this.handleCloseModal = this.handleCloseModal.bind(this);
    this.handleOpenModal = this.handleOpenModal.bind(this);
  }

  handleOpenModal() {
    this.setState({ showModal: true });
  }

  handleCloseModal() {
    this.setState({ showModal: false });
  }

  preVerification(rowItem) {
    this.setState({ clicked: rowItem, showModal: true });
  }

  verification(msg, item) {
    this.setState({ showModal: false });
    var tempData = this.state.data
    for (var i = 0; i < tempData.length; i++) {
      if (tempData[i]["id"] == item[0]) {
        tempData[i]["verified"] = msg;
        this.setState((state) => ({
          data: tempData
        }));
        break;
      }
    }
    console.log(this.state.data);
  }

  async componentDidMount() {
    this.setState({ loading: true });
    const getCodes = await axios.get(`api/listrequests`);
    this.setState({
      data: getCodes.data,
      loading: false
    });
  }

  render() {
    const { loading, totalRows } = this.state;
    const options = {
      filterType: "dropdown",
      page: 0,
      pagination: true,
      rowsPerPage: 5,
      rowsPerPageOptions: [5, 10, 20, 30, 50, 100, 1000, 10000],
      fixedHeaderOptions: { xAxis: true, yAxis: true },
      rowHover: true,
      search: true,
      download: true,
      print: true,
      selectableRows: "none",
      onRowClick: rowData => this.preVerification(rowData),
    };
    return (
      <div className="container">
        <Modal
          isOpen={this.state.showModal}
          ariaHideApp={false}
          onRequestClose={this.handleCloseModal}
          style={customStyles}
          overlayClassName="Overlay"
        >
          <p>{this.state.clicked}</p>
          <button onClick={() => this.verification("NOT OK", this.state.clicked)}>NOT OK</button>
          <button onClick={() => this.verification("PAUSE", this.state.clicked)}>
            PAUSE
          </button>
          <button onClick={() => this.verification("OK", this.state.clicked)}>OK</button>
        </Modal>
        <MUIDataTable
          data={this.state.data}
          columns={columns}
          options={options}
        />
      </div>
    );
  }
}

```

**Comment by gabrielliwerant** [comment]
Hey @fuzunspm, can you create a minimal example that I can run, like in a codesandbox? The problem with trying to run your sample code here is that it uses a lot of things I would need to spend time setting up locally (I don't know what Modal you're using, I don't know what endpoint you're using, checking for missing variables, etc.). Verification and finding the issue is much simpler when the code is exactly as complex as it needs to be, so not including external libraries or http requests, and using minimal options necessary to produce the error.

In the mean time, have a look at the `custom-action-columns` example, as it demonstrates table actions changing data via setState, so it may prove instructive somehow.

**Comment by fuzunspm** [comment]
[codesandbox demo](https://codesandbox.io/s/elegant-bhabha-wqk4n)

I output the data every time it changes to the console. It changes but the table remains the same

**Comment by gabrielliwerant** [comment]
Thanks for the example. In your example, you're setting the new data equal to the old data. So in that case, I would not expect the data or the table to change. Am I missing something?

**Comment by fuzunspm** [comment]
I'm overwriting new data on to the old data via setState. Isn't it how I'm suppose to do?

**Comment by gabrielliwerant** [comment]
In theory, yes, but in this section:

```
var tempData = this.state.data;
for (var i = 0; i < tempData.length; i++) {
  if (tempData[i]["id"] == item[0]) {
    tempData[i]["verified"] = msg;
    this.setState(state => ({
      data: tempData
    }));
    break;
  }
}
```
we set the new data to the old data with `var tempData = this.state.data;` and then set it back again with
```
this.setState(state => ({
  data: tempData
}));
```

So I'm not sure if that's what's happening in your main application, but this would result in no change to the table. If you instead insert some new fake data like
```
this.setState(state => ({
  data: [{id: 123, name: 'foo', ...}, {id: 456, name: 'bar'}]
}));
```
then the table will update to reflect the new data, which is what I saw when I modified your example to do the above.

**Comment by gabrielliwerant** [comment]
Sorry, I realized I may not have been clear. In javascript, when you assign an object (array in this case, but js treats arrays like objects under the hood) to variable, the reference of the object is passed, rather than the value. This means that, even though you modify it later, under the hood, it looks to js like it's the same object, and so it doesn't update the way you would expect in react.

To fix this, you need to actually copy the object (array of objects in your case). One way to do so is
```
var tempData = [...this.state.data];
```

If you do that, you will notice it now updates. This is not an issue with the table library, it's a consequence of how js and react work.

**Comment by fuzunspm** [comment]
Thank you very much, copying object did the trick but even thought this is unrelated to mui-datatables, could you please explain why it won't do the same thing. In the end when i output state.data, it outputs modified values so it actually overwrites

**Comment by gabrielliwerant** [comment]
@fuzunspm React re-renders if it detects a change via setState, but the change in your case occurs before setState is called due to the object reference issue.
