### ISSUE TITLE
Add new icon in header of table

### ISSUE THREAD

**Issue by DigiGroundJohn** [gregnb/mui-datatables#1085]
Hi,

If I pass the function as props, it didn't work for me

onViewStoriesClick(){
console.log("button clikc is working")
this.setStoryDialog(true);
}

<CustomToolbar text={"View New Stories"} onClick={()=>this.onViewStoriesClick() } cssClasses={"blue-button"}/>

and my custom toolbar is

render() {
// const { classes } = this.props;
console.log(this.props)
return (
<React.Fragment>
            <Button onClick={()=>this.props.onClick} className={this.props.cssClasses}>
                {/* <AddIcon className={classes.deleteIcon} /> */}
                {/* <SvgIcon> */}
                  {this.props.text}
                {/* </SvgIcon> */}
            </Button>
    </Tooltip>
  </React.Fragment>
);
}

}

any suggestion, what I am doing wrong

**Comment by gabrielliwerant** [comment]
I responded to your question here https://github.com/gregnb/mui-datatables/issues/129#issuecomment-559579383, as that's where I saw it first. Cheers!
