### ISSUE TITLE
make filter date range in MUI datatable

### ISSUE THREAD

**Issue by monicayanethacosta** [gregnb/mui-datatables#1090]
can anyone tell me how to make filter date range in MUI datatable? Please?

**Comment by patorjk** [comment]
Check out the customize-filter example: https://github.com/gregnb/mui-datatables/blob/master/examples/customize-filter/index.js

Code Sandbox link here: https://codesandbox.io/s/github/patorjk/mui-datatables/tree/examplegrid_updates

That example shows how to do a filter with a number range - min and max. Doing the same for a date should be pretty straight forward, though myself or someone else can help out if you have any questions.

**Comment by monicayanethacosta** [comment]
Thank you very much, the example worked perfect. For the date range, it was just change type = "date"
