### ISSUE TITLE
 How can I not display the "none fields?"

### ISSUE THREAD

**Issue by monicayanethacosta** [gregnb/mui-datatables#1094]
I have data that I bring from a query, the null fields are shown as "none". How can I visualize them empty?
![datos](https://user-images.githubusercontent.com/44326142/70082782-1e614880-15d9-11ea-98df-d40d7a582ae8.png)

Thanks

**Comment by patorjk** [comment]
Are you sure you're not doing this somewhere in your code? If a field is changed to null in a codesandbox I don't see this:

https://codesandbox.io/s/wy2rl1nyzl

However, setting this aside, one solution would be to use the customBodyRender method. That allows you to control exactly what is displayed in a table cell.

**Comment by monicayanethacosta** [comment]
customBodyRender it was the solution, thanks
