### ISSUE TITLE
Styling Problems due to revert of 'boxSizing: "border-box"' for cells

### ISSUE THREAD

**Issue by patorjk** [gregnb/mui-datatables#1097]
I noticed the [latest release](https://github.com/gregnb/mui-datatables/pull/1096/files) reverts the "border-box" changes that were made for the setTableProps method. Not using "border-box" leads to problems in a number of cases. For example, see the customize-styling example:

https://codesandbox.io/s/friendly-goldwasser-fvw49

You'll notice the red background no longer covers the whole cell (flip between dense and non-dense modes). There are also other problems that will arise if someone customizes the styles through setTableProps or setCellsProps (like td cells stacking because they're more than 50% the width of the table), which is why the cells were changed to use "border-box" rather than a fixed pixel size amount when determining their width.

**Comment by gabrielliwerant** [comment]
Some of the styling changes should not have been released in the last minor version, my fault for adding them in. They created regressions, which we shouldn't have in minor releases. So if we want to move forward, they'll have to be resolved in a way that is backwards compatible, unless we hold off for a major release.

Right now, the only issue I see on my end is the last item in the stacked view has extra padding, which interferes in the event that someone wanted to highlight the whole row. This isn't base functionality, so it's not as important as maintaining consistency in appearance between minor and patch releases.

**Comment by patorjk** [comment]
There are more problems than just the highlight color. In the customize-styling example, if someone wanted to add extra padding instead of just changing the color to "#FAA", it would result in a misaligned display. You can test this by editing the customStyles object in that example.

Theoretically, the fix can be done with no issues by changing these style rules:

    height: '24px',
    width: 'calc(50% - 80px)',

Back to this:

    width: '50%',
    boxSizing: 'border-box',
    height: '32px',

I'm not sure why they were changed in your update unless the box-sizing breaks something I'm not aware of.

**Comment by gabrielliwerant** [comment]
The box sizing and width are responsible for changing the appearance of the stacked view in mui v4 as described in this issue https://github.com/gregnb/mui-datatables/issues/1095. You can see it in the codesandbox example using stacked view and switching between v2.12.4 and v2.13.0. There may be a way to keep box sizing and fix the issue. I think the padding changes in mui v4 are the culprit, and I do have a PR up for that, but it's a breaking appearance change, so it needs to wait for v3. You could add those box sizing and width changes back as a companion to https://github.com/gregnb/mui-datatables/pull/949, and I'll make sure to put them in together.
