### ISSUE TITLE
Filter concatinate same values

### ISSUE THREAD

**Issue by JordanKadish** [gregnb/mui-datatables#11]
## Issue

Hey, I'm having an issue with the filter.

I am filtering ~6000 items, and when I click the upside down triangle that shows filter options, the page halts. I have many items with the same value in some fields (eg, location USA), and I'm wondering if there's a way to concatinate/reduce all the duplicate locations in the filter option (possibly before a render even occurs to save time like in componentWillMount) to the 8 or so unique locations I have? In your example I see you have locations, so maybe I am just missing something in the docs... I'm also assuming the column filter option to hide unwanted filter options is not adding to why I'm getting a halt
(by halt, I mean the browser freezes until a message pops up saying a script on this page is running for an unusually long time, and I can either stop it or wait)

## Your Environment

| Tech         | Version |
|--------------|---------|
| mui-datatables  |   1.0.8     |
| node        |   9.1.2      |
| OS      |     Arch Linux    |

**Comment by gregnb** [comment]
Could you share the data set and options you used? I'll try to recreate this when I get some down time. Maybe post your repo on github if the information is not sensitive ?

**Comment by JordanKadish** [comment]
The info is sensitive but essentially I'm loading a json file into the program and then looping through each item adding it to the rows, and the columns are also being defined by what's in the json file. It all works, except the filter triangle. When I limit the number of entries from 6k to 15, it works perfectly. An example entry would be:
{
    "A": "1",
    "B": "9999999999999999",
    "SHAPE": "circle",
    "LOCATION": "USA",
    "C": "xyz",
}

One issue my side is that I'm currently not correctly mapping location column heading to row in the filtering section (so the values are under the right column in the grid, but in the filter, A's values are under B's heading) but that's definitely something wacky on my side. The halting thing that's happening is, I want to only filter by location (as an example) and when I've set all the other filter headings to false, I click the triangle and it just loads forever. When I limit the number of entries to 15, it loads right away (albeit the "locations" are all numbers because A's values are mapping to location, which is my fault)

**Comment by gregnb** [comment]
Ok no problem. I think I can take it from here. I'll follow your structure and beef the data set up to 10,000 rows and look where the issues are. BTW does this happen in any browser you test? Which one are you using to round out this big report

**Comment by JordanKadish** [comment]
Idk if I should make a new issue for this, but I'd also like to suggest that in your docs example, you make it as generic as possible. So instead of hard coding in stuff like a user database and column headings, perhaps write a mapping function that takes in a json file with a headings obj list and user db obj list, and then maps the user's data correctly to the heading fields of each created row. This makes your code easy to swap out and makes sense for the kind of use cases the library would work with.

Example:
//read in json file
for (var i = jsonData.colNames.length - 1; i >= 0; i--) {
                columns.push({
                    name:jsonData.colNames[i],
                    options:{
                        //wantFilter contains a list of parameters we want to have the filter, also read in from json
                        filter: wantFilter.indexOf(jsonData.colNames[i]) > -1 ? true:false
                    }
                });
}

That'd do your headings for you, then a mapping function like the one used here could work for rendering the table values correctly maybe
https://codesandbox.io/s/kwyy504y57
(This demo also contains those tick boxes per row people want)

**Comment by JordanKadish** [comment]
##Related to this issue
Alright I've made it so every column appears in the filter section, and that correctly maps the uniques, and gets the correct data under each column (when using dropdown filtering). But if I choose to turn filtering off for certain headings, this misaligns which values go under the remaining headings in the filter. IE, if I leave Amount and Location on as filterable, their values in the dropdowns are correct. If I make Amount not filterable, when I click Location, the values for Amount are being listed. I'd also like to know how to sort the shown values under each heading in the filter box (when I click Location with the correct values showing, they aren't in any order)

**Comment by gregnb** [comment]
Ok, I would open another issue and title it maybe "improve examples documentation + JSON loader function" maybe? I still want to keep the first example a user sees very simple and brief but expanding the examples to show how to load in a JSON file or even creating a standard function to load that in are good suggestions

**Comment by gregnb** [comment]
@JordanKadish ok, I'll roll that into this. As of today there's no sorting in the filter list but it's easy to add so I'll make it an option that is on by default but if a user doesn't want a filter list to be sorted alphabetically then it'll be shown as is.

**Comment by gregnb** [comment]
Anyway, my plane is landing soon I'll look into this next couple of days

![Uploading IMG_7946.JPG…]()

**Comment by JordanKadish** [comment]
Cool, so just to summarise this (I went a bit of track sorry)
Sorting the filter list
Bug (possibly my side only) where hiding a column from the filter section shifts the listed values of all the other columns so heading X now has heading Y's row values

**Comment by gregnb** [comment]
Ok, I just published version 1.0.9. This will sort by default the filter list generated for each column.  Also, there was a bug when the filter was turned off and did indeed shift the results. I took care of that bug so thanks for spotting it! 

Let me know how it goes

**Comment by JordanKadish** [comment]
Thanks, I'll get back to you by tomorrow with results

**Comment by gregnb** [comment]
Hey @JordanKadish did you get a chance to try? I've tested again and it seems fine on my end

**Comment by JordanKadish** [comment]
Yeah thanks, tested and working. Great job! I'm going to be super busy for a while but when I can, I'll try pop up some generic json loader code for you to slot in somewhere

**Comment by gregnb** [comment]
@JordanKadish Thanks for reporting the bug! I'm still going to think about the JSON loader as a main feature. For sure I will include it as an examples/ but as for main feature I still need some time to decide

**Comment by JordanKadish** [comment]
@gregnb no worries, I just think most people won't be working with this framework on hardcoded data, that's all. I am sure there are multiple ways to load in data, json just seems to be the most common in my experience. Thanks for fixing the bug :)
