### ISSUE TITLE
See applied filters when server-side: true

### ISSUE THREAD

**Issue by BjoernRave** [gregnb/mui-datatables#1105]
Maybe I didn't set up it properly, but it seems those bubbles on the top of the table to indicate which filters are applied are only visile when server-side is false

**Comment by ff-luis-carrillo** [comment]
I think I have the same problem, is it related to #1102?

**Comment by patorjk** [comment]
When serverSide is true you need to manually populate the serverSideFilterList to show the filters. See this example: https://github.com/gregnb/mui-datatables/blob/master/examples/serverside-filters/index.js

As an aside, I have a PR https://github.com/gregnb/mui-datatables/pull/1093 in that would make this simplier (ie, no management of an additional filterList - just a function you call to confirm filters if you want to wait before applying filters).

**Comment by patorjk** [comment]
@ff-luis-carrillo - yep, same thing, you currently have to manage the serverSideFilterList when using serverSide: true.

**Comment by ff-luis-carrillo** [comment]
@patorjk I can confirm it is working. Thank you!
