### ISSUE TITLE
Double Click is also intercepted as two single clicks

### ISSUE THREAD

**Issue by siddharthbhagwan** [gregnb/mui-datatables#1107]
A double click works but also triggers two single clicks.

## Expected Behavior
If there are listeners for both a single click and a double click, the double click should be a standalone event that doesn't translate to two single clicks. There should be no overlap between the two functionalities whatsoever, just like the native browser events behavior for the same.

## Current Behavior
If you add a single click listener via `onRowClick` and a double click listener via `setRowProps` and `onDoubleClick`, a double click will also register as two single clicks.

## Steps to Reproduce (for bugs)
[Sandbox Reproduction](https://codesandbox.io/s/muidatatables-custom-toolbar-hd9kw)
1. Open the link 
2. Open the browser console.
3. Do a double click on any row
4. See an alert for the double click as well as 2 entries in the console for each single click

## Your Environment
Chrome Version 78.0.3904.97 (Official Build) (64-bit)
OSX Mojave 10.14.6

EDIT: This [thread on SO](https://stackoverflow.com/a/54463793/1311020) explains how single click and double clicks are handled by browsers. TIL they are **not discrete** events and do have an overlap.

**Comment by gabrielliwerant** [comment]
Not sure how I feel about 1st class support for double clicks to be honest. Double click is a desktop paradigm, not a web paradigm, and many, extremely complex and sophisticated web applications get by just fine without it (gmail, facebook, github). I don't want this library to encourage questionable UX behaviors, when there is a lot of information and prior art concerning how to allow users to interact with a sophisticated web application without use of desktop-style interaction.

**Comment by patorjk** [comment]
This is just how the web works. onClick always fires when you have an onDoubleClick event. However, unrelated to this table, you can get around this by using setTimeout in your onClick event and canceling the timer:

    setRowProps: () => ({
      onDoubleClick: (row, dataIndex) => {
        clearTimeout(tt);
        alert("Double click!");
      }
    }),
    onRowClick: (rowData, rowMeta, e) => {
      clearTimeout(tt);
      tt = setTimeout(function() {
        console.log("Single Click");
      }, 1000);
    }

**Comment by siddharthbhagwan** [comment]
@patorjk Thanks, this was news to me! I always thought that a double click and single click would be separate, non overlapping events. I added a [SO link](https://stackoverflow.com/a/54463793/1311020) in my question as well that explains the mechanism well.

**Comment by siddharthbhagwan** [comment]
Thanks for your thoughts, @gabrielliwerant. My improved understanding of the workings and semantics of single/double clicks has helped address the issue; I'll be revising my requirement to want to have a single and double click on the same element.

If you have any links for must reads on how to allow users to interact with a sophisticated web application without use of desktop-style interaction, I'd be grateful, else I'll close the issue.

**Comment by gabrielliwerant** [comment]
@siddharthbhagwan, apologies if it sounds like I came on strong, as it was not my intent. We're all learning, and I like the attitude with which you're approaching this. I think a good place to start if you're looking for some good web-based UX guidelines is the material design specs themselves. Google did a very good job in analyzing web usage and creating some great components to fit that behavior. This link can get you started: https://material.io/design/material-studies/about-our-material-studies.html#. One helpful tip is to look into switches/checkboxes, as these are often used to enable/disable things in a single-click context.

Ultimately, UX is hard, and there's often no single approach that always works. I would analyze which behaviors you want that seem to need doubleclick and then to consider if there are other structures (expandable panels is another common option) that would achieve the same goals, or perhaps to flatten out data hierarchies (overly nested sets of data or functionality that are hidden from users is often a reason to want special means of accessing them, but can often be solved by eliminating the nesting itself). Sorry if that's vague, but I hope it helps.
