### ISSUE TITLE
How to apply filter on initial mounting ,  table mounted with applied filter

### ISSUE THREAD

**Issue by paritoshraj11** [gregnb/mui-datatables#1109]
I have to restore applied filter for list. example if user applied filter and pagination then go to the detail page and come back to the list then applied filter, and page should show there.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by ff-luis-carrillo** [comment]
Hello @paritoshraj11, I had to implement something similar to what you describe and I ended applying the next solution.

I saved the table state in the localStorage using the onTableChange method exposed in the table option and then loaded it with the following code in a service that I had in a tableWrapper component.
```
const tableState = retrieveTableState(storeId);
if (tableState) {
  // these are all the values I store in the localstorage
  const { rowsPerPage, searchText, columnsData, filterList } = tableState;
  // filter are applied in a column level, so it is necessary to iterate on each column
  this.columns = this.columns.map((col, index) => {
    col.options = { ...col.options, filterList: filterList[index], ...columnsData[index] };
    return col;
  });
  this.options = {
    ...this.options,
    ...{
      rowsPerPage,
      searchText,
    },
  };
}
```
this.columns and this.options are the same props you send to the table, I just handled them in the service

**Comment by gabrielliwerant** [comment]
Yes, I believe the `filterList` option in the column options, is the thing you want. As @ff-luis-carrillo says, you save your data however you wish, then you can set the state of the filters by changing the `filterList` option.

**Comment by gabrielliwerant** [comment]
Closing as resolved.
