### ISSUE TITLE
How to change checkbox color?

### ISSUE THREAD

**Issue by shubham81407** [gregnb/mui-datatables#111]
How i can change the checkbox color.

**Comment by mantzuri** [comment]
You can override the theme, I didn't manage to do it without ```important```

```
   getMuiTheme = () =>
    createMuiTheme({
      overrides: {
        MUIDataTableSelectCell: {
          checked: {color: "yellow !important" }
        }
      }
    });
```

**Comment by phanshiwen** [comment]
This should work. Looking at the source helped me find the right identifiers
https://github.com/gregnb/mui-datatables/blob/6da45d04da214f40172fdf33b5d32e99ac75c56a/src/components/TableSelectCell.js#L35

`
    MUIDataTableSelectCell: {
      checkboxRoot: {
        '&$checked': {
          color: 'rgba(0, 0, 0, 0.54)',
        },
      },
    },
`
