### ISSUE TITLE
Unable to add additional columns to CSV download

### ISSUE THREAD

**Issue by ertw** [gregnb/mui-datatables#1114]
##  Expected Behavior
In my datatable, I combine multiple pieces of data into a single cell. As far as I can tell, this is supported behavior as long as the data array used to build the datatable is flat. I would like to be able to add an additional column to the downloaded CSV to display the actual data that is referenced, rather than just the index that I am using. I'd like to ascertain whether this is intended behavior or not. I've taken a look at the code and so far haven't figured out where it is indexing into something undefined, but could probably submit a PR to fix this if it is not intended behavior.  

## Current Behavior
I can add an additional column to the CSV using `onDownload` `buildHead`. However, if I attempt to populate it using `buildBody`, I am unable to download the CSV, and see an undefined typeError in the browser console.

## Steps to Reproduce (for bugs)
I have created a minimal reproduction, which demonstrates the motivation for having additional columns when viewed in a tabular file format (in this case, I have an animal object with nose and species properties that are displayed in a single cell in web view, but which I'd like to display in individual columns in a downloaded file).

https://codesandbox.io/s/custom-filter-issue-lwxy0

You'll see that I am able to add additional columns without issue- in the example I use `buildHead` to create 3 columns. However, when I try to populate the 3rd column, I get an undefined typerror. You can verify that the additional column is present and works if you delete line 66 (`animals[x.data[2]].animal`), which is where I attempt to extend the data array.

## Your Environment
    "@material-ui/core": "4.7.2",
    "@material-ui/icons": "4.5.1",
    "@types/mui-datatables": "2.12.2",
    "mui-datatables": "2.13.3",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-scripts": "3.3.0"

**Comment by gabrielliwerant** [comment]
Line 66 looks like the issue to me! Your object references are undefined. If you fix the map function, you should be fine. I don't think this demonstrates a library problem.

**Comment by ertw** [comment]
@gabrielliwerant thanks for taking a look! I rebuilt my example more simply, and in doing so, realized that a more idiomatic way to solve my problem (displaying columns in the csv, but not in the datatable) is to have `{display: "false"}` on the column definition for columns I don't want to display 🤦

Thanks!
