### ISSUE TITLE
Don't use 'none' as sortDirection

### ISSUE THREAD

**Issue by KrzysztofMadejski** [gregnb/mui-datatables#1115]
## Expected Behavior
Following typescript definition:
```
MUIDataTableColumnOptions {
  ...  
  sortDirection?: 'asc' | 'desc';
}
```
## Current Behavior
Currently sortDirection when is not defined sometimes is `undefined` and sometimes a string `'none'`

| Tech         | Version |
|--------------|---------|
| MUI-datatables  | 2.12         |

**Comment by gabrielliwerant** [comment]
I think I need some clarification. `sortDirection` is an enum, and users need a way to specify that no sort direction is set, which is done with `'none'`. The typescript definition is likely out of date if it does not accommodate that.

**Comment by KrzysztofMadejski** [comment]
Wouldn't `undefined` be a natural value for no sort direction is set?

**Comment by gabrielliwerant** [comment]
Enums in js should have all string options. We also do this with `selectableRows` where `'none'` is an option there. Using `undefined` also leads to some confusion in situations where people want to dynamically change the sort direction, as setting values to `undefined` is atypical.

**Comment by KrzysztofMadejski** [comment]
Thanks for feedback!
