### ISSUE TITLE
"filterType" value "textField" does nothing different than "dropdown"

### ISSUE THREAD

**Issue by mxmlnglt** [gregnb/mui-datatables#1117]
Column options section says about "filterType":
https://github.com/gregnb/mui-datatables#column-options

> Choice of filtering view. Takes priority over global filterType option.enum('checkbox', 'dropdown', 'multiselect', 'textField', 'custom') Use 'custom' if you are supplying your own rendering via filterOptions.

However in MUIDataTable options:
- if no filterType set, seems like it's checkboxes...?
- filterType: "checkbox", => OK; checkboxes too (as a default?)
- filterType: "dropdown", => OK; drop-down
- filterType: "multiselect", => OK; drop-down with checkboxes
- filterType: "textField", => displays as a drop-down (bug?)

I forked one of the code sandboxes at https://www.material-ui-datatables.com/ to showcase the (so-called) bug:
with "dropdown": https://codesandbox.io/s/muidatatables-customize-columns-7lpen
with "textField": https://codesandbox.io/s/muidatatables-customize-columns-y8il4
Both render the same way.

**Comment by gabrielliwerant** [comment]
Hello @mxmlnglt. In your codesandbox repos, the version of mui-datatables you have is out of date. If you use the latest, the filters will show the correct types.

**Comment by mxmlnglt** [comment]
Oh @gabrielliwerant so you mean the version of MUI-DataTables used on its own website https://www.material-ui-datatables.com/ is out of date?

**Comment by mxmlnglt** [comment]
WOW OK you're right...
- Custom Component: https://codesandbox.io/s/xrvrzryjvp mui-datatables 2.0.0-beta-21
- Customize Columns: https://codesandbox.io/s/xowj5oj8w mui-datatables 2.0.0-beta-19
- Customize Footer: https://codesandbox.io/s/5z0w0w9jyk mui-datatables 2.0.0-beta-19
- Customize Styling: https://codesandbox.io/s/0ylq1lqwp0 mui-datatables 2.0.0-beta-19
- Customize Toolbar: https://codesandbox.io/s/wy2rl1nyzl mui-datatables 2.0.0-beta-51
- Customize ToolbarSelect: https://codesandbox.io/s/545ym5ov6p mui-datatables 2.0.0-beta-19
- Resizable Columns: https://codesandbox.io/s/q8w3230qpj mui-datatables 2.0.0-beta-23

**Comment by gabrielliwerant** [comment]
Haha, yes, unfortunately that website is out of date, and I do not have the access required to fix it! Sorry for the confusion. The up-to-date information is all within the repo at this point.

**Comment by mxmlnglt** [comment]
> Haha, yes, unfortunately that website is out of date, and I  to fix it! Sorry for the confusion. The up-to-date information is all within the repo at this point.

What do you mean by *do not have the access required*?

**Comment by gabrielliwerant** [comment]
I do not own the website.
