### ISSUE TITLE
Feature Request: Resizable columns 

### ISSUE THREAD

**Issue by jkeruzec** [gregnb/mui-datatables#112]
Another improvement that can be cool : 
Be able to resize with a resize bar the column size

@see project react-split-pane for inspiration

**Comment by gregnb** [comment]
Looks pretty neat I could see something like an option say
```
options: {
  resizeableColumns: true|false
}
```

that would allow you to adjust any column.  If someone wants to take this work up I would approve of it

**Comment by gregnb** [comment]
I just added this feature and published in version 2.0.0-beta-2.

it is **off** by default for now until more testing can be done.

**Comment by ziadrida** [comment]
resizableColumns not working in 2.0.0-beta-37. Is that a known issue?

**Comment by osamamehmood** [comment]
Resizeable columns not working properly.

**Comment by gregnb** [comment]
Please upgrade to the latest. if you have any issues please provide a codesandbox for me to look at

**Comment by iamvishalbisht** [comment]
Resizable column is not working properly in 2.0.0-beta.59

**Comment by opandey007** [comment]
resizable column is not working if column is more then 20 ...so what can i do any help

**Comment by opandey007** [comment]
> Please upgrade to the latest. if you have any issues please provide a codesandbox for me to look at

resizable column is not working if column is more then 20 ...so what can i do any help
