### ISSUE TITLE
Malfuncting peer dependencies

### ISSUE THREAD

**Issue by jmarucha** [gregnb/mui-datatables#113]
`@material-ui/icons@^2.0.0` in current version (2.0.0) doesn't provide `@material-ui/icons/FileDownload`, resulting in `ModuleNotFoundError`

**Comment by gregnb** [comment]
Try upgrading to the latest version of mui-datatables we've moved the peerdepends up and also changed the fileicon

**Comment by jkeruzec** [comment]
Same here with latest version : 
`"mui-datatables": "2.0.0-beta-18",` 

In minified code, I always have FileDownload Icon and not CloudDownload Icon.
I also delete folder on node_modules repository and npm install again.. 
Master branch on Github is OK.

Maybe some problem of build on your side?

**Comment by jkeruzec** [comment]
There is also no custom toolbar in latest version :( 

reverting to previous version^^

**Comment by jmarucha** [comment]
Just installed version `2.0.0.-beta-18` and got `Module not found: Error: Can't resolve '@material-ui/icons/FileDownload'` again. The `@material-ui/icons` are installed in vesion `2.0.0`. Are you using any additional icon set in the project?

**Comment by gregnb** [comment]
I'll take a look at this in about a half hour

**Comment by jkeruzec** [comment]
Ok for icon, ok for customtoolbar but now I loose the customRender method ... :'( 

next version will be good ! I'am sure ;)

**Comment by jmarucha** [comment]
works for me :)

**Comment by jmarucha** [comment]
Just to confirm: the FileDownload icon has been removed from mui.
https://github.com/mui-org/material-ui/issues/12344#event-1762445446
