### ISSUE TITLE
Unable to apply overridden styles in MUI theme

### ISSUE THREAD

**Issue by ertw** [gregnb/mui-datatables#1131]
First off, thanks again for this great library! I've been submitting a lot of issues, and really appreciate the work that goes into triaging them. 

I'm trying to upgrade from mui-datatables 2.11.1 to 2.13.3, and have run into an issue where styles that were previously overridden are no longer overridden. I previously had a MUI theme with an override specified like this:

```
const theme = createMuiTheme({
  overrides: {
    MUIDataTableBodyCell: {
      cellStacked: {
          ....
      },
    }
  }
});
```
Now these styles are not applied. In the browser console, I see a warning about this:

```
Material-UI: you are trying to override a style that does not exist.
Fix the `cellStacked` key of `theme.overrides.MUIDataTableBodyCell`.
```

This issue is reproducible on 2.13.1 and above. 2.13.0 and below (from what I've tested) do not exhibit the issue. I read through the release notes and don't see any changes mentioned that should affect this, so I think it's a regression somewhere in 2.13.1.

## Expected Behavior
Apply certain styles to customize responsive display of table. This is inherited code, so please let me know if I'm doing it wrong and there is a better way to apply responsive styles to stacked table cells.

## Current Behavior
Styles are not overridden, and I see a console warning.

## Steps to Reproduce (for bugs)
Install mui-datatables@2.13.1 , 2.13.2, or 2.13.3
Attempt to override a style from a MUI theme

Please see reproduction of issue here: https://codesandbox.io/s/custom-filter-issue-g1o4l
If you look in the console, you'll see warnings about missing keys from Material-UI. Tested on Firefox & Chrome.

## Your Environment
    "@material-ui/core": "4.8.1",
    "@material-ui/icons": "4.5.1",
    "@types/mui-datatables": "2.13.3",
    "mui-datatables": "2.13.3",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-scripts": "3.3.0"

**Comment by gabrielliwerant** [comment]
Hey @ertw, thank you for bringing this up. `cellStacked` was removed in `2.13.2`, so it should not be reproducible before that, but should be after that. This issue is an unintended consequence of fixing another issue. I suppose it's technically a breaking change, though I tend to vet the styles a little less carefully, because there's usually a way around it. In this case, the new class names replacing it are `stackedCommon` and `cellStackedSmall`. If you switch to these, you should be ok.

I apologize for the inconvenience. Let me know if you're able to get around the problem with those other classes.

**Comment by ertw** [comment]
@gabrielliwerant thanks, updating the classnames fixed my issue. For future reference, what's the best way to determine which classnames to target? Per the documentation `determine which component you would want to target and then lookup the override classname`, does this mean that I should just look in the browser inspector to see what classname has been applied? In this case, I see `class="MuiTableCell-root MuiTableCell-body MUIDataTableBodyCell-root-416 MUIDataTableBodyCell-cellHide-417 MUIDataTableBodyCell-stackedCommon-418"`, so it's not immediately clear to me which class to use. When overriding Material UI, I typically start with the documentation for an individual component (for example, here is the [Button API CSS list](https://material-ui.com/api/button/#css)), as they have a list of all the overrides. Ideally I would like to be able to depend on Typescript definitions, but I have not yet found a good way to type my Material UI theme, as the Material UI type Theme type does not allow unspecified keys on the theme object.

**Comment by gabrielliwerant** [comment]
I think you're correct to inspect the DOM, as this is how I would do it. Documentation would be better, but that level of documentation does not exist for this library at the present time. Looking through the code would probably take a lot longer, so I'd inspect the DOM and look at the styles applied to each class to determine which I wanted to override.
