### ISSUE TITLE
How to preselect filters

### ISSUE THREAD

**Issue by mohammad5055** [gregnb/mui-datatables#1133]
## Expected Behavior
Is there any way to preselect a filter before the table is displayed? For example in the filter below,  I would like Active to be selected when the table loads:
![filterCapture](https://user-images.githubusercontent.com/9754536/71752437-b0f93f80-2e44-11ea-80f2-98ac43e2bab5.PNG)

if you could call something from the columns options like this:

const columns = [
 {
  name: "name",
  label: "Name",
  options: {
   filter: true,
   sort: true,
  }
 },
 {
  name: "state",
  label: "State",
  options: {
   filter: true,
   sort: false,
   **prefilter: ["Texas", "New Mexico"]**
  }
 },
];

And then when the table load only records with Texas and New Mexico would initially be displayed.

## Current Behavior
I dont think there is any current functionality for this. I am trying to use the filterList option as follows:
{ name: "status", label: "Status", **filterList: ['Acitve']**}, with no success.

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.5.2    |
| MUI-datatables  |   2.13.3      |
| React        |    16.10.2     |
| browser      |     Chrome    |

**Comment by patorjk** [comment]
Check out the "filterList" option for a column. It allows you to populate the filters. You can see an example of it in action here:

https://github.com/gregnb/mui-datatables/blob/master/examples/customize-filter/index.js

The "Age" column has a filter pre-selected (25 to 50).

**Comment by mohammad5055** [comment]
https://codesandbox.io/s/muidatatables-custom-toolbar-gthuj?fontsize=14&hidenavigation=1&theme=dark


For some reason I cannot get codesandbox to display my data, but this same code works on my end. This is the same code i am using

**Comment by gabrielliwerant** [comment]
Hey @mohammad5055. In your codesandbox, your version of this library is too low. Additionally, the `filterList` option needs to be placed inside the `options` object as you do in the other columns. If you use a recent version of this library, and put your options in the proper objects, it will work.
