### ISSUE TITLE
Title as a Link

### ISSUE THREAD

**Issue by xStorm111** [gregnb/mui-datatables#1139]
Hello, is there anyway to transform a Datatable Tittle in a Link?

## Expected Behavior
Insert a title as a Link

## Current Behavior
If we use a <Link/> inside the tittle={} it will appear [Object object] instead the supposed string inside.

![image](https://user-images.githubusercontent.com/22938156/71838652-426ce980-30b1-11ea-8903-506a1f2b137d.png)

## Steps to Reproduce (for bugs)
![image](https://user-images.githubusercontent.com/22938156/71838370-90352200-30b0-11ea-9ac4-66757c305540.png)

**Comment by patorjk** [comment]
I'm pretty sure this works. Can you remove the "'Test' + " part and try it out? In JavaScript, I'm pretty sure a string plus anything else equals always equals a string (ex: "Test " + {} in the console will give you something similar to what you described). If you need the "Test" part, change it to this:

    title={<span>Test <Link to={'someplace'}>123</Link></span>}

**Comment by gabrielliwerant** [comment]
The `title` attr must take a valid element, so you need to wrap everything in tags, as @patorjk suggests.

**Comment by xStorm111** [comment]
Thank you very much for the replies @patorjk @gabrielliwerant.
You're solution works perfectly for me @patorjk, thanks for the explanation
