### ISSUE TITLE
Bug UI when using scrollFullHeight in mobile Screen

### ISSUE THREAD

**Issue by Vn-ChemGio** [gregnb/mui-datatables#1141]
![image](https://user-images.githubusercontent.com/25608423/71972468-429aef80-323f-11ea-9fdc-db438bd0d898.png)
When screen is small and I''m using scrollFullHeight in demo text-location I found that
Could anybody tell me  How to fix it ?
Thank so much

**Comment by gabrielliwerant** [comment]
This has come up a few times and is being addressed here https://github.com/gregnb/mui-datatables/pull/1134. Feel free to watch that PR for updates on progress, but I'll be closing this one as it's a duplicate.
