### ISSUE TITLE
How to define the min width to the 'responsive' behavior take effect?

### ISSUE THREAD

**Issue by DanZeuss** [gregnb/mui-datatables#1145]
Hello guys!

I'd like to know how could I be defining the min width in order to the 'responsive' behavior take effect?

Looks like that currently it's taking effect when then browser is resized in 50% of the width. 

How to override the theme in order to change the responsive behavior?

**Comment by gabrielliwerant** [comment]
The breakpoints are set using the material ui theme defaults. If you want to change these, you'll need to customize the material ui theme. You can get started reading about how to do that here https://material-ui.com/customization/theming/.
