### ISSUE TITLE
How do I add/remove data to the table?

### ISSUE THREAD

**Issue by burton666** [gregnb/mui-datatables#1146]
I am trying to build an app where I have one component that uses a form and I have the MUIDatatable in another component. I was thinking that I could use useState to send data from the form-component to the MUIDatatable-component. But that does not work.

How are you supposed to add new data to the Datatable from an external component? and also be able to delete rows ?

**Comment by gabrielliwerant** [comment]
The concepts here are no different than they would be for any other react app, so information along those lines may be helpful to you. You'll want to have your data managed via state and then have a means of updating that state. In the case where you want two different components to interact on the same set of data, one approach is to use a container component to manage the state and state update functions, and pass them down to the other components (research "container components" for more information).

You may also want to centralize your state via some system like redux, though there are other less involved options, depending on what you want/need.

See also the `serverside-pagination` which may give you some ideas about how to update state based on retrieval from another source (fake xhr requests in the case of the example).

**Comment by burton666** [comment]
Thanks for the answer I googled "container component" and it looks like I already have the same functionallity.

I have an app.js which contains `const [rows, setRows] = useState([])`
I am then returning two components: 
`<div className="inputForm">
          <Form rows={rows} setRows={setRows} />
        </div>
        <div>
          <Datatable rows={rows} setRows={setRows} />
        </div>`
Where <Datatable/> is the MUI-Datatables component. In the Datatable-component I am returning:
`<MUIDataTable
      title={"Verificationer"}
      data={rows}
      columns={columns}
      options={options}
    />`

I can get the default data from the example to show , but when I try to provide my own data from the Form I get only blank rows

**Comment by burton666** [comment]
Ah, my problem was that I tried to add an array of objects without setting up the columns correctly. It seams to work now.
