### ISSUE TITLE
On rows change, table height remains the same

### ISSUE THREAD

**Issue by VassilisPallas** [gregnb/mui-datatables#1147]
## Expected Behavior
Table should change height when number of rows changes.

## Current Behavior
Height remains the same

## Steps to Reproduce (for bugs)
1. Select rows number

Check your [demo](https://codesandbox.io/s/wy2rl1nyzl)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.7.0     |
| MUI-datatables  |    2.13.3     |
| React        |    16.9.0     |
| browser      |    Chrome 79.0.3945.88 (macOS)     |

**Comment by gabrielliwerant** [comment]
The behavior looks good on my end. Both number of rows and height changes in the latest version `2.13.3`:
![capture](https://user-images.githubusercontent.com/1779564/72190777-65a7d980-33ce-11ea-9dcd-7ad6508c9015.gif)

I need more information to reproduce your issue. I'll need all of the steps, options you have and/or a codesandbox repo. The one you linked is out of date, so it's not a good representation.

**Comment by gabrielliwerant** [comment]
Also, can you update the title here to explain what doesn't work?

**Comment by VassilisPallas** [comment]
Ok thanks, I will take a look again, and if I'm still facing the issue I will create a codesandbox.

**Comment by VassilisPallas** [comment]
The div that wraps the table has these css rules
```
height: 100%;
overflow: auto;
max-height: 499px;
overflow-x: auto;
```

When I remove the max-height,  it works fine. Is there any way to override that rule?

**Comment by gabrielliwerant** [comment]
There are a number of responsive options. Have you tried others aside from the one you are using?

**Comment by VassilisPallas** [comment]
You are right, I haven't seen them. Thank you very much, now it works like a charm!
