### ISSUE TITLE
Compatible with CSS Baseline?

### ISSUE THREAD

**Issue by sompol13** [gregnb/mui-datatables#1149]
I have include this to my code https://material-ui.com/components/css-baseline/#css-baseline
After that it make my mui-datatables collapse on mobile.
 
## Expected Behavior
![image](https://user-images.githubusercontent.com/33342822/72332530-c431c800-36ec-11ea-9fcd-0425194871a5.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/33342822/72332551-cb58d600-36ec-11ea-8814-e3a87bf25243.png)

## Version
2.13.3

NOTE: Sorry for the less information, I very new to react and material-ui.

**Comment by domind** [comment]
@sompol13 - this is same issue as reported in #1142 
As per my checking - overriding style for `.MuiTableCell-body {  width: calc(50% - 60px);} ` should fix it. At least it works in [sandbox](https://codesandbox.io/s/mui-datatable-10-row-overflow-n1ord).

**Comment by sompol13** [comment]
Thanks for response krub : )

#### Sound #1142 not work to me
![image](https://user-images.githubusercontent.com/33342822/72399325-75317480-3778-11ea-8ff1-a7a18337a3c3.png)
