### ISSUE TITLE
Running mui-datatables locally to contribute

### ISSUE THREAD

**Issue by jose-donato** [gregnb/mui-datatables#1157]
Cloning the repo and running it gives me error and does not compile.

## Expected Behavior

npm run dev running the project

## Current Behavior

when i run npm run dev, it breaks and localhost:5050 displays blank page with errors
Browser console output:
![image](https://user-images.githubusercontent.com/43375532/72493006-37cff400-3817-11ea-90f0-4fbc57fb61b7.png)

Terminal output:
ERROR in ./examples/serverside-sorting/index.js
Module not found: Error: Can't resolve './Cities' in '/mui-datatables/examples/serverside-sorting'
resolve './Cities' in '/mui-datatables/examples/serverside-sorting'
  using description file: /mui-datatables/package.json (relative path: ./examples/serverside-sorting)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /mui-datatables/package.json (relative path: ./examples/serverside-sorting/Cities)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /mui-datatables/examples/serverside-sorting/Cities doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /mui-datatables/examples/serverside-sorting/Cities.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /mui-datatables/examples/serverside-sorting/Cities.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
       /mui-datatables/examples/serverside-sorting/Cities.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /mui-datatables/examples/serverside-sorting/Cities.json doesn't exist
      as directory
        /mui-datatables/examples/serverside-sorting/Cities doesn't exist

## Steps to Reproduce (for bugs)

1. git clone https://github.com/gregnb/mui-datatables.git
2. cd mui-datatables
3. npm i
4. npm run dev

## Your Environment

| Tech         | Version |
|--------------|---------|
| browser      |    chrome 79.0.3945.117     |
| npm          |    6.13.2     |
| node       | v12.13.1 |

**Comment by gabrielliwerant** [comment]
This is related to https://github.com/gregnb/mui-datatables/pull/1122 and will be fixed in the next release.

**Comment by jose-donato** [comment]
Any temporary fix until next version is released?

**Comment by gabrielliwerant** [comment]
You can make the changes locally to the files you've cloned that are given in the PR I linked here, if it's urgent. If this is about opening a PR related to your issue with the selected rows, you won't need to worry about that. See my response for more details.

**Comment by gabrielliwerant** [comment]
Deleting the `serverside-sorting` example may also unblock your ability to run the repo locally, fyi.

**Comment by jose-donato** [comment]
After deleting serverside-sorting and removing the corresponding line in examples/examples.js I was able to run it locally.
