### ISSUE TITLE
TableResize - when changing window size resizers moving wrongly or do not move.

### ISSUE THREAD

**Issue by domind** [gregnb/mui-datatables#1164]
TableResize - when changing window size resizers moving wrongly or do not move.

## Expected Behavior
It should move accordingly to window size changes.

## Current Behavior
![1](https://user-images.githubusercontent.com/37326840/72709502-cae99080-3b6d-11ea-8a91-f1807d75d577.gif)

## Steps to Reproduce (for bugs)
You can check it in this [sandbox](https://codesandbox.io/s/mui-datatable-column-resize-o3b0h)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.8.3    |
| MUI-datatables  |   2.14.0     |
| React        |   16.12.0      |

If you confirm that it should be fixed, can write PR, as seems that this will require only some deletion of code in setDividers function.

**Comment by gabrielliwerant** [comment]
Looks like a bug to me, thanks for reporting! Let's see how the other PR you have up for resizing goes first, and then I think it'll make sense to tackle this one.

**Comment by domind** [comment]
@gabrielliwerant - should I send PR for this one already?

**Comment by gabrielliwerant** [comment]
@domind Hm, that might be awkward if it depends on the unmerged PR up now. If so, it's probably best to wait until after that one is released.

**Comment by domind** [comment]
Tested it on my end, and it does not depend, so will pass PR for this.

**Comment by patorjk** [comment]
This has been resolved as of version 3.0.1 of the library. You can see an example here:

https://codesandbox.io/s/muidatatables-custom-toolbar-zomv5?file=/index.js
