### ISSUE TITLE
How to change style of one row

### ISSUE THREAD

**Issue by jkeruzec** [gregnb/mui-datatables#117]
How can I change the style of one row ? 
For example to set a background color to see a selected row ?

Tthanks,

**Comment by gregnb** [comment]
Right now there's no styling per rows. Just global styles

**Comment by aliaanis** [comment]
I needed to give styling to a particular row when clicked->
instead of 'setCellProps', use 'setRowProps'
https://github.com/gregnb/mui-datatables/blob/master/examples/customize-styling/index.js

**Comment by javadev-jef** [comment]
Style with color property not work. Any tips?

**Comment by patorjk** [comment]
@javadev-jef can you provide a codesandbox? The set[Cell/Row/CellHeader]Props methods are the best way to set styles.

Example: https://github.com/gregnb/mui-datatables/blob/master/examples/customize-styling/index.js

Also, another example here: https://codesandbox.io/s/muidatatables-custom-toolbar-ys183?file=/index.js

**Comment by javadev-jef** [comment]
I need to style the line based on a cell value. I tried using setRowProps, but the color property does not apply. See a simple example, for changing the color of the thread that doesn't work.
`const options = {
        setRowProps: (row, dataIndex, rowIndex) => {
            return {style: {color: "blue"}}
        }
      };`

**Comment by javadev-jef** [comment]
Hey man, I resolved this with overrides. Ex:

`
const theme = () => createMuiTheme({ overrides: 
        {
            MUIDataTableBodyCell: 
            {
                root: 
                {
                  backgroundColor: "transparent !important",
                  color: "inherit",
                }
            }
}
}
`

Thanks!

**Comment by MohamedSherif-arbadev** [comment]
HI, I tried this way its working Nicely for me.

> `const [id,setId]=useState(null);
const options={
   setRowProps: (row, index) => {
      return {
        style: {
          backgroundColor: index===id? 'yellow': "#e3e3e3",cursor:'pointer'
        },
      };
    },
    onRowClick:(rowData, rowMetaData)=>{
      const id=rowMetaData.rowIndex;        
      setId(id)      
      });       
    }
}`

**Comment by MohamedSherif-1997** [comment]
HI, I tried this way its working Nicely for me.

> `const [id,setId]=useState(null);
const options={
   setRowProps: (row, index) => {
      return {
        style: {
          backgroundColor: index===id? 'yellow': "#e3e3e3",cursor:'pointer'
        },
      };
    },
    onRowClick:(rowData, rowMetaData)=>{
      const id=rowMetaData.rowIndex;        
      setId(id)      
      });       
    }
}`
