### ISSUE TITLE
Remove print and view columns icon from top 

### ISSUE THREAD

**Issue by bharatjyoti** [gregnb/mui-datatables#1170]
Hi,

Thanks for this awesome lib. Just wanted know how to customize the top action toolbar or How to remove the print and view-column icon from the top?

Also would like to remove the checkbox from every row element. Is it possible?

## Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     ^4.5.1    |
| MUI-datatables  |   ^2.12.4      |
| React        |    ^16.10.2     |

**Comment by gabrielliwerant** [comment]
Hello @bharatjyoti. All of that is possible. Please read the documentation and you find the answers you seek.
