### ISSUE TITLE
Wait for user stop typing in search

### ISSUE THREAD

**Issue by naothomachida** [gregnb/mui-datatables#1174]
Hi I can implement some one like this:

https://schier.co/blog/wait-for-user-to-stop-typing-using-javascript

| Tech         | Version |
| MUI-datatables  |     2.14.0    |
| browser      |     Chrome    |

**Comment by patorjk** [comment]
What you're thinking of is a debounced search. I have a PR in related to this. You can see it here: https://github.com/gregnb/mui-datatables/pull/1089

I don't think that PR is on @gabrielliwerant's radar, so for the moment you can implement a debounced search by looking at that PR and pulling out the DebounceSearchRender.js file and putting it in your project. Then use that component as an input to the customSearchRender property on the options object:

    customSearchRender: debounceSearchRender(500),

The examples/large-data-set/index.js in the PR shows how to use the component.

**Comment by naothomachida** [comment]
I already implemented it.

All ok!

Thanks @patorjk !

**Comment by mariouzae** [comment]
Thank you @patorjk,  it works pretty well.
