### ISSUE TITLE
How to remove ALL at dropdown filter

### ISSUE THREAD

**Issue by wdh2100** [gregnb/mui-datatables#1175]
How to remove ALL at dropdown filter

I want to choose one item.

![image](https://user-images.githubusercontent.com/16433770/73625513-893a0900-4688-11ea-821d-50197a1cddc6.png)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |^4.8.0|
| MUI-datatables  | ^2.14.0|
| React        |^16.12.0|
| browser      |chrome|
| etc          |         |

**Comment by gabrielliwerant** [comment]
"All" is the default when no filters have been selected. It means, show me all results. You pick the filter you want by selecting it from the dropdown. Does this answer the question?

**Comment by wdh2100** [comment]
@gabrielliwerant Thanks!

I know ' "All" is the default  ' but I want to choose one dropdown Item unconditionally

Do I have to use 'custom' to do this?

** drop down Sample**

![image](https://user-images.githubusercontent.com/16433770/73631440-513cc100-469c-11ea-88de-fdf76a9d3349.png)

**Comment by gabrielliwerant** [comment]
Sorry, trying to get a handle on what you're looking for. Are you asking for a way to not show the "All" option? If so, you would have to go full custom to do this. Removing "All" will not be a supported option because this is the way to return to the default view in the interface. Without it, users will not be able to return to the default.

**Comment by wdh2100** [comment]
@gabrielliwerant 
Thanks you answer!

**Comment by gabrielliwerant** [comment]
Glad I could help, but sorry I won't help! ;)

**Comment by 0plus1** [comment]
I would like to request the same, at least a way to change the wording from "All" to something else.
All is a very confusing choice of word, as "All" might imply All of the options below I feel like "Any" could be a bit better in this context, irregardless would be nice to be able to change the label.

**Comment by hherbert1978** [comment]
> I would like to request the same, at least a way to change the wording from "All" to something else. All is a very confusing choice of word, as "All" might imply All of the options below I feel like "Any" could be a bit better in this context, irregardless would be nice to be able to change the label.

Better would be a version where you can change it by yourself. I use three languages on my site and i want to use translation on the default filter also. How can I do this?
