### ISSUE TITLE
Not able to download a json object in csv file.

### ISSUE THREAD

**Issue by gk108000** [gregnb/mui-datatables#1179]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gk108000** [comment]
When the data array contains a object like ["asd","asd",{name:"abc",title:"xyz"}]
in csv file is is downloaded as "asd","asd",[object,object]

**Comment by gabrielliwerant** [comment]
This is not supported csv behavior in this library, and it is also not recommended to pass your data into the table in the format you have. This is discussed in the API section of the documentation if you'd like more information https://github.com/gregnb/mui-datatables#api. Best of luck!
