### ISSUE TITLE
Passing array of nested objects to muiDataTable

### ISSUE THREAD

**Issue by RaedShihab** [gregnb/mui-datatables#1180]
I am trying to pass data coming from JsonPlacholder Api to MUIDataTable but it can't read som thing like this :
{
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",}
    }, 
 the 'street' key for example is not accessible.
I tried this as column
const columns = [
      { name: "id", label: "ID" },
      { name: "name", label: "Name" },
      { name: "email", label: "Email" },
      { name: "address.street", label: "Adress" },
    ]; 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by RaedShihab** [comment]
this is the best way to solve  the problem

**Comment by gabrielliwerant** [comment]
Can you open a codesandbox that reproduces the issue?
