### ISSUE TITLE
Contributors Not Receiving Credit on this Project

### ISSUE THREAD

**Issue by gabrielliwerant** [gregnb/mui-datatables#1186]
It has come to my attention that due to the way github used to handle squash and merge, there are PRs which I continued from someone else's work, where the original author did not receive credit for the contributions he/she made.

If anyone thinks this might have happened to them, please comment here. I plan to combat this by creating a separate ATTRIBUTIONS page which will provide any of those affected with the proper credit.

It was never my intent to deprive anyone of proper credit for their work. I think it's important for anyone that helps out to be recognized for having done so. Community is an important part of any open source project.

This should no longer be a problem moving forward, as github has updated how they handle squash and merge, but I will need to make it right for anyone before this point.

**Comment by wdh2100** [comment]
>“Stop treating Open Source like a product you purchased and start treating it like a team you belong to.”
https://twitter.com/GetSource/status/1190286739014901761

That's a wonderful thing to say.
