### ISSUE TITLE
Can you change the functionality of multiple row select to do something else besides delete rows?

### ISSUE THREAD

**Issue by snsheth55** [gregnb/mui-datatables#1187]
I want to provide custom functionality for multiple row select.  If possible please explain how to implement/override current functionality.

Thank you

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gabrielliwerant** [comment]
I think what you've looking for is the `customToolbarSelect` option, so have a look at that in the documentation and the `customize-toolbarselect` example.
