### ISSUE TITLE
Documentation does not mention that `page` option is 1-indexed.

### ISSUE THREAD

**Issue by ashbc** [gregnb/mui-datatables#119]
The `page` option takes a page index starting at 1, whereas Material UI's `TablePagination` component takes them 0-indexed. This is implemented in mui-datatables by subtracting 1 from the page.

The 1-indexed functionality of mui-datatables is not documented anywhere.

See:

- [mui-datatables npm docs](https://www.npmjs.com/package/mui-datatables#options)
- [line of code that subtracts 1 from page option](https://github.com/gregnb/mui-datatables/blob/master/src/MUIDataTable.js#L169)
- [material-ui's `TablePagination` docs](https://material-ui.com/api/table-pagination/#props)

## Expected Behavior

npm docs state the `page` option is 1-indexed.

## Current Behavior

npm docs state `page` option as "User provided starting page for pagination"

## Steps to Reproduce (for bugs)

n/a

## Your Environment

n/a

**Comment by gregnb** [comment]
Ok fair point, would you like to send in a PR to let people know it is 1-indexed?

**Comment by gregnb** [comment]
I have a WIP PR that will resolve this and everything will start from the 0 index

**Comment by gregnb** [comment]
The library is now 0-indexed and this PR has been merged and released
