### ISSUE TITLE
unknown filter chip is active after deleting filter

### ISSUE THREAD

**Issue by maxkarkowski** [gregnb/mui-datatables#1191]
I have a custom dropdown filter for one column. 
the filter works as expected, i select one item from the dropdown and the table filters by this value.
After deleting the "chip" i get another chip with an unknown value. and the table shows no results.
 **it only happens if the filtered string has a whitespace'**
![gif-filter](https://user-images.githubusercontent.com/622841/74349434-8a6be400-4db4-11ea-9639-8137a21482fc.gif)

## Expected Behavior
- after deleting a filter pill, no data is shown

## Current Behavior
- deleting a filter pill should reset the filter

## Steps to Reproduce (for bugs)
```
{
    name: 'orderStatus',
    label: 'Status',
    options: {
      filter: true,
      sort: true,
      customBodyRender: (orderStatus: Status) => {
        return <StatusText orderStatus={orderStatus} />;
      },
      filterType: 'custom' as any,
      filterOptions: {
        logic: (orderStatus: any, filters: any) => {
          if (filters.length) return !filters.includes(orderStatus.status);
          return false;
        },

        display: (filterList: any, onChange: any, index: any, column: any) => {
          const optionValues = [
           'active',
'string with whitespace'
           .. more filter values
          ];
          return (
            <FormControl>
              <InputLabel htmlFor="select-status">Status</InputLabel>
              <Select
                labelId="select-status"
                id="select-status"
                value={filterList[index]}
                onChange={event => {
                  filterList[index] = event.target.value;
                  onChange(filterList[index], index, column);
                }}
              >
                {optionValues.map(item => (
                  <MenuItem key={item} value={item}>
                    {item}
                  </MenuItem>
                ))}
              </Select>
            </FormControl>
          );
        }
      }
    }
  }
```
i also recreated this issue here: [https://codesandbox.io/s/custom-filter-issue-hh5re](https://codesandbox.io/s/custom-filter-issue-hh5re)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.8.3    |
| MUI-datatables  |    2.13.4     |
| React        |    16.12.0     |
| browser      |      Chrome 80.0.3987.100   |
| etc          |         |

**Comment by wdh2100** [comment]
me too 👀

**Comment by gabrielliwerant** [comment]
So, the problem occurs due to what you are sending back as the `filterList` in the `onChange`. The `onChange` expects an array here, but you are returning a string, which is causing issues. You would still receive issues here even when using strings with no spaces. You have to either ensure you are sending an array or use the `multiple` prop in the `Select` which changes values to arrays for you.

This issue highlights the need for better documentation around the arguments in the `display` function, but this is not a bug as such.
