### ISSUE TITLE
Filter overlay is too small

### ISSUE THREAD

**Issue by maxkarkowski** [gregnb/mui-datatables#1193]
Similar to the request to change the filter layout, there seems to be a bug with the filter overlay as seen in the image
<img width="761" alt="20-02-13-custom-filter-issue - CodeSandbox-n2pw5" src="https://user-images.githubusercontent.com/622841/74425164-8216b600-4e53-11ea-9cec-b70f2d3624a9.png">

I have two filters active so they are side by side, but it seems that it is way too small to fit two elements in one row

## Expected Behavior
* filter toolbar should be wider or customizable

## Current Behavior
* filter toolbar ist too small to fit two filters side by side
## Steps to Reproduce (for bugs)

see codesandbox link: [https://codesandbox.io/s/custom-filter-issue-hh5re](https://codesandbox.io/s/custom-filter-issue-hh5re)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.8.3    |
| MUI-datatables  |  2.14.0      |
| React        |   16.12.0      |
| browser      |   Chrome 80.0.3987.100      |

**Comment by gabrielliwerant** [comment]
Is this a bug or a matter of taste? It looks to me like two filters do fit side by side and that they are functional.

**Comment by Flavyoo** [comment]
The way I addressed this was by creating a component and using it like this:

# add this to your table
`customFilterDialogFooter: () => <FilterDialogFooter />,`

# the component
`export const FilterDialogFooter = () => <Box width={360} />`

**Comment by gabrielliwerant** [comment]
You can change the size of the filter dialog by overriding the styles of `MUIDataTableToolbar-filterPaper`. You will need to set new `width` and `left` properties.

**Comment by maxkarkowski** [comment]
> You can change the size of the filter dialog by overriding the styles of `MUIDataTableToolbar-filterPaper`. You will need to set new `width` and `left` properties.

how can i override the styles ?
i have a theme.ts file with overrides like this
`MuiPaper: {
      root: {
        overflow: 'auto'
      }
    },`
but this will not work 
`MUIDataTableToolbar-filterPaper:{
width: 360
}`

**Comment by gabrielliwerant** [comment]
You'll need to consult the various resources available on overriding styles in material ui. There are examples of how to do so in the library, like `customize-styling`. Hyphens mean separate layers. `MuiPaper-root` translates as it is in your first example. I regret that I do not have the time to walk you all the way through, but I trust you will figure it out.

**Comment by maxkarkowski** [comment]
it is not an issue to understand the override syntax, i think it has something to do with this
<img width="1012" alt="Bildschirmfoto 2020-02-20 um 11 08 42 (2)" src="https://user-images.githubusercontent.com/622841/74923879-d0870000-53d1-11ea-9d2d-8ab92e8f6b19.png">

**Comment by Flavyoo** [comment]
You need to use:

`MUIToolbar` not `MUIDatatableToolBar`

https://material-ui.com/api/toolbar/#toolbar-api

**Comment by thiago-anjos** [comment]
I found a solution that works on newest browser: I'm using material-ui so, in my theme I override this component:
theme.overrides = {
  MuiPopover: MuiPopover(theme),
};
and in my file, I did this:
export default theme => ({
  root: {
    '& div[class*="MUIDataTableToolbar-filterPaper"]': {
      [theme.breakpoints.down('xs')]: {
        minWidth: '92%',
      },
    },
  },
});

**Comment by Npervic** [comment]
Its still unclear how these can be override when creating a theme to pass to the `<MuiThemeProvider />` I cant seem to target a  specific element under `override` and apply simple styling. Any one got some in depth info on how to achieve something like this?

**Comment by Npervic** [comment]
I don't know how this got closed by using `customFilterDialogFooter` as this has nothing to do with the original question.

**Comment by iamdevhk** [comment]
To change the size of the Filter overlay override the 
MUIDataTableToolbar:{ 
filterPaper:{
width: "450px"
}
}
This above snippet would help you increase the width. :)

**Comment by thefat32** [comment]
Mui V5 example

```ts
import { createTheme } from '@mui/material';

export const getMuiTheme = () =>
  createTheme({
    components: {
      // @ts-ignore custom component
      MUIDataTableToolbar: {
        styleOverrides: {
          filterPaper: {
              width: "450px",
          },
        },
      },
    },
  });
```

**Comment by cassioseffrin** [comment]
Follow below the only way that have worked for me:

```
import { createTheme } from '@mui/material';

export const getMuiTheme = () =>
  createTheme({
    components: {
       MuiPopover: {
                styleOverrides: {
                    paper: {
                        borderColor: divider,
                        borderStyle: 'solid',
                        borderWidth: 2,
                        borderRadius: 10,
                        minWidth: '90%'
                    }
                }
        }
    }
  });
```
