### ISSUE TITLE
Table displays wrong data on filter or search.

### ISSUE THREAD

**Issue by Flavyoo** [gregnb/mui-datatables#1194]
As the columns can take a `customBodyRender` function to render a component, when I have it return a component that uses a `<Select/>`, it seems that the wrong data is displayed in the table.
However, when the `customBodyRender` returns a component that just wraps the original value, filter and search work correctly. I know that my filter works and it uses the correct values to filter because this issue does not happen when the function just returns the original value.

An interesting thing to note, is that the rows of the data displayed are for the original rows that were filtered, but the component rendered in the column has the wrong value. It does not have the wrong value for all, but for some.

I have a feeling that the issue is because, a rerender is not occuring, or the component is rendering before the table is filtered or searched.

![Screen Shot 2020-02-16 at 5 22 54 PM](https://user-images.githubusercontent.com/14948074/74613935-3d07b380-50e1-11ea-8525-3b3eced0f396.png)

## Expected Behavior
I expect that no matter what component is returned from the `customBodyRender`, the display has the correct values.

## Current Behavior
Some components in the column are rendering the wrong initial value. When not filtering or searching, they render the correct values.

## Steps to Reproduce (for bugs)
- Create component that uses a `<Select/>`
- Have this component be rendered in a Column
- Filter the table by an option of the `<Select/>`
- Not all the components show the correct value.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  4.8.2       |
| MUI-datatables  |    2.13.3     |
| React        |      16.12   |
| browser      |      Chrome   |
| etc          |         |

**Comment by gabrielliwerant** [comment]
I'm afraid I can't reproduce this on my end. It's likely that you have a lot of code doing a lot of things, so I would need to see an example in codesandbox to understand what is going on.

**Comment by Flavyoo** [comment]
I was actually able to identify the problem. It was a mistake on my end. Essentially, I was passing the new value for the state directly to the `useState()`. By using a `useEffect` and updating the state there, this is no longer an issue.
