### ISSUE TITLE
JSON loader method

### ISSUE THREAD

**Issue by JordanKadish** [gregnb/mui-datatables#12]
## Issue

If possible, creating a JSON loader method where people can submit a headings object and rows object would be nice. This loader would autoload and map the rows under the given headings based on the keys of each object.

Example:
```
{
  {Headings:[
     "X",
     "Y",
     "Z"
  ]}
  {Users:[
    {
      "X":1,
      "Y":2,
      "Z":3
    }
    {
      "X":4,
      "Y":5,
      "Z":6
    }
  ]}
}
```
## Your Environment

| Tech         | Version |
|--------------|---------|
| mui-datatables  |     1.0.8    |
| node        |     9.2.1    |
| OS      |     Arch Linux    |

**Comment by gregnb** [comment]
Determined this is out of scope for the project and something that an individual developer should handle on their own
