### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by NickToye** [gregnb/mui-datatables#120]
I am using a date picker that allows for a clearable option, but whenever I do it throws up the above error.  Also if I have an empty value in the data it doesn't render an empty label, instead renders Unknown.

I appreciate that this is a compatibility issue, but was wondering if we were able to add null values in that it would work.

**Comment by gregnb** [comment]
I'll look into it when I get some time this weekend

**Comment by gregnb** [comment]
mui-datatables@2.0.0-beta-20 now accepts nulls

**Comment by NickToye** [comment]
I'm afraid this still doesn't work.  If I put in null as a value it still throws the same error.

eg.

```
const data = [
      ['THC123789', '123456/1', true, true, '2018-01-01', 1],
      ['THC123789', '159351/3', true, false, null, 1],
]
```

**Comment by gregnb** [comment]
https://codesandbox.io/s/403wk6omj4

Take a look at that example it has a null value working on beta-20 version

**Comment by NickToye** [comment]
Ok, turns out my lock file had a really old version - 20 beta works.  However, the sort breaks if you have a null in it.

**Comment by gregnb** [comment]
Ok I'll do a release later today let me know if anything else related to this comes up and I'll tackle that

**Comment by NickToye** [comment]
Ok.

**Comment by NickToye** [comment]
Not sure if this is related since beta 20 dropped, but getting this error:

Warning: Failed prop type: Invalid prop `children` supplied to `TableCell`, expected a ReactNode.

I narrowed it down to having a value of true like so:

```
const data = [
      ['THC123789', '234', '987', true, false],
    ];
```

Feel free to move this comment if its a separate bug, but I don't recall it breaking under the previous versions.

**Comment by NickToye** [comment]
Can confirm that date picker no longer works with your recent beta, 

https://material-ui-pickers.firebaseapp.com/demo/datepicker

**Comment by NickToye** [comment]
customRender stopped working also.

**Comment by NickToye** [comment]
ah have just realised customRender was changed to customBodyRender - so it kind of works.

**Comment by gregnb** [comment]
Ok, so the remaining issue is still data rows with just one entry? Sorry, I haven't had lot of time this week to look into issues

**Comment by NickToye** [comment]
Well I don't know if it is related, but if I have a null in my data row, and then click the filter drop down I get this error:

`index.js:1 Uncaught TypeError: Cannot read property 'toString' of undefined`

Everything else seems to work.

**Comment by gregnb** [comment]
Try beta-21

**Comment by NickToye** [comment]
Still does the same.

This happens when I click the filter icon.

**Comment by gregnb** [comment]
https://codesandbox.io/s/xrvrzryjvp

Seems to be working ok to me?

**Comment by NickToye** [comment]
I have a date-picker component, and it returns a null if there is no value.  If I remove that data the filter dropdown works.  I'm wondering then if it is the component that is not playing nicely with your component.

**Comment by gregnb** [comment]
Try to post up a sandbox so I can take a look

**Comment by NickToye** [comment]
https://codesandbox.io/s/8zzyl6yn69

Click the date cell and clear the date, then do the filter dropdown.

**Comment by massarakh** [comment]
I have the same error. How can I avoid it or make some fix?

**Comment by aprakash-sovrn** [comment]
I think I'm also running into this, any sort of work-around or resolution?

**Comment by gregnb** [comment]
Please update to the latest version. If there are still any issues please file a new issue.
