### ISSUE TITLE
Provide a custom table header.

### ISSUE THREAD

**Issue by Flavyoo** [gregnb/mui-datatables#1200]
Is it possible to create a custom table header and provide it to the table? Right now the table header does not look good on mobile devices and I wanted to create my own.
![Screen Shot 2020-02-22 at 4 14 38 PM](https://user-images.githubusercontent.com/14948074/75099395-2bb22180-558f-11ea-85e9-5d2c6209532f.png)

**Comment by gabrielliwerant** [comment]
It depends on what you mean by custom table header. You can customize the toolbar with `customToolbar` and you can pass in components for the `title` as well as override any class styles.

**Comment by Flavyoo** [comment]
I have tried modifying the toolbar. It works fine on desktop, but it is harder to get right on mobile. What do you think if I get a PR out to add this feature?

**Comment by gabrielliwerant** [comment]
I think I'd need to understand the problem in more detail before I decide that a PR would be a good thing. Here is it how it looks on iPhone X in Chrome's mobile view emulator:

![image](https://user-images.githubusercontent.com/1779564/75215062-8a2cfa80-575d-11ea-8ac3-fb496bc1539b.png)

That looks ok to me. If what you see is different, can you explain how this comes about? I may also need to see an example in codesandbox.

**Comment by Flavyoo** [comment]
I think in the example you gave it looks good. The problem starts when the header only has 1 or 2 icons.

**Comment by gabrielliwerant** [comment]
Try adding `flex: none` to `MUIDataTableToolbar-actions` and let me know if that resolves it. If so, I'll open a PR, as I think the nested flex behavior might be causing issues.

**Comment by Flavyoo** [comment]
I tried this but I still can not get it the icons to align properly. The table is taking more width than the viewport and the icons are being moved the viewport.

An option to place a custom header will useful because some tables have complex headers or need to be customized in a special way.

**Comment by gabrielliwerant** [comment]
I need a codesandbox to see what you're doing, otherwise, there is no way I can help, as I don't see your issue on my machine on in the examples. Also, not sure about the need for custom header. Everything in the header can already be customized with styles and components of your choosing.

**Comment by patorjk** [comment]
The only way I'm able to re-create this is if I input a compontent as the title:

    <MUIDataTable title={<div><div>Table Prefix - Really long</div><div>table header, table header</div></div>} data={data} columns={columns} options={options} />

However, it looks like it's solvable with some styling:

    <MUIDataTable title={<div style={{display:'flex',flexDirection:'column',width:'100%'}}><div style={{textAlign:'center'}}>Table Prefix - Really long</div><div style={{textAlign:'center'}}>table header, table header</div></div>} data={data} columns={columns} options={options} />
