### ISSUE TITLE
API to interact with filters and search externally?

### ISSUE THREAD

**Issue by normmcgarry** [gregnb/mui-datatables#1201]
## Expected Behavior

I'd love to see simple public methods for interacting with the table. For example, I'd love an easy way to filter externally from the table. My table is pretty dense with information and quite a few columns, but one column is particularly important, and outside of the table, there is a row of togglable tabs that I want to trigger a filter on the table. 
For example:
<John, Susan, Paul, Steve, Jennifer>
Something like this maybe?
`this.tableRef.filter(columnName, filterValue<Array<str>|str)`

## Current Behavior

I'm inspecting the source code, and there seems to be an `updateFilter` method, but it seems more for internal usage and the API is rather undocumented.
`this.tableRef.filterUpdate(columnIndex, newValue, columnName, filterType);`

In this context, specifying the filterType and columnIndex isn't ideal for external usage.

## Steps to Reproduce (for bugs)

N/A

## Your Environment

N/A

**Comment by GeenCo86** [comment]
Did you find a way?

**Comment by porfyriosv** [comment]
Any updates on this ?
