### ISSUE TITLE
How to add an "Apply Filters" button to the filters, in order to avoid calls every time a filter changes?

### ISSUE THREAD

**Issue by rpelorosso** [gregnb/mui-datatables#1204]
Hi!

Is it possible to have the filters applied only when pressing an "Apply filters" button? 

When having a large remote database, I'd like to avoid it making requests every time a filter changes, more so if using textField.

I've found [this PR](https://github.com/gregnb/mui-datatables/pull/1093) but it was never merged.

Is there a way to do this?
thank you! 

Rodrigo

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.9.0    |
| MUI-datatables  | 2.14.0        |
| React        |     16.12.0    |

**Comment by gabrielliwerant** [comment]
Serverside filters allows you to create this custom behavior, though it will take some work on your end to set up. See the `serverside-filters` example for a demonstration of how to do this to get you started.

**Comment by patorjk** [comment]
This has been simplified for version 3.0.0. You now just need to set the "confirmFilters" option to true, and then invoke the applyFilters callback in the customFilterDialogFooter option to add the filters. No more managing filterLists.

You can find an example here: https://github.com/gregnb/mui-datatables/blob/master/examples/serverside-filters/index.js
