### ISSUE TITLE
Filter on individual column

### ISSUE THREAD

**Issue by isidius92** [gregnb/mui-datatables#1208]
Hello MUI-Datatables community 😊,
Is there is a way to add the filter icon on each column cell header and then create a filter for individual column?
Thank you in advance for your response,

Have a good day.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gabrielliwerant** [comment]
Not yet, but there is a PR open for it, although the approach troubles me a bit, as I think the code needs better abstraction around it. Closing this as a duplicate.
