### ISSUE TITLE
Set default sorting not working

### ISSUE THREAD

**Issue by Eithcowich** [gregnb/mui-datatables#1209]
I need to sort the table on a column when it first loads. Is this possible? It's not working for me so far, and is a really important feature. 

The column definition is 

    {
       name: "totalNumMembers",
       label: "Members",
       options: {
             filter: true,
             sort: true,
             options: { sortDirection: 'desc' }
         }
    },

this is the only column that has `sort: true`.

The table definition:

      <MUIDataTable
           title={"Analyzed DAOs"}
           data={data.hits}
           columns={columns}
           options={options}
     />

But when the table loads it is not sorted at all. How do I solve this on the client?

**Comment by wdh2100** [comment]
```
{
   name: "totalNumMembers",
   label: "Members",
   options: {
         filter: true,
         sort: true,
         options: { sortDirection: 'desc' }
     }
},
```

https://github.com/gregnb/mui-datatables#column-options

```

{
   name: "totalNumMembers",
   label: "Members",
   options: {
         filter: true,
         sort: true,
         **sortDirection: 'desc',**
     }
},
```

**Comment by Eithcowich** [comment]
Ugh, I missed it. Works now, thanks.

**Comment by anonimeishon** [comment]
Not working for me, when i do 
```{
   name: "totalNumMembers",
   label: "Members",
   options: {
         filter: true,
         sort: true,
         sortDirection: 'asc',
     }
},```

it sorts the column on a desc order

**Comment by EdwardMartin123** [comment]
> Not working for me, when i do
> 
> ```
>    name: "totalNumMembers",
>    label: "Members",
>    options: {
>          filter: true,
>          sort: true,
>          sortDirection: 'asc',
>      }
> },
> ```
> 
> it sorts the column on a desc order

I'm having the same problem - 

>options: {
>                filter: true,
>                sort: true,
>                draggable: true,
>                sortDescFirst: false,
>                sortDirection: "asc"
>            }

still sorts in the wrong order and nothing seems to be able to change it

**Comment by anonimeishon** [comment]
> > Not working for me, when i do
> > ```
> >    name: "totalNumMembers",
> >    label: "Members",
> >    options: {
> >          filter: true,
> >          sort: true,
> >          sortDirection: 'asc',
> >      }
> > },
> > ```
> > 
> > 
> > it sorts the column on a desc order
> 
> I'm having the same problem -
> 
> > options: {
> > filter: true,
> > sort: true,
> > draggable: true,
> > sortDescFirst: false,
> > sortDirection: "asc"
> > }
> 
> still sorts in the wrong order and nothing seems to be able to change it
Try
'''
     const options = {
        sortOrder: {
            name: 'id',
            direction: 'asc',
        }
'''
