### ISSUE TITLE
Disabling sort for a single column doesn't seem to work

### ISSUE THREAD

**Issue by kirstenland** [gregnb/mui-datatables#121]
The documentation says you can enable/disable sort for the whole table, or for each column individually. Currently only enabling/disabling sort for the whole table seems to have any effect.

## Expected Behavior

According to the documentation, you should be able to enable or disable sorting for a particular column with the options, e.g. if the columns are:
`const columns = [
 {
  name: "Name",
  options: {
   filter: true,
   sort: false
  }
]
`
then sorting should be disabled on the name column (even if sort is true in the options passed to the table).

If sort is true in the table options (default), then sort should be enabled/disabled depending on the options for each column.
If sort is false in the table options, then sort should be disabled for all columns.
## Current Behavior

If sort is true in the table options, then sort is enabled for all columns.
If sort is false in the table options, then sort is disabled for all columns.

## Steps to Reproduce (for bugs)

See here for the standard example modified to attempt to make the name column have sort disabled.
https://codesandbox.io/s/oo5kjmvz2q
However, you can still sort by name (in the non-stacked view) by clicking on the Name header.

## Fix?
I think I can fix this by changing the dataTableHeadCell to consider both props.options.sort and props.sort, I can submit a pull request possibly I think?

**Comment by gregnb** [comment]
Sounds like a great idea!
