### ISSUE TITLE
Changing Page Whilst Keeping Select Header Visible - Serverside

### ISSUE THREAD

**Issue by heymega** [gregnb/mui-datatables#1210]
I'm trying to get the custom select header to show (and stay) visible as the user changes pages. Since I'm fetching my data serverside its proving difficult.

![image](https://user-images.githubusercontent.com/5940664/75904137-90e0ff00-5e3a-11ea-8461-c2e541b5add6.png)

It is my understanding that the custom select header shows up depending on whether or not there are items in the `selectedRows` array. If any of the items indexes match an index in the data then it will be selected.

In terms of managing this serverside, the only thing I think of is to manage two lists. One to control the selected items by id and the other to manage the `selectRows` index-based list.

**Example**

1. User selects the first row...

```
selectedRows = [0]
mySelectedList = ['c9b13fcb-d9af-4281-94d8-3bb6543a4a4d']
```
2. User navigates to the next page

Iterate over the data rows and see if any of the IDs are in `mySelectedList`. If they are, add the index of the datarow to `selectedRows`. 

```
selectedRows = [] 
mySelectedList = ['c9b13fcb-d9af-4281-94d8-3bb6543a4a4d']
```

Whilst this works the custom select header has now disappeared because there's nothing in the `selectedRows` array.

The only thing I can think of is to add dummy values to the `selectedRows` like this...

```
selectedRows = [-1] 
mySelectedList = ['c9b13fcb-d9af-4281-94d8-3bb6543a4a4d']
```

Is there a better way of doing this?

**Comment by wdh2100** [comment]
I think it's gonna be hard...

You have to make Custom Header, save selectedRows Index or Data and etc....

**Comment by gabrielliwerant** [comment]
There is no `selectedRows` option. There is a `rowsSelected` option, which you need to populate and track if you're using serverside.
