### ISSUE TITLE
How to use isDeselect on a row

### ISSUE THREAD

**Issue by christiantigre** [gregnb/mui-datatables#1211]
## How to use isDeselect on a row
I need uncheck a active check on my MUIDataTable but, I can't find documentation for this funcion isDeselect since a function.

**Comment by wdh2100** [comment]
Shouldn't we exclude selected data from the entire data?

**Comment by gabrielliwerant** [comment]
There is no `isDeselect`. Use `onRowsSelect`, it fires any time the select is clicked, whether on or off. The first argument tells you the row.
