### ISSUE TITLE
Upgrade to Material UI 4

### ISSUE THREAD

**Issue by rhuanbarreto** [gregnb/mui-datatables#1213]
I'm using material UI 4 and I'm getting these warnings on `npm install`:

```
npm WARN mui-datatables@2.14.0 requires a peer of @material-ui/core@^3.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN mui-datatables@2.14.0 requires a peer of @material-ui/icons@^3.0.1 but none is installed. You must install peer dependencies yourself.
```

Is there a plan to upgrade material ui to v4?

**Comment by gabrielliwerant** [comment]
Yes https://github.com/gregnb/mui-datatables/pull/1077, but not sure on timeline.

**Comment by nativanando** [comment]
Hi @rhuanbarreto I've got the same problem with Material UI 4. Have you already solve it?

**Comment by rhuanbarreto** [comment]
I didn't solve. It works fine with material UI 4, but I wanted to have the warning fixed, so I asked 😄
