### ISSUE TITLE
How do I change the tables font color? 

### ISSUE THREAD

**Issue by Eithcowich** [gregnb/mui-datatables#1214]
I created a theme, which works for everything else, but not for the font color. I tried any of the options inside the `root` element, but none of them works. 

    MUIDataTable: {
        root: {
             textColor: 'red',
             fontColor: 'red',
             color: 'red',
       },
    }

How should I do it? I want the font color to be white.

**Comment by wdh2100** [comment]
ref : https://github.com/gregnb/mui-datatables/blob/master/examples/customize-styling/index.js


setRowProps | function |   | Is called for each row and allows you to return custom props for this row based on its data. function(row: array, dataIndex: number) => object Example
-- | -- | -- | --
setTableProps | function |   | Is called for the table and allows you to return custom props for the table based on its data. function() => object Example

**Comment by gabrielliwerant** [comment]
If you want to modify the style directly, you need to modify `MuiTableCell-body`.

**Comment by Eithcowich** [comment]
I tried this inside my MuiTheme: 

        MuiTableCellBody: {
              root: {
                 background: 'green',
                 color: 'blue',
              }
         },

But it has no effect.

**Comment by gabrielliwerant** [comment]
Hyphens mean different layers of nesting. You should research JSS and material ui styling.

**Comment by Eithcowich** [comment]
Any chance for a complete update? Thanks.
