### ISSUE TITLE
Customize background color for the whole space a cell takes

### ISSUE THREAD

**Issue by Eithcowich** [gregnb/mui-datatables#1215]
I need to customize the background color of a table column based on its value. The code below works only for the area around the text -- and **not** the whole space the cell takes. 

This is the code: 

        customBodyRender : (value, tableMeta, update) => {
             let color = value === 'Pass' ? 'green' : 'red'
             return (
                 <span style={{backgroundColor: color}}>{value}</span>
             )
        }

The result looks like this:  

![Screen Shot 2020-03-07 at 12 19 02 PM](https://user-images.githubusercontent.com/6975895/76141531-fc5ee280-606d-11ea-92aa-4729318063ed.png)

I need it like this, with the whole space the cell takes colored: 

![Screen Shot 2020-03-07 at 12 19 12 PM](https://user-images.githubusercontent.com/6975895/76141538-08e33b00-606e-11ea-95ba-bbf30a04341c.png)

Is there a way to achieve this in `mui-datatables`?

**Comment by wdh2100** [comment]
{
        name: "Outcome",
        options: {
          setCellProps: (value) => {
            return {
              className: classnames(
                {
                  [this.props.classes.PassCell]: value === "Pass",
                  [this.props.classes.FailCell]: value === "Fail",
                })
            };
          },
        }
      }

**Comment by Eithcowich** [comment]
Thanks @wdh2100, this works great.
