### ISSUE TITLE
Sort options in documentation

### ISSUE THREAD

**Issue by sebastiendan** [gregnb/mui-datatables#1218]
More an improvement than an issue: could you sort alphabetically the lists of options (general and column specific).

Would be much easier to find what we need!

Thanks for the very nice library 👍

**Comment by wdh2100** [comment]
function getCollatorComparator() {

**Comment by gabrielliwerant** [comment]
I believe there is a PR up for this.

**Comment by sebastiendan** [comment]
The title of this issue was clear but the content wasn't so much: I am referring to the documentation of this library, not the code. The README lists two quite long tables of options (for the table and for the column) but those lists aren't alphabetically ordered which makes finding a specific one a hassle.

**Comment by gabrielliwerant** [comment]
@sebastiendan Yep, I'm referring to the documentation as well. There's a PR up to alphabetize it now.
