### ISSUE TITLE
Search bug (count doesn't change after search)

### ISSUE THREAD

**Issue by pavlovicIvan** [gregnb/mui-datatables#122]
## Expected Behavior

Search bug (count doesn't change after search) - after successful search, total number of rows should be according to search results
## Current Behavior

Total number of rows is same after searching (example: there are 2 results after search but total number of rows is still unchanged: 30)

## Your Environment

| Tech         | Version |
|--------------|---------|
| MUI-datatables  |  2.0.0-beta-19  |

**Comment by gregnb** [comment]
I'm not seeing this issue? https://wy2rl1nyzl.codesandbox.io/
If I search 'Business Analyst' I get five results and it prints 5 results at the bottom

![screen shot 2018-08-03 at 5 51 31 pm](https://user-images.githubusercontent.com/19170080/43667429-e198c436-9745-11e8-9666-a410b647f5e2.jpg)

**Comment by pavlovicIvan** [comment]
Hmm.. please can you check this link: https://codesandbox.io/s/r4jn0l4lxq
It is beta-19 and total count doesn't changing.

**Comment by gregnb** [comment]
You're right there is a bug in -19 thanks for reporting. I will look into it

**Comment by gregnb** [comment]
This should be resolved in mui-datatables@2.0.0-beta-20
