### ISSUE TITLE
Print option stacks columns unnecessarily for each row vs. horizontal columns being used 

### ISSUE THREAD

**Issue by mostlyfabulous** [gregnb/mui-datatables#1222]
When using the print option on a table, the table stacks columns for each row vertically instead of horizontally which makes the printed table unfriendly for use.

## Expected Behavior
Printing should layout the table as is seen in the web browser.

## Current Behavior
Printing causes the table to be reformatted to have columns stacked for each entry/row.
![Annotation 2020-03-12 233244](https://user-images.githubusercontent.com/15062048/76595786-d1cfb800-64b9-11ea-987c-782785b1fe83.png)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  | 4.0.0 |
| MUI-datatables  | 2.14.0 |
| React        | 16.13.0 |
| browser      | Chrome, Edge |
| etc          |         |

**Comment by gabrielliwerant** [comment]
Printing follows the `responsive` option along with any styles added to those, so change your `responsive` to affect this. Otherwise, it uses default.

**Comment by mostlyfabulous** [comment]
Thank you for the clarification, it might be worth adding that information to the guide :)
One other question, is there a way to hide the rows per page and pagination UI in the print mode as well? It gets overlaid on top of the data when printing.

![Annotation 2020-03-16 172252](https://user-images.githubusercontent.com/15062048/76810303-cbd42280-67aa-11ea-8652-e9f09ef9699b.png)

**Comment by gabrielliwerant** [comment]
@mostlyfabulous Anywhere that you can add the `.datatables-noprint` class, you can hide it in printing mode. You might need custom render options to put the class in certain areas, otherwise look for custom props options to add it.

**Comment by mostlyfabulous** [comment]
@gabrielliwerant Thank you very much!
