### ISSUE TITLE
Window resize changes table layout unexpectedly

### ISSUE THREAD

**Issue by appukuttan-shailesh** [gregnb/mui-datatables#1225]
## Expected Behavior
I have two tables with several columns in each, but only two of the columns (Name, Author) are initially set to be displayed. On resizing the browser window, I expect the layout of the columns to remain the same, with the horizontal scrollbar for each table accomodating the available display space.

## Current Behavior
When I resize the browser window (such as in the screen capture below), I see that the layout of the tables change for small window sizes. It starts to show the two column headers (Name, Author) on the rows for each entry. The actual value of these columns cannot be viewed even by scrolling to the right of these rows.

![Screen Capture](https://i.ibb.co/HK5t3Tj/Peek-2020-03-15-12-05.gif)

## Steps to Reproduce (for bugs)
Outline of my code for one of the tables:
```
<MUIDataTable
            title="Tests"
            columns={[
                      {name:'Name', options: {display: true}},
                      {name:'Alias', options: {display: false}},
                      {name:'Status', options: {display: false}},
                    ]
                    }
            data={this.state.data.map(item => {
              return [
                      item.id,
                      item.name,
                      item.status,
                    ]
            })}
            options={{
              filter: true,
              sort: true,
              rowsPerPage: 20,
              rowsPerPageOptions: [10, 20, 100],
              onRowClick: this.props.handleRowClick,
              responsive: 'stacked', // 'scrollMaxHeight', 'scrollFullHeight', 'scrollFullHeightFullWidth', 'stackedFullWidth'
            }}
        />
```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.9.4   |
| MUI-datatables  |  2.14.0   |
| React        |   16.12.0   |
| browser      | Google Chrome Version 80.0.3987.132 (Official Build) (64-bit) |

**Comment by wdh2100** [comment]
https://codesandbox.io/s/muidatatables-custom-toolbar-ykj7y

![asdasd](https://user-images.githubusercontent.com/16433770/76702423-1bfca780-670d-11ea-888b-5c2e8ecc1bdf.gif)

um....
This issue cannot be reenacted

**Comment by gabrielliwerant** [comment]
@appukuttan-shailesh This table has default responsive behavior which you can change via the `responsive` option. See docs for more info.

**Comment by appukuttan-shailesh** [comment]
Thanks @wdh2100 and @gabrielliwerant for looking at this. I agree that the problem goes away by setting `responsive:scroll` (or `scrollMaxHeight` as the former is now deprecated). But the problem here is that the height of the table is much reduced when using this, i.e. it doesn't even cover the available display space. How does one workaround this?

**Comment by appukuttan-shailesh** [comment]
If instead I use `scrollFullHeightFullWidth` then the tables overlap weirdly as seen here:
https://codesandbox.io/s/muidatatables-custom-toolbar-8z657

Same with `scrollFullHeight`:
https://codesandbox.io/s/muidatatables-custom-toolbar-y6sn7

**Comment by arunkmr25** [comment]
@appukuttan-shailesh can you please help on how you achieved 'stacked' for lower resolution and scroll for higher ones!

**Comment by appukuttan-shailesh** [comment]
@arunkmr25 : I haven't yet made much progress on this. I am still facing the problems mentioned in my previous posts. 

@wdh2100 , @gabrielliwerant : any suggestions on how to proceed?
