### ISSUE TITLE
onRowsSelect I need the row data too. or if possible change the dataindex to with my own un-ID .

### ISSUE THREAD

**Issue by soomay55** [gregnb/mui-datatables#1226]
## Steps to Reproduce (for bugs)

onRowsSelect: (rowsSelected, allRows) => {               
                
            console.log(rowsSelected, allRows);
            
            this.setState({ rowsSelected: allRows.map(row => row.dataIndex) });
            console.log(allRows)
            
                 }

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     ^4.9.5    |
| MUI-datatables  |  ^2.14.0       |
| React        |    ^16.2.0     |
| browser      |         |
| etc          |         |

**Comment by wdh2100** [comment]
onRowsSelect | function |   | Callback function that triggers when row(s) are selected. function(currentRowsSelected: array, allRowsSelected: array) => void
-- | -- | -- | --


ref : https://codesandbox.io/s/muidatatables-custom-toolbar-0j54b
