### ISSUE TITLE
Max height in scrollMaxHeight mode

### ISSUE THREAD

**Issue by honzasram** [gregnb/mui-datatables#1227]
Hi,

First off, I'd like to thank you for everyone's hard work. It is amazing component and most of the time is is pleasure to work with it.
However there is one small and really frustrating problem. [This line](https://github.com/gregnb/mui-datatables/blob/4f836096a56be93ee1322f3c98cbaca485f0b064/src/MUIDataTable.js#L1371) contains very static value. So far i do not know how to overwrite it as it is applied as element style. Which means I can overwriting hell of styles, but this will remain there as last applied value. 

Is this intentional? How am i supposed to stretch it to given height of view? I managed to get it working in version 2.13.3, but on latest 2.14 it is with this value 

This is newer version:

![image](https://user-images.githubusercontent.com/9151345/76798188-67778a00-67cf-11ea-85f1-8d3c0d7514a6.png)

This is older one with same overrides and settings:
![image](https://user-images.githubusercontent.com/9151345/76798725-68f58200-67d0-11ea-8579-12a5ad2968de.png)

**Comment by wdh2100** [comment]
ref

responsive | string | 'stacked' | Enable/disable responsive table views. Options: 'stacked', 'scrollMaxHeight' (limits height of table), 'scrollFullHeight' (table takes on as much height as needed to display all rows set in rowsPerPage), 'scrollFullHeightFullWidth' (same as 'scrollFullHeight' except that paper container wraps the table and the width takes the full browser window), 'stackedFullWidth' (same as stacked with the addition of the paper container changes with 'scrollFullHeightFullWidth') ('scroll' option has been deprecated in favor of scrollMaxHeight)
-- | -- | -- | --

**Comment by honzasram** [comment]
scrollFullHeight won't work. It will allow to overflow and create scroll on whole table, not on rows section. I tried that.

scrollFullHeight - will show all rows
scrollMaxHeight - limit height and allow scrollable rows portion (keeps footer visible)

I want scrollMaxHeight to max out on my own value.

**Comment by wdh2100** [comment]
That's right. The user can't change the value with the options.

**Comment by wdh2100** [comment]
@gabrielliwerant  
Can I add MaxHeight to the options?

**Comment by honzasram** [comment]
@wdh2100 
I went thru all issues regarding this and I had feeling like this is intentional. Reasoning is not clear to me, tough. 
Setting style after render seems to me like really ugly hack. I'm sure this is either a bug or an feature.

**Comment by gabrielliwerant** [comment]
@honzasram You are correct that this style should be applied with a class and not directly. I have been aware of this issue, but I do not have much time, so have not fixed it yet.

**Comment by rpateld** [comment]
import css : 
`.MUIDataTable-responsiveScrollMaxHeight-784 {
  position: relative !important;
  max-height: 999px !important;
}`

**Comment by Belisarith** [comment]
Thank you all for the great library.
But wow, I really struggled with setting the maxheight. Somehow, when you look at the source code there is a fixed max height of 499px. As mentioned in other issues, you can override the theme. However, as the style precedes the class, you have to use important. THis was what I used in the end. Hope this helps. Maybe, we could update the documentation for this. Especially what classnames to override:
`  const theme = createMuiTheme({
    overrides: {
      //@ts-ignore
      MUIDataTable: {
        responsiveScrollMaxHeight: {
          maxHeight: `${height - 150}px !important`
        }
      }
    }`

`<MuiThemeProvider theme={theme}>
      <MUIDataTable
        title={"Visio Files"}
        data={data}
        columns={columns}
        options={{
          download: false,
          print: false,
          rowHover: false,
          expandableRows: true,
          selectableRows: "none",
          responsive: "scrollMaxHeight",`

and so on....

**Comment by danielmgzzg** [comment]
Hi guys I tought I would share a config that is working for me:

- First import the createBreakpoints hook to be able to use breakpoints when creating the theme for our data table
`import createBreakpoints from "@material-ui/core/styles/createBreakpoints";
`

- Then create a theme by importing 


   `import { createMuiTheme, MuiThemeProvider } from "@material-ui/core/styles";`

- in `const getMuiTheme = () =>    createMuiTheme({ ... `  set an option for `minHeight` with breakpoints and adjust according to your table, this is the config I used:

```
overrides: {
        MUIDataTable: {
          responsiveScrollMaxHeight: {
            [breakpoints.up("lg")]: {
              minHeight: window.innerHeight - 280,
            },
            [breakpoints.down("md")]: {
              minHeight: window.innerHeight - 300,
            },
            [breakpoints.down("sm")]: {
              minHeight: window.innerHeight - 310,
            },
          },
        },
```

- Don't forge to set `responsive: "scrollMaxHeight"` on the options

- Wrap the data table with the created theme and feed the options
```
 <MuiThemeProvider theme={getMuiTheme()}>
        <MUIDataTable data={data} columns={columns} options={options} />
      </MuiThemeProvider>
```

Maybe there is a way to calculate the window offset so it adapts automatically but I haven't tried that option

hope it's helpful

**Comment by rpateld** [comment]
It works @danielmgzzg  thanks.
just add one more line `const breakpoints = createBreakpoints({})`

**Comment by patorjk** [comment]
As of version 3.0.0, there are two new options for controlling the table height:

* tableBodyHeight
* tableBodyMaxHeight

The responsive option has also been simplified to use just 3 options: standard, vertical, simple

Though all old responsive values will still work.
