### ISSUE TITLE
Reversing the sorting direction

### ISSUE THREAD

**Issue by patryknawolski** [gregnb/mui-datatables#1230]
Is there an option in mui-datatables API to reverse the sorting directions in a way that after clicking sortable header column for the first time the column will be sorted in an ascending order?

## Expected Behavior
After clicking header of any sortable column for the first time should be sorted in ascending order. after clicking it second time it should be sorted in descending order.

## Current Behavior
After clicking header of any sortable column for the first time should be sorted in descending order. after clicking it second time it should be sorted in ascending order.

**Comment by wdh2100** [comment]
sortDirection | string |   | Set default sort order enum('asc', 'desc', 'none') (null option has been deprecated, use 'none' instead)
-- | -- | -- | --

**Comment by patryknawolski** [comment]
> sortDirection	string	 	Set default sort order enum('asc', 'desc', 'none') (null option has been deprecated, use 'none' instead)

This is for changing the default sorting, not changing the order of sorting directions.

**Comment by patorjk** [comment]
Updated as of version 3.0.0
