### ISSUE TITLE
Table row doubleclick

### ISSUE THREAD

**Issue by am0nshi** [gregnb/mui-datatables#1231]
Hi guys, is there a way to operate with row doubleclick event? Any kind of search in issues here and researching of source code has no luck.

Thank you for reply,
Nike

**Comment by patorjk** [comment]
Yes, double click events can be added via setRowProps option. Example:
```
setRowProps: () => ({
  onDoubleClick: (row, dataIndex) => {
    alert("Double click!");
  }
}),
```

**Comment by AlCalzone** [comment]
For anyone stubling across this, the correct signature is
```js
setRowProps: (row, dataIndex) => ({
	onDoubleClick: event => {
		alert("Double click!");
	}
}),
```
