### ISSUE TITLE
onRowsSelect function brings it as if it was selected

### ISSUE THREAD

**Issue by ermancom** [gregnb/mui-datatables#1232]
Hi, Firstly thank you for component. I have a problem with onRowsSelect function. if you selected a row and then unchecked it, when you select other one of the rows again, It appears like not selected but function brings it as if it was selected;
for example ;

const handleRowSelected = (currentRowsSelected, allRowsSelected) => {   
    console.log("currentRowsSelected :");
    console.log(currentRowsSelected);
    console.log("allRowsSelected :");
    console.log(allRowsSelected);

  if(allRowsSelected && allRowsSelected.length >0)  
     setEditBtnDisable(false);
  else
     setEditBtnDisable(true);
}

const columns = [{ name: "_id", label: "_id",options: {display:false}},
                 { name: "firstName", label: "First Name", options: {sort: true}},
                 { name: "lastName", label: "Last Name", options: {sort: true,}},
                 { name: "userName", label: "Username", options: {sort: true,}},
                 { name: "email", label: "Email", options: { sort: true}},
                 { name: "mobilePhone", label: "Mobile Phone"},
                ];

                let sortColumnName = Object.keys(formState.sort)[0];
                    let colIndex =columns.findIndex(value => value.name === sortColumnName );
                columns[colIndex].options.sortDirection = formState.sort[sortColumnName];

const options = {  
                 filter     : false
                ,search     : false
                ,serverSide : true
                ,count      : formState.totalPage
                ,rowsPerPage: formState.limit
                ,rowsPerPageOptions:[5,10,15,20]
                ,onTableChange:handleTableChange
                ,selectableRows:'single'
                ,selectableRowsOnClick:true
                ,disableToolbarSelect:true
                ,responsive:'stacked'
                ,onRowsDelete:(rowsDeleted) => false
                ,onRowsSelect:handleRowSelected
                ,setTableProps: () => {
                                        return {
                                                size: "small"
                                               };
                                      }
                };

 Material-UI     | 4.9.5   |
 MUI-datatables  | 2.14.0  |
 React           | 16.13.0 |
 browser         | Google Chrome latest|
  
![bug](https://user-images.githubusercontent.com/18524467/77531235-838fc100-6e8a-11ea-8c6b-33f07c1a11ad.gif)

**Comment by wdh2100** [comment]
![asdasdasd](https://user-images.githubusercontent.com/16433770/79230095-0fe83f00-7e9f-11ea-8e04-53d642debee0.gif)

https://codesandbox.io/s/muidatatables-custom-toolbar-vkrhe


I can't reproduce

**Comment by ermancom** [comment]
Thank you for your response. I realized that  if you change  a state object in rowSelected function, muidatatable does not render. Please look at this example. I want  to enabled a button when  a row selected. If It wish  onRowSelected function return promise.resolve with parameters so you rendered 
it afterwards we would rendered. For example ;   
https://codesandbox.io/s/muidatatables-custom-toolbar-pegsd?file=/index.js

**Comment by ermancom** [comment]
I apologize for losing time, I could not realize. I was suppose to assign the rowsSelected acquired in  OnRowSelected function  to grid option rowsSelected array field.

const [rowsSelected,setRowsSelected] = useState([]);

in  OnRowSelected
setRowsSelected(allRowsSelected.map(row => row.dataIndex));

in grid option like this
                    ,selectableRows:'single'
                    ,selectableRowsOnClick:true
                    ,responsive:'stacked'
                    ,rowsSelected:rowsSelected     /* this is array we need to feed again to option.
                    ,onRowsSelect:handleRowSelected
