### ISSUE TITLE
Sorting lost while selecting row/re-rendering

### ISSUE THREAD

**Issue by aditidave17** [gregnb/mui-datatables#1237]
## Expected Behavior
Once column header is clicked to sort an column, it gets sorted. After that if a row is selected/custom button column is clicked, the sorted column should remain as it is. 

## Current Behavior
Sorted column is lost if row is selected or button column is clicked.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.8    |
| MUI-datatables  |   2.13.3    |
| React        |    16.12     |
| browser - Chrome  |   78    |
| etc          |         |

**Comment by wdh2100** [comment]
Do you use server-side? 

So see the below example

https://github.com/gregnb/mui-datatables/blob/master/examples/serverside-sorting/index.js

**Comment by patorjk** [comment]
This is fixed as of version 2.15.0 (latest version is 3.0.0).
