### ISSUE TITLE
unexpected behavior with resizableColumns when column-width < cell-content-width

### ISSUE THREAD

**Issue by caligo-erik** [gregnb/mui-datatables#1240]
When resizing columns where the text-content is "un-wrappable", I'd expect the text to abbreviated and to show an ellipsis [...]

E.g. "account.error.account.exists.with.email.address.title".

## Expected Behavior

The text should be shortened and show an ellipsis, or a horizontal scrollbar could be displayed

## Current Behavior

When reducing the width of the column "below the minimum width needed to show the content", the column borders follow the re-size, but the content remains visible. Furthermore, it resizes other columns 

## Steps to Reproduce (for bugs)

1. take your _.../mui-datatables/examples/resizable-columns/index.js_ and change the following line: 
```javascript
    const data = [
      [
        "account.error.account.exists.with.email.address.title",  // not wrappable text
        "Business Analyst",
        "Minneapolis",
        30,
        "$100,000"
      ] 
```
2. run the project and check the resizable columns example
3. reduce the width of the first column

## Your Environment

dependencies: {
    "@material-ui/core": "^4.9.8",
    "@material-ui/icons": "^4.9.1",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "mui-datatables": "^2.14.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
}
| Tech         | Version |
|--------------|---------|
| browser   |   chrome: Version 80.0.3987.149 (Official Build) (64-bit)      |
| Ubuntu     |  18.04   |

**Comment by patorjk** [comment]
This has been resolved as of version 3.0.1 of the library. The effect you're asking for requires some CSS to get working. You can see an example of how to do the text-overflow ellipsis with resizable columns here: (see "Business Title" column)

https://codesandbox.io/s/muidatatables-custom-toolbar-zomv5?file=/index.js
