### ISSUE TITLE
disable this auto focus in search input

### ISSUE THREAD

**Issue by naothomachida** [gregnb/mui-datatables#1243]
Hi everyone!

I'm using option "searchOpen: true"

When aplicattion starts is auto focus in search input

How can I disable this auto focus in search input?

**Comment by tomduval** [comment]
@naothomachida did you figure this out?

**Comment by tomduval** [comment]
@naothomachida actually I've just figured this out so let me know if you want any help

**Comment by davegyerek** [comment]
@tomduval can you tell how how did you manage to do this?

**Comment by tomduval** [comment]
@davegyerek you can override the default search using "customSearchRender" in the options. Then copy [`TableSearch`](https://github.com/gregnb/mui-datatables/blob/master/src/components/TableSearch.js) component into a new file. Set autoFocus={false} within that component (or just remove autoFocus). Import the component in and set customSearchRender: CustomSearchComponent... 

Hope this help! Let me know if you have issues.

**Comment by naothomachida** [comment]
Hi tom, thanks

This solve the problem, but autofocus true is makes more sense

I've been notified in my e-mail about this issue, so I will close this now

**Comment by fe-lix-werner** [comment]
A better/updated solution is to use extend the options given to the TableSearch. I'm using TypeScript so for me it is:

```
....
customSearchRender: (
                        searchText: string,
                        handleSearch: (text: string) => void,
                        hideSearch: () => void,
                        options: any
                    ) => (
                        <TableSearch
                            searchText={searchText}
                            onSearch={handleSearch}
                            onHide={hideSearch}
                            options={{
                                ...options,
                                searchProps: {
                                    autoFocus: false,
                                },
                            }}
                        />
....
```
