### ISSUE TITLE
How can I add a button in the data fields. I'm only able to pass data as strings right now.

### ISSUE THREAD

**Issue by piyush97** [gregnb/mui-datatables#1246]
How can I add a button in the data fields. I'm only able to pass data as strings right now. and even in column

**Comment by piyush97** [comment]
or even any jsx?

**Comment by SwapnilShoreline** [comment]
I also want to add a custom table cell progress bar and button in one table cell.
Please see the below image
![Screenshot from 2020-03-18 14-59-06](https://user-images.githubusercontent.com/57210114/78798011-1c1f5880-79d6-11ea-9d8b-4562d71e6a17.png)

**Comment by SwapnilShoreline** [comment]
how to add multiple Views (Button, TextField, Progress Bar, Image ) into one table cell
