### ISSUE TITLE
Feature Request: Custom filter list

### ISSUE THREAD

**Issue by jmarucha** [gregnb/mui-datatables#125]
For the data provided from external source, such as database, providing custom list of avialable filters would be extremaly useful.

## Current Behavior

The filter options are based on the data passed to the component. For the data:
```
[1, 'a']
[2, 'b']
[3, 'a']
```
avialable filters on column 2 are 'a' and 'b'
## Expected Behavior

A user should be able to provide list of filters to override the possible filter options via custom column field. Passing
```
columns = [
 {
     name: "ID",
     options: {
       filter: false,
       sort: true,
  }
  {
    name: "value",
    options: {
      filter: true,
      filterOptions: [
        'a', 'b', 'c', 'd'
      ]
    }
  }
];
```
As columns option should make filtering by 'a', 'b', 'c', 'd' on column 'value' avialable regardless of options.

**Comment by gregnb** [comment]
There is an option to allow you to specify the filter list. Take a look at example located here:
https://github.com/gregnb/mui-datatables/blob/master/examples/serverside-options/index.js

**Comment by gregnb** [comment]
Sorry, misunderstood a provided filterList for filterOptions. Ok, I'll get back to you on this.

**Comment by toolaugh** [comment]
I have the same problems like @jmarucha . I want to custom filter list menu options . and wonder how to custom ?

**Comment by toolaugh** [comment]
I also want to custom styles of filter view like width and height ? Let me know how to how to use ? @gregnb

**Comment by phelion** [comment]
Hi, what is the progress with this request? I'd really need to add custom filter options, because I don't always query all the data from the database, and then the values what are not in the list, but it's possible to exist, not showing in the filter options.

**Comment by gregnb** [comment]
This is now available in the latest release. There are two column options `filterList` and `filterOptions`.  I have removed the `filterList` from the root level options and now they must be provided per column.

Look at the README for an example. Thanks for all your patience.

**Comment by dafapramudya** [comment]
Hi @gregnb how can I custom filter type on each column? for ex: I have 3 columns: username(filterType: 'textField'), date(filterType: 'multiselect'), age(filterType: 'dropdown').

I already tried this on each column, but didn't work:

```
column: [
      {
        name: 'Username',
        options: {
          filter: false,
          sort: false,
          filterType: 'textField',
        },
      },
      {
        name: 'Date',
        options: {
          filter: true,
          sort: false,
          filterType: 'multiselect',
        },
      },
      {
        name: 'Age',
        options: {
          filter: true,
          filterType: 'dropdown',
          sort: false,
        },
      }
]
```

**Comment by rayray93** [comment]
> Hi @gregnb how can I custom filter type on each column? for ex: I have 3 columns: username(filterType: 'textField'), date(filterType: 'multiselect'), age(filterType: 'dropdown').
> 
> I already tried this on each column, but didn't work:
> 
> ```
> column: [
>       {
>         name: 'Username',
>         options: {
>           filter: false,
>           sort: false,
>           filterType: 'textField',
>         },
>       },
>       {
>         name: 'Date',
>         options: {
>           filter: true,
>           sort: false,
>           filterType: 'multiselect',
>         },
>       },
>       {
>         name: 'Age',
>         options: {
>           filter: true,
>           filterType: 'dropdown',
>           sort: false,
>         },
>       }
> ]
> ```

@gregnb Hi there, really great project you have here ! thumbs up ;) 

Im also interested in this option to filter each column with different filterType... is this possible or added todo list? 
Thanks 

@dafapramudya maybe already fixed this?

**Comment by dafapramudya** [comment]
@rayray93 nope

**Comment by Heera64** [comment]
How can I filter a date range?

**Comment by GeekeuzZ** [comment]
Hi @gregnb how can I filter a date range ?

**Comment by dafapramudya** [comment]
@Heera64 @GeekeuzZ Currently there is no feature to filter date range, if u wanna filter date, I recommended to use other libraries, for ex: [react-date-range](https://github.com/Adphorus/react-date-range), then u need to get the date value from react-date-range and request API again with date range value query, and replace the previous data with the new data from query date API.

**Comment by GeekeuzZ** [comment]
@dafapramudya  Thanks I will try your solution

**Comment by sachin196** [comment]
Hi, I want to  add custom filter to mui Data table, where on filter button click and custom view will open depending the requirement and on apply filter or on reset filter button click i want to close that pop.Please help anyone knows how to achieve this.
[index.zip](https://github.com/gregnb/mui-datatables/files/3767505/index.zip)

**Comment by nmdhulipud** [comment]
Hello @gregnb 
Scenario: Filter dialog box remains open after Applying Filters & only closes if the user clicks outside the dialog box
Requirement:  I need filter dialog box closed, as soon as I apply filters on click of 'Apply button,
Is there any method I can use to complete this requirement?

**Comment by gabrielliwerant** [comment]
@nmdhulipud Yes there is, have a look at the `severside-fitlers` example.

**Comment by nmdhulipud** [comment]
@gabrielliwerant 
**In reference to your previous thread**
https://github.com/gregnb/mui-datatables/issues/961#issuecomment-536048612

This states that Filter diloag closing on Button click is not possible for now, Is it now implemented in serverside ? as i have a look on serverside filters but was not able to find any function or hook which close the filter dialog box.
Though i am doing king of same as i am setting the serversidefilterlist in Redux and binded to the options.
Let me know if i miss something.

**Comment by gabrielliwerant** [comment]
@nmdhulipud Sorry, misunderstood, no there isn't a way to fire the onClose manually, and it's pretty complicated to add this due to how the dialogs are created at the moment, so it's unlikely to happen anytime soon.

**Comment by multikitty** [comment]
Now, filterOptions: [ 'a', 'b', 'c', 'd'] is deprecated.

Use this instead.
```
{
      name: "type",
      label: "Type",
      options: {
        sort: true,
        filterOptions: {
          names: ["Starter", "Silver", "Gold", "Premium"],
        },
      },
    },
}
```
