### ISSUE TITLE
MUI datables example requested

### ISSUE THREAD

**Issue by ashatrisk** [gregnb/mui-datatables#1252]
I googled around about the below mentioned things, but haven't got examples on it yet. It would be of great help, if you can provide help on below questions

- How to add Title on each Cell element & custom attribute on row? 
- Is Download as excel option available? Since CSV doesn't retain table format
- How to do column aggregation?
- How to do sticky first column?

## Environment
 "dependencies": {
    "@date-io/date-fns": "^1.3.13",
    "@material-ui/core": "^4.9.9",
    "@material-ui/pickers": "^3.2.10",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "date-fns": "^2.12.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1"
  },
  "devDependencies": {
    "mui-datatables": "^2.14.0",
    "react-bootstrap": "^1.0.0",
    "react-redux": "^7.2.0",
    "react-router-dom": "^5.1.2",
    "redux": "^4.0.5",
    "redux-promise": "^0.6.0",
    "redux-thunk": "^2.3.0"
  }

**Comment by wdh2100** [comment]
>How to do sticky first column?


fixedHeaderOptions | object | {xAxis: true, yAxis: true} | Enable/disable fixed header columns according to axis in any combination desired Example
-- | -- | -- | --

**Comment by ashatrisk** [comment]
Closing the issue, i dropped sticky column stuff & column aggregation. For rest i did some customization to add excel download feature
