### ISSUE TITLE
Responsive 'stacked' causes rows to go over each other

### ISSUE THREAD

**Issue by Eithcowich** [gregnb/mui-datatables#1253]
I have large tables with a lot of data columns. The stacked option is a great idea for having the table provide data on smaller screens.

But the rows appear scrunched against each other, like this:

![Screen Shot 2020-04-14 at 6 01 30 PM](https://user-images.githubusercontent.com/6975895/79240621-b241fb80-7e7a-11ea-86ef-4c4cb7a842e8.png)

I tried the other responsive options but they are not what I'm looking for. Is there a solution?

**Comment by Eithcowich** [comment]
Following @wdh2100's response on another issue I looked [here](https://github.com/gregnb/mui-datatables/blob/master/examples/customize-styling/index.js) and figured out a scheme that would work for me. But there is still one issue. 

This is how I'm setting the relevant options on the table. First I check if the app is running on mobile or desktop:

    let scroll = isMobile ? 'scrollMaxHeight' : 'scrollFullHeight';

Then in the table options: 

    denseTable: false,
    responsive: scroll,

This works fine on mobile and large desktop screens, but on laptops or smaller desktop screens data is hidden on the right side of the screen, and there is no way to do horizontal scroll to view it. 

You can see an example on https://deepdao.world, if you select one of the rows in the dashboard, and then either Proposals or Members. Both tables have a larger number of columns. Play with the screen size and you'll see the effect. 

Is there a solution?

**Comment by wdh2100** [comment]
I think it's better to give you style {overflow : auto}

**Comment by Eithcowich** [comment]
Great, thanks @wdh2100

**Comment by patorjk** [comment]
This should be fixed in version 3.0.0.
