### ISSUE TITLE
Customize color of the select row checkboxes at the side of the table

### ISSUE THREAD

**Issue by Eithcowich** [gregnb/mui-datatables#1255]
The default for the table is to have a column of checkboxes on the left side, for selecting rows. 

Is there a way to customize the color of this column? 

Alternatively, can I simply remove them altogether? I don't really need to allow row selection.

**Comment by IanMDay** [comment]
In options you can add:

selectableRows: "none"

**Comment by Eithcowich** [comment]
Thanks. This is good for some of my tables at https://deepdao.world, but for most of them I need them selectable, and for some clients the color needs to be customizable.

**Comment by ivan-cbqa** [comment]
@Eithcowich  did you figured out how to customize the checkbox selected row background color?

**Comment by Eithcowich** [comment]
@ivan-cbqa no, I did not.

**Comment by patorjk** [comment]
As of version 3.0.0, you can use the option selectableRowsHideCheckboxes to hide the checkboxes. If you don't want selectable rows, set the selectableRows option to "none".

Currently there is no way to change the checkbox color, however, that should be easy to add. I'll put it on the list for version 3.1.0.

**Comment by patorjk** [comment]
Now possible in version 3.2.0 by using a custom checkbox component (example in examples/customize-example).

**Comment by akshay-acharya-ey** [comment]
Hello, is it also possible to move the position of the select all checkbox to another position in the toolbar?
