### ISSUE TITLE
library print only appeared content rows

### ISSUE THREAD

**Issue by new-furry** [gregnb/mui-datatables#1257]
Expected Behavior: I would like to print all content(rows)
Current Behavior: it prints only appeared rows.
![image](https://user-images.githubusercontent.com/53916675/79410538-4c1cbc00-7fd3-11ea-92b3-60df91090a99.png)

My code:
options:
export const listOptions = {
  fixedHeader: true,
  filterType: "multiselect",
  responsive: "scrollMaxHeight",
  // responsive: 'scroll',
  download: false,
  print: true,
  viewColumns: false,
  filter: false,
  selectableRows: "none",
  elevation: 0,
  rowsPerPage: 15,
  pagination: true,
  rowsPerPageOptions: [15, 30, 60, 100, 10000],
  textLabels: { body: { noMatch: "Change to Please wait..." } }
};

customize: 
const myTheme = createMuiTheme({
  overrides: {
    MUIDataTable: {
      root: {
        overflow: 'scroll',
        backgroundImage: 'none !important'
      },
      responsive: {
        overflow: 'scroll',
        maxWidth: 'none !important',
        msMaxWidth: 'none !important'
      },
      responsiveStacked: {
        overflow: 'scroll',
      },
      responsiveScroll: {
        overflow: 'scroll',
        maxHeight: "none !important",
        maxWidth: 'none !important'
      },
      responsiveScrollMaxHeight: {
        overflow: 'scroll',
        // maxHeight: 'none !important',
      },
      responsiveScrollFullHeight: {
        overflowX: 'scroll',
      }
    },

Please help me... I want to print all data with bellow option-
 responsive: "scrollMaxHeight",

thanks in advance.

**Comment by new-furry** [comment]
Expected Behavior: I would like to print all content(rows)
Current Behavior: it prints only appeared rows.
![image](https://user-images.githubusercontent.com/53916675/79410538-4c1cbc00-7fd3-11ea-92b3-60df91090a99.png)

My code:
options:
export const listOptions = {
  fixedHeader: true,
  filterType: "multiselect",
  responsive: "scrollMaxHeight",
  // responsive: 'scroll',
  download: false,
  print: true,
  viewColumns: false,
  filter: false,
  selectableRows: "none",
  elevation: 0,
  rowsPerPage: 15,
  pagination: true,
  rowsPerPageOptions: [15, 30, 60, 100, 10000],
  textLabels: { body: { noMatch: "Change to Please wait..." } }
};

customize: 
const myTheme = createMuiTheme({
  overrides: {
    MUIDataTable: {
      root: {
        overflow: 'scroll',
        backgroundImage: 'none !important'
      },
      responsive: {
        overflow: 'scroll',
        maxWidth: 'none !important',
        msMaxWidth: 'none !important'
      },
      responsiveStacked: {
        overflow: 'scroll',
      },
      responsiveScroll: {
        overflow: 'scroll',
        maxHeight: "none !important",
        maxWidth: 'none !important'
      },
      responsiveScrollMaxHeight: {
        overflow: 'scroll',
        // maxHeight: 'none !important',
      },
      responsiveScrollFullHeight: {
        overflowX: 'scroll',
      }
    },

Please help me... I want to print all data with bellow option-
 responsive: "scrollMaxHeight",

thanks in advance.

**Comment by rodrigoxavier** [comment]
Hi! I've faced the same problem. I solve it by replacing "scollMaxHeight" by "scrollFullHeight".

Hope can help you.

**Comment by new-furry** [comment]
Thank you @rodrigoxavier ... actually, I have solved this problem.
but I really appreciate your help. )
