### ISSUE TITLE
Filter dialog is not closed when filter applied

### ISSUE THREAD

**Issue by MahadiHasanMiazi** [gregnb/mui-datatables#1259]
I want to close the filter dialog after clicking apply filter

## Expected Behavior
After clicking "Apply Filters" button on filter dialog in Mui-datatables, filter dialog should be closed automatically. 

## Current Behavior
When I click "Apply Filters" button on filter dialog in Mui-datatables, filter dialog is not closed automatically.  Instead I had to press on outside the filter dialog box to close the dialog box. Users always need a extra click to hide the filter dialog.

## Your Environment
Macbook pro

| Tech         | Version |
|--------------|---------|
| Material-UI/Core |   4.6.0      |
| MUI-datatables  |   2.13.3  |
| React        |    16.3.0     |
| Google chrome      |    80.0.3987.163     |

<img width="434" alt="Screenshot 2020-04-16 at 4 32 19 PM" src="https://user-images.githubusercontent.com/24210856/79447001-fc54e980-8000-11ea-9874-a34cfc1eb7d7.png">

**Comment by geekashu** [comment]
Hello @gregnb , 

I think we use `handleFilterSubmit` function as shown in your example `serverside-filters` after user has clicked on th apply filters. Can you please suggest which api to call to close the filter dialog?

**Comment by patorjk** [comment]
This is now fixed in version 3.0.0
