### ISSUE TITLE
Is it possible to hide the title and select checkbox?

### ISSUE THREAD

**Issue by jpaulsen-apixio** [gregnb/mui-datatables#126]
This is an exceptional implementation. Is is possible to make this table simpler and not have the title or title bar, as well as select checkboxes for the first column?

**Comment by gregnb** [comment]
Title/titlebar not as of today.

Selectable rows just pass in the following options:

```
const options = {
   selectableRows: false
};
```

**Comment by benjaminbours** [comment]
What is the best solution ?

- add an option "viewToolbar", type: boolean, default: true, to see or not the MUIDataTableToolbar component. ( not compatible with option customToolbar )
- add an option "topBar", type: TopBarOptions | false.  I imagine something like:

```
interface TopBarOptions {
    title?: boolean,
    toolbar?: ToolBar | boolean
}

interface ToolBar {
    filter?: boolean
    search?: boolean
    print?: boolean
    download?: boolean
    viewColumns?: boolean
}
```
options.topBar = false  => MUIDataTableToolbar component not rendered
options.topBar = { toolbar: false } => We show the title but not the toolbar.
options.topBar = { title: false } => We show the title but not the toolbar.

It's about to have the full control on what you want to render or not.

That is the idea, I hope you understand what I mean.

- The previous solution mixed with the options.customToolBar. This is all options about the same thing and I think it can be helpful to regroup everything about toolbar under a subobject of options.

**Comment by gregnb** [comment]
@benjaminbours Good API design. As this library starts to grow in features the options page is starting to become messy.  I want to take this a step further because this change you're proposing is a breaking change. When we do make this breaking change I want to have it apply to each section.

right now we have

```
  customFooter,
  customToolbar
  customToolbarSelect
```

Then there are various options tied to some of these items that could be folded under and make the first glance of the API smaller but then a user would need to drill down.  If you're interested in creating a concept PR where you focus on nothing but README/API design of converting these I would be interested in seeing how it looks. I don't want it to be a pain to figure out how to configure this library but I also realize the options needs to be more organized

**Comment by gregnb** [comment]
I'm thinking about making the following change:

```
const options = {

  toolbarSelect: fn

  footer: 
    function(count, page, rowsPerPage, changeRowsPerPage, changePage) => string|React Component


  toolBar: obj | fn,

  // option #1
  toolBar: (props) => {
    return (<section id="toolbar"><h1>some title</h1><div>some custom toolbar</div></section>)
  },

  // option #2
  toolBar: {
    title: "custom title",
    options: {
      filter: {
        display: true
        icon: customIcon
      },
      search: {
        display: false
      },
      print: {
        display: true
      },
      download: {
        display: true
      },
      viewColumns: {
        display: true
      }
    }
  }
```

**Comment by tonymckendry** [comment]
To answer the original question, I was able to hide the entire title/tool bar by adding this to my theme overrides: 

```
MUIDataTableToolbar: {
     root: {
        display: 'none'
    }
}
```

**Comment by kedpak** [comment]
@tonymckendry Is there a way to keep the toolbar, but remove only the title bar section? Also any idea how to change font color in toolbar?

**Comment by tonymckendry** [comment]
@kedpak I can't say for sure without having it in front of me, but you would most certainly use an override like I did above, instead of `root` there is probably another subclass in `MUIDataTableToolbar` that you could target to hide the title. As for changing the font color, I would try to add `color: <yourColor>` to the same override I used above

**Comment by ajay-bsoft** [comment]
Seems options setting been changed now. If need to remove only "print" icon then write

```
const options = {
print: false
}
```
This works to me

**Comment by gabrielliwerant** [comment]
Removing the toolbar section is now possible just by removing any options that might appear there, as well as passing an empty title. There is an example here: https://github.com/gregnb/mui-datatables/blob/master/examples/simple-no-toolbar/index.js.

Removing the checkboxes can be done with `selectableRows: false` or `selectableRows: 'none'`. You can also set exactly which rows are selectable with `isRowSelectable`.

As I believe these options now satisfy the original issue, I will close.

**Comment by svendeckers** [comment]
It doesn't say so in the docs, it says the options are 'multiple', 'single' or 'none', and 'none' is not working. Passing the boolean value `false` does work.

**Comment by Ainnop** [comment]
> Title/titlebar not as of today.
> 
> Selectable rows just pass in the following options:
> 
> ```
> const options = {
>    selectableRows: false
> };
> ```

Does not work with remote data, the column checkbox disappears but the checkboxes on the rows still appear
![image](https://user-images.githubusercontent.com/8756573/62444011-0c73b400-b765-11e9-89ec-83f9744fd492.png)

**Comment by AlexFenoul** [comment]
> > Title/titlebar not as of today.
> > Selectable rows just pass in the following options:
> > ```
> > const options = {
> >    selectableRows: false
> > };
> > ```
> 
> Does not work with remote data, the column checkbox disappears but the checkboxes on the rows still appear
> ![image](https://user-images.githubusercontent.com/8756573/62444011-0c73b400-b765-11e9-89ec-83f9744fd492.png)

selectableRows: 'none' seems to works

**Comment by Ainnop** [comment]
@AlexFenoul , selectableRows: 'none'  works perfectly. Thanks.
Do you have and idea on how fix the issue of when columns are many and the table looks distorted, I have tried using responsive: 'stacked' but does not work. look at the table below:

![image](https://user-images.githubusercontent.com/8756573/62465253-20380e00-b797-11e9-9251-c06e4ecda715.png)

**Comment by AlexFenoul** [comment]
I don't really know, did you try to use responsive: 'scroll', i never had this problem 🤐

**Comment by Ainnop** [comment]
> I don't really know, did you try to use responsive: 'scroll', i never had this problem 🤐

Yes I tried that too but failed, I wonder if there is a way to fix this issue, it seems the table has a fixed width

**Comment by gabrielliwerant** [comment]
@Ainnop It looks like you are overriding things in a way that is getting you into trouble. If you look at the `custom-action-columns` example, you'll see how the table looks with many columns, some of which are used for buttons.

**Comment by Ainnop** [comment]
@gabrielliwerant I used the same example to come up that, but when i add just 2 or more columns to the **custom-action-columns** example, the table still looks distorted, I tried using **responsive: 'scroll'** but it only scrolls vertically, I thought maybe it would scroll the table horizontally and auto resize the columns, none of what i expected worked.
![image](https://user-images.githubusercontent.com/8756573/62514414-c6cbef80-b827-11e9-94e3-f4a86a3dae68.png)


`import React from 'react';
import MUIDataTable from 'mui-datatables';

class Activities extends React.Component{
    constructor(props) {
        super(props);
    
        this.state = {
          data: [
            ["Gabby George", "Business Analyst", "Minneapolis", 30, "$100,000", 30, "$100,000"],
            ["Aiden Lloyd", "Business Consultant", "Dallas",  55, "$200,000", 30, "$100,000"],
            ["Jaden Collins", "Attorney", "Santa Ana", 27, "$500,000", 30, "$100,000"],
            ["Franky Rees", "Business Analyst", "St. Petersburg", 22, "$50,000", 30, "$100,000"],
            ["Aaren Rose", "Business Consultant", "Toledo", 28, "$75,000", 30, "$100,000"],
            ["Blake Duncan", "Business Management Analyst", "San Diego", 65, "$94,000", 30, "$100,000"],
            ["Frankie Parry", "Agency Legal Counsel", "Jacksonville", 71, "$210,000", 30, "$100,000"],
            ["Lane Wilson", "Commercial Specialist", "Omaha", 19, "$65,000", 30, "$100,000"],
            ["Robin Duncan", "Business Analyst", "Los Angeles", 20, "$77,000", 30, "$100,000"],
            ["Mel Brooks", "Business Consultant", "Oklahoma City", 37, "$135,000", 30, "$100,000"],
            ["Harper White", "Attorney", "Pittsburgh", 52, "$420,000", 30, "$100,000"],
            ["Kris Humphrey", "Agency Legal Counsel", "Laredo", 30, "$150,000", 30, "$100,000"],
            ["Frankie Long", "Industrial Analyst", "Austin", 31, "$170,000", 30, "$100,000"],
            ["Brynn Robbins", "Business Analyst", "Norfolk", 22, "$90,000", 30, "$100,000"],
            ["Justice Mann", "Business Consultant", "Chicago", 24, "$133,000", 30, "$100,000"],
            ["Addison Navarro", "Business Management Analyst", "New York", 50, "$295,000", 30, "$100,000"],
            ["Jesse Welch", "Agency Legal Counsel", "Seattle", 28, "$200,000", 30, "$100,000"],
            ["Eli Mejia", "Commercial Specialist", "Long Beach", 65, "$400,000", 30, "$100,000"],
            ["Gene Leblanc", "Industrial Analyst", "Hartford", 34, "$110,000", 30, "$100,000"],
            ["Danny Leon", "Computer Scientist", "Newark", 60, "$220,000", 30, "$100,000"],
            ["Lane Lee", "Corporate Counselor", "Cincinnati", 52, "$180,000", 30, "$100,000"],
            ["Jesse Hall", "Business Analyst", "Baltimore", 44, "$99,000", 30, "$100,000"],
            ["Danni Hudson", "Agency Legal Counsel", "Tampa", 37, "$90,000", 30, "$100,000"],
            ["Terry Macdonald", "Commercial Specialist", "Miami", 39, "$140,000", 30, "$100,000"],
            ["Justice Mccarthy", "Attorney", "Tucson", 26, "$330,000", 30, "$100,000"],
            ["Silver Carey", "Computer Scientist", "Memphis", 47, "$250,000" , 30, "$100,000"],
            ["Franky Miles", "Industrial Analyst", "Buffalo", 49, "$190,000", 30, "$100,000"],
            ["Glen Nixon", "Corporate Counselor", "Arlington", 44, "$80,000", 30, "$100,000"],
            ["Gabby Strickland", "Business Process Consultant", "Scottsdale", 26, "$45,000", 30, "$100,000"],
            ["Mason Ray", "Computer Scientist", "San Francisco", 39, "$142,000", 30, "$100,000"]
          ]
        };
      }
    
      render() {
        const columns = [
          {
            name: "Delete",
            options: {
              filter: true,
              sort: false,
              empty: true,
              customBodyRender: (value, tableMeta, updateValue) => {
                return (
                  <button onClick={() => {
                    const { data } = this.state;
                    data.shift();
                    this.setState({ data });
                  }}>
                    Delete
                  </button>
                );
              }
            }
          },
          {
            name: "Edit",
            options: {
              filter: true,
              sort: false,
              empty: true,
              customBodyRender: (value, tableMeta, updateValue) => {
                return (
                  <button onClick={() => window.alert(`Clicked "Edit" for row ${tableMeta.rowIndex}`)}>
                    Edit
                  </button>
                );
              }
            }
          },
          {
            name: "Name",
            options: {
              filter: true,
            }
          },
          {
            label: "Modified Title Label",
            name: "Title",
            options: {
              filter: true,
            }
          },
          {
            name: "Location",
            options: {
              filter: false,
            }
          },
          {
            name: "Age",
            options: {
              filter: true,
            }
          },
          {
            name: "Salary",
            options: {
              filter: true,
              sort: false,
            }
          },
          {
            name: "Days",
            options: {
              filter: true,
            }
          },
          {
            name: "Debt",
            options: {
              filter: true,
              sort: false,
            }
          },
          {
            name: "Add",
            options: {
              filter: true,
              sort: false,
              empty: true,
              customBodyRender: (value, tableMeta, updateValue) => {
                return (
                  <button onClick={() => {
                    const { data } = this.state;
                    data.unshift(["Mason Ray", "Computer Scientist", "San Francisco", 39, "$142,000"]);
                    this.setState({ data });
                  }}>
                    Add
                  </button>
                );
              }
            }
          },
        ];
    
        const data1 = [
          {Name: "Gabby George", Title: "Business Analyst", Location: "Minneapolis", Age: 30, Salary: "$100,000"},
          {Name: "Aiden Lloyd", Title: "Business Consultant", Location: "Dallas", Age: 55, Salary: "$200,000"},
          {Name: "Jaden Collins", Title: "Attorney", Location: "Santa Ana", Age: 27, Salary: "$500,000"},
          {Name: "Franky Rees", Title: "Business Analyst", Location: "St. Petersburg", Age: 22, Salary: "$50,000"},
          {Name: "Aaren Rose", Title: "Business Consultant", Location: "Toledo", Age: 28, Salary: "$75,000"},
          {Name: "Blake Duncan", Title: "Business Management Analyst", Location: "San Diego", Age: 65, Salary: "$94,000"},
          {Name: "Frankie Parry", Title: "Agency Legal Counsel", Location: "Jacksonville", Age: 71, Salary: "$210,000"},
          {Name: "Lane Wilson", Title: "Commercial Specialist", Location: "Omaha", Age: 19, Salary: "$65,000"},
          {Name: "Robin Duncan", Title: "Business Analyst", Location: "Los Angeles", Age: 20, Salary: "$77,000"},
          {Name: "Mel Brooks", Title: "Business Consultant", Location: "Oklahoma City", Age: 37, Salary: "$135,000"},
          {Name: "Harper White", Title: "Attorney", Location: "Pittsburgh", Age: 52, Salary: "$420,000"},
          {Name: "Kris Humphrey", Title: "Agency Legal Counsel", Location: "Laredo", Age: 30, Salary: "$150,000"},
          {Name: "Frankie Long", Title: "Industrial Analyst", Location: "Austin", Age: 31, Salary: "$170,000"},
          {Name: "Brynn Robbins", Title: "Business Analyst", Location: "Norfolk", Age: 22, Salary: "$90,000"},
          {Name: "Justice Mann", Title: "Business Consultant", Location: "Chicago", Age: 24, Salary: "$133,000"},
          {Name: "Addison Navarro", Title: "Business Management Analyst", Location: "New York", Age: 50, Salary: "$295,000"},
          {Name: "Jesse Welch", Title: "Agency Legal Counsel", Location: "Seattle", Age: 28, Salary: "$200,000"},
          {Name: "Eli Mejia", Title: "Commercial Specialist", Location: "Long Beach", Age: 65, Salary: "$400,000"},
          {Name: "Gene Leblanc", Title: "Industrial Analyst", Location: "Hartford", Age: 34, Salary: "$110,000"},
          {Name: "Danny Leon", Title: "Computer Scientist", Location: "Newark", Age: 60, Salary: "$220,000"},
          {Name: "Lane Lee", Title: "Corporate Counselor", Location: "Cincinnati", Age: 52, Salary: "$180,000"},
          {Name: "Jesse Hall", Title: "Business Analyst", Location: "Baltimore", Age: 44, Salary: "$99,000"},
          {Name: "Danni Hudson", Title: "Agency Legal Counsel", Location: "Tampa", Age: 37, Salary: "$90,000"},
          {Name: "Terry Macdonald", Title: "Commercial Specialist", Location: "Miami", Age: 39, Salary: "$140,000"},
          {Name: "Justice Mccarthy", Title: "Attorney", Location: "Tucson", Age: 26, Salary: "$330,000"},
          {Name: "Silver Carey", Title: "Computer Scientist", Location: "Memphis", Age: 47, Salary: "$250,000" },
          {Name: "Franky Miles", Title: "Industrial Analyst", Location: "Buffalo", Age: 49, Salary: "$190,000"},
          {Name: "Glen Nixon", Title: "Corporate Counselor", Location: "Arlington", Age: 44, Salary: "$80,000"},
          {Name: "Gabby Strickland", Title: "Business Process Consultant", Location: "Scottsdale", Age: 26, Salary: "$45,000"},
          {Name: "Mason Ray", Title: "Computer Scientist", Location: "San Francisco", Age: 39, Salary: "$142,000"}
        ];
    
        const options = {
          filter: true,
          filterType: 'dropdown',
          responsive: 'scroll',
          page: 2,
          onColumnSortChange: (changedColumn, direction) => console.log('changedColumn: ', changedColumn, 'direction: ', direction),
          onChangeRowsPerPage: numberOfRows => console.log('numberOfRows: ', numberOfRows),
          onChangePage: currentPage => console.log('currentPage: ', currentPage)
        };
    
        return (
          <MUIDataTable title={"ACME Employee list"} data={this.state.data} columns={columns} options={options} />
        );
    }
}

export default Activities`

**Comment by gabrielliwerant** [comment]
@Ainnop So, first order of business, can you create a new issue for us to track the discussion? I think it's misplaced here.

Secondly, can you add your example to https://codesandbox.io, so I can tell we're looking at the same thing, including version of libraries being used? I'm unable to verify the issue based on your code, so it could be a version issue, but I have no way to tell at present.

**Comment by svendeckers** [comment]
@Ainnop Try lowering the padding on the columncells:
```
const theme = createMuiTheme({
  palette: {
  /* ... */
  },
  overrides: {
    MUIDataTableBodyCell: {
      root: {
        padding: "0em 2em",
      }
    },
    MUIDataTableHeadCell: {
      root: {
        padding: "0em 2em",
        color: '#EE7D11'
      }
    },
  },
});```

**Comment by sajish-sasidharan** [comment]
How to hide the entire tool bar?

**Comment by gabrielliwerant** [comment]
@sajish-sasidharan See the `simple-no-toolbar` example for a way to do that.

**Comment by mercyjulliyana** [comment]
u
