### ISSUE TITLE
React.StrictMode prevent removing filter

### ISSUE THREAD

**Issue by RedFish** [gregnb/mui-datatables#1261]
I am testing some features of this library into my app, and I have noticed that the closing icon of active filter is not working.

Some warnings appear as well in the console:
- Warning: Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

- Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of t which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in th (created by ForwardRef(TableCell))
    in ForwardRef(TableCell) (created by WithStyles(ForwardRef(TableCell)))

## Expected Behavior
Remove the filter

## Current Behavior
Nothing append

## Steps to Reproduce
https://codesandbox.io/s/muidatatables-custom-toolbar-0nhte

1. <React.StrictMode><App /></React.StrictMode>
2. Add a filter
3. Remove added filter from the X icon

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.9.9    |
| MUI-datatables  |    2.14.0     |
| React        |     16.13.1    |
| browser      |     chrome Version 80.0.3987.163    |

**Comment by wdh2100** [comment]
https://github.com/gregnb/mui-datatables/issues/679 
😢

**Comment by patorjk** [comment]
Hmm, I think both these issues can be taken care of without much of an issue. I think the last of the findDOMNode calls will be removed after the [draggable columns](https://github.com/gregnb/mui-datatables/pull/1329) PR is complete, and refactoring out UNSAFE_componentWillMount seems pretty straight forward: There are 2-3 methods that need to return objects rather than setting the state. They can then be called from the constructor.

I'll put this on my list.

**Comment by johnsonsamuel** [comment]
Hi team, I am seeing the same issue.

```
Using UNSAFE_componentWillMount in strict mode is not recommended and may indicate bugs in your code
Move code with side effects to componentDidMount, and set initial state in the constructor.
```
Please advise.

**Comment by johnsonsamuel** [comment]
@RedFish Were you able to solve this issue?

**Comment by patorjk** [comment]
The findDOMNode code was refactored away in the last release. The UNSAFE_componentWillMount part will be tackled in the next release (probably in a week or so).

**Comment by patorjk** [comment]
Actually, as an aside, I updated the codesandbox above to use the latest version of the table and I don't have the issue with closing a filter chip:

https://codesandbox.io/s/muidatatables-custom-toolbar-3jun2

The UNSAFE_componentWillMount warning will still be there, but it shouldn't affect the ability to close a filter chip.

**Comment by uodami** [comment]
Hello,
I am using typescript and the version 3.1.1 of @types/mui-datatables. I still have both od warnings:
unsafe_componentWillMount and findDOMNode.
Is this related to the usage of @types/mui-datatables ?
If not, can I get some help please?

**Comment by uodami** [comment]
Hello, I am using typescript v 3.7.2 in my project along with mui-datatables v 3.2.0 and @types/mui-datatables v3.1.1
I am still getting the findDOMNode error.

![image](https://user-images.githubusercontent.com/10802895/87716096-9e29d500-c7ae-11ea-8ce6-7ffcfda52483.png)

Is this normal?

**Comment by patorjk** [comment]
Does just rendering the table trigger that? Are you using any other components inside the table? I've searched the project and we're no longer using findDOMNode anywhere in the code.

The error also doesn't come up in this codesandbox (which is in strict mode): https://codesandbox.io/s/sleepy-bardeen-3orzk

**Comment by uodami** [comment]
I no longer have the error! My bad, Thanks for the reply :)
