### ISSUE TITLE
Unable to override scroll max height

### ISSUE THREAD

**Issue by maxmann74** [gregnb/mui-datatables#1264]
I'm using Material UI 4.9.2 , MUI-DataTables 2.14, React 16.13.1.

After reading other posts it is mentioned several times that you can set the max scrollheight override like this:
                      MUIDataTable: {
                        responsiveScroll: {
                          maxHeight: '400px'
                        }
                      }

I have done this, and also have options.responsive ="scrollMaxHeight"

The MUIDataTable-responsiveScrollMaxHeight div always gets rendered with height 499px regardless.   Is this still a bug, or is there another way to set the actual height of the scrolling area?

**Comment by DangerousDetlef** [comment]
Create the override in the theme like so:

```
const getMuiTheme = () => createMuiTheme({
  overrides: {
    MUIDataTable: {
      responsiveScrollMaxHeight: {
        maxHeight:'400px !important' 
      }
    },
  }
})
```
In your (functional) component, load the the theme:
`const theme = getMuiTheme();`

Then create your MUI DataTable and wrap it in a MuiThemeProvider, passing the loaded theme like this:
```
    <MuiThemeProvider theme={theme}>
        <MUIDataTable
          ...
        />
      </MuiThemeProvider>
```

**Comment by maxmann74** [comment]
Thanks, that worked. None of the examples I saw referenced the "responsiveScrollMaxHeight" class, and none of them used "important".   I figured override meant override :)  Good to know you still have to use "important".
