### ISSUE TITLE
Can not Navigate Table rows Using Tabkey.

### ISSUE THREAD

**Issue by karanbk-eGov** [gregnb/mui-datatables#1270]
## Expected Behavior
On clicking on Tabkey it should navigate through rows of the table.

## Current Behavior
Its Not navigating through tab key,

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    1.5.0    |
| MUI-datatables  |   2.14. 0      |
| React        | 16.13.1        |.
| browser      | Any        |
| etc          |         |

**Comment by wdh2100** [comment]
![dddd](https://user-images.githubusercontent.com/16433770/80816046-c40cf800-8c09-11ea-8638-b331db182e28.gif)

um...

**Comment by patorjk** [comment]
I get the same result as @wdh2100. The actual cells inside of the table can't be tabbed to unless they're clickable or some kind of input component ([example](https://github.com/gregnb/mui-datatables/blob/master/examples/component/index.js)).
