### ISSUE TITLE
Updating rowsSelected state variable doesn't update selected grid rows

### ISSUE THREAD

**Issue by maxmann74** [gregnb/mui-datatables#1273]
I have my options.rowsSelected set to use state.  If I have a button on my form that I want to click and have it set some rows as selected, this should work:

    handleClick = () =>{
        this.setState({rowsSelected: [0,1,2,3]});
    }

The checked rows in the grid should change at this point, but they don't.  Any idea why? How can I control which rows are check AFTER I have rendered the datatable. It seems the options.rowsSelected is only honored on initial render.

                <MUIDataTable
                    data={this.state.rows}
                    columns={this.columns}
                    options={{
                        rowsSelected: this.state.rowsSelected,  //<--------------------------
                        selectableRowsHeader: false,
                        filterType: "checkbox",
                        selectableRows: "multiple",
                        selectableRowsOnClick: false,
                        onRowsSelect: (rowsSelected, allRows) => {
                            this.setState({ rowsSelected: allRows.map(row => row.dataIndex) });
                        }
............
                />

**Comment by wdh2100** [comment]
https://codesandbox.io/s/muidatatables-custom-toolbar-6033q?file=/index.js

It works well?

**Comment by maxmann74** [comment]
Not sure why your example works and my code doesn't. I can't see anything you are doing differently. I will have to look into it more. For now I had to wipe my rows out of state and reset them for it to refresh. 

this.setState({rowSelected: selRows}); 

//update rows state to get new selected rows to be checked
let rowsBak = [...this.state.rows];
this.setState({rows: []});
this.setState({rows: rowsBak});
