### ISSUE TITLE
customBodyRender is not called 

### ISSUE THREAD

**Issue by aggounix** [gregnb/mui-datatables#1275]
I ma trying to have a custom rendering for a column in the table whit customBodyRender, but the rendering is not taken into consideration

```
{
    name: "rang",
    label: "boosted",
    option: {
      filter: false,
      customHeadRender: (columnMeta, updateDirection) => (
        <th key={2} onClick={() => updateDirection(2)} style={{ cursor: 'pointer' }}>
          {columnMeta.name}
        </th>
      ),
      customBodyRender: (value, tableMeta, updateValue) => 
        {
          console.log('hey');
        return <FormControlLabel
        value={value}
        control={<TextField value={value} />}
        onChange={event => updateValue(event.target.value)}
      />;}
      
    }
```

the console.log is not shown but the customhead is working

## Expected Behavior

Having a column cell with textfield
## Current Behavior

the column is showing simple value of  the column data

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.3.0     |
| MUI-datatables  |   2.14.0      |
| React        |   16.13.1      |
| browser      |    chrome  81.0.4044.129     |
| etc          |         |

**Comment by wdh2100** [comment]
option -> options

```js
const columns = [
 {
  name: "Name",
  options: {
   filter: true,
   sort: false
  }
 },
 ...
];
```

**Comment by aggounix** [comment]
Thanks :)
it worked
