### ISSUE TITLE
Complex CSS/JSS/Theme overrides do not work due to minification in production

### ISSUE THREAD

**Issue by kevin-lindsay-1** [gregnb/mui-datatables#1279]
I have slightly more advanced overrides that use class selectors based on the names that are given to the components via `withStyles`, but unlike the components of `@material-ui`, these classnames get minified in a production bundle, which then breaks the theme overrides.

Looking into it on my own to see how to disable it for this particular project I'm working on, but would appreciate any assistance or pointers if I'm missing something.

## Expected Behavior

When creating a `theme` in `@material-ui` and specifying overrides that actually utilize the classnames of components, such as:
```
createMuiTheme({
  overrides: {
    MUIDataTableBodyRow: {
      root: {
        // select the 2nd element if the first cell is hidden
        '& > td[class*="MUIDataTableBodyCell-cellHide"]:first-child ~ td:nth-child(2)': {
          backgroundColor: 'azure',
        },
      },
    },
  },
})
```

When running locally using `create-react-app/react-scripts`, the output CSS looks like this:
```
.MUIDataTableBodyRow-root-347 > td[class*="MUIDataTableBodyCell-cellHide"]:first-child ~ td:nth-child(2) {
  background-color: azure;
}
```

## Current Behavior

Whereas the production build's CSS looks like this:
```
.jss347 > td[class*="MUIDataTableBodyCell-cellHide"]:first-child ~ td:nth-child(2) {
    background-color: azure;
  }
```

## Steps to Reproduce (for bugs)

1. Attempt to use `createMuiTheme` to override styles, as shown in the documentation
2. Attempt to use the class names assigned to components
3. Build a production bundle
4. `mui-datatables` class names are minified, `@material-ui`'s class names are not.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.9.13      |
| MUI-datatables  |     2.14.0    |
| React        |     16.13.1    |
| browser      |    chrome latest     |
| etc          |         |

**Comment by kevin-lindsay-1** [comment]
Update: I have determined the/a cause of the issue.

Per https://material-ui.com/styles/advanced/#class-names, if you are using `withStyles` via `@material-ui/styles`, you should expect them to be minified and non-deterministic. If you are using `@material-ui/core/styles`, you can expect unminified, deterministic names if the following are true:
* Only one theme provider is used (No theme nesting)
* The style sheet has a name that starts with `Mui` (all Material-UI components).
* The `disableGlobal` option of the class name generator is `false` (the default).

On the second point, I went into my `node_modules` and changed the class names to `Mui` rather than `MUI`, and the issue went away.

It appears that this somewhat forces the hand on #139, and should be handled sooner rather than later in my opinion, as it breaks a core CSS system.

I'm going to see if I can find another workaround, but this simply appears to be a bug caused by deviation from convention.

**Comment by kevin-lindsay-1** [comment]
My workaround is as follows:
per https://material-ui.com/customization/components/#use-rulename-to-reference-a-local-rule-within-the-same-style-sheet

I can write my JSS as:
```
MUIDataTableBodyCell: {
  root: {
    '&$cellHide': {
      // select the 2nd element if the first cell is hidden
      '&:first-child ~ td:nth-child(2)': {
        backgroundColor: 'azure',
      },
    },
  },
},
```

And the issue does not persist. Hopefully this will work for my future use cases as well, but it would be preferable to at the least have the option to enable deterministic class names.

**Comment by patorjk** [comment]
Drat, wish I'd seen this earlier (I took over maintainer responsibilities earlier this month and just released v3). 

I will have to think about this, as I wouldn't want to do another major release so soon. I'm glad there is a workaround. This should probably be addressed though.
