### ISSUE TITLE
left coordinate with resizableColumns option affects dividers position

### ISSUE THREAD

**Issue by kiryl-fively** [gregnb/mui-datatables#1280]
## Expected Behavior

When you set resizableColumns option,  moving left coordinate of the table or its wrapper shouldn't affect dividers position and columns width. 

## Current Behavior

Currently, when you set resizableColumns option and for example add left margin/padding to the table wrapper, dividers are rendered in wrong positions so the last one overflows container.

## Steps to Reproduce (for bugs)

1. Set resizableColumns option
2. Set either left margin/padding or change left position of the table component or add some block to the left of the table. Basically you need to change left coordinate of the table rectangle.

## Your Environment

https://codesandbox.io/s/muidatatables-resizeable-columns-nk0yt
| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.9.0    |
| MUI-datatables  |  2.14.0       |
| React        |     16.12.0    |
| browser      |    Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)     |

**Comment by patorjk** [comment]
I can confirm this is a bug, I'll try and dig deeper if I get some time.

**Comment by patorjk** [comment]
I've created a PR to resolve this issue. It can be viewed here: https://github.com/gregnb/mui-datatables/pull/1330

**Comment by patorjk** [comment]
Resolved in version 3.0.1
