### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by matanbakshi** [gregnb/mui-datatables#1281]
Hey, we need to support the Hebrew language, is there any way that the table can be transformed to RTL?

## Expected Behavior

The table's row, columns, actions buttons, and pagination will be RTL

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.9.13     |
| MUI-datatables  |    2.14.0     |
| React        |     16.13.1    |
| browser      |    Chrome 81    |
| etc          |         |

**Comment by dmp359** [comment]
You can use the `textLabels` option to localize.

**Comment by matanbakshi** [comment]
Hi @dmp359, thanks for the response. The localization option is great, but we would also like to change the direction of the columns, buttons etc. to be right to left.

**Comment by dmp359** [comment]
I believe you could implement this on your own with customFooters and just changing the columns yourself.

**Comment by YonatanHanan** [comment]
@matanbakshi hi matan!
Could you share your solution?
