### ISSUE TITLE
setCellProps receives cell body value, instead of original one

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [gregnb/mui-datatables#1282]
Hi there,
It seems that `setCellProps` receives processed cell body(by `customBodyRender`) instead of original value. This is an issue because `setCellProps` receives different value, depending on `customBodyRender` used or not. 
Now simple example would be, a column of `user id`. One would want to translate `user id` into string name in `customBodyRender`, but then `setCellProps` receives this plain user name, loosing any context, to say make the background different color.

Correct behaviour would be `setCellProps` to receive original value, braking the API in the meantime :)

**Comment by patorjk** [comment]
It also gives you the dataIndex though, so you should be able to look the original value up in your unprocessed data array.

**Comment by Dragomir-Ivanov** [comment]
Cool, so closing this issue then.
