### ISSUE TITLE
createMuiTheme override with Typescript

### ISSUE THREAD

**Issue by LuisEdMB** [gregnb/mui-datatables#1283]
Hi, i have a problem:

When I use "createMuiTheme" with typescript, I get this error:

![image](https://user-images.githubusercontent.com/21093220/81769295-d9541300-94a2-11ea-938d-da61d1dda8e8.png)

Thanks for the reply.

**Comment by aostrander-source** [comment]
Hey @LuisEdMB , I also receive this TS error, and if I ignore it the styles are not propagated to the table as desired and as shown in the examples. Any luck with a solution?

**Comment by LuisEdMB** [comment]
Hi @aostrander-source, I had to pass my TS code to JS 😕.
