### ISSUE TITLE
Is it possible to hide some elements on print?

### ISSUE THREAD

**Issue by brunoselva** [gregnb/mui-datatables#1286]
I tried to hide the toolbar and checkbox at print but had no success.

![image](https://user-images.githubusercontent.com/51175507/82342553-5d346080-99b7-11ea-9487-01f4114d3084.png)

That is by Material UI documentation should work, what I am missing here?

**Comment by BingoXuan** [comment]
try overrides MuiToolbar than MUIDataTableToolbar. toolbar was hide when print.

**Comment by patorjk** [comment]
As of version 3.0.0 (released today), the table toolbar, select cells and footer are hidden on print. See the [customize-styling](https://github.com/gregnb/mui-datatables/blob/master/examples/customize-styling/index.js) example for additional info on how to do overrides.
