### ISSUE TITLE
Sort is disabled when serverSide is set to true

### ISSUE THREAD

**Issue by carllau999** [gregnb/mui-datatables#1287]
I have noticed setting serverSide: true in the options parameter will disable any sorting functionality, despite sort being set to true for all columns.

## Expected Behavior
Clicking on a column should sort the table's data 

## Current Behavior
Right now the sort icon appears on the column headers, but it doesn't actually do anything.

I have found the exact line this issue originates from on **line 927** in src/MUIDataTable.js:
```
if (this.options.serverSide) {
          newState = {
            ...newState,
            data: prevState.data,
            displayData: prevState.displayData,
            selectedRows: prevState.selectedRows,
          };
        } else {
          const sortedData = this.sortTable(data, index, newOrder);
          newState = {
            ...newState,
            data: sortedData.data,
            displayData: this.getDisplayData(columns, sortedData.data, prevState.filterList, prevState.searchText),
            selectedRows: sortedData.selectedRows,
            previousSelectedRow: null,
          };
        }
        return newState;
```

sortedData should be added to the if condition as well.

**Comment by wdh2100** [comment]
I think that's right.

ref : https://github.com/gregnb/mui-datatables/blob/master/examples/serverside-sorting/index.js

**Comment by patorjk** [comment]
When serverSide=true, the table assumes sorting is handled on the server (ex: a table with 10k rows only displaying 10 at a time - the server would need to be involved to correctly sort). The example @wdh2100 shows how the handle this situation.
