### ISSUE TITLE
Reset sorting on the third click

### ISSUE THREAD

**Issue by danielbyun** [gregnb/mui-datatables#1288]
## Expected Behavior

First click -> 'asc', second click -> 'desc', third click -> 'back to default'
Could this be supported?

## Current Behavior

The sort behavior is more like a toggle right now, where it goes from 'asc' <--> 'desc'

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by patorjk** [comment]
I'd be open to a PR for this. I'm guessing the sortOrder option would go from {} to {name:"Column",direction:"asc"} to {name:"Column",direction:"desc"} to {} when being clicked.

It looks like [toggleSortColumn](https://github.com/gregnb/mui-datatables/blob/master/src/MUIDataTable.js#L1072) would need to be updated as well as the [sortTable](https://github.com/gregnb/mui-datatables/blob/master/src/MUIDataTable.js#L1568) function for handling an empty order object by not sorting the table.

**Comment by danielbyun** [comment]
I'll take a look around when I'm not swamped with work.

Really appreciate this great package btw!

**Comment by danielbyun** [comment]
PR created #1428

**Comment by cee-money** [comment]
What PR was this resolved in? It was not PR [#1428](https://github.com/gregnb/mui-datatables/pull/1428), it looks like that one was not merged. Also [the docs](https://material-ui.com/components/tables/#sorting-amp-selecting) still show examples of sort asc and desc only for the `Table` component while the `DataGrid` does have a 3rd click resets sort default. Was this not implemented on `Table`? Thanks!
