### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [gregnb/mui-datatables#1290]
Hi guys, 
I see lot of activity on the Issues, but the main developer. Four months since the last release either.
Is this project still alive?

**Comment by patorjk** [comment]
@gabrielliwerant @gregnb ?

If the project is dead, I wouldn't mind taking it up, as I've been extensively using a modified version of the table in my own project for the past year, and have maybe a dozen outstanding PRs.

**Comment by patorjk** [comment]
I reached out to Greg and am now a maintainer for the project. I've merged in a few small PRs and have a version 2.15.0 of the library ready. As soon as I have permission to publish I'll release the next version.

**Comment by Dragomir-Ivanov** [comment]
Cheers man, you rock!

**Comment by gabrielliwerant** [comment]
@patorjk I have not had time for a while to work on this project, so cheers to getting involved and helping out. Not sure when I'll be able to return, so best of luck to you if you want to take it on.

**Comment by Dragomir-Ivanov** [comment]
Thanks @gabrielliwerant for handing this project out.

**Comment by patorjk** [comment]
@gabrielliwerant thanks Grabriel :). I don't plan on doing anything too drastic, mostly just moving the table forward.

@Dragomir-Ivanov I've merged your PR into the v3 branch I'm preparing for release later this week. I'll have more details on it later, it's not a super major upgrade but it will have some small breaking changes (thus the major version change). It's mostly just adding some outstanding features, updating all of the dependencies and getting the table in-line with Material UI v4.
