### ISSUE TITLE
setRowProps based on rowIndex

### ISSUE THREAD

**Issue by kev-landry** [gregnb/mui-datatables#1294]
Like setCellsProps i would like to get rowIndex.

```javascript
    setRowProps: (row, dataIndex) => {
      return {
        className: classNames({
          [classes.greyLine]: dataIndex % 2 === 0,
        }),
      };
    },
```
This code will set a grey background on 1 out of 2 lines.
But if i sort the table, dataIndex will remain the same id and i need it to be based on rowIndex so when my table state change the rows background changes accordingly.

**Comment by patorjk** [comment]
Looks like that information isn't passed in:

https://github.com/gregnb/mui-datatables/blob/master/src/components/TableBody.js#L225

setCellProps takes in the column index. If you put in a PR to add rowIndex to setRowProps, I could put it in the next release.

**Comment by kev-landry** [comment]
@patorjk ok i did one here #1298.

Thank you.

**Comment by patorjk** [comment]
Added in v3 (released today).
