### ISSUE TITLE
When I add two React Apps programmed for the SharePoint Framework, the layout collapses.😵

### ISSUE THREAD

**Issue by SakatoShogo** [gregnb/mui-datatables#1295]
## Describe the bug
When I add two React Apps programmed for the SharePoint Framework, the layout collapses.

## To Reproduce
In order to reproduce, I recreated 2 React Apps according to the source cords in the link below, under the Usage tab.
https://github.com/gregnb/mui-datatables

〇React App No.1
MUIDatatableTest001

〇React App No.2
MUIDatatableTest002

Here is a screenrecording of the bug: the layout collapses when I add two React Apps.
https://youtu.be/Vzt3Yl6QE5U

## Expected behavior
What I am looking for is a remedy that would allow me to add the two React Apps without collapsing the layout.

Please let me know if there are any possible remedies or ideas that may help solve this issue. Thank you.

**Comment by wdh2100** [comment]
what is options(responsive ... etc)

**Comment by SakatoShogo** [comment]
@wdh2100 
thanks for your comment.

I only use the below options.
`
const options = {
  filterType: 'checkbox',
};
`

**Comment by patorjk** [comment]
Using the new v3.0.0 (released today), in the options, try: 

    const options = { responsive: 'standard' };

That will prevent the table from collapsing into a vertical responsive layout. In an older version of the table try:

    const options = { responsive: 'scrollMaxHeight' };

**Comment by SakatoShogo** [comment]
@patorjk 
Thank you very much for your kind support.
The problem is solved.
