### ISSUE TITLE
mui-datatables does not render the table with supplied data, instead shows "Sorry, no matching records found"

### ISSUE THREAD

**Issue by liya-josh** [gregnb/mui-datatables#1297]
Mui-datatables displays "Sorry, no matching records found" even when the dataArray variable is supplied to the data prop of the component. 

**Expected Behavior**
Display the dataArray supplied to the data prop of the table.

**## Current Behavior**
Displays "Sorry, no matching records found" even when data is supplied. 

**## Steps to Reproduce (for bugs)**

1. Initial set of data supplied to the table is rendered correctly.
2. Used the OnChangePage option to manipulate the data.
3. The dataArray variable which is supplied to the data prop is updated. (Did a console log on the dataArray variable supplied to the data prop, and it consoled the right data)
4. But the table displays "Sorry, no matching records found", which means the mui-datatable hasn't accepted the supplied variable to the data prop.

Material-UI  v4.9.14
MUI-datatables v2.14.0
React  v16.13.1

**Comment by patorjk** [comment]
Can you create a CodeSandbox showing this? If so, I'll take a look. (ex: https://codesandbox.io/s/wy2rl1nyzl)

**Comment by liya-josh** [comment]
@patorjk thank you so much, but I think https://github.com/gregnb/mui-datatables/issues/189  ticket addressed my problem. And I got few insights from the same. I am sorry, I didn't find it earlier before creating this ticket and hence closing it now.
