### ISSUE TITLE
Editing No Data Default Text

### ISSUE THREAD

**Issue by avgupta456** [gregnb/mui-datatables#1299]
## Expected Behavior

Would it be possible to add an option to change the default message when no data is present? I'm loading data from an API, and for the first 2-3 seconds, don't want users to think there is no data, but that it is on the way.
## Current Behavior

Currently, "Sorry, no matching records found" is displayed, and there is no method to replace this text (as far as I know)

Thank you in advance for the help!

**Comment by patorjk** [comment]
You can change the text via the textLabels option:

    const options = {
      textLabels: {
        body: {
          noMatch: '', // this would be whatever you want the message to say
        }
      },
      ...
    };

    <MUIDataTable
      title={"Employee List"}
      data={data}
      columns={columns}
      options={options}
    />

More info here: https://github.com/gregnb/mui-datatables#localization

**Comment by avgupta456** [comment]
Thank you so much, don't know how I missed that
