### ISSUE TITLE
Checkbox in TableHead shows checked if data is empty which is confusing on load

### ISSUE THREAD

**Issue by mattcorner** [gregnb/mui-datatables#1301]
## Expected Behavior
If the table has no data, the default checkbox state should be unchecked rather than checked.

## Current Behavior
Checkbox shows as checked while table data loads, but once data loads, becomes unchecked because no rows are selected.

## Steps to Reproduce (for bugs)
https://codesandbox.io/s/infallible-archimedes-ulsmb?file=/src/App.js

https://github.com/gregnb/mui-datatables/blob/master/src/components/TableHead.js#L37

I think this line should become something like:

`    
let isChecked = numSelected > 0 && numSelected === count ? true : false;
`

**Comment by patorjk** [comment]
I agree, and I think your proposed fix would probably solve it. If you put in a PR I can get it into the [v3 branch](https://github.com/gregnb/mui-datatables/pull/1300) that's currently being worked on.

**Comment by mattcorner** [comment]
Feel free to close issue now, or when v3 is released. Thanks @patorjk

**Comment by patorjk** [comment]
Fixed in v3 (released today).
