### ISSUE TITLE
Proposal for updating "stacked" appearance

### ISSUE THREAD

**Issue by patorjk** [gregnb/mui-datatables#1308]
**EDIT 2020.06.05:** An update to the responsive option is in a PR here: https://github.com/gregnb/mui-datatables/pull/1312

The below post is now out of date, please see that PR for information on how the responsive option will change.

**Original Post:**

Hello all, I'm currently working on putting together [v3 of this package](https://github.com/gregnb/mui-datatables/pull/1300).

There have been some  issues relating to trouble with the stacked view (https://github.com/gregnb/mui-datatables/pull/1150, https://github.com/gregnb/mui-datatables/issues/1142, https://github.com/gregnb/mui-datatables/issues/1149, https://github.com/gregnb/mui-datatables/issues/1253, https://github.com/gregnb/mui-datatables/issues/1097), and if you toggle the 2.14.0 and 2.13.3 releases in the following example, you can see the formatting has changed:

https://codesandbox.io/s/muidatatables-custom-toolbar-khrv8

I'm not sure I like the current approach, and fixing it so that the two cells are next to each other seems to lead to problems with text overflow if a column has a lot of text. While looking through the issues I found one solution which I thought was rather nice: (https://github.com/gregnb/mui-datatables/issues/1188)

![stackedFullWidth_fixed](https://user-images.githubusercontent.com/46763360/73977242-dadbd100-48de-11ea-995c-1c704a13acf4.jpg)

I asked if they'd do a PR, but I realized it'd probably be good to get some community feedback on this. Does anyone have any opinions about the appearance of the stacked view? Would this be a good solution?

The current implementation has the following problems:
* Text overflow when there is a lot of data in a column.
* Cells look odd with their border not reaching all the way across.

The proposed solution would eliminate these issues and provides a cleaner look that is easy to read on mobile.

**Comment by patorjk** [comment]
Also, I'm wondering if it makes sense to split the "responsive" option into two different parameters:

* `displayMode`: stacked (table always in stacked mode), scroll (table always in scroll mode), and stackedResponsive (table in stacked mode when small and scroll mode when large)
* `displaySizeOptions`: fullWidth (boolean), fullHeight (boolean)

I think doing it this way would make everything a little more clear.

**Comment by wdh2100** [comment]
As you said, "responsive" is confused now.

I think we should consider this (#1264, #1227 ) as well.

**Comment by patorjk** [comment]
I agree, the height on scrollMaxHeight is frustrating and needs to be addressed.
