### ISSUE TITLE
ViewColumn Panel’s Close button does not work

### ISSUE THREAD

**Issue by pranavtheway** [gregnb/mui-datatables#1323]
ViewColumn Panel’s Close button does not work.

On inspecting, its found that the “X” button viewColumn Panel does not have button element.

**Comment by wdh2100** [comment]
@pranavtheway  thank reporting!

There's a problem with **z-index.** 
found a bug.

I'll have to fix it soon.

**Comment by patorjk** [comment]
Fixed in version 3.0.1
