### ISSUE TITLE
Sorting Icon Doesnt Display

### ISSUE THREAD

**Issue by pranavtheway** [gregnb/mui-datatables#1324]
Sorting Icon Doesnt Display

**Comment by patorjk** [comment]
You mean the asc/desc arrow in the column headers? It looks like it displays for me. Which version of material-ui and mui-datatables are you using?

**Comment by pranavtheway** [comment]
Yes exactly those Icons

Below are my details:

Material Ui- 4.10.0
/icons - 3.0.2
/pickers - 3.2.6

Mui-datatables - ^3.0.0

**Comment by patorjk** [comment]
Looks like they appear for me in this codesandbox with those versions: https://codesandbox.io/s/muidatatables-custom-toolbar-zk0t3?file=/index.js

Are you using any special customHeaderRender functions? What browser are you using?

**Comment by pranavtheway** [comment]
No I am not using any customHeadRenderer, I am on Chrome Browser and IE11

**Comment by patorjk** [comment]
Does the codesandbox above work for you? 

I have a feeling this could just be a style override somewhere. I vaguely remember encountering this, however, if I can't recreate it, it's going to be hard to debug. If you inspect the header element of your cells, do you see an element with a class of "MUIDataTableHeadCell-sortAction-[number]"? And for the currently sorted column, is there any svg element inside of this div?

**Comment by pranavtheway** [comment]
Yes the sandbox work fine...

And I did saw the mentioned class and associated svg in inspect element, but it doesnt appear on header cell

**Comment by patorjk** [comment]
So if you click on a column to sort it, and then you inspect the column, you see an svg like this, correct?

![image](https://user-images.githubusercontent.com/521224/84424991-dc9c0500-abee-11ea-82d6-093e72a4fc3d.png)

If so, I would look at the styles placed on the element to see if anything is overriding it from being visible. Basically compare the "Styles" in your console sidebar to the "Styles" in console for the codesanbox example.

**Comment by pranavtheway** [comment]
I found it the color of svg is overriden to white color hence was not visible... thanks for this Patrick

**Comment by patorjk** [comment]
No prob, glad to hear it's fixed :)
