### ISSUE TITLE
Styling the Expandable Row Icon Button

### ISSUE THREAD

**Issue by mattspahr** [gregnb/mui-datatables#1326]
I am looking to remove the padding around the expandable row Icon Button. I cannot just simply override the 2 classes its given, MuiButtonBase-root MuiIconButton-root because that will affect all of my Icon Buttons throughout my application. Is there any fix to this or maybe I am missing something?

**Comment by patorjk** [comment]
I'm not seeing any padding around that button in my setup:

![image](https://user-images.githubusercontent.com/521224/84438285-4bd02400-ac04-11ea-9a18-95f298d975fb.png)

You also may be able to target the button by using the MUIDataTableSelectCell class. Something like:

      MUIDataTableSelectCell: {
        root: {
          '& .MuiButtonBase-root': {
            padding: 0,
          }
        }
      }

**Comment by mattspahr** [comment]
@patorjk Yeah, for some reason the 12px of padding from .MuiIconButton-root was getting applied. The styling you wrote below fixed my issue. Thank you
