### ISSUE TITLE
onCellClick doesnt work with filters or searching [Question]

### ISSUE THREAD

**Issue by AaronKauffman** [gregnb/mui-datatables#133]
## Current Behavior

onCellClick returns the index of the column and row selected of the current page. So this index will always be 0 - [(# rows per page)-1]. So if the user filters or searches then the index value returned is not able to be associated back with the data the user clicked on. 

## Expected Behavior

The expected behavior would be that the index returned is the index value in the data array of the cell that you clicked so that you can then use it to access that data to be used. 

## Alternative Actions?
Is there another way that I can get an on row click like functionality without the checkboxes being used that works across pages, rows per pages, filters, and searching?

**Comment by gregnb** [comment]
Hey @AaronKauffman thanks for the issue. I agree, the dataIndex should be provided too. I'll look into this as I do return that on another callback

**Comment by gregnb** [comment]
This has been addressed. onCellClick now returns

```
(colData: any, cellMeta: { colIndex: number, rowIndex: number })
```

**Comment by AaronKauffman** [comment]
Hey @gregnb sorry for a huge delay in getting back to this but this doesnt seem to fully solve the initial problem of the sort and filter situation. I still have to use the row and column index along with the page number and rows per page to get the index of the data in my original data set vs just using the dataIndex value like in onRowClick. And doing that math leads to incorrect indexing if the user has sorted or filtered the table.
