### ISSUE TITLE
How to customize how the values appear in the filter list?

### ISSUE THREAD

**Issue by mxmlnglt** [gregnb/mui-datatables#1335]
Hello,

We're using MUIDataTable for a while now, because that's the best table-oriented component the previous front developer had chosen.
Now he's not here, we have to try our best to make it meet our users' expectation.

That's why I'm opening a few issues regarding various aspects of customization of MUIDataTable.
For this purpose, I've forked your Codesandbox and created a little showcase of all our issues:
https://codesandbox.io/s/muidatatables-misc-requests-4vkxk

Some columns can have no data (either empty string or null), and nothing get display: it's OK for us.
Same for the filters - we use `multiselect` but that's the same with either `checkbox` or `dropdown`: it's OK for us.
However, we would like to customize the way these "empty" values appear in the filters e.g. in our example put `(empty)` instead of either (not displayed) `""` or `null`.
Note: but the filter should pertain the original value i.e. when clicking on this `(empty)` only rows with values `""` or `null` for this column should be displayed.

Current:
![MUIDataTable_filters_empty_values](https://user-images.githubusercontent.com/29626929/84711934-ba481580-af67-11ea-904d-3713bc80a543.png)

Expected:
![MUIDataTable_filters_(empty)_placeholder](https://user-images.githubusercontent.com/29626929/84711950-c0d68d00-af67-11ea-8108-477a5c2d3985.png)

Note: there is an related open issue: https://github.com/gregnb/mui-datatables/issues/931 but in that case, the developer wants to remove the empty values from the filter, not keep them, like us.

**Comment by patorjk** [comment]
Each column has a filterOptions object that has a "renderValue" property. This property allows you to control how the value is rendered in the filter dialog. Here is a fork of your fork with what you're looking for:

https://codesandbox.io/s/muidatatables-misc-requests-xi611?file=/index.js

Here's the relevant code:

      {
        name: "New Role",
        options: {
          filterOptions: {
            renderValue: val => {
              if (val === "" || val === null || val === undefined) {
                return "(empty)";
              }
              return val;
            }
          }
        }
      },

**Comment by mxmlnglt** [comment]
Ah, thanks.

I think I saw that `renderValue` when reading the doc https://github.com/gregnb/mui-datatables but as there wasn't anything related in the Description, I think I mistakenly took it as a parameter of `onChange`.

I checked your new fork, and it looks promising; however it shows duplicates (twice `(none)`) - do you know if this could be "fixed"? or should we rely on a customFilter?

**Comment by patorjk** [comment]
It's because your Role field has two different empty values, "" and null:

      ["Blake Duncan", "Business Management Analyst", "", 65, false],
      ["Frankie Parry", "Agency Legal Counsel", null, 71, false],

Since they're different values, they'll both be added to the list. You're best bet would just be to change nulls to "" (or vice verse) in your data. Or you could do something like this:

        renderValue: val => {
          if (val === null) {
            return "(null)";
          } else if (val === "") {
            return "(empty)";
          }
          return val;
        }

**Comment by mxmlnglt** [comment]
Thanks. Yes, I do know we have different "empty" values, but I thought that by using the same "rendered" value `(empty)`, they would be merged into the same filterList value.

But you're right, that would be probably better to merge/initialize those values before passing them to the data table (and by the way I think that's probably what we're already doing with such expression as `... || ""` - it's just my example is way more simpler in the way it creates its data).

**Comment by gerasvm** [comment]
is there any way to render the value based on the value of another column?

**Comment by vebinua** [comment]
The renderValue works on the filter lists, however, the return value doesn't reflect on the filter chip or tag that shows up after selecting:
![image](https://user-images.githubusercontent.com/8110083/186282732-c690486b-87e5-43e5-9fa3-9ed674fe8ca6.png)

Is there a way that we could easily override the render value for the corresponding chips too? :)

**Comment by j8jacobs** [comment]
> The renderValue works on the filter lists, however, the return value doesn't reflect on the filter chip or tag that shows up after selecting: ![image](https://user-images.githubusercontent.com/8110083/186282732-c690486b-87e5-43e5-9fa3-9ed674fe8ca6.png)
> 
> Is there a way that we could easily override the render value for the corresponding chips too? :)

@venbinua Found it with a bit of digging -  [setFilterChipProps](https://github.com/gregnb/mui-datatables/blob/e09c39cb3c5713c7c157845b3d3e4b7d77c77649/examples/customize-filter/index.js#L244)

my use case was simple, all I needed was to add the column name in the chip label. Did it with:
```
        options={{
          setFilterChipProps: (colIdx, colName, data) => {
            return {
              label: `${colName}: ${data}`,
            }
          },
        }}
```

Absolutely love this library. Shoutout to the creators 👏🏽

**Comment by GoaKoala** [comment]
This solution doesn't seem to work anymore. You can not change label with the setFilterChipProps. Only these options are available?

```
        return {
          color: 'primary',
          variant: 'outlined',
          className: 'testClass123',
        };
```

Does anybody know any other solution for this?

**Comment by GoaKoala** [comment]
Managed to solve this by using a CustomFilterList component. 

[https://github.com/gregnb/mui-datatables/blob/master/examples/custom-components/index.js](https://github.com/gregnb/mui-datatables/blob/master/examples/custom-components/index.js)


You can change the label in the CustomChip.
