### ISSUE TITLE
Next page button leading to 'Sorry, no matching records found' when list is filtered

### ISSUE THREAD

**Issue by harissokoli** [gregnb/mui-datatables#136]
When you filter the list and get only few items pagination still remains active and if you try to change the page you get 'Sorry, no matching records found' on next page.

## Expected Behavior
- Pagination must be disabled if items per page doesnt surpass current items count

## Current Behavior
- Pagination remains active and clickable

## Steps to Reproduce (for bugs)
- https://wy2rl1nyzl.codesandbox.io/
- Filter a name
- click next page

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  1.2       |
| MUI-datatables  | beta 19        |
| React        |  16.4       |

**Comment by gregnb** [comment]
Yep a bug indeed. Thanks for submitting

**Comment by gregnb** [comment]
This issue looks resolved in the latest version: https://1r0rxklovl.codesandbox.io/
