### ISSUE TITLE
Use Frament rather than Paper

### ISSUE THREAD

**Issue by sornman** [gregnb/mui-datatables#137]
## Expected Behavior
For design purposes, using a Fragment rather than a Paper would allow the user to control how the datatable is contained/displayed in the application.

## Current Behavior
Currently, the datatable is inside a Paper, which can cause nested Papers and other issues depending on how the user designs their application.

**Comment by SidharthRaveendran** [comment]
I would also like the same functionality implemented.

**Comment by Diaver** [comment]
@sornman @SidharthRaveendran 
Done in my fork: https://www.npmjs.com/package/material-datatable
Option usePaperPlaceholder

**Comment by gregnb** [comment]
There is now an option called `elevation` which you can set to 0 to hide the default elevation provided to the Paper component
