### ISSUE TITLE
Fixed number of selectable rows ?

### ISSUE THREAD

**Issue by mattspahr** [gregnb/mui-datatables#1375]
I am trying to make it so the user can only select a max number of 25 rows. 
```
isRowSelectable: (dataIndex, selectedRows) => {
      return selectedRows.data.length < 25;
},
```
This does not let a row be selected after there are 25 but I cannot unselect a row. I looked at the selected-rows example but cannot get something to work for me. Thanks

**Comment by patorjk** [comment]
Below is a codesandbox of it working with 25 rows:

https://codesandbox.io/s/muidatatables-custom-toolbar-ps9co?file=/index.js
