### ISSUE TITLE
csv output trims 0 which are in the first position i.e,("0000111111" to "111111")

### ISSUE THREAD

**Issue by sh4rm4** [gregnb/mui-datatables#1377]
When I download CSV, the output of that should be the exact replica of the table. but it skips the '0'  values and displays the remaining number.

Expected Behavior
One column in the table consists of value as "0000111111", so when I download it in CSV, it should display as "0000111111"

Current Behavior
instead of "0000111111" but it is displaying as "111111"

## Steps to Reproduce (for bugs)
1. add data in the column starting with 0 followed by the digits from 1-9 i.e., (002220002)
2. download the CSV
3. Check whether the 0 is displayed in that particular column

Thanks in advance.

**Comment by patorjk** [comment]
This is your CSV display program (probably Excel) that is doing this. If you right click the CSV file and open it in Nodepad, you'll see that the value is indeed "0000111111". Different CSV display programs will act differently when displaying data. Excel likes to look at the input and then guess how it should be displayed. It's probably seeing "0000111111" and deciding it should be displayed like a number.

**Comment by sh4rm4** [comment]
Thank you for the info @patorjk. Is there any possibility of displaying the result "0000111111" as it is instead of formatting by default? Any help would be appreciated.

**Comment by patorjk** [comment]
This is really more of an Excel issue. However, one way of getting around it would be to format the cells prior to creating the CSV (using the onDownload option) and setting the cells up to equal this:

="0000111111"

That would force Excel to render the value as a string. Example:

```
onDownload: (buildHead, buildBody, columns, data) => {
    var newData = data.map( row => {
        // format data here
    });
    return "\uFEFF" + buildHead(columns) + buildBody(newData); 
} 
```
