### ISSUE TITLE
Display row number

### ISSUE THREAD

**Issue by Eithcowich** [gregnb/mui-datatables#1379]
Is there a way to display the row numbers? One of my tables is ranking assets and it would be very helpful for the users to see if an asset is ranked, for example, 28 or 12. Thanks!

**Comment by patorjk** [comment]
See the customBodyRender/customBodyRenderLite methods. customBodyRender has a rowIndex on the tableMeta object and customBodyRenderLite takes in a rowIndex parameter. You can use this value for the display.

**Comment by Eithcowich** [comment]
Thanks. For future searches here's the code I used. I added a column as the first one: 

        {
            name: '',
            label: '',
            options: {filter: false,
                customBodyRender : (value, tableMeta, update) => {
                    let rowIndex = Number(tableMeta.rowIndex) + 1;
                    return ( <span>{rowIndex}</span> )
                }
            },
        },
