### ISSUE TITLE
Add documentation / demo for server side filtering, paging, searching, sorting

### ISSUE THREAD

**Issue by rooby** [gregnb/mui-datatables#138]
I notice some resolved issues around server side paging, sorting, etc.

It would be great if there was documentation and a demo regarding the implementation of that.

**Comment by gregnb** [comment]
Absolutely agree. It's on my todo list

**Comment by nathpree** [comment]
@gregnb  I need this please.

**Comment by gabrielliwerant** [comment]
There are now two examples for serverside rendering:

- https://github.com/gregnb/mui-datatables/blob/master/examples/serverside-pagination/index.js
- https://github.com/gregnb/mui-datatables/blob/master/examples/serverside-options/index.js

@rooby. @nathpree Do these provide what you need?

**Comment by nbrustein** [comment]
I don't see in either of those an example of server-side filtering.  I'm trying to use a textField filter, but in order to do that with server side filtering, I would at least have to debounce the request.  Seems like it would be even better if, in that case, there were a submit button on the filter form, so I could finish selecting my filters before the request went out.

Are there built-in features that make filtering work with a text field filter that I'm not seeing?

**Comment by patorjk** [comment]
@nbrustein there's been some discussion here: https://github.com/gregnb/mui-datatables/issues/857

I'm in a similar boat, I wouldn't mind taking on this issue if @gabrielliwerant decides it'd be a good addition.

**Comment by Orlayhemmy** [comment]
This demo only shows pagination working. Sorting, filtering and searching are not. I have observed that they don't work alongside the pagination properties. Can you please confirm this?

**Comment by pedroguibueno** [comment]
Yeah, it seems like the demo only show pagination. Doesn't the datatable allow the action of sorting a column to return a new array of items from server side? Changing the page number and all? Same for searching and filtering.

**Comment by gabrielliwerant** [comment]
There are now 4 examples for serverside functionality:

- `serverside-filters`
- `serverside-options`
- `serverside-pagination`
- `serverside-sorting`

I'm willing to add more, so feel free to open PRs for other specific serverside demos.

**Comment by loretoruiz** [comment]
Hello friend, greetings from Venezuela. I am something new in Reactjs ... I have the same problem in Mui-Datatatables, the paging buttons are not enabled and from my Back-end I am fetching the data (count, data, page) well. Can I show you my code to see if you can help me?

I attach the js file with the code, modify it using Hooks, the number of pages returns it correctly from the back-end but the buttons are also not enabled.

I hope you can help me !

Cheers.

`import React, { useState, useEffect } from "react";
import ReactDOM from "react-dom";
import reqwest from "reqwest";
import { CircularProgress, Typography } from "@material-ui/core";
import MUIDataTable from "mui-datatables";

export default function Example(props) {
  const [page, setPage] = useState(1);
  const [count, setCount] = useState(1);
  const [data, setData] = useState([["Loading Data..."]]);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    getData();
  });

  // get data
  const getData = (page = 1) => {
    setIsLoading(true);

    reqwest({
      url: `http://localhost:3000/api/musers/${page}`,
      method: "get",
      type: "json",
    }).then((data) => {
      setCount(data.total);
      setData(data.data);
      setIsLoading(false);
    });
  };

  const changePage = (page) => {
    setIsLoading(true);
    getData(page);
    setPage(page);
    // this.xhrRequest(`http://localhost:3000/api/musers/${page}`).then((res) => {
    //   this.setState({
    //     isLoading: false,
    //     page: page,
    //     data: res.data,
    //     count: res.total,
    //   });
    // });
  };
  /*********************** Cargar data ************************ */

  /*********************************************************** */

  const columns = ["ID_Users", "FirstName", "LastName", "Email"];
  //   const { data, page, count, isLoading } = this.state;

  const options = {
    filter: true,
    filterType: "dropdown",
    responsive: "stacked",
    serverSide: true,
    count: count,
    page: page,
    searchBox: true,
    pagination: {
      next: "Next Page",
      previous: "Previous Page",
      rowsPerPage: "Rows per page:",
      displayRows: "off",
    },
    onTableChange: (action, tableState) => {
      console.log(action, tableState);
      // a developer could react to change on an action basis or
      // examine the state as a whole and do whatever they want

      switch (action) {
        case "changePage":
          changePage(tableState.page);
          alert(page);
          break;
      }
    },
  };
  return (
    <div>
      <MUIDataTable
        title={
          <Typography variant="title">
            ACME Employee list
            {isLoading && (
              <CircularProgress
                size={24}
                style={{ marginLeft: 15, position: "relative", top: 4 }}
              />
            )}
          </Typography>
        }
        data={data}
        columns={columns}
        options={options}
      />
    </div>
  );
}
`

**Comment by patorjk** [comment]
Closing issue due to age. Examples now added in examples folder and available here: https://codesandbox.io/s/github/gregnb/mui-datatables

**Comment by eminence88th** [comment]
> There are now 4 examples for serverside functionality:
> 
> * `serverside-filters`
> * `serverside-options`
> * `serverside-pagination`
> * `serverside-sorting`
> 
> I'm willing to add more, so feel free to open PRs for other specific serverside demos.

Hi, are these functions already available on the latest update of mui-datatables?
I'm using Axios package for my API calls.

* `serverside-filters`
* `serverside-options`
* `serverside-pagination`
* `serverside-sorting`

Please I need this.

**Comment by patorjk** [comment]
@eminence88th Yes, see the examples folder in this project. You can also use the link in my previous comment to see a live version of them.

**Comment by eminence88th** [comment]
> @eminence88th Yes, see the examples folder in this project. You can also use the link in my previous comment to see a live version of them.

Hi sir @patorjk , thank you for your response. I just want to ask. Is it possible to customize my own search input here in mui-datatables? Do you have examples to do it?

I found this [example](https://github.com/gregnb/mui-datatables/blob/master/examples/customize-search/index.js), Because I wanted to create my own search input. 

Thank you !

**Comment by sohelbaba1998** [comment]
can any one send example code how i can do ?

**Comment by sunnystark-dev** [comment]
Is that possible move MUI data-table pagination  bottom left position to top right (want to align with toolbar)

```
   ];
    const getMuiTheme = () =>
      createMuiTheme({
        overrides: {
          MuiChip: {
            root: {
              backgroundColor: "lightgrey"
            }
          },
          MuiTableCell: {
            head: {
              backgroundColor: "lightgray !important"
            }
          },
          MuiTypography: {
            root: {
              // backgroundColor: "lightgrey",
            }
          },
          MuiTableFooter: {
            root: {
              backgroundColor: "lightgrey"
            }
          },
          MuiTablePagination: {
            actions: {
              marginLeft:"1px",
              color:"red"
            }
          },
          // MuiIconButton:{
          //   root:{
          //       padding:"0px"
          //   }
          // }
        }
      });
```
Code sand box https://codesandbox.io/s/muidatatables-custom-toolbar-forked-ptcuqu?file=/index.js:3558-4390
