### ISSUE TITLE
Rows per page always set to 10

### ISSUE THREAD

**Issue by Blackfire363** [gregnb/mui-datatables#1381]
When I set rows per page in the options to anything other than 10, the table still uses 10 as the default number and if 10 is taken out of the rows per page options array then it becomes blank. I can tell the options were put in correctly however due to the sorting col stuff working
![tableIssue](https://user-images.githubusercontent.com/9978342/86018444-456fe380-ba1d-11ea-84f0-34e6f2373c10.png)

## Expected Behavior
Set rowsPerPage to say 1 it should be 1 row per page and 35 pages

## Current Behavior
Set rowsPerPage to 1, table keeps 10 as the default rows and if 10 is not an option in the rows per page options it becomes blank

## Steps to Reproduce (for bugs)
1. Set rows per page to anything other than 10
2.  Remove 10 from the rows per page options
3. Note table is now still using the 10 rows per page and the dropdown is blank
## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  ^4.9.3  |
| MUI-datatables  |   3.1.3  |
| React        |   ^16.8.6      |
| browser      |     chrome version 83.0.4103.116    |

**Comment by patorjk** [comment]
Can you show me a codesandbox of this happening? It seems to work correctly for me:

https://codesandbox.io/s/muidatatables-custom-toolbar-rifwe?file=/index.js

**Comment by Blackfire363** [comment]
> Can you show me a codesandbox of this happening? It seems to work correctly for me:
> 
> https://codesandbox.io/s/muidatatables-custom-toolbar-rifwe?file=/index.js

Your sandbox does work correctly, it seems this is an issue related more on the react side rather than this package
