### ISSUE TITLE
Complex table does not have headers for each cell properly defined with 'header' or 'scope'

### ISSUE THREAD

**Issue by NidhiKJha** [gregnb/mui-datatables#1386]
I am getting this accessibility issue. I want to generate this kind of table with `headers` in each row that reference the `id` given in `th`

```html
<table>
  <tr>
    <th id="name">Name</th>
    <th id="email">Email</th>
    <th id="phone">Phone</th>
    <th id="addr">Address</th>
  </tr>
  <tr>
    <td headers="name">John Doe</td>
    <td headers="email">someone@example.com</td>
    <td headers="phone">+45342323</td>
    <td headers="addr">Rosevn 56,4300 Sandnes,Norway</td>
  </tr>
</table>
```

**Comment by patorjk** [comment]
You want to look at these options:

    setCellProps
    setCellHeaderProps

They will allow you to set properties on the th and td elements of the table. You can see an example of them being used here: https://github.com/gregnb/mui-datatables/blob/master/examples/customize-styling/index.js
