### ISSUE TITLE
Search Results Defaults to 20 rows

### ISSUE THREAD

**Issue by SirPhemmiey** [gregnb/mui-datatables#1389]
Search results return 20 rows

## Expected Behavior

I want to be able to set my preferred number of search results row just like there's `rowsPerPage` to set Number of rows allowed per page.

## Current Behavior

It only returns 20 results for any search made.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables| ^2.12.4        
| React        | ^16.11.0        
| browser      |         |
| etc          |         |

**Comment by patorjk** [comment]
I'm not sure what you're talking about. Searches will return all results that match the search. Can you provide a codesandbox showing the issue?

**Comment by SirPhemmiey** [comment]
Like, i mean i'm getting data from a remote source. So if i search for anything in the table, it always returns 20 rows/results for any search term.

**Comment by patorjk** [comment]
Does your API tell you the total number of search results? Typically the way you'd do this is you'd set the **count** option to the total number of search results and then you'd set the **page** to the current page of results that you're looking at, and you'd page through the search results.

**Comment by SirPhemmiey** [comment]
You're very right. My API was returning 20 results. Thanks a lot for your help.
