### ISSUE TITLE
Missing ability to change default tooltip placement of TableHead "Sort" tooltip

### ISSUE THREAD

**Issue by dceballos1991** [gregnb/mui-datatables#1390]
Currently the placement value of the tooltip used on the TableHeadCell component is a hard coded "bottom-start". It seems like it would be easy to make it so it takes a placement specified by the user or default on "bottom-start". Current way of doing it would be to create a custom Tooltip but even that way is not working for me. 

## Expected Behavior

A quick an easy way to do this (but perhaps wrong since is not technically a text label) is to allow the user to specify the placement inside the textLabels overrides. For example: 
`const options = {
  ...
  textLabels: {
    body: {
      noMatch: "Sorry, no matching records found",
      toolTip: {
          title:"Sort",
          placement:"top-end"}
      ...`

Otherwise, tooltipPlacement could be its own property under options.
## Current Behavior

    I think they only way of doing this currently is to create your custom tooltip component, but even that is not working for me at the moment. See below:
## Steps to Reproduce (for bugs)

    The way I tried to create a custom Tooltip component:
`const CustomTooltip = (props) => {
        return (
            <MuiTooltip
                placement={'top-end'}
                title={'Sort'}
                >{props.children}</MuiTooltip>
        );
    };

return (
        <React.Fragment>
            <MuiThemeProvider theme={getMuiTheme()}>
                <MUIDataTable
                    title={title}
                    data={data}
                    columns={columns}
                    options={baseOptions}
                    components={{
                        Tooltip: CustomTooltip
                    }}
                />
            </MuiThemeProvider>
        </React.Fragment>`

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.0    |
| MUI-datatables  |    2.6.4     |
| React        |    16.8.6     |
| browser      |         |
| etc          |         |

**Comment by patorjk** [comment]
The custom Tooltip component was introduced recently, try upgrading to mui-datatables version 3.1.4.

**Comment by dceballos1991** [comment]
Sounds good, I will do that and report back. 
I'm wondering, would it still be worth it to allow the user to change the placement of the tooltip without having to make a custom tooltip?

**Comment by patorjk** [comment]
Since it's doable without an option, I'm not sure an option would make sense, since it would be a pretty obscure feature.

The only drawback I could see would be not wanting to change the tooltip position of the toolbar tooltips, but one could always use the text of the tooltip to differentiate.

**Comment by dceballos1991** [comment]
That makes sense. Thank you!
