### ISSUE TITLE
'enableNestedDataAccess' does not exist in type 'MUIDataTableOptions' 

### ISSUE THREAD

**Issue by MinaroShikuchi** [gregnb/mui-datatables#1397]
enableNestedDataAccess property in options doesn not exist for typescript

## Expected Behavior
Type should exist 

## Current Behavior
Type does not exist

## Steps to Reproduce (for bugs)
Try adding the property in options
``
<MuiDataTable
              title={'Profiles'}
              data={profiles}
              columns={columns}
              options={{
  enableNestedDataAccess: '.'
              }}
            /> 
``

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  ^4.9.12  |
| MUI-datatables  |    ^3.1.4     |
| React        |     ^16.13.1    |

**Comment by patorjk** [comment]
Are you are using DefinitelyTyped? I see it listed in their file over there: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mui-datatables/index.d.ts

**Comment by MinaroShikuchi** [comment]
Yes I've installed the last version with no result. 
I uninstall, install again and it's work. 
Thanks
Sorry for inconvenience
