### ISSUE TITLE
DataTable doesn't show when data array is empty

### ISSUE THREAD

**Issue by lucasharada** [gregnb/mui-datatables#140]
When there is no data to display, DataTable doesn't appear.

## Expected Behavior

The DataTable skeleton should appear, with the message provided to `textLabels.body.noMatch`.
## Current Behavior

The DataTable just doesn't render anything.
## Steps to Reproduce (for bugs)

https://codesandbox.io/s/283rq2r5j

**Comment by jkeruzec** [comment]
For reference : #84

**Comment by lucasharada** [comment]
@jkeruzec Thanks for pointing the maintainer response.

In case anyone need to change its code, I just pulled the code and removed the lines 686-688 from `MUIDataTable.js` file. It's now working as expected for my case.

**Comment by jkeruzec** [comment]
@lucasharada 
The trick I used was to set the data like this 
`
data = [[]];
`
to display an empty datatable with no row in it.

It avoids you to touch directly the src code and loose your modification if npm is updated.

**Comment by majose1500** [comment]
@jkeruzec the problem is that your solution show like a one empty register but the ideal is that the table show like "no registers"

**Comment by jkeruzec** [comment]
With latest, you have a new message that is implemented by default : 
[![Edit MUIDatatables example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w0jvm9xm58)
