### ISSUE TITLE
Incorrect V3 deprecation message for onRowsExpand

### ISSUE THREAD

**Issue by dmbarry86** [gregnb/mui-datatables#1402]
### Description
In version 3, the onRowsExpand option is being deprecated in favour of the new onRowExpansionChange option. However, the deprecation warning in the console appears to be incorrect and mentions onRowsSelect instead of onRowsExpand.

### Expected behaviour
Deprecation Notice:  **onRowsExpand** has been renamed onRowExpansionChange. More info: https://github.com/gregnb/mui-datatables/tree/master/docs/v2_to_v3_guide.md

### Actual behaviour
Deprecation Notice:  **onRowsSelect** has been renamed onRowExpansionChange. More info: https://github.com/gregnb/mui-datatables/tree/master/docs/v2_to_v3_guide.md

**Comment by patorjk** [comment]
Thank you for the report! I'll have this fixed in the next version (3.2.0), which should come out next week.
