### ISSUE TITLE
How to clear/reset applied filter chips from a button in custom toolbar?

### ISSUE THREAD

**Issue by geekashu** [gregnb/mui-datatables#1408]
I am upgrading from v2 to v3.1.4.

I have a refresh button in toolbar.. 
```
        customToolbar: () => {
            return <React.Fragment>
                <Tooltip title="Refresh">
                    <IconButton onClick={handleFilterReset}>
                        <RefreshIcon/>
                    </IconButton>
                </Tooltip>
            </React.Fragment>;

        },
```
In v2 I used to set the value of `serverSideFilterList` to [] whenever refresh button was clicked. This also cleared any filter chips that were applied. 
In v3, with `serverSideFilterList` deprecated/gone when I click on refresh button, and if any filter chip is present, how it should be cleared?

**Comment by patorjk** [comment]
The new method uses the filterList array of the [columns.options](https://github.com/gregnb/mui-datatables#column-options) object (the same way non-serverSide filters work). So if you wanted to remove all of the filters, you could do something like this on your columns array:

```
const resetFilters = () => {
  let newCols = this.state.columns.map(col => {
    col.options.filterList = [];
    return col;
  });
  this.setState({
    columns: newCols
  });
};
```

**Comment by geekashu** [comment]
Thank you that worked perfectly. Awesome.
