### ISSUE TITLE
AJAX based pagination

### ISSUE THREAD

**Issue by geekashu** [gregnb/mui-datatables#141]
Hi,

Is there an example which uses ajax based pagination and renders the data-table. I am stuck at it, would appreciate if anyone who has done it and willing to share it. I am using Django Rest Framework with pagination for my list API.

Thanks

**Comment by gadanihiman** [comment]
Hei you can use onChangePage callback options that you can find on the documentation.

first you make componentDidmount function for get datas from api and set it to datas state.
Then
Set your options custom for onChangePage 

```
const options = {
     onChangePage  : (currentPage) => {
        const { prev, limit } = this.state;
        // every change page it will check the page that should be make a new request or not
        if(currentPage > prev) {
          this.setState({prev: prev+1})
          this.onNextPage(limit, currentPage*limit); 
        }
     }
}
```
our state
> state = {
    datas: [],
    limit: 10, 
    prev: 0;
  };


Next Page Function would be like this
```
onNextPage = (limit, start) => {
    const { datas} = this.state;
    // fetch api with limit and start parameter for url
    getDatas(limit, start)
      .then(res => {
       // Set the new datas from last datas and next datas 
        this.setState({
          datas: [...datas, ...res.result]
        });
      })
      .catch(err => console.log(err));
  }
```

**Comment by gregnb** [comment]
PR has been merged to finally provide remote data via the `serverSide` option.
