### ISSUE TITLE
Sort Icon displayed reverse

### ISSUE THREAD

**Issue by pranavtheway** [gregnb/mui-datatables#1410]
With our previous discussion on issue of sorting: https://github.com/gregnb/mui-datatables/issues/1394

We ended up to a solution:

https://codesandbox.io/s/inspiring-lederberg-nde7o?file=/src/App.js

But I have noticed another observation here.

Ideally Arrow Pointing Up is termed or expected to have Ascending order where in Arrow pointing down to be descending. But this sandbox gives the reverse behavior(On salary column)

Please suggest

**Comment by patorjk** [comment]
I probably had 1 and -1 mixed up in the order part. I’m not near a desktop today, but may be able to take a look later tonight if it turns out not to be a 1/-1 flip.

**Comment by wdh2100** [comment]
> I probably had 1 and -1 mixed up in the order part. I’m not near a desktop today, but may be able to take a look later tonight if it turns out not to be a 1/-1 flip.

https://codesandbox.io/s/amazing-northcutt-sqsot?file=/src/App.js

**Comment by pranavtheway** [comment]
Thank You Guys!!! This worked
