### ISSUE TITLE
Remove selection checkboxes but keep rows clickable

### ISSUE THREAD

**Issue by Eithcowich** [gregnb/mui-datatables#1412]
My table has clickable rows - when clicking on each row it goes to a page related to that row. I need this function to stay. 

But I do not need the selection boxes on the left, they just take space and have no functionality I need: 

![Screen Shot 2020-07-14 at 7 25 03 PM](https://user-images.githubusercontent.com/6975895/87451180-320d6c80-c608-11ea-8b15-6ae237298651.png)

Is it possible to remove them?

**Comment by patorjk** [comment]
Yes, set the selectableRows option to "none".

**Comment by Eithcowich** [comment]
Thanks for replying, @patorjk. 

This makes the checkboxes disappear, but now the rows are not selectable (a click on them does nothing). I need them selectable without the checkboxes.

**Comment by patorjk** [comment]
Ah I see, try the selectableRowsHideCheckboxes option then, set it to true.

**Comment by Eithcowich** [comment]
I tried several combinations of these three:

    selectableRows: 'none',
    selectableRowsOnClick: true,     
    selectableRowsHideCheckboxes: true,

None of them does what I need.

**Comment by patorjk** [comment]
What about selectableRowsHideCheckboxes doesn't work? Is it not hiding the checkboxes?

**Comment by Eithcowich** [comment]
With this combination:

        selectableRows: "none",
        selectableRowsOnClick: true,
        selectableRowsHideCheckboxes: true,

The boxes are hidden but the rows are not clickable. 

With this combination: 

        selectableRows: "single",
        selectableRowsOnClick: true,
        selectableRowsHideCheckboxes: true,

The boxes are visible and the rows are clickable.

**Comment by patorjk** [comment]
What version of the library are you using? I do not see the checkboxes:

https://codesandbox.io/s/muidatatables-custom-toolbar-kwemy?file=/index.js

**Comment by Eithcowich** [comment]
I'm using ^2.6.4. Should I upgrade? If I do, is the new version completely backwards compatible or are there changes?

**Comment by patorjk** [comment]
If you're using Material UI v4, then yes. As for compatiblity, it should be backward compatible. There are features that are deprecated or changed (ex: the responsive parameter takes news inputs - but the old ones still work, they just give a deprecation message), but I don't believe anything breaks (assuming you're using Material-UI v4).

**Comment by Eithcowich** [comment]
Fixed once I moved to V3. This is great, thanks!
