### ISSUE TITLE
Moving to V3 breaks text wrapping

### ISSUE THREAD

**Issue by Eithcowich** [gregnb/mui-datatables#1413]
I updated to V3 and now the text wrapping is broken. I'm reading that it was changed but not sure how to fix it. This is my table options: 

    const tableOptions = {     
        selectableRows: "none",
        selectableRowsOnClick: false,
        selectableRowsHideCheckboxes: true,
        responsive: 'vertical',
        denseTable: false,
        rowsPerPage: 50,
        rowsPerPageOptions: [10, 20, 50],
        fixedHeaderOptions: {
          xAxis: true,
          yAxis: true
        },
        isRowSelectable : false,
        selectToolbarPlacement:"none",
        rowHover : false,
   };

This is how it looks now: 

![Screen Shot 2020-07-15 at 11 28 10 AM](https://user-images.githubusercontent.com/6975895/87522470-56ac2780-c68e-11ea-8205-2b27e371bb59.png)

And this is the "before" picture, which is how it should be: 

![Screen Shot 2020-07-15 at 11 29 19 AM](https://user-images.githubusercontent.com/6975895/87522583-780d1380-c68e-11ea-9cd3-ccc1f8efdf3a.png)

How do I fix it?

**Comment by patorjk** [comment]
Can you provide me a codesandbox showing this happening? The default codesandbox has wrapping and just copying and pasting your options doesn't seem to re-create the effect you show above. You can fork this sandbox:

https://codesandbox.io/s/muidatatables-custom-toolbar-rvmcj?file=/index.js

**Comment by Eithcowich** [comment]
Thanks for the codesandbox, seeing that it works there had me take another look. In my theme I had

          MUIDataTableBodyCell: {
              root: {
                  maxHeight: 20,
                  maxWidth: 200,
                  fontSize: 16,
                  color: fontColor,
                  fontFamily: fontFamily,
              }
          },
Commenting out the `maxHeight` removed the problem. Thank you.
