### ISSUE TITLE
setCellProps changed following V3 update

### ISSUE THREAD

**Issue by Eithcowich** [gregnb/mui-datatables#1414]
I'm setting a cell's border by calling `setCellProps` in the column's options. This is the code: 

    setCellProps: (value) => { return { className: classnames ({ [classes.BorderCell]: value !== undefined, }) }}

`BorderCell` is simple CSS: 

    BorderCell: {
        borderRight: '1px solid gray',
    },

In V2 it looked like this: 

![Screen Shot 2020-07-15 at 11 45 57 AM](https://user-images.githubusercontent.com/6975895/87524426-d4713280-c690-11ea-9b58-111d68c49e01.png)

Now it V3 there's a border both for the cell and for the text in it: 

![Screen Shot 2020-07-15 at 11 47 17 AM](https://user-images.githubusercontent.com/6975895/87524558-fbc7ff80-c690-11ea-933f-f5d63323bd7e.png)

What's the new way of doing it?

**Comment by patorjk** [comment]
Looks like this is a bug, the props get spread on the inner cell as well as the table cell: https://github.com/gregnb/mui-datatables/blob/master/src/components/TableBodyCell.js#L136

I'll get a fix into the 3.2.0 release, which should either happen tonight or tomorrow (more info here: https://github.com/gregnb/mui-datatables/pull/1404)

**Comment by patorjk** [comment]
Try with the new 3.2.0 version, this issue should be resolved there.
