### ISSUE TITLE
Pagination behavior problem when serverSide is true

### ISSUE THREAD

**Issue by Sigmarus** [gregnb/mui-datatables#1417]
I have a Datatable with **option `serverSide` set to true** and `rowsPerPage` fixed to 50.
I have a large set of data, so I have to load on demand, and I have custom server side filters.
After the component did mount, I load a first set of 50 items through my api, and with the `onChangePage` table option, I fetch a next set of 50 items and append it to the stored data when a new page is browsed.

CodeSandbox Example :
https://codesandbox.io/embed/throbbing-leftpad-07xj5?fontsize=14&hidenavigation=1&theme=dark

## Expected Behavior

When going to the next page, the page displays only 50 rows (that were previously fetched).

## Current Behavior

When going to the next page, the page append the fetched data but keeps the previously displayed data.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  | 4.10.0 |
| MUI-datatables | 2.14.0 |
| React             | 16.13.1 |
| browser        | firefox 78.0.2 |
| typescript     | 3.9.6 |
| node        |  13.6.0 |
| etc  |  (see CodeSandbox example)  |

**Comment by patorjk** [comment]
setData([...data, result]);

It looks like when you're adding data, you're just appending it onto the data array that you plug into the table. For serverside data, this data array should equal what's displayed in the table. See the server-side pagination example:

https://github.com/gregnb/mui-datatables/blob/master/examples/serverside-pagination/index.js

It can also be viewed live here: https://codesandbox.io/s/github/gregnb/mui-datatables

**Comment by Sigmarus** [comment]
So I don't have a way to actually store the data I fetched before to avoid refetching it if I come back to the previous pages ?

**Comment by patorjk** [comment]
You can use a separate cache variable for storing all of the data you get from the server, but what you plug into the table for serverside should be what's displayed.

**Comment by Sigmarus** [comment]
Ok, understand. Thanks !
