### ISSUE TITLE
Csv export Bug

### ISSUE THREAD

**Issue by ouchaaou** [gregnb/mui-datatables#1418]
https://439oorwx3w.sse.codesandbox.io/#csv-export

After do search
After click to 'Show Columns'
After removing the display of certain column
After click to 'download CSV'
The CVS file to generate does not contain all the Columns

**Comment by patorjk** [comment]
The example is meant to show off the different options available for exporting. You have the following downloadOptions set for the example you ran:

```
      downloadOptions: {
          filename: 'excel-format.csv',
          separator: ';',
          filterOptions: {
            useDisplayedColumnsOnly: true,
            useDisplayedRowsOnly: true,
          }
      },
```

useDisplayedColumnsOnly will cause only the displayed columns to be in the exported file.

Additionally, using a separator of ";" won't work in every CSV application.
