### ISSUE TITLE
Column checkbox.

### ISSUE THREAD

**Issue by Maark007** [gregnb/mui-datatables#1419]
How can I make a checkbox column ? 
I have this column, an EXAMPLE column, I want to make it all checkbox method.:
 ```  const columns = [
    "Nome",
    "Email",
    "CPF",
    {
      name: "Example",
      options: {
        sort: false,
      },
    },
  ];```

**Comment by patorjk** [comment]
You'll want to use either the customBodyRender or customBodyRenderLite column option. See this example: https://github.com/gregnb/mui-datatables/blob/master/examples/component/index.js
