### ISSUE TITLE
Bug on change statut

### ISSUE THREAD

**Issue by ouchaaou** [gregnb/mui-datatables#1420]
https://439oorwx3w.sse.codesandbox.io/#component

Hello,
When i change status from left to right, other line are assigned at the same time.
I checked in the back-end, Data note affected.
To correct the situation I should do an F5
Have you solved this problem before?
Thank you
Note: I have been using a download version for about a year now

**Comment by patorjk** [comment]
I don't follow. I checked the example you linked and there's no status column. I see an "Active" column, but toggling the switch in that column does not effect other rows. Can you provide the exact steps for what you're seeing?
