### ISSUE TITLE
Remote filtering with options having separate labels and values

### ISSUE THREAD

**Issue by marknagy** [gregnb/mui-datatables#1422]
Hey,

Is it possible for filters to define a separate label and value for the options?

Let's say I have the following filter
```js
{
    name: "testEntity",
    label: "Test entity",
    options: {
        filter: true,
        filterType: "dropdown",
        filterOptions: {
            names: ["Only test users", "Only not test users"],
        },
    },
},
```

<img src="https://user-images.githubusercontent.com/4243339/87764869-5a1eea80-c817-11ea-841d-a31be209e128.png" width="400">
<img src="https://user-images.githubusercontent.com/4243339/87764942-76bb2280-c817-11ea-9d64-c2f618e01adb.png" width="400">

I'd like to filter results on the server-side, so the two options would need the values `true` and `false`.

I don't see what would be the straightforward way to do this using `filterOptions`.

## Expected Behavior
Be able to define filter `values` next to `names` in `filterOptions` for remote data filtering.

## Current Behavior
I get `Only test users` or `Only not test users` in `filterList` of `tableState`, I'd need to define a map with these strings to map to `true` or `false`.

**Comment by patorjk** [comment]
Yes, example here:

https://codesandbox.io/s/muidatatables-custom-toolbar-h8hm9?file=/index.js

Don't use filterOptions.names, it's not what you want in this case.

```
  const columns = [{
    name: "Some Value",
    options: {
      // controls filter dialog display
      filterOptions: {
        renderValue: v => {
          if (v === true) {
            return "Only test users";
          } else if (v === false) {
            return "Only not test users";
          }
        }
      },
      // controls filter chip display
      customFilterListOptions: {
        render: (v) => {
          if (v === true) {
            return "Only test users";
          } else if (v === false) {
            return "Only not test users";
          }
        }
      }
    }
  }, "Title", "Location"];
```

Use filterOptions.renderValue to control the display inside of the filter dialog window. Use customFilterListOptions.render to control the display of the filter chips.

**Comment by marknagy** [comment]
Thank you for the quick response!

The example you sent seems to work if in the currently loaded data has both of the options (`true` and `false`), but I'd like to be able to filter for values not present in the current result.

It also looks like it doesn't work with `customBodyRender`, I'd like to show different text in the table than on the filter dialog.

```
{
    name: "testEntity",
    label: "Test entity",
    options: {
        filter: true,
        filterType: "dropdown",
        filterOptions: {
            renderValue: (v: boolean) => {
                if (v === true) {
                    return "Only test users";
                } else if (v === false) {
                    return "Only not test users";
                }
                return "";
            },
        },
        customBodyRender: (isTest: boolean) => {
            return isTest ? "Yes" : "No";
        },
    },
}
```

**Comment by patorjk** [comment]
Ah, I see. Then you will want to use names, but in conjunction with the other options I mentioned:

```
  const columns = [{
    name: "Some Value",
    options: {
      // controls filter dialog display
      filterOptions: {
        names: [true, false],
        renderValue: v => {
          if (v === true) {
            return "Only test users";
          } else if (v === false) {
            return "Only not test users";
          }
        }
      },
      // controls filter chip display
      customFilterListOptions: {
        render: (v) => {
          if (v === true) {
            return "Only test users";
          } else if (v === false) {
            return "Only not test users";
          }
        }
      },
      customBodyRender: (value) => {
        return value ? "Yes" : "No";
      },
    },
  }, "Title", "Location"];
```
Updated example: https://codesandbox.io/s/muidatatables-custom-toolbar-h8hm9?file=/index.js:605-1263

Think of the values in "names" getting processed by renderValue before being shown in the filter dialog.

**Comment by marknagy** [comment]
Thanks, it works 👍
