### ISSUE TITLE
Filter when server-side is true

### ISSUE THREAD

**Issue by SirPhemmiey** [gregnb/mui-datatables#1431]
I want to be able to get the filter text and filter label (or index) of the text selected in the filter dropdown

Okay so, i noticed that the filterList is an array of arrays which is a bit difficult to get the values of the filters. I also noticed that the index numbers denotes the column positions in the array. Actually, i have no problem in checking if the user selects one filter value in the dropdown, i would just need to check if `filterList[2][0]` is empty or not and then use it in my database `where` clause. 

But the really challenge i am having is when they select more than one value in the filter, then i need to know which index was selected (not empty) and the value so as for me to use in my query at the backend. I opted to use filter function to get non-empty values in the `filterList` array (as in `filterList.filter((v) => v.length > 0)`) but only gets me the values and obviously i don't know which index or labels those value belong to. 

I would appreciate any help for me to solve this issue. 

Thanks.

**Comment by patorjk** [comment]
What you're asking is possible, though I'm a little confused what you mean by "which index was selected". Can you create a codesandbox demonstrating the issue? All of the filters should be in that column's filterList (ex: filterList[2][0] should be an array of the filter values).

> I opted to use filter function to get non-empty values in the filterList array (as in filterList.filter((v) => v.length > 0)) but only gets me the values and obviously i don't know which index or labels those value belong to.

How are you trying to transform the data? You may want to use more traditional looping instead:

```
for (let ii = 0; ii < filterList.length; ii++) {
  if (filterList[ii].length > 0) {
    let columnName = columns[ii].name;
    let filterListForColumn = filterList[ii];
    let colStr = columnName + '=' + filterList[ii].join(',');
  }
}
```

Also, server-side filter list example here: https://github.com/gregnb/mui-datatables/blob/master/examples/serverside-filters/index.js

**Comment by SirPhemmiey** [comment]
@patorjk , this is exactly what i needed. 

Thank you very much!
