### ISSUE TITLE
Sort by default checked items asc

### ISSUE THREAD

**Issue by tecnoher** [gregnb/mui-datatables#1437]
Hi, anyone can help me with?
I need to set order by default of items checked 

## Expected Behavior
On load datatable order by checked asc

## Current Behavior
When datatable is loaded it orders by default the items by index

## Steps to Reproduce (for bugs)

https://codesandbox.io/s/001jq

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   3.0.1     |
| MUI-datatables  |    2.14.0     |
| React        |    16.13.1     |
| browser      |    chrome     |
| etc          |         |

**Comment by patorjk** [comment]
You'll want to look at the customSort option: https://github.com/gregnb/mui-datatables/blob/master/examples/customize-sorting/index.js

You'll need to use that in combination with the rowsSelected data from the table, which you can get from the onRowSelectionChange callback.

To make this easier, I could pass some table meta info (like the rowsSelected data) to the customSort function. But for the moment you'd have to get it from the onRowSelectionChange callback.

**Comment by tecnoher** [comment]
Thanks @patorjk that seems to be the way, but I cannot get how to trigger the customSort option, could you please take a look at this: https://codesandbox.io/s/001jq

thanks in advance

**Comment by patorjk** [comment]
I think I got it working: https://codesandbox.io/s/muidatatables-custom-toolbar-r49m0?file=/index.js

**Comment by tecnoher** [comment]
you really are awesome! that's what I needed to order it correctly.
But it still seems the method "custom Sort" is never triggered, could you please give me a clue about calling manually on table initialization?

**Comment by patorjk** [comment]
If you look at my codesandbox you'll see that customSort is being triggered. It's not firing in your sandbox because you set sort=false in the options.

**Comment by tecnoher** [comment]
> I think I got it working: https://codesandbox.io/s/muidatatables-custom-toolbar-r49m0?file=/index.js

patorjk, I've tried this but it is not ordering rows by selected (asc/desc), and the "sort=true" option is setted.

Maybe other option setted is "blocking" the customSort ?
Could you please take a second view on your sandbox?

**Comment by patorjk** [comment]
Are you saying the codesandbox I provided isn't working for you? Do the rows not sort correctly for you? Below is a gif capture of me using the codesandbox:

![chrome-capture](https://user-images.githubusercontent.com/521224/88491794-d205b700-cf73-11ea-808b-a6b0201a2d42.gif)

**Comment by tecnoher** [comment]
It works but not as expected. The behaviour I want is to init the table ordered by selected=ASC. On first render

**Comment by patorjk** [comment]
You can use the sortOrder option to initially sort the table by a certain column.

Updated example: https://codesandbox.io/s/muidatatables-custom-toolbar-r49m0?file=/index.js

**Comment by tecnoher** [comment]
thanks a lot!! that really works !!
