### ISSUE TITLE
Close Button of Show Columns Tool Is Unclickable

### ISSUE THREAD

**Issue by JimCoates** [gregnb/mui-datatables#1440]
## Expected Behavior

Expect that after opening the show columns tool, "x" button should be clickable to close. 
## Current Behavior

The menu still closes on click away, but the button is not clickable. 
## Steps to Reproduce (for bugs)

https://codesandbox.io/s/crazy-archimedes-93bnp?file=/src/App.js

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.9.12     |
| MUI-datatables  |  3.2.0       |
| React        |    13.3.1     |
| browser      |         |
| etc          |         |

Running just the standard example from the documentation in code sandbox shows the button is not clickable.
I tried using older versions, it seems to not be an issue with v2.x

The library is excellent, thank you for taking the time to view this issue!

**Comment by patorjk** [comment]
Thank you for the report! Looks like this can be resolved by adjusting the z-index property of the button. I'll have a fix in version 3.3.0.

**Comment by patorjk** [comment]
Fixed in 3.3.0
