### ISSUE TITLE
Disable checkbox option

### ISSUE THREAD

**Issue by efartCohen** [gregnb/mui-datatables#1442]
I want to disable the checkbox option in the in the table

## Expected Behavior

 Disable the checkbox option. I there an option to disable the checkbox option?
In a specific table I don't want the option to select & delete. 

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.10.0    |
| MUI-datatables  |     3.3.0    |
| React        |   16.13.1      |
| browser      |     Chrome    |
| etc          |         |

**Comment by patorjk** [comment]
See the documentation of the selectableRows option. Ex:

    let options = {
        selectableRows:"none"
    };

**Comment by efartCohen** [comment]
I can't believe I missed that. 
Thanks!
