### ISSUE TITLE
How to hide rowsperpage option on table footer

### ISSUE THREAD

**Issue by hyeoncheolkim91** [gregnb/mui-datatables#1448]
Is there a way to hide or remove rowsperpage on the table footer?

I want to set default rows per page and no selectable options for users.

**Comment by patorjk** [comment]
There are a couple of ways:

* You can set the pagination option to false, and the footer won't display.
* You can use the customFooter option and render your own footer.
* You can use the [components](https://github.com/gregnb/mui-datatables#custom-components) option and override the footer component with your own component.

**Comment by hyeoncheolkim91** [comment]
@patorjk 
But I want to keep the buttons next page and prev page. If I set pagination option false, it removes everything

**Comment by patorjk** [comment]
Set "rowsPerPageOptions" to 1 item which is the same as the "rowsPerPage":

```
    rowsPerPageOptions: [10],
    rowsPerPage: 10,
```

Example: https://codesandbox.io/s/muidatatables-custom-toolbar-mn7ni?file=/index.js

**Comment by hyeoncheolkim91** [comment]
@patorjk Thank you. It works perfectly
