### ISSUE TITLE
Trigger the close search button

### ISSUE THREAD

**Issue by gadanihiman** [gregnb/mui-datatables#145]
I just want to ask simple issues here, because i can't trigger the close button for search, you just give callback onSearchChange for trigger when the textSearch changed.

I just wonder to have a trigger callback when i close the search placeholder here.

Or maybe i want to hide the close button for that search placeholder

Thanks so much!

**Comment by gregnb** [comment]
So you're asking for a callback function when a user clicks the 'x' on the search or hits the escape key? Sure sounds reasonable.

I would probably name it something like 

```
 onSearchClose
```

**Comment by gadanihiman** [comment]
That's sounds good, i need that. Thanks so much!
