### ISSUE TITLE
Warning: Prop `data-tableid` did not match. Server: "08323920907465618" Client: "06902255999981364"

### ISSUE THREAD

**Issue by rfermann** [gregnb/mui-datatables#1452]
## Expected Behavior
No warning about prop mismatch should appear when doing SSR (e.g. with next.js).

## Current Behavior

A warning about prop mismatch appears when using mui-datatables in a next.js context:
<img width="706" alt="screenshot" src="https://user-images.githubusercontent.com/18217019/89051937-431ee300-d355-11ea-8e34-3c46349ec28a.png">

## Steps to Reproduce (for bugs)

See https://codesandbox.io/s/exciting-dhawan-fsrl0 for reproduction.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  4.11       |
| MUI-datatables  |  3.3.1       |
| React        |     16.13    |

The issue is related to the prop `data-tableid`, which is only used for dragging of columns. Turning off the `draggable` option for all columns does not solve the issue.

I took a look into the code and did not fully grasp why `data-tableid` has to be a dynamic value. The only case that would make sense to me is that multiple tables are rendered at once. If that is the reason, it might a possibility to hand over responsibility to the developer and require him to pass a unique identifier to each table.

**Comment by patorjk** [comment]
So the table generates a unique ID for the table so that when it does the selection of cells for the drag transition, sub-tables don't have their columns included in the animation (ref: https://github.com/gregnb/mui-datatables/issues/1406).

I could setup the tableid to be a prop that could be passed in (and if not passed in, it would default to a random number). That would allow the values to match.

**Comment by rfermann** [comment]
Thanks for your reply. Would it also be an option to only generate the random number if `draggableColumns.enabled === true` is passed as a prop? This way people would only have to define `tableid` explicitly when they do SSR and want to use draggable columns.

I could also prepare PR if that would take some effort from you.

**Comment by patorjk** [comment]
@rfermann sure, that would definitely be helpful. I'm thinking of doing a release later today (mostly just a hand full of small issues). If you have it in before then I could include this in that release (realistically I'm thinking this evening).

**Comment by rfermann** [comment]
@patorjk apparently I am not that fast :sweat_smile: ...but a PR has just been created.
