### ISSUE TITLE
Hovering over icons in toolbar generates a warning

### ISSUE THREAD

**Issue by w3bdesign** [gregnb/mui-datatables#1459]
## Expected Behavior

I expect no warnings to display.

## Current Behavior

When hovering over icons in the toolbar I get the following warning in my console. 

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node

## Steps to Reproduce (for bugs)

1. Install React with CRA and --template=typescript with @material-ui/core
2. Install @types/material-ui and @types/mui-datatables
3. Implement the simple example from the docs
4. Start the application and hover over an icon in the toolbar
5. See console

See screenshot below:

![image](https://user-images.githubusercontent.com/45217974/89247714-3d9ff200-d60e-11ea-908e-8b8197b51828.png)

## Your Environment

"dependencies": {
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "@testing-library/jest-dom": "^5.11.2",
    "@testing-library/react": "^10.4.7",
    "@testing-library/user-event": "^12.1.0",
    "@types/jest": "^26.0.8",
    "@types/material-ui": "^0.21.7",
    "@types/mui-datatables": "^3.1.1",
    "@types/node": "^14.0.27",
    "@types/react": "^16.9.44",
    "@types/react-dom": "^16.9.8",
    "@types/react-router-dom": "^5.1.5",
    "easy-peasy": "^3.3.1",
    "mui-datatables": "^3.3.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "typescript": "^3.9.7"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^3.8.0",
    "@typescript-eslint/parser": "^3.8.0",
    "eslint": "6.8.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-airbnb-typescript": "^9.0.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.5",
    "eslint-plugin-react-hooks": "^4.0.8",
    "prettier": "^2.0.5"
  }

**Comment by patorjk** [comment]
These [warnings](https://github.com/mui-org/material-ui/issues/13394) are from Material UI itself. This library (as of version 3.2.0) no longer uses findDOMNode.
