### ISSUE TITLE
how to use loading body when fetch more data from API

### ISSUE THREAD

**Issue by toolaugh** [gregnb/mui-datatables#146]
I want to loading body when fetch more data from API. How I can  use to custom ? 
<!--

**Comment by Aaron-Lei** [comment]
Did you mean when fetch much data from server side, it will cost some time, in the mean time, a loading layer upper the mui-datatable body is needed?
If so, that is also what I'm concerned.

**Comment by gabrielliwerant** [comment]
Checkout https://github.com/gregnb/mui-datatables/pull/583 and see if it answers your question. There are lots of ways to go about showing that loading data is taking place. If you need some other kind of example, let me know.
