### ISSUE TITLE
Cell Content should be stretched even on Mobile

### ISSUE THREAD

**Issue by allindeveloper** [gregnb/mui-datatables#1465]
## Expected Behavior

I expect that the content in the cells should stretch even on mobile
## Current Behavior

Currently the content are being squashed together
## Steps to Reproduce (for bugs)

ScreenShot
[https://drive.google.com/file/d/16FQvAKuKdjiNWqq4jbhlpRcJm8pmw8j0/view?usp=sharing](ScreenShot)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.11.0     |
| MUI-datatables  |  3.4.0       |
| React        |  16.8.4       |
| browser      |  Chrome       |
| etc          |         |

**Comment by allindeveloper** [comment]
Doing this worked on desktop.. but the cell content was still squashed on mobile.
```js
const columns = [{
  label: "Ssn", name: "Ssn",   options: {
    filter: true,
    sort: true,
    setCellHeaderProps: value => ({ style: { width:200 } }),
  }
}, 
{
  label: "Lastname", name: "Lastname",   options: {
    filter: true,
    sort: true,
   }
},
]
```

**Comment by patorjk** [comment]
What do you mean stretched? Have you tried setting the responsive option to "vertical"?

Also, try these options and see if it gives you what you want:

```
const columns = [{
  label: "Ssn", name: "Ssn",   options: {
    filter: true,
    sort: true,
    setCellProps: value => ({ style: { whiteSpace: 'pre' } }),
  }
}, 
{
  label: "Lastname", name: "Lastname",   options: {
    filter: true,
    sort: true,
    setCellProps: value => ({ style: { whiteSpace: 'pre' } }),
   }
},
]
```

**Comment by allindeveloper** [comment]
> What do you mean stretched? Have you tried setting the responsive option to "vertical"?
> 
> Also, try these options and see if it gives you what you want:
> 
> ```
> const columns = [{
>   label: "Ssn", name: "Ssn",   options: {
>     filter: true,
>     sort: true,
>     setCellProps: value => ({ style: { whiteSpace: 'pre' } }),
>   }
> }, 
> {
>   label: "Lastname", name: "Lastname",   options: {
>     filter: true,
>     sort: true,
>     setCellProps: value => ({ style: { whiteSpace: 'pre' } }),
>    }
> },
> ]
> ```

`setCellProps: value => ({ style: { whiteSpace: 'pre' } })`
This just resolved my issue, so that on mobil view, the cell content are squeezed or squashed
Thank you very much!!
