### ISSUE TITLE
Allow passing data as an array of objects

### ISSUE THREAD

**Issue by rooby** [gregnb/mui-datatables#147]
It would be very useful to be able to pass in an array of object for data and then in the column definition you would specify the name of the property on the object.

It would be even better if you could specify nested properties with dot notation, similarly to how [react-table](https://react-table.js.org) works.

**Comment by jkeruzec** [comment]
For feedback,

With my spring rest controller, I have developped utils to take my Rest JSON data and transform it to a raw data array mapped to column to be able to display the data.

It will be very usefull to directly be able to read the JSON and avoid this specific mapping technique.

So for short, yes interested in this functionnality ! ;)

**Comment by benjaminbours** [comment]
Same as @jkeruzec , i'm interested too :)

**Comment by x0fma** [comment]
Does someone started to work on this ?

**Comment by stipe09** [comment]
I'm interested too, it will be very usefull.

**Comment by VIJAYMYSORE** [comment]
+1

**Comment by pavlovicIvan** [comment]
Hi, this feature would be very usefull for our project.
Do you know when will be implemented?

**Comment by stipe09** [comment]
Are you considering to do this feature?

**Comment by sidharthdigiworks** [comment]
It's easier if we have array of objects since data from server usually is formatted that way and we can opt to choose which properties need to be shown in the table.

**Comment by jpmillan** [comment]
+1

**Comment by revskill10** [comment]
You can use this helper function to transform:
```
const convertDataToArray = (data, keys) =>
  data.map(obj => Array.from(keys, k=>obj[k]))

```

**Comment by Diaver** [comment]
I've made in my fork: https://www.npmjs.com/package/material-datatable

**Comment by rooby** [comment]
@Diaver are you going to submitting a pull request to address this issue in this project?

**Comment by Diaver** [comment]
@rooby I am not it is possible -> In my form at least one big change: my datatable accept object array

**Comment by revskill10** [comment]
@Diaver Why not adding one prop like `itemDataType`, which could be `array` or `object` ?

**Comment by Diaver** [comment]
@revskill10 because it is not just one required change

**Comment by revskill10** [comment]
@Diaver I mean let's just reuse the logic, and what we can do is transforming/processing props before passing down the render logic. Because we want to keep maintainance on one project only (?)

**Comment by Diaver** [comment]
@revskill10 
There are some reasons:
1. It is already a lot of changes in my fork.
2. Keep both logic in one project doesn't seems to be good idea for me, at least until current code will be completely refactored.
3. I don't want to be dependent from other people.

**Comment by ginman86** [comment]
You could even do it dynamically by checking the type on the data elements. Is it an array of strings? Then match it by index to the columns. Is it an object? Then match it by key to a `columnKey` property on the column object.

**Comment by pedroo21** [comment]
Not sure why it isn't added yet, so I'm here to increase the feedback. Definitely interested on this!

**Comment by mgolkardev** [comment]
Hi
I pull request to add this option.
https://github.com/gregnb/mui-datatables/pull/331

**Comment by victor-arcane** [comment]
Hi,
It would be very useful, do we have any updates on this?

**Comment by jaksco** [comment]
isn't this the same as #331 ?

**Comment by gregnb** [comment]
The latest release now supports data as objects. Example: https://github.com/gregnb/mui-datatables/blob/master/examples/data-as-objects/index.js

**Comment by raikusy** [comment]
@gregnb How can I access a nested property? For example:
```javascript
const data = [
{
  id: 1,
  parent: {
    child: "wah"
  }
}
]
```
I want to access the child property like:
```javascript
columns={
  [
    {
      name: 'parent.child',
      label: 'Child'
    }
  ]
}
```

**Comment by saurabh8nitrr** [comment]
> You can use this helper function to transform:
> 
> ```js
> const convertDataToArray = (data, keys) =>
>   data.map(obj => Array.from(keys, k=>obj[k]))
> ```

Can you specify in details...what is the key variable and all

**Comment by anjanikumar496** [comment]
Is there any To make a MUI Element as Form as similar to the Jquery Datatable  as i mentioned below

![Screenshot 2020-01-14 at 12 02 21 AM](https://user-images.githubusercontent.com/43503509/72281776-2e049000-3661-11ea-890c-c654520493ac.png)

**Comment by allindeveloper** [comment]
https://github.com/gregnb/mui-datatables/blob/master/examples/data-as-objects/index.js

**Comment by tjatwood** [comment]
This appears to be broken in version 3.7.1. When I upgraded from v2, these columns stopped showing content. Here's a codesandbox to verify. https://codesandbox.io/s/tender-morning-gknfz

**Comment by wdh2100** [comment]
@tjatwood 

thank you for reporting.

As it changed to **v3**, it seems that the data-as-object does not work.

**Comment by tjatwood** [comment]
Thank you! This works great.

**Comment by TKdevlop** [comment]
Thanks dude.

**Comment by musindo** [comment]
This is great thanks a lot. Spent hours on this

**Comment by pradeepdev001** [comment]
Just add <enableNestedDataAccess: '.',> in option object.
For Example:

const options = {
filter: true,
filterType: 'dropdown',
responsive: 'vertical',
enableNestedDataAccess: '.', // allows nested data separated by "." (see column names and the data structure above)
};

Ref: [Link](https://github.com/gregnb/mui-datatables/blob/master/examples/data-as-objects/index.js)
