### ISSUE TITLE
Card view vs Table view

### ISSUE THREAD

**Issue by johnsonsamuel** [gregnb/mui-datatables#1478]
Hello :),

Thank for you for Mui datatables.

Just wanted to check if there is a possibility of displaying the data as card view instead of table view? 😁

Thanks,

**Comment by patorjk** [comment]
You can look at customRowRender for custom display. There's also the responsive mode "simple", which does something similar for small screen sizes.

**Comment by johnsonsamuel** [comment]
@patorjk thank you so much.

**Comment by jinman** [comment]
@johnsonsamuel @patorjk is there anyway you can share an example of the card view. We can customize the row but the cards are still stacked and not sure how they will appear side by side. We're you able to achieve this in any way?
