### ISSUE TITLE
Add an event that fires on any table change

### ISSUE THREAD

**Issue by rooby** [gregnb/mui-datatables#148]
For people who want to let mui-datatables manage table state but want to handle paging, filtering, sorting, etc. on the server side, it would help if there was an extra callback that fires for all state changes (eg. change page, change page size, filter, sort, search), that passes in the whole table state as the parameter.

That would make it really easy to be able to fire off a new API call each time anything happens.

**Comment by rooby** [comment]
I don't really have a preference in regards to naming, however react-table uses onFetchData for their equivalent, since they fire it every time you would have to fetch new data if you were in full server side mode.

**Comment by gregnb** [comment]
PR has been merged and released to finally provide remote data via the `serverSide` option and the callback is `onServerRequest`
