### ISSUE TITLE
Extremely visible lag with confirmFilters: true

### ISSUE THREAD

**Issue by tbarrettwilsdon** [gregnb/mui-datatables#1488]
In an attempt to mitigate the lag introduced by the component updating with each character typed into a filterType: textField type filter, I implemented the confirmFilters flag using the following unmodified code:

`              confirmFilters: true,
                customFilterDialogFooter: (
                  currentFilterList,
                  applyNewFilters
                ) => {
                  return (
                    <div style={{ marginTop: '40px' }}>
                      <Button
                        variant='contained'
                        onClick={applyNewFilters}
                      >
                        Apply Filters
                      </Button>
                    </div>
                  )
                },
`

I'll be the first to admit that this is a fairly customized setup, with the following options:
`
              options={{
                onRowClick: (rowData, rowMeta) => {
                  setDrawerOpen(true)
                  setClickedAsset('assets[rowMeta.dataIndex].barcode')
                },
                draggableColumns: { enabled: true },
                downloadOptions: {
                  filename: 'yamsExport.csv',
                  filterOptions: {
                    useDisplayedColumnsOnly: true,
                    useDisplayedRowsOnly: true
                  }
                },
                customToolbar: bulkImportButton,
                responsive: 'standard',
                customSearchRender: debounceSearchRender(500),
                fixedHeader: true,
                fixedSelectColumn: true,
                tableBodyHeight: size.height - 310,
                customToolbarSelect: (
                  selectedRows,
                  displayData,
                  setSelectedRows
                ) => (
                  <CustomToolbarSelect
                    parentBulkCallback={callbackBulkFunction}
                    parentDeleteCallback={callbackDeleteFunction}
                    parentTransitionCallback={callbackBulkTransitionFunction}
                    selectedRows={selectedRows}
                    displayData={displayData}
                    setSelectedRows={setSelectedRows}
                  />
                ),
                rowsPerPage: 25,
                rowsPerPageOptions: [15, 25, 50, 100]
`

However, if you comment out confirmFilters everything goes back to working well enough, just with lag when you try to enter text in the filter panel. The debounce search worked fantastic for the inline search, but I have not been able to identify a way to implement that for filter text boxes without just rewriting the component, which I'm hoping to avoid for future updates sake.

## Expected Behavior
You hit apply, it updates the filter chip list and applies the filter within a few seconds.

## Current Behavior
Same as above, but it takes nearly 15 seconds where everything is completely frozen before it applies the filter. Very poor UX, they think it's broken or crashed and refresh/close out. System is a 16" Macbook Pro i9 (8 core 2.3ghz), so there's not a whole lot of room for improvement in the client platform - if anything, most users will have an even worse experience with a slower box. 

## Steps to Reproduce (for bugs)
Video of actual performance:
https://drive.google.com/file/d/1alBVtWBQxS-j0aFCBSaoQWHe9KhkAMXN/view?usp=sharing

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.10.2      |
| MUI-datatables  |    3.4.0     |
| React        |    16.8.6     |
| browser      |    Chrome 84     |
| etc          |    Roughly 25-30k records with 15 columns - large data set, total payload is ~11mb of JSON     |

**Comment by patorjk** [comment]
This lag isn't normal when using confirmFilters, and is not something I've run into. All the applyFilters callback does it update the internal filter list:

https://github.com/gregnb/mui-datatables/blob/master/src/components/TableFilter.js#L332

The props.onFilterUpdate is simply a call to the filterUpdate method inside of the main table:

https://github.com/gregnb/mui-datatables/blob/master/src/MUIDataTable.js#L1399

When confirmFilters is false, this method is invoked immediately on change:

https://github.com/gregnb/mui-datatables/blob/master/src/components/TableFilter.js#L121

So it doesn't make any sense why there'd be a lag. I suspect something else may be going on, but I'd need a codesandbox to investigate.

**Comment by tbarrettwilsdon** [comment]
Appreciate you taking a look! I attempted to recreate the config as closely as I can publicly, but I'm actually seeing the behavior that should be happening even with a huge data set - it does appear to be isolated to my environment, so I'll have to dig further and I'll close this out unless anyone has any suggestions where I should start. CodeSandbox for reference => https://codesandbox.io/s/clever-leaf-h99ix?file=/src/index.js

**Comment by tbarrettwilsdon** [comment]
Curious if this provides anymore insight - attached a profiler report showing where the script execution breaks down to when I click "Apply Filters" - you can see how absurdly long it takes. Looks like a big chunk of that time is going to my customBodyRender, where I apply date formatting to date fields. Interesting...

<img width="2420" alt="Screen Shot 2020-08-20 at 5 16 42 PM" src="https://user-images.githubusercontent.com/6508528/90826899-3e709d80-e309-11ea-89cd-f8f1122c5b66.png">

**Comment by tbarrettwilsdon** [comment]
Wanted to close the loop - I can't give you a good explanation as to the delay of "apply filters" versus the normal realtime inline filter updates, but after rewriting the backend to remove the need for the customBodyRender formatting the lag is essentially gone. Thanks for taking a look, @patorjk!
