### ISSUE TITLE
Add column ID property to be used to identify columns throughout

### ISSUE THREAD

**Issue by rooby** [gregnb/mui-datatables#149]
Currently the column name property is used throughout as the identifier for a column, for example in the onColumnSortChange callback.

It is often preferable though to have a separate column identifier to the human readable column name/label. For example, if you are implementing server side filtering or sorting, you would definitely be more interested in the column id than the human readable name.

You also want to be able to change the name without it affecting other code, which is easier if you have an ID that can remain the same when making tweaks to the name.

**Comment by gregnb** [comment]
If you want to take this up I would accept a PR that if providing an id it will use that for the callback. If not column id is provided it'll continue to use the name as it does today

**Comment by jkeruzec** [comment]
For information :

I have been using these techniques to map my rest controller data to columns.
I have added the id when necessary to a new field in option (kind of hybrid system between name and ID).

For example : 
```
// Prepare columns for grid
        this.columns = [
                       {
                            name: 'Device technologies',
                            computed: true,
                        {
                            name: 'Wafer size',
                            computed: true,
                            options: {
                                field: "waferSizeId",
...
```

**Comment by gregnb** [comment]
this is available by using the `label` property: 

```
    const columns = [
      {
        name: "name",
        label: "Name",
    ];
```
