### ISSUE TITLE
How to reset table page to first page when I reload the data ?

### ISSUE THREAD

**Issue by Sigmarus** [gregnb/mui-datatables#1493]
I added a 'refresh' button to the toolbar, which clears the table `data` and `count`, then re-fetches the `data` and `count`. The `rowsPerPage` option is fixed to 50.

## Expected Behavior
I'd like to be able to reset the pagination while resetting the table's data.

## Current Behavior
If I go from page 1 (rows 1-50 of 29000) to page 2 (rows 51-100 of 29000) and refresh the table with the button, the fetched data corresponds to the first page, but the footer still displays `51-100 of 29000`.

## Your Environment
| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.11.0   |
| MUI-datatables  |    3.3.1    |
| React        |    16.13.1     |
| browser      |    Firefox     |
| Typescript |    3.9.7    |

**Comment by wdh2100** [comment]
> I added a 'refresh' button to the toolbar

when click refresh button 

page | number |   | User provided page for pagination.
-- | -- | -- | --
```js
 page : 0
```

**Comment by Sigmarus** [comment]
I tried to set the `page` option whenever I change the page or I refresh the table (and go to page 0), but it didn't work. The description is not very precise, but I think it's actually the user-provided starting page after table loading.

**Comment by patorjk** [comment]
Starting in version [3.4.0](https://github.com/gregnb/mui-datatables/releases/tag/3.4.0), the page option was updated to allow it to control the page rather than simply act as a starting page (this was done to make it consistent with other parameters).

**Comment by Sigmarus** [comment]
Ah ! Yes, I updated my version and it works, thank you ! \(*v*)/
