### ISSUE TITLE
How exactly do you right align the contents of a column?

### ISSUE THREAD

**Issue by nickraphael** [gregnb/mui-datatables#1495]
I'm thinking it can't be too hard.  I've tried using setCellProps but I'm not having much luck.

**Comment by patorjk** [comment]
You're on the right track. I'd need to see what you were doing, but that's how you do it. Example: https://codesandbox.io/s/muidatatables-custom-toolbar-forked-ixq31?file=/index.js

**Comment by nickraphael** [comment]
That works.  I was incorrectly using float: right.   You solution works.  Thanks.
