### ISSUE TITLE
Document that you can configure the default sort direction for a column

### ISSUE THREAD

**Issue by rooby** [gregnb/mui-datatables#150]
By default the table loads with no specific sorting, based on the data array that is passed in however if you have already sorted that data that is being passed in then it is useful to be able to indicate that on the table with the sort direction indicator you get when you click sort a column.

You can actually do this however it is not documented.

You can do it by setting the sortDirection option on a column as 'asc' or 'desc'.

Note that this doesn't actually sort the data, it relies on you passing in already sorted data.

**Comment by gregnb** [comment]
Sounds good. If you would like to take this up I'll accept the PR

**Comment by gregnb** [comment]
The data is now sorted by provided sortDirection value

**Comment by sandeepjain24** [comment]
Data is sorted but the arrow (icon) is still not coming, is there any way to bring it on default
