### ISSUE TITLE
How to exclude specific columns from CSV download?

### ISSUE THREAD

**Issue by vitorlimadev** [gregnb/mui-datatables#1502]
I have a table where the first column is a '_id' column, and the last one is a custom column with JSX some icons.

I want to download the CSV without those columns, I'm trying to do it manually for some days now, but still without success. Is there a way to do it within the lib itself?

**Comment by patorjk** [comment]
Yes, see the "download" column option: https://github.com/gregnb/mui-datatables#column-options (set it to false for the column you want to exclude from the CSV download)

**Comment by vitorlimadev** [comment]
Oh, I didn't realize this! Thank you a lot, my friend! 😃

**Comment by vitorlimadev** [comment]
Closing, since the issue was my fault.
