### ISSUE TITLE
How to get rowData of all rows selected using onRowsSelect?

### ISSUE THREAD

**Issue by turbolego** [gregnb/mui-datatables#1508]
I understand that i can get the rowData of a row that is clicked using "onRowClick", but how can i get the rowData of all rows selected using onRowsSelect?

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.10.0     |
| MUI-datatables  |  2.13.5       |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by patorjk** [comment]
It should be the second parameter to the onRowsSelect callback (which is called onRowSelectionChange in v3 - though onRowsSelect still works in v3).

**Comment by ShqipognjaLL** [comment]
@patorjk doesn't that just give you the index in the data set of that row? How do you actually get the data from there?

**Comment by juanbomfim22** [comment]
@ShqipognjaLL store the table rows in an array state and then save all the `dataIndex` (not `rowIndex`) selected to use that to get the corresponding row in the n-th row of state.
