### ISSUE TITLE
Using createMuiTheme results in a much smaller, zoomed-out table.

### ISSUE THREAD

**Issue by kublyblu** [gregnb/mui-datatables#1509]
When using `createMuiTheme`, I'm seeing some unexpected zoom behavior where the table suddenly gets very small, even if the createMuiTheme is essentially empty:

Without any theme provided:
![image](https://user-images.githubusercontent.com/62248156/92417912-cdb3e880-f132-11ea-922e-2e130f8ae48e.png)

Seemingly any use of `createMuiTheme` results in this zooming issue, so I am showing with *nothing* custom in the theme as a simple case for debuging:
![image](https://user-images.githubusercontent.com/62248156/92417955-08b61c00-f133-11ea-90f7-edf64858bf39.png)

Example: 
```
import {MuiThemeProvider, createMuiTheme} from '@material-ui/core';
import MUIDataTable from "mui-datatables";

function getMuiTheme() {
  return createMuiTheme({});
};

class MyTable extends React.Component {
  ...

  render() {
    return (
      <MuiThemeProvider theme={getMuiTheme()}>
        <MUIDataTable
          title={"Testing"}
          columns={...}
          data={...}
        />
      </MuiThemeProvider>
    );
}
```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  4.11.0       |
| MUI-datatables  |   3.4.1      |
react | 16.13.1
| Chrome      |  84.0.4147.135       |

**Comment by kublyblu** [comment]
I figured it out, it had to do with some default values in CSS. This ultimately did the trick

```
createMuiTheme({
      spacing: factor => `${factor}rem`,
      typography: {
        htmlFontSize: 10,
      }
    });
```

**Comment by Sumiya-Sayeed** [comment]
Any idea how to do it in MUI v5?
