### ISSUE TITLE
On hover a table row - change backgroundColor style

### ISSUE THREAD

**Issue by ariel262626** [gregnb/mui-datatables#1517]
Hi, 
I want to change the color of the default on hover row background.
I'm trying to override the MUITheme of the on hover row with this code:

`const theme = createMuiTheme({
  overrides: {
    MuiTableRow: {
      hover: {
        backgroundColor: "rgba(0, 97, 250, 0.03)"
      }
    },
...`
But the result is that the background color changed to my custom color but on hover, nothing changed.
It's possible?

**Comment by ariel-upstream** [comment]
goo

**Comment by patorjk** [comment]
This is possible, you can target it with JSS:

https://codesandbox.io/s/muidatatables-custom-toolbar-forked-pd6xg?file=/index.js

Unfortunately I'm not sure how to target an element with 2 classes on it, thus I'm resorting to using "!important" to force the hover override (the rule with the CSS default hover color is ".MuiTableRow-root.MuiTableRow-hover:hover").

**Comment by ariel262626** [comment]
> This is possible, you can target it with JSS:
> 
> https://codesandbox.io/s/muidatatables-custom-toolbar-forked-pd6xg?file=/index.js
> 
> Unfortunately I'm not sure how to target an element with 2 classes on it, thus I'm resorting to using "!important" to force the hover override (the rule with the CSS default hover color is ".MuiTableRow-root.MuiTableRow-hover:hover").
> 
> ```
>   let getMuiTheme = () => createMuiTheme({
>     overrides: {
>       MuiTableRow: {
>         root: {
>           '&:hover': {
>             backgroundColor: 'yellow !important'
>           }
>         }
>       },
>     }
>   });
> ```

Any solution without the 'important' ?

**Comment by patorjk** [comment]
I've updated the example, the below code will work without "!important". I could have sworn I tried this previously and it didn't work, but I was probably just tired. 

```
    createMuiTheme({
      overrides: {
        MuiTableRow: {
          root: {
            "&.MuiTableRow-hover": {
              "&:hover": {
                backgroundColor: "yellow"
              }
            }
          }
        }
      }
    });
```

**Comment by ariel262626** [comment]
> I've updated the example, the below code will work without "!important". I could have sworn I tried this previously and it didn't work, but I was probably just tired.
> 
> ```
>     createMuiTheme({
>       overrides: {
>         MuiTableRow: {
>           root: {
>             "&.MuiTableRow-hover": {
>               "&:hover": {
>                 backgroundColor: "yellow"
>               }
>             }
>           }
>         }
>       }
>     });
> ```

Thank you!

I'm actually found another solution:
let getMuiTheme = () => createMuiTheme({
    overrides: {
      MuiTableRow: {
        root: {
          '&:hover': {
            backgroundColor: 'yellow' // without important
          }
        }
      },
    }
  });

then add to your table options: {{    rowHover: false, ... }}

**Comment by Eraguzy** [comment]
i know this is old and closed, but if you don't use `@material-ui/core`, here is an easier solution :
in your table options, use the `setRowProps` property

```
  const options = {
    setRowProps: () => {
      return {
        sx: {
          '&:hover': {
            backgroundColor: '#fff9c4'
          }
        }
      }
    }
  }
```
