### ISSUE TITLE
Store the sort state in the main state object instead of on the column

### ISSUE THREAD

**Issue by rooby** [gregnb/mui-datatables#152]
Almost all the table state (page, num results, filtering, searching) is stored in the main state object, however sort column and sortDirection are not.

I think it would be preferable to move sort configuration (index and direction) into the main object and add user provided sort options to the main table options object (like page, count and filterList).

Also, I opened another issue about potentially adding a column ID to columns. If that happens, it would be a better developer experience to specify the column ID instead of the index when specifying a sort column.

**Comment by gregnb** [comment]
So I looked into this and the sortDirection is available in the root columns state. The other item about the activeColumn is not so I moved that into root.

It's along side the server side PR I have that is a WIP 

#168

**Comment by rooby** [comment]
Thanks, I will review ASAP within the next couple of days.

**Comment by gregnb** [comment]
PR has been merged to finally provide remote data via the `serverSide` option.
