### ISSUE TITLE
Suggestion: Tooltips for TableCells

### ISSUE THREAD

**Issue by turbolego** [gregnb/mui-datatables#1521]
## Expected Behavior
When hovering over a cell in the table, a tooltip should be available.

## Current Behavior
No tooltips for cells are available.

## Your Environment

| Tech         | Version |
|--------------|---------|
| @material-ui/core  |    4.10.0     |
| MUI-datatables  |    3.4.0     |
| React        |   16.13.1      |
| browser      |    Edge  87.0.634.0     |

**Comment by patorjk** [comment]
I'm not sure this would really be needed. This is already possible by adding a tooltip via the customBodyRender/customBodyRenderLite methods.
