### ISSUE TITLE
Returning the table data while "onFilterChange" 

### ISSUE THREAD

**Issue by neverased** [gregnb/mui-datatables#1525]
Hi,

I'm just looking for a solution to be able to access the table data while triggering "onFilterChange". 

What I mean - accessing the table data the same way as triggering "onDownload" do.

## Expected Behavior

I would like to access the table data like this...

1. Data is being filtered
2. While clicking "Download" I'm able to access the filtered data JSON by running this code:
 `onDownload: (buildHead, buildBody, columns, data) => {
    console.log(data);
    return false
  },`
3. I can see the data I need on web-console:
[https://i.imgur.com/wiKNwem.png](url)

...but using "onFilterChange".

## Current Behavior

Only able to do it while using "onDownload" which is not enough for me.

What I would like to do is to pass the data to external function/module which generates charts based on that data after processing it. (Hope it's possible to do it like that). 

That's why I need it to be refreshed every time after applying filters.

Just looking for best solution / way of doing that.

I would be thankful for any hints.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  4.11.0   |
| MUI-datatables  |   3.4.1  |
| React        |    16.13.1   |
| browser      |   latest Chrome  |

**Comment by patorjk** [comment]
I'm not sure I understand, you should have access to most of what you want in the onFilterChange function:

```
function(changedColumn: string, filterList: array, type: enum('checkbox', 'dropdown', 'multiselect', 'textField', 'custom', 'chip', 'reset'), changedColumnIndex, displayData) => void
```

There's also the "onTableChange" callback, which will give you the tableState.

**Comment by neverased** [comment]
"onTableChange" was exactly what I needed. Thanks a lot!
