### ISSUE TITLE
Render Component or Text in Filter with customBodyRender

### ISSUE THREAD

**Issue by cbeltrangomez84** [gregnb/mui-datatables#1526]
Hi, I use custom components for my table for example in my data structure I have a "contracted" boolean field for every row, if the  field has "true" as value I render a check icon (customBodyRender), but I need to use filters over that column as well, So I need to specify something such as "customFilterRender" or "customFilterText" for that column to showthe string "contracted" if the value is true or "non contracted" if the value is false. (to be used in the filter window and in the filter chip)

This is an example of my table:

![image](https://user-images.githubusercontent.com/5134461/94106863-ec3c0400-fe01-11ea-8f17-466f0fda1b66.png)

An this is how the filter is shown:

![image](https://user-images.githubusercontent.com/5134461/94106906-04138800-fe02-11ea-8f8e-18b925b99e86.png)

Thanks a lot

**Comment by cbeltrangomez84** [comment]
Sorry, I just found "filterOptions" on the API.

**Comment by JSsantana** [comment]
How did you put the green icon inside table row?

**Comment by cbeltrangomez84** [comment]
Hi @JSsantana, I used the `customBodyRender` as specified in documentation:
[](https://github.com/gregnb/mui-datatables#column-options)

In my case the customBodyRender returns a div with an Icon inside, but it could be anything else such as a Material Icon or similar.

`
customBodyRender: (value, tableMeta, updateValue) => value?<div className="flex justify-start"><Icon icon={bxCheckCircle} style={{width: '30px', height: '30px',color:'#00b500'}}/></div>:value
`
