### ISSUE TITLE
Default sort using sortDirection isn't working

### ISSUE THREAD

**Issue by nickraphael** [gregnb/mui-datatables#1529]
Taking the column-sort example from the repo as an example.  Adding sortDirection: 'asc' does not sort the table as expected.  It does nothing.

```
const columns = [
      {
        name: "Name",
        options: {
          sort: true,
          sortDirection: 'desc',
        }
      },
      {
        name: "Title",
        options: {
          sort: false,
        }
      },
...
```

**Comment by patorjk** [comment]
That's deprecated, that particular example probably needs to be updated. See the sortOrder option.

**Comment by mromauricio** [comment]
Please, @patorjk where I can find information about sortOrder option?
Thank you in advance.

**Comment by mromauricio** [comment]
Hi, @nickraphael   
Did you succeed to sort?

**Comment by patorjk** [comment]
@mromauricio It's documented in the main documentation. You can also see an example here:

https://github.com/gregnb/mui-datatables/blob/master/examples/customize-columns/index.js

**Comment by nickraphael** [comment]
> Hi, @nickraphael
> Did you succeed to sort?

I sure did!  Just tested it.  Thanks!
