### ISSUE TITLE
Add an option to put the table into server side mode

### ISSUE THREAD

**Issue by rooby** [gregnb/mui-datatables#153]
There is mention in issues (such as #38) of there being support for server side controls like paging, however I don't think server side control has been fully considered.

Currently you can hook into interactions with table controls like the paging and sorting, however the default client side functionality still happens. This causes some very strange results when the table is still updating on the client side while you are fetching new data from the server.
I would say it's not currently production ready for server side control.

Ideally you would put the table into manual mode, where the table then expects you to change the data appropriately via the available events and doesn't do any filtering/sorting/paging/etc on the client side.

**Comment by rooby** [comment]
Off-topic:

I am currently evaluating mui-datatables for a project I'm working on.
In relation to this and some of the other issues I've recently opened, are these things that you would be willing to add to the project if we were to submit acceptable pull requests?

**Comment by gregnb** [comment]
@rooby So I started working on this feature. It's close to what you are proposing where the option is caleld 'serverSide' and then from there it would force a user to provide those functions. 

As for your other question, let me look through the issues you sent and assign you some of them

**Comment by rooby** [comment]
That sounds great, thanks.
To be honest, this is the only issue that is really a show stopper for us.
The rest are really more nice to have or discussion items at this stage.

**Comment by rooby** [comment]
Do you have any idea roughly when that feature would be ready?

**Comment by rooby** [comment]
Related issue: #70

**Comment by gregnb** [comment]
Hopefully sometime soon. I'll be posting up a branch this weekend

**Comment by gregnb** [comment]
PR has been merged to finally provide remote data via the `serverSide` option.
