### ISSUE TITLE
Question: Possible to disable toolbar buttons but still render them?

### ISSUE THREAD

**Issue by natac13** [gregnb/mui-datatables#1547]
Just not sure if this option is available with Mui-datatable?

I would like to be able to disable the icon buttons that make up the Toolbar without having to recreate the entire thing just to add a disabled attr.

I know that I can add a CustomToolbar which is 'appended' to the other one but not sure if I can choose to disable the pre defined buttons like search, download, filter, etc...

Thank you so much!

**Comment by patorjk** [comment]
There is no way to disable them. I'd accept a PR for this though. Perhaps the "search", "filter", etc options could optionally accept string values ("true", "false", "disabled").

In addition to the customToolbar option, you could also replace the Toolbar component with a custom one that had that option: https://github.com/gregnb/mui-datatables#custom-components

**Comment by natac13** [comment]
>Perhaps the "search", "filter", etc options could optionally accept string values ("true", "false", "disabled").
I was thinking the same thing based off how `display` is handled in `column options`.

>I'd accept a PR for this though.
I will look into that.

>In addition to the customToolbar option, you could also replace the Toolbar component with a custom one that had that option:
I am going to try this out as well. I just thought I would have to re-implement the logic this library gives for the `filter`, `search`, etc buttons
