### ISSUE TITLE
Outdated examples (option 'logic')

### ISSUE THREAD

**Issue by Sigmarus** [gregnb/mui-datatables#1548]
I'd like to use the column option `options` > `filterOption` > `logic` to manage my table row's display (if I understood correctly its purpose), but Typescript's typings shows me this isn't `logic: (location, filters, row)` anymore but `logic: (prop: string, filterValue: any[])`. And the custom-filters example is still using the old version.
Can I have an updated usage example, and an explanation of what is `logic` for ?

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.11.0     |
| MUI-datatables  |    3.5.0     |
| React        |    16.13.1     |

**Comment by Sigmarus** [comment]
Ok, I managed to find out how to use `logic`, but I think it's worth better explanation in the documentation.
I understood the following behavior : 
> Return *false* if no filter is set for the current column, or when the row has not to be masked when the filter corresponds to the current value.
> `props` : the value (for each row) of the cell at current column
> `filterValue` : the current column's filter value

**Comment by Sigmarus** [comment]
Can you tell me if I'm correct ? @patorjk @gabrielliwerant @wdh2100

**Comment by wdh2100** [comment]
I think it can cause confusion.
`isFiltered` value is changed through the corresponding logic.

https://github.com/gregnb/mui-datatables/blob/e75d2fe9a25d166a3472e7d3bb4670e3e539b493/src/MUIDataTable.js#L990-L1021

What does `isFiltered` mean to users?


* example

https://github.com/gregnb/mui-datatables/blob/e75d2fe9a25d166a3472e7d3bb4670e3e539b493/examples/customize-filter/index.js#L137-L145

**Comment by Sigmarus** [comment]
Ok, well, my misunderstanding was if "is filtered" meant "is blocked by the filter" or "is selected through the filter"...
So what I understand is that a row won't be displayed if `isFiltered` is set to true, so it means "is excluded by the filter".

https://github.com/gregnb/mui-datatables/blob/e75d2fe9a25d166a3472e7d3bb4670e3e539b493/src/MUIDataTable.js#L1053-L1054
