### ISSUE TITLE
Allow each column to specify its own sort function

### ISSUE THREAD

**Issue by rooby** [gregnb/mui-datatables#155]
Currently the column sorting is limited to a basic string sort, which doesn't necessarily work properly for all cases. For example, sorting a column of dates will almost never work, unless you are displaying a format like YYYY-MM-DD.

It would be great if you could optionally specify a sort function at the column level, which then gets passed into the sort call.

**Comment by ccurtin** [comment]
@rooby, I opened up a PR for custom sorting.
https://github.com/gregnb/mui-datatables/pull/176/files

**Comment by Flavyoo** [comment]
The customSort seems to override the sorting for all the columns. Is there a way to have the custom sort, but have other columns use a different sort function?

**Comment by gabrielliwerant** [comment]
@Flavyoo `customSort` passes an argument for column index (see documentation for more information). With the column index, you can conditionally set sorting logic per column.

**Comment by Flavyoo** [comment]
Okay thank you. That is pretty cool
