### ISSUE TITLE
import jspdf asynchronously

### ISSUE THREAD

**Issue by fcollonval** [gregnb/mui-datatables#1554]
## Expected Behavior

It will be nice to load jspdf asynchronously. When packaging a application using this (wonderful :wink: ) component with webpack, I realized that jspdf is as big as @material-ui/core itself. As I'm even not using the export PDF feature, I think it will be nice to asynchronously load jspdf to reduce the main bundle size.

![image](https://user-images.githubusercontent.com/8435071/96685898-0ecc2900-137e-11eb-85e1-0510608bb290.png)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.11.0     |
| MUI-datatables  |     1.69.1   |
| React        |    16.9.0     |
| webpack | 4.44.2 |

**Comment by wdh2100** [comment]
You mean dynamic import?

**Comment by wdh2100** [comment]
But it doesn't exist. (jspdf)

https://github.com/gregnb/mui-datatables/blob/master/package.json

**Comment by fcollonval** [comment]
Sorry @wdh2100 I got a couple of GitHub projects opened implementing material-ui tables and I reported on the wrong one. I apologize for the error.
