### ISSUE TITLE
Display empty table if no data is given

### ISSUE THREAD

**Issue by jmarucha** [gregnb/mui-datatables#156]
Behaviour on displaying empty dataset is weird.

## Expected Behavior

When I provide `data=[]` prop, a table with "Sorry, no matching records found" message is provided, similarly to manner when search or filtering shows nothing.

## Current Behavior

When I provide `data=[]` prop, no table is rendered.

| Tech         | Version |
|--------------|---------|
| Material-UI  | 1.4.1 |
| MUI-datatables  | 2.0.0-beta-19 |
| React        | 16.4.1 |

**Comment by jmarucha** [comment]
edit: it's the same on MUI-datatables 2.0.0-beta-

**Comment by gregnb** [comment]
I can't replicate this issue. See sandbox below:

https://codesandbox.io/s/n0xk6pz9o0

**Comment by gregnb** [comment]
This is intended behaviour. If a user provides empty data nothing will render.  I'm leaving this up to the user to decide how they want to handle situation where data is not available yet (say a loading state)

**Comment by brianpmaher** [comment]
>  I'm leaving this up to the user to decide how they want to handle situation where data is not available yet

Well, the user could also decide not to display the table.  Allowing the empty table to display gives the user more options for how to display when the data set is empty.
