### ISSUE TITLE
Docs - Drawer with codesandbox demo

### ISSUE THREAD

**Issue by benjaminbours** [gregnb/mui-datatables#157]
Hello @gregnb ,

I'm doing the drawer we talked about(#109).

I was wondering what is the best way to create Codesandboxes with everything listed in the exemples.

I found this link https://codesandbox.io/docs/importing#example-sandbox

It shows different ways to create sandboxes, I don't know how you want to do it. I'm ok to create them if you want but I think sandboxes are linked to an account, right ? So maybe you prefer do it.

I will push a first version with fake links in few minutes.

**Comment by gregnb** [comment]
Let's close this issue down and we'll keep the PR going and figure out a solution
