### ISSUE TITLE
Any option to submit filter on 'Enter key press'?

### ISSUE THREAD

**Issue by getsomex** [gregnb/mui-datatables#1572]
I am using confirmFilters=true. Right now, customFilterDialogFooter has a button which apply the filters with onClick event however i also want to apply the filters if the user press enter key

**Comment by bbourn** [comment]
Try this.
```
useEffect(() => {
    const ALLOWED_KEYS = ['Enter'] // ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight']
    const handleKeyDown = event => {
      const { key } = event
      if (ALLOWED_KEYS.includes(key)) {
        const applyButton = document.getElementById('<ID-OF-YOUR-BUTTON-HERE>')
        if (applyButton) applyButton.click()
      }
    }

    document.addEventListener('keydown', handleKeyDown)

    return () => {
      document.removeEventListener('keydown', handleKeyDown)
    }
  }, [])
```

**Comment by getsomex** [comment]
> Try this.
> 
> ```
> useEffect(() => {
>     const ALLOWED_KEYS = ['Enter'] // ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight']
>     const handleKeyDown = event => {
>       const { key } = event
>       if (ALLOWED_KEYS.includes(key)) {
>         const applyButton = document.getElementById('<ID-OF-YOUR-BUTTON-HERE>')
>         if (applyButton) applyButton.click()
>       }
>     }
> 
>     document.addEventListener('keydown', handleKeyDown)
> 
>     return () => {
>       document.removeEventListener('keydown', handleKeyDown)
>     }
>   }, [])
> ```

my guy!!! thank you!
