### ISSUE TITLE
Row height - same height to all rows

### ISSUE THREAD

**Issue by ariel-upstream** [gregnb/mui-datatables#1575]
Hi,
I would like to have the same height for all the row in the table,
Is it possible to change the height of the rows? 

I tried that in my useStyles section: 
```
"MuiTableRow": {
    "&.root": {
      height: "80px"
    },
  },
```
but it didn't work,
I don't want to override the theme globally, this change should be only in one specific component 

Thanks.

**Comment by wdh2100** [comment]
ref : #1578
