### ISSUE TITLE
Columns display to false throwing console errors

### ISSUE THREAD

**Issue by leonardolouie** [gregnb/mui-datatables#1576]
Warning: Failed prop type: Invalid prop `columns[0]` supplied to `a`.
    in a (created by WithStyles(a))
    in WithStyles(a) (created by Styled(WithStyles(a)))
    in Styled(WithStyles(a)) (created by DataTable)
    in div (created by DataTable)
    in DataTable (created by Report)

![image](https://user-images.githubusercontent.com/29114998/98509417-1fe0c980-229c-11eb-83f6-f48ec3e7c4de.png)

## Expected Behavior
When I'm trying to hide the first column the console must not throw any error.
## Current Behavior

imagine this is the column that I passing on the data table as a prop

```
 const columns = [
    {
      name: 'user_id',
      options: {
        display: false
      }
    },
    {
      name: 'first_name',
      label:'First Name'
    },
  ];

```
the data table checking the first column which is the column[0] and throwing consoles error that
Failed prop type: Invalid prop `columns[0]` supplied to `a`

## Steps to Reproduce (for bugs)

1. Import mui-datatable 
2.pass this columns  as a prop
```
 const columns = [
    {
      name: 'user_id',
      options: {
        display: false
      }
    },
    {
      name: 'first_name',
      label:'First Name'
    },
  ];

const data = [
    {
       user_id: '12321313',
       first_name:'sample name'
    }
]
```

## Your Environment

| Tech         | Version |
|--------------|---------|
 "@material-ui/core": "^4.10.0",
 "@material-ui/icons": "^4.9.1",
 "@material-ui/lab": "^4.0.0-alpha.56",
 "@material-ui/styles": "^4.10.0",
 "mui-datatables": "^3.7.1",

**Comment by dbyun-doinglab** [comment]
Also running into this issue!

**Comment by tbarrettwilsdon** [comment]
Seeing the same issue, but not setting display: false to anything - the only place I even declare `display` as a param in column options is within filterOptions. It seems to have been introduced in datatables, not mui-datatables because it only appeared after a version bump of the underlying packages.

**Comment by goldpot** [comment]
am seeing this issue too after upgrade to 3.7.1. Any ideas?

**Comment by wdh2100** [comment]
When I look, the **propTypes** declaration is wrong.

Name | Type | Default
-- | -- | --
display | `boolean` or `string` | true

https://github.com/gregnb/mui-datatables/blob/fde3497a552040505f70c274466715fce1d7e8ab/src/MUIDataTable.js#L125

```js
 display: PropTypes.oneOf(['true', 'false', 'excluded', 'always', true, false]),
```

if you use a `string`, you can avoid `waring`.

There is no problem performing the operation, but I think it must be fixed.

I'll fix it soon.

**Comment by tbarrettwilsdon** [comment]
@wdh2100 - you nailed it, good catch! The only thing I'd add is that those are not the only proptypes - `display` should also accept an Object when used as a param for filterOptions - see example here: https://github.com/gregnb/mui-datatables/blob/master/examples/customize-filter/index.js#L66

That's my use case, so the PR open wouldn't actually resolve it for me. Thanks!

**Comment by leonardolouie** [comment]
> @leonardolouie
> 
> thank you for reporting.
> 
> When I look, the **propTypes** declaration is wrong.
> 
> Name	Type	Default
> display	`boolean` or `string`	true
> * AS-IS
>   https://github.com/gregnb/mui-datatables/blob/fde3497a552040505f70c274466715fce1d7e8ab/src/MUIDataTable.js#L125
> * TO-BE
> 
> ```js
>  display: PropTypes.oneOf(['true', 'false', 'excluded', 'always', true, false]),
> ```
> 
> if you use a `string`, you can avoid `waring`.
> 
> There is no problem performing the operation, but I think it must be fixed.
> 
> I'll fix it soon.

Sorry for the late response, btw thanks cheers!

**Comment by leonardolouie** [comment]
options: {
        display: 'false'
   }

If the pr still didn't merged just do this folks and the console error will be rid off. 


My console looks nice now!
![image](https://user-images.githubusercontent.com/29114998/99294092-8b1f3280-287e-11eb-924f-7dc07940144f.png)


Thanks, @wdh2100
