### ISSUE TITLE
Cell custom style - limit the number of rows globally

### ISSUE THREAD

**Issue by ariel-upstream** [gregnb/mui-datatables#1578]
Hi,
I'm trying to limit the number of rows of each cell data in the body to 1 row.
I know how to do it for a specific column but I want to do it in the theme for all the table in my project.

I added to theme file the rule:
```
 MUIDataTableBodyCell: {
    simpleCell: {
      display: "-webkit-box",
      overflow: "hidden",
      maxWidth: "26vw",
      "-webkit-box-orient": "vertical",
      "-webkit-line-clamp": 1,
    }
  },
```
 
but when I change the display prop to "-webkit-box" the table shrinks 

Any suggestion?

**Comment by wdh2100** [comment]
ref : https://material-ui.com/customization/theming/

**Comment by ariel-upstream** [comment]
> Style is dependent on material-ui (cell, table, pagination, footer... etc).
> 
> Please refer to the address below.
> 
> ref
> 
> * https://material-ui.com/customization/theming/
> * https://material-ui.com/customization/globals/
> * #1343

I tried that but the MUIDataTableBodyCell style class belongs to mui-datatables

**Comment by ariel-upstream** [comment]
Found a solution: 

For example: In case all cells in the table wrapped with p tag:
```
 MUIDataTableBodyCell: {
    simpleCell: {
      "& $p": {
        display: "-webkit-box",
        overflow: "hidden",
        maxWidth: "20vw",
        "-webkit-box-orient": "vertical",
        "-webkit-line-clamp": 1,
      },
    },
  },
```
