### ISSUE TITLE
Applying object type values ​​to dropdown filters

### ISSUE THREAD

**Issue by developergunny** [gregnb/mui-datatables#1579]
![image](https://user-images.githubusercontent.com/67149898/98813453-7fd79b80-2467-11eb-8599-ce6e633fc965.png)
![image](https://user-images.githubusercontent.com/67149898/98813532-a72e6880-2467-11eb-8106-460432b56e2c.png)

## Expected Behavior
{"pipeline":{"$skip":0,"$limit":10,"$match":{"$and":[{"paid_method":{"$regex":"^.*⏲가상계좌.*$"}}]}}}

When a filter is selected and confirmed, the filter list is fetched and parameters are sent to the server. However, the item “⏲가상계좌” is stored as “a” in the actual database. Can I work this way?

### Code to dynamically generate columns
`setHeaderColumns (
        metaData.viewListMeta.items.map(($meta, index) => {
          
          let obj = {
            name: $meta.id, // field name in the row object
            label: $meta.name, // column title that will be shown in table
            options: {
              filter: searchList.includes($meta.id),
              filterType: searchType($meta.lego?.name ? $meta.lego?.name : 'text')
            }
          }

          if(searchType($meta.lego?.name ? $meta.lego?.name : 'text') == "dropdown"){
            let codeItem = [];
            let nameItem = [];

            if($meta.hasOwnProperty('dataCode') && $meta.hasOwnProperty('dataCodes')){
              $meta.dataCodes.map((dataCode, index) => {
                //codeItem.push(`${dataCode._name} : <div>${dataCode._code}</div>`);
                codeItem.push(dataCode._code);
                nameItem.push(dataCode._name);
              })
            }
            obj.options.customFilterListOptions = { render: v => `${$meta.name} : ${v}` };
            obj.options.filterOptions = { 
              names: nameItem
             };
            //
          }

          return obj;
        })
      )`

### click the confirm button
`
onFilterConfirm: (filterList) => { 
    handleMatchParamMapping(filterList); 
}

  const handleMatchParamMapping = (filterList) => {
    filterColumn = [];
              
    for(let i in filterList) {
      if(filterList[i].length > 0) {
        let mappingObject = {};
        
        mappingObject[headerColumns[i].name] = filterList[i].toString();
        filterColumn.push(mappingObject);
      }
    }
  };

`

**Comment by wdh2100** [comment]
You want to replace filter value?


Name | Type | Default | Description
-- | -- | -- | --
filterOptions | object |   | renderValue: A function to customize filter choices Example. Example use case: changing empty strings to "(empty)" in a dropdown.


example : https://github.com/gregnb/mui-datatables/blob/master/examples/customize-filter/index.js

**Comment by developergunny** [comment]
> 필터 값을 바꾸시겠습니까?
> 
> 처럼 보이지만 `⏲가상계좌`실제 데이터는`some`
> 
> 이름	유형	기본	기술
> filterOptions	목적	 	renderValue : 필터 선택을 사용자 정의하는 함수 예제. 사용 사례 예시 : 드롭 다운에서 빈 문자열을 "(비어 있음)"으로 변경.
> 예 : https://github.com/gregnb/mui-datatables/blob/master/examples/customize-filter/index.js


Maybe I can assign an object value to the filter list?

const items = [
   { "a": "⏲가상 계좌"},
   { "b": "some1"},
   { "c": "som2"}
]

filterOptions = {
   names : Object.value(itmes),
   renderValue: v => v ? Object.keys(v) : ''
}

**Comment by wdh2100** [comment]
@developergunny 

```js
const items = [
{ "a": "⏲가상 계좌"},
{ "b": "some1"},
{ "c": "som2"}
]

filterOptions = {
   names : items.map(innerItem => Object.keys(innerItem).toString()),
   renderValue: key => items.filter(item => Object.keys(item).includes(key ))[0].key 
}
```

Not the perfect answer. However, it seems to work under the given conditions.

**Comment by developergunny** [comment]
> @developergunny
> 
> ```js
> const items = [
> { "a": "⏲가상 계좌"},
> { "b": "some1"},
> { "c": "som2"}
> ]
> 
> filterOptions = {
>    names : items.flatMap(item=> Object.keys(item)),
>    renderValue: key => items.flatMap(item=> Object.values(item))[items.flatMap(item=> Object.keys(item)).indexOf(key)]
> }
> ```
> 
> Not the perfect answer. However, it seems to work under the given conditions.
> I think it would be better to map the items
> 
> like this
> 
> ```js
> const items = [
>    { key : "a", value : "⏲가상 계좌"},
>    { key : "b", value : "some1"},
>    { key : "c", value : "som2"}
> ]
> 
> const hashMap =  Object.fromEntries(
>    items.map(item => [item.key, item.value])
> )
> 
> ... 
> 
> 
> filterOptions = {
>    names : Object.keys(hashMap),
>    renderValue: key => hashMap.key
> }
> ```

Thank you for your kindness.
I solved the problem.
감사합니다.
