### ISSUE TITLE
How to style filter tags area?  

### ISSUE THREAD

**Issue by IbrahimSam96** [gregnb/mui-datatables#1590]
I have the basic table filter however, after I select a filter the tag gets added to the table and leaves a white space across the table horizontally. Is there a way to style it? Need to change backgroundColor :)

**Comment by IbrahimSam96** [comment]
<img width="1064" alt="TableFilterIssue" src="https://user-images.githubusercontent.com/72482204/100583097-43ee6400-32b8-11eb-998a-cc955ff40652.PNG">

**Comment by wdh2100** [comment]
https://github.com/gregnb/mui-datatables/blob/fde3497a552040505f70c274466715fce1d7e8ab/src/components/TableFilterList.js#L6-L20


Fix `MUIDataTableFilterList.root` style.

style sample : https://github.com/gregnb/mui-datatables/blob/master/examples/customize-styling/index.js
