### ISSUE TITLE
Sort Icon Color 

### ISSUE THREAD

**Issue by IbrahimSam96** [gregnb/mui-datatables#1593]
Hey guys how can I change the default black color of the sort icon and text whenever I click on a column to sort it. Thank You :)

**Comment by IbrahimSam96** [comment]
<img width="85" alt="Sort Color" src="https://user-images.githubusercontent.com/72482204/101076693-c48bb980-3571-11eb-8047-cd4109ed6e3e.PNG">

**Comment by wdh2100** [comment]
ref : https://github.com/gregnb/mui-datatables/blob/master/examples/customize-styling/index.js

**Comment by IbrahimSam96** [comment]
Sorry I'm still not sure which style reflects change in the sort header/icon color

**Comment by IbrahimSam96** [comment]
I was able to override the sort icon color but not the text using this 

  ```
MUIDataTableHeadCell: {
                    sortAction: {
                      '& path': {
                        color: "white" // or whatever you need
                      }, 
                      }, 
                  }, 
```
If anyone knows how to change the text color too, please share it here. Thanks:)

**Comment by IbrahimSam96** [comment]
This is to change the text color :)
```
sortActive: {
      color: ""  // whatever you need
    }
```
