### ISSUE TITLE
Give option to disable delete button on selected row

### ISSUE THREAD

**Issue by jkeruzec** [gregnb/mui-datatables#160]
Could you give an option to disable, make disapear the delete button when a row is selected ?

Thanks ! 👍

**Comment by gregnb** [comment]
You could override that component and then have whatever you want:

https://github.com/gregnb/mui-datatables/blob/master/examples/customize-toolbarselect/index.js

**Comment by jkeruzec** [comment]
Yes Thank you, it works for me !
Just created a custom select toolbar with empty render in it to have no buttons at all!

**Comment by opandey007** [comment]
> m

can u give one option there to hide only delete option and i want to edit only selected rows in table using props based data
