### ISSUE TITLE
(Server Side Rendering) broken table layout on page refresh

### ISSUE THREAD

**Issue by hafizhrf** [gregnb/mui-datatables#1600]
So I make a simple datatable in nextjs with server side rendering, when I refresh the page the datatable got some bug like this
![image](https://user-images.githubusercontent.com/52806525/101633880-7c313780-3a5a-11eb-8b2f-82168c473b6a.png)
sometime it goes blank 

## My Code
```tsx
import React from 'react'
import Head from 'next/head'
import Paper from '../../../components/Dashboard/General/Paper'
import MUIDataTable, { MUIDataTableOptions } from 'mui-datatables'

import Layout from '../../../layout/Dashboard'
import { Button } from '@material-ui/core'

const Index = (): React.ReactElement => {
  const columns = ['Name', 'Company', 'City', 'State']

  const data = [
    ['Joe James', 'Test Corp', 'Yonkers', 'NY'],
    ['John Walsh', 'Test Corp', 'Hartford', 'CT'],
    ['Bob Herm', 'Test Corp', 'Tampa', 'FL'],
    ['James Houston', 'Test Corp', 'Dallas', 'TX']
  ]

  const options: MUIDataTableOptions = {
    filterType: 'checkbox',
    elevation: 0
  }
  return (
    <Layout title='User'>
      <Head>
        <title>User</title>
      </Head>
      <Paper title="Data List" tools={
        <Button style={{ textTransform: 'none' }} variant="outlined" color="primary">Add Data</Button>
      }>
        <MUIDataTable
          title={'User List'}
          data={data}
          columns={columns}
          options={options}
        />
      </Paper>
    </Layout>
  )
}

export default Index
```

## Expected Behavior
normal datatable
![image](https://user-images.githubusercontent.com/52806525/101635344-6c1a5780-3a5c-11eb-9044-fc7f052ab90c.png)

## Current Behavior
datatable header got duplicated like this
![image](https://user-images.githubusercontent.com/52806525/101633880-7c313780-3a5a-11eb-8b2f-82168c473b6a.png)

## Steps to Reproduce (for bugs)
1. create a simple datatable with local data in ssr (im using nextjs typescript) 
2. force refresh browser

## Your Environment
| Tech         | Version |
|--------------|---------|
| Material-UI  |    7.11.6     |
| MUI-datatables  |    3.7.1     |
| React        |    16.14.0     |
| browser      |    Opera, Chrome     |
| next          |    9.5.5     |

**Comment by wdh2100** [comment]
https://github.com/gregnb/mui-datatables/tree/master/examples

The current example is running with next.js(^9.4.4).

But I think it's a bit difficult to reproduce the bug...

**Comment by hafizhrf** [comment]
closed

you've to set server initial render for material ui styling in `_document.js`
here's the documentation https://material-ui.com/guides/server-rendering/

example if you use styled component in `_document.js`
```
import React from 'react'
import NextDocument from 'next/document'
import { ServerStyleSheet as StyledComponentSheets } from 'styled-components'
import { ServerStyleSheets as MaterialUiServerStyleSheets } from '@material-ui/core/styles'
export default class Document extends NextDocument {
  static async getInitialProps (ctx) {
    const styledComponentSheet = new StyledComponentSheets()
    const materialUiSheets = new MaterialUiServerStyleSheets()
    const originalRenderPage = ctx.renderPage
    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: App => props =>
            styledComponentSheet.collectStyles(
              materialUiSheets.collect(<App {...props} />),
            ),
        })
      const initialProps = await NextDocument.getInitialProps(ctx)
      return {
        ...initialProps,
        styles: [
          <React.Fragment key="styles">
            {initialProps.styles}
            {materialUiSheets.getStyleElement()}
            {styledComponentSheet.getStyleElement()}
          </React.Fragment>,
        ],
      }
    } finally {
      styledComponentSheet.seal()
    }
  }
}
```

**Comment by snoop088** [comment]
Hi guys, this is a problem with using _app.tsx.
The styles are still broken the very same way as posted above. This happens on hard refresh of the page. Does not happen when you navigate to it..
This is a standard next.js app setup in a NX monorepo.
 I have tried using the _app.js supplied in the documentation above.
`import React from 'react';
import { AppProps } from 'next/app';
import Head from 'next/head';
import './styles.scss';
import { LayoutWrapper } from '@se6/shared/layout';

import { ThemeProvider } from '@material-ui/styles';
import CssBaseline from '@material-ui/core/CssBaseline';
import { theme } from '@se6/shared/helpers';

function CustomApp({ Component, pageProps }: AppProps) {
  React.useEffect(() => {
    // Remove the server-side injected CSS.
    const jssStyles = document.querySelector('#jss-server-side');
    if (jssStyles) {
      jssStyles.parentElement.removeChild(jssStyles);
    }
  }, []);
  return (
    <ThemeProvider theme={theme()}>
      <Head>
        <title>Welcome to main-app!</title>
      </Head>
      <main>
        <CssBaseline />
        <LayoutWrapper {...pageProps}>
          <Component />
        </LayoutWrapper>
      </main>
    </ThemeProvider>
  );
}

export default CustomApp;`
Should I be using _document.js instead?  I don't understand why the styles are only broken when I refresh the page. There is an error message in the console:
Warning: Prop `className` did not match. Server: "MuiTypography-root MUIDataTableToolbar-titleText-108 MuiTypography-h6" Client: "MuiTypography-root MUIDataTableToolbar-titleText-20 MuiTypography-h6"
![Screenshot 2021-04-10 at 11 24 11](https://user-images.githubusercontent.com/5306184/114263612-4ba0e080-99ef-11eb-9de1-d8241c65caf2.png)
Where am I missing the point :)

thanks!
