### ISSUE TITLE
Tooltips in Header are available only till the first click on any column's title (even in examples on CodeSandBox)

### ISSUE THREAD

**Issue by weltix** [gregnb/mui-datatables#1606]
## Expected Behavior
   Expected, that tooltips in header titles works everytime, even after sort operation calling.

## Current Behavior
   Now, after click on header's title (for column sorting), tooltips disappear.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  | 4.11.2       |
| MUI-datatables  |  3.7.3       |
| React        |  16.13.1       |
| browser      |  Opera 73.0.3856.257       |
| etc          |         |

**Comment by wdh2100** [comment]
@weltix 

thanks report!

**Comment by alexprey** [comment]
Thanks @leandroercoli! Great fix! I'm just check it on my code and that fix also fix issue with double click to sort with custom tooltips (React-tippy)
@wdh2100 When you can merge and release it with new package?

**Comment by wdh2100** [comment]
Fixed 3.7.4
