### ISSUE TITLE
Pagination is not working

### ISSUE THREAD

**Issue by SheikSena** [gregnb/mui-datatables#1621]
## Expected Behavior

When I click on next page data table has to fetch next page data but it is not happening and also the screen is getting frozen.
![image](https://user-images.githubusercontent.com/40268724/103229385-e1d95b00-4958-11eb-8fab-a9088db0a1ff.png)

## Current Behavior

Next page link not working.
![image](https://user-images.githubusercontent.com/40268724/103229518-2cf36e00-4959-11eb-8141-47883dd162e5.png)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI Core  |      4.11.2   |
| MUI-Datatables  |    3.7.3     |
| React        |  17.0.1       |
| browser      |      Chrome   |

Console Error Screenshots
![image](https://user-images.githubusercontent.com/40268724/103229747-b440e180-4959-11eb-92a0-f9d9d581338a.png)
![image](https://user-images.githubusercontent.com/40268724/103229775-c6bb1b00-4959-11eb-8547-b72ab00119b8.png)
![image](https://user-images.githubusercontent.com/40268724/103229801-d5093700-4959-11eb-9ad6-c27b6f91df52.png)

**Comment by wdh2100** [comment]
If you provide a codeSandBox, i will check it.
ref : https://codesandbox.io/s/muidatatables-custom-toolbar-forked-h3p7p?file=/index.js

**Comment by xulioc** [comment]
Same sanbox with this configuration not working:
@emotion/react 11.4.0
@emotion/styled 11.3.0
@material-ui/core 5.0.0-alpha.34
@material-ui/icons 5.0.0-alpha.34
mui-datatables 3.7.7
react 17.0.2
react-dom 17.0.2

Same sandbox just downgrading
@material-ui/core 5.0.0-alpha.10
its working.

Hope it helps!
