### ISSUE TITLE
Slow Performance on search when serverSide is true

### ISSUE THREAD

**Issue by Moussawi7** [gregnb/mui-datatables#1624]
The datatable is working properly with server side data, but i am facing a performance issue when i am trying to search for an item, where a single key is taking up to 500ms for a number of rows equal to 10.

## Expected Behavior
fast performance

## Current Behavior
very slow performance

## Steps to Reproduce (for bugs)
```
    const options = {
      selectableRows: false,
      count: totalCount,
      serverSide: true,
      page,
      rowsPerPage,
      filter: false,
      searchText,
      onSearchChange: (data) => {
        this.setState({searchText: data || ''}, ()=>{
            this.load();
        });
      },
      onSearchClose: () => {
        this.setState({searchText: ''});
      }
    };
```

1. try to search with serverSide: true

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    ^3.9.2     |
| MUI-datatables  |    ^2.0.0-beta.58     |
| React        |    ^16.5.2     |
| browser      |    chrome :Version 88.0.4324.50 (Official Build) beta (x86_64)     |

**Comment by wdh2100** [comment]
Tech | Version
-- | --
MUI-datatables | ^2.0.0-beta.58


Would you like to upload the version?

ref : https://github.com/gregnb/mui-datatables#plug-ins

**Comment by Moussawi7** [comment]
Thank you @wdh2100 for your reply,
sorry, i didn't get well what should i upload?
do you mean upload **MUI-datatables** from node_modules ?
Thank you

**Comment by wdh2100** [comment]
@Moussawi7 

sorry, Update version 3.x.x And use `debounceSearchRender`

**Comment by Moussawi7** [comment]
Thank you @wdh2100 , everything is working fine.
