### ISSUE TITLE
How to make a customSort by a condistion

### ISSUE THREAD

**Issue by Jakub41** [gregnb/mui-datatables#1625]
Hello,
I would like to make a `customSort`after a specific condition is met.
I have a column which is render when I have a state `usingLocation === true`.
When I render this column I need to have a sort by the results of a `nearestSites` calculation:

```
const nearestSites = calculateNearestSites(
    usingLocation,
    sites,
    DISTANCE_MEASURE,
  );
```
This already results sites in the required order.

By default I have like this:

```
sortOrder: {
        name: 'Id',
        direction: 'asc',
      },
```

The init state I need to keep is that the order by Id and ASC always until the `userLocation` is true.

What I have added under my columns:

```
{
        name: intl.formatMessage({
          id: 'SitesColumn.distance',
          defaultMessage: 'Distance',
        }),
        options: {
          display: !!usingLocation,
          filter: false,
          customBodyRender: value => {
            return !value ? 'N/A' : `${value} ${DISTANCE_MEASURE}`;
          },
        },
      },
```
As you see I have `display: !!usingLocation` so based on that I'm showing the column.

Now my issue is that, how can I make a `customSort` which based if that column is displayed or not makes the sort as per nearestSites result?

So what should happen is that when I have the `displayed: true` I need to see the table sorted by `nearestSites` else I should see sorted as per init state by `Id`

I hope this was clear enough to understand my issue. 

My code to reference:
https://pastebin.com/qRPvPLNB

Thank you

## Expected Behavior
When `usingLocation === true` I should see the sites sorted by `nearestSites`

## Current Behavior
The sites are not sorted as expected. 
As a temp fix I just put this
```
sortOrder: {
      name: intl.formatMessage({
          id: 'SitesColumn.distance',
         defaultMessage: 'Distance',
         }),
         direction: 'asc',
       },
```

**Comment by wdh2100** [comment]
If what I understand is correct, is it correct that you want to specify the sorting function according to conditions?

Name | Type | Default | Description
-- | -- | -- | --
sortCompare | function |   | Custom sort function for the column. Takes in an order string and returns a function that compares the two column values. If this method and options.customSort are both defined, this method will take precedence. (order) => ({data: val1}, {data: val2}) => number Example


ref : https://github.com/gregnb/mui-datatables/blob/master/examples/customize-columns/index.js

**Comment by Jakub41** [comment]
Thank you,
My goal is to have an initial sort condition based on Id.
However, when a user select a location and usingLocation is true then the sort need to change based on that and use the sort of Distance. 
I have some difficulties with that even looking on this example you shared. 
There is a way to see another example about it? 
Thanks
@wdh2100

**Comment by Jakub41** [comment]
@wdh2100 
This come from the example 
```
{
        name: "Salary",
        options: {
          filter: true,
          sort: true,
          sortThirdClickReset: true,
          sortDescFirst: true,
          sortCompare: (order) => {
            return (obj1, obj2) => {
              var val1 = parseInt(obj1.data.substr(1).replace(/,/g,''), 10);
              var val2 = parseInt(obj2.data.substr(1).replace(/,/g,''), 10);
              return (val1 - val2) * (order === 'asc' ? 1 : -1);
            };
          }
        }
      }      
      
```

In my situation can I make in this way?

```
{
        name: "Distance",
        options: {
          filter: false,
          sort: true,
          sortThirdClickReset: true,
          sortDescFirst: true,
          display: !!usingLocation,
          sortCompare: (order) => {
            return (nearestSites) => {
              return (nearestSites)
            };
          }
        }
      }      
```

I have to show the nerestSites as are already in order or in ASC order.
Also the sort will be reset to initial one soon as I close the dialog?

I just need a help to get this work correctly

Thanks

**Comment by Jakub41** [comment]
Whatever I do the order remain by Id and I have no clue how to do it :( 

```
{
        name: intl.formatMessage({
          id: 'SitesColumn.distance',
          defaultMessage: 'Distance',
        }),
        options: {
          display: !!usingLocation,
          filter: false,
          sort: true,
          sortThirdClickReset: true,
          sortDescFirst: true,
          customBodyRender: value => {
            return !value ? 'N/A' : `${value} ${DISTANCE_MEASURE}`;
          },
          sortCompare: order => {
            return () => {
              return order === nearestSites ? 1 : -1;
            };
          },
        },
      },
```

**Comment by wdh2100** [comment]
@Jakub41 

MSDN Sort `compareFunction `

ref : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by Jakub41** [comment]
@wdh2100 Maybe can you help me with a simple example in codeSandbox based on the example you already showed me before.

My Data of nearestSites look like this
<img width="316" alt="Screenshot 2021-01-03 at 14 35 38" src="https://user-images.githubusercontent.com/8559542/103479909-26d61500-4dd1-11eb-8903-9a61ce73cf5a.png">

So when I have this column displayed I should see my table sorted as per distance and as you see our result is already sorted in this way. 

I do not understand how to use the sortCompare

I tried this way but is not correct for sure

```
sortCompare: order => {
            nearestSites.sort((a, b) => {
              const distA = a.distance;
              const distB = b.distance;
              if (distA < distB) {
                return -1;
              }
              if (distA > distB) {
                return 1;
              }
              // must be equal
              return 0;
            });
            return order === 'asc' ? 1 : -1;
          },
```

Bu order is not changing the order is kept by the column Id.

**Comment by Jakub41** [comment]
I found a different approach I just did in this way

```
usingLocation
    ? {
        name: intl.formatMessage({
          id: 'SitesColumn.distance',
          defaultMessage: 'Distance',
        }),
        direction: 'asc',
      }
    : {
        name: 'Id',
        direction: 'asc',
      };
```

I'm just changing the OBJ based if I use or not usingLocation
