### ISSUE TITLE
sorting by checked rows

### ISSUE THREAD

**Issue by noylevy12** [gregnb/mui-datatables#1627]
Hi there!
Q1: Is there any way to sort data table every time the row's checkbox is checked or rowsSelected props change? 
That is, display the selected rows first?

Q2:  Is there any way to disable some rows checkboxes? (by list of rows indexes).

Thank you very much !!!

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.11     |
| MUI-datatables  |    3.7.1     |
| React        |     16.13.1    |

**Comment by wdh2100** [comment]
@noylevy12 

A1. using sortOrder 

ref : https://github.com/gregnb/mui-datatables/issues/1437

A2. using isRowSelectable 
Name | Type | Default | Description
-- | -- | -- | --
isRowSelectable | function |   | Enable/disable selection on certain rows with custom function. Returns true if not provided. function(dataIndex: number, selectedRows: object(lookup: {dataindex: boolean}, data: arrayOfObjects: {index, dataIndex})) => boolean.

**Comment by noylevy12** [comment]
> Sets the column to sort by and its sort direction. To remove/reset sorting, input in an empty object. The object options are the column name and the direction: name: string, direction: enum('asc', 'desc') Example
@wdh2100 
First of all, thanks for the quick reply
Regarding Answer 1: I saw it, can you tell me what I should put in the column name? That is, what is the "column name" of the "checkboxes column"?
Regarding Answer 2: I saw it too - and did not quite understand, I need to return Boolean variable- if I return a false then all the checkboxes become disabled and not just selected as I intended :(

**Comment by noylevy12** [comment]
> @noylevy12
> 
> A1. using sortOrder
> 
> Name	Type	Default	Description
> sortOrder	object	{}	Sets the column to sort by and its sort direction. To remove/reset sorting, input in an empty object. The object options are the column name and the direction: name: string, direction: enum('asc', 'desc') Example
> ref : #1437
> 
> A2. using isRowSelectable
> 
> Name	Type	Default	Description
> isRowSelectable	function	 	Enable/disable selection on certain rows with custom function. Returns true if not provided. function(dataIndex: number, selectedRows: object(lookup: {dataindex: boolean}, data: arrayOfObjects: {index, dataIndex})) => boolean.

@wdh2100 
First of all, thanks for the quick reply
Regarding Answer 1: I saw it, can you tell me what I should put in the column name? That is, what is the "column name" of the "checkboxes column"?
Regarding Answer 2: I saw it too - and did not quite understand, I need to return Boolean variable- if I return a false then all the checkboxes become disabled and not just selected as I intended :(

**Comment by noylevy12** [comment]
@wdh2100 thank you !
