### ISSUE TITLE
Sortable headers have tabindex=0 on both span containing header/button and button, causing you to have to tab twice through the headers

### ISSUE THREAD

**Issue by pkmnct** [gregnb/mui-datatables#1629]
## Expected Behavior
You should only have to tab through each header once to be able to get to a different header to sort. Additionally, the headers should have a focus style so that it is clear which is focused when using keyboard navigation.

## Current Behavior
You have to hit tab on each header twice, since both the MUIDataTableHeadCell-toolButton and the MUIDataTableHeadCell-sortLabelRoot have `tabindex="0"`. When tabbing, it is unclear which header you are tabbed to (except that you can see the tooltip).

## Steps to Reproduce (for bugs)

https://codesandbox.io/s/muidatatables-custom-toolbar-rvmcj?file=/index.js

1. Ensure the example is displaying the non-responsive view
2. Click into the example area
3. Press Tab until you see the _Sort_ tooltip. Press enter to sort by the first column.
4. Press Tab once more. Notice there is no tooltip. Press enter to sort by the second column.
5. Press Tab once more. Notice the _Sort_ tooltip. Press enter and notice that you again sort by the second column.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  | 4.10.2 |
| MUI-datatables  | 3.4.1 |
| React        | 16.9.0 |
| browser      | Chrome 87.0.4280.88 |

**Comment by wdh2100** [comment]
@pkmnct 

good idea!
