### ISSUE TITLE
Columns resize when resizing window height

### ISSUE THREAD

**Issue by brianpmaher** [gregnb/mui-datatables#164]
Columns resize unexpectedly when resizing the window height only.  Refreshing the browser reverts the columns to their original state.

![mdt-column-resize-bug](https://user-images.githubusercontent.com/5590010/44621534-e101fd00-a864-11e8-8c11-071daadc4921.gif)

## Expected Behavior

The columns should not resize at all when resizing the window height only.

## Current Behavior

The columns resize and don't revert when resizing the window height to its original height.

## Steps to Reproduce (for bugs)

1. Run `npm run dev` in mui-datatables repo
2. Navigate to `localhost:5050`
3. Resize only the height of your browser window
4. Note the resizing data tables columns

## Your Environment

| Tech         | Version |
|--------------|---------|
| MUI-datatables  | 2.0.0-beta-22 |
| OS | Ubuntu 18.04.1 LTS |
| browser      | Mozilla Firefox 61.0.1 |

**Comment by gregnb** [comment]
Hah, thanks for finding this. This is mainly way this feature is disabled by default it was really kind of tricky to pull off. I still don't think it works perfectly but it is better than nothing.  I'm going to submit a patch for this within a few minutes
