### ISSUE TITLE
Style Pagination

### ISSUE THREAD

**Issue by L-U-C-K-Y** [gregnb/mui-datatables#1641]
Hi all

Thanks for this library!

I would like to style the pagination component, but the font that I apply does not show up.

## Expected Behavior

I expect to be able to style the pagination (font).

## Current Behavior

The applied font to the theme does not apply.

## Steps to Reproduce (for bugs)

I have added the following code:

I have added the following code in the theme that is applied without success:

```typescript
      MUIDataTablePagination: {
        caption: {
          fontFamily: ['ManropeMedium', 'sans-serif'].join(','),
        },
      },
      MUIDataTableJumpToPage: {
        caption: {
          fontFamily: ['ManropeMedium', 'sans-serif'].join(','),
        },
      },
```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |4.11.3|
| MUI-datatables  |2.15.0|
| React        |16.14.0|
| browser      |Google Chrome|

**Comment by patorjk** [comment]
Example: https://codesandbox.io/s/muidatatables-custom-toolbar-forked-9gtf7?file=/index.js

```
const getMuiTheme = () =>
  createMuiTheme({
    overrides: {
      MuiTablePagination: {
        caption: {
          fontFamily: ["ManropeMedium", "sans-serif"].join(","),
          fontSize: "8px"
        }
      },
      MUIDataTableJumpToPage: {
        caption: {
          fontFamily: ["ManropeMedium", "sans-serif"].join(","),
          fontSize: "8px"
        }
      }
    }
  });
```

**Comment by L-U-C-K-Y** [comment]
Thanks @patorjk for your swift answer!

I have added it exactly as you have posted, but it seems not to take effect:

![image](https://user-images.githubusercontent.com/14868134/105880219-66280800-6003-11eb-9a77-ce156c409430.png)

Is the version I use too old?

**Comment by patorjk** [comment]
Yeah, it may be a version issue. I'd recommend updating. The move from 2.x to 3.x actually isn't that big. Changes are outlined here:

https://github.com/gregnb/mui-datatables/blob/master/docs/v2_to_v3_guide.md

**Comment by L-U-C-K-Y** [comment]
I'll update and try it again. If the issue persists, we can reopen it.
