### ISSUE TITLE
Updating row data re-renders the whole table instead of just the row data

### ISSUE THREAD

**Issue by anonimeishon** [gregnb/mui-datatables#1645]
Updating row data re-renders the whole table instead of just the row data

## Expected Behavior
The row data should update when it receives the new data

## Current Behavior
The whole component renders again, even losing state data such as "Rows per page(It goes back to the default one)".
Also, i noticed the tag at the end of each table component changes with each update (MUIDataTableBodyCell-root-2825  (Notice the 2825, it goes up by 100 or 200 on each update))

## Steps to Reproduce (for bugs)

https://codesandbox.io/s/dreamy-forest-yjupp?file=/src/App.js

1. Inspect one of the rows of the table with your browser.
2. Change the rows per page option.
3. Press the update button below the table.
4. Watch the table row id change to a higher one and the rows per page option reset to default

(edit)
I found out the id's thing was because i declared the MUI theme inside of the component, but the rows per page issue still remains
## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |4.11.3|
| MUI-datatables  |3.7.4|
| React        |17.0.1|
| browser      |Chrome|
| Material-UI/icons  | 4.11.2 |

**Comment by wdh2100** [comment]
```js
  const options = {
    filterType: "multiselect",
    resizableColumns: false,
    pagination: true,
    responsive: "standard",
    rowsPerPage: 10,
    rowsPerPageOptions: [5, 10, 20, 50, 100],
    selectableRowsOnClick: false,
    selectToolbarPlacement: "none",
    selectableRowsHideCheckboxes: true,
    tableBodyHeight: "300px",
    viewColumns: "true",
    draggableColumns: { enabled: true, transitionTime: 300 },
    onRowClick: (e) => {
      // ChngCoord(state, setState);
    }
  };
```

This is normal operation due to the component structure.
If you change the parent's state, it is updated & re-render.

Remove `rowsPerPage`

**Comment by wdh2100** [comment]
Please check and close the issue.

**Comment by anonimeishon** [comment]
That was the problem, thanks!!!
