### ISSUE TITLE
Theme not working for table cell

### ISSUE THREAD

**Issue by imengheris** [gregnb/mui-datatables#1652]
Warning: Failed prop type: Invalid prop `placement` of value `bottom-center` supplied to `ForwardRef(Tooltip)`, expected one of ["bottom-end","bottom-start","bottom","left-end","left-start","left","right-end","right-start","right","top-end","top-start","top"].
If changes are provided via theme provider they are not applied.

Please see the same warning in codesandbox:
https://codesandbox.io/s/happy-roentgen-4xlhg?file=/src/App.js

Maybe this warning appears because of migration of components of material-ui
https://github.com/mui-org/material-ui/issues/24405

**Comment by wdh2100** [comment]
@imengheris 

thanks report 👍 👍 

ref : https://github.com/gregnb/mui-datatables/pull/1630

**Comment by wdh2100** [comment]
I will correct it and release it soon.

**Comment by wdh2100** [comment]
Fixed 3.7.6
