### ISSUE TITLE
Sort issue when use the same name field

### ISSUE THREAD

**Issue by ariel-upstream** [gregnb/mui-datatables#1657]
Hi,
I'm facing an issue with the sort design in my table, 
On clicking the header for sort the sort icon appears in more columns and not only the one that was clicked.

```
`  const columns: any = [
    {
      label: "Names",
      name: "myValuesObject",
      options: {
        customBodyRender: ({ names }): JSX.Element => (
          <div>{names}</div>
        ),
        sortCompare: (order: string) => (o1: any, o2: any) => {
          return (o1.data.names > o2.data.names ? 1 : -1) * (order === "asc" ? 1 : -1)
        },
      },
    },
    {
      label: "Numbers",
      name: "myValuesObject",
      options: {
        customBodyRender: ({ numbers }): JSX.Element => (
         <div>{numbers}</div>
        ),
        sortCompare: (order: string) => (o1: any, o2: any) => {
          return (o1.data.numbers > o2.data.numbers ? 1 : -1) * (order === "asc" ? 1 : -1)
        },
      },
    },
]`
```

I think the reason is the name is the same in both columns but this is my inner object,
how can I fix it? (maybe add a unique key to each column)

**Comment by ccChrisHH** [comment]
"name" is, to my knowledge, only used as an identifier internally in MDT and there should be no need to use the same name twice, so simply using "names" and "numbers" in your example should be fine.

**Comment by ariel-upstream** [comment]
myValuesObject is the name of the field in which the values of names and numbers are in.
So it will not fix it

**Comment by ccChrisHH** [comment]
I see. What might work is setting `enableNestedDataAccess: "."` on your table definition and then use "myValuesObject.names" and "myValuesObject.numbers" as names for your columns.

**Comment by ariel-upstream** [comment]
Nice solution, is that possible to get 2 values in a column with the enableNestedDataAccess prop?

For example:  name: "myValuesObject.names, myValuesObject.anotherFiled",

**Comment by ccChrisHH** [comment]
I shouldn't think so. What we did was extending the column defintion with a function that selects the object that shall be used to populate said field and then map the data of the table by referencing the column definitions - that sounds a bit awkward, but it works. Personally, I feel that MDTs approach of not exposing the original data object a bit problematic.

Here is what we did:
`const columns: (MUIDataTableColumn & { select?: (myValuesObject: MyValuesObject) => any })[] = [
        {
            name: "name",
            label: "Name"
            select: (myValuesObject: MyValuesObject) => myValuesObject, // you could do anything here, the result will be the data you receive in the column
            options: {
                     customBodyRender: (myValuesObject: MyValuesObject) => (<div>{myValuesObject.name}</div><div>{myValuesObject.whatEverfield}</div>)
            }
        },
        // ...
];        

const mapData = (myValuesObject: MyValuesObject) => {
       return Object.fromEntries(colums.map(column => [column.name, column.select ? column.select(myValuesObject) : myValuesObject[column.name]]));
}
`
Your table defintion would then include your data mapped by the function above. I hope this is somewhat clear.
Again: IMO, this is not optimal, but it works.
