### ISSUE TITLE
some warnings

### ISSUE THREAD

**Issue by irongear74** [gregnb/mui-datatables#1662]
any idea why is chrome generates this warnings? (when i manually change tabindex to tabIndex in your dist source, then the warning dissapears)

index.js:1 Warning: Invalid DOM property `tabindex`. Did you mean `tabIndex`?

...also

Warning: Failed prop type: Invalid prop `placement` of value `bottom-center` supplied to `ForwardRef(Popper)`, expected one of ["bottom-end","bottom-start","bottom","left-end","left-start","left","right-end","right-start","right","top-end","top-start","top"].

**Comment by viktorsteinwand** [comment]
we have the same warnings get logged in webpack-internal:

Warning: Failed prop type: Invalid prop `placement` of value `bottom-center` supplied to `ForwardRef(Popper)`, expected one of ["bottom-end","bottom-start","bottom","left-end","left-start","left","right-end","right-start","right","top-end","top-start","top"].
Popper@webpack-internal:///./node_modules/@material-ui/core/esm/Popper/Popper.js:67:18
Tooltip@webpack-internal:///./node_modules/@material-ui/core/esm/Tooltip/Tooltip.js:207:22
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
span
th
TableCell@webpack-internal:///./node_modules/@material-ui/core/esm/TableCell/TableCell.js:135:22
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
TableHeadCell@webpack-internal:///./node_modules/mui-datatables/dist/index.js:1:55098
tr
TableRow@webpack-internal:///./node_modules/@material-ui/core/esm/TableRow/TableRow.js:60:17
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
TableHeadRow@webpack-internal:///./node_modules/mui-datatables/dist/index.js:1:58657
thead
TableHead@webpack-internal:///./node_modules/@material-ui/core/esm/TableHead/TableHead.js:32:17
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
TableHead@webpack-internal:///./node_modules/mui-datatables/dist/index.js:1:59860
table
Table@webpack-internal:///./node_modules/@material-ui/core/esm/Table/Table.js:45:17
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
DndProvider<@webpack-internal:///./node_modules/react-dnd/dist/esm/common/DndProvider.js:32:18
div
div
Paper@webpack-internal:///./node_modules/@material-ui/core/esm/Paper/Paper.js:48:17
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
a@webpack-internal:///./node_modules/mui-datatables/dist/index.js:1:88352
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
div
Grid@webpack-internal:///./node_modules/@material-ui/core/esm/Grid/Grid.js:234:29
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
div
Grid@webpack-internal:///./node_modules/@material-ui/core/esm/Grid/Grid.js:234:29
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
div
div
SomeTable@webpack-internal:///./src/components/SomeTable.tsx:42:86
Route@webpack-internal:///./node_modules/react-router/esm/react-router.js:464:29
Switch@webpack-internal:///./node_modules/react-router/esm/react-router.js:670:29
div
div
Router@webpack-internal:///./node_modules/react-router/esm/react-router.js:93:30
BrowserRouter@webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:59:35
ThemeProvider@webpack-internal:///./node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:44:18
div
App@webpack-internal:///./src/pages/App.tsx:40:86

and 

Warning: Invalid DOM property `tabindex`. Did you mean `tabIndex`?
span
ButtonBase@webpack-internal:///./node_modules/@material-ui/core/esm/ButtonBase/ButtonBase.js:87:16
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
TableSortLabel@webpack-internal:///./node_modules/@material-ui/core/esm/TableSortLabel/TableSortLabel.js:84:23
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
div
div
span
button
ButtonBase@webpack-internal:///./node_modules/@material-ui/core/esm/ButtonBase/ButtonBase.js:87:16
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
Button@webpack-internal:///./node_modules/@material-ui/core/esm/Button/Button.js:306:18
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
Tooltip@webpack-internal:///./node_modules/@material-ui/core/esm/Tooltip/Tooltip.js:207:22
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
span
th
TableCell@webpack-internal:///./node_modules/@material-ui/core/esm/TableCell/TableCell.js:135:22
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
TableHeadCell@webpack-internal:///./node_modules/mui-datatables/dist/index.js:1:55098
tr
TableRow@webpack-internal:///./node_modules/@material-ui/core/esm/TableRow/TableRow.js:60:17
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
TableHeadRow@webpack-internal:///./node_modules/mui-datatables/dist/index.js:1:58657
thead
TableHead@webpack-internal:///./node_modules/@material-ui/core/esm/TableHead/TableHead.js:32:17
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
TableHead@webpack-internal:///./node_modules/mui-datatables/dist/index.js:1:59860
table
Table@webpack-internal:///./node_modules/@material-ui/core/esm/Table/Table.js:45:17
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
DndProvider<@webpack-internal:///./node_modules/react-dnd/dist/esm/common/DndProvider.js:32:18
div
div
Paper@webpack-internal:///./node_modules/@material-ui/core/esm/Paper/Paper.js:48:17
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
a@webpack-internal:///./node_modules/mui-datatables/dist/index.js:1:88352
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
div
Grid@webpack-internal:///./node_modules/@material-ui/core/esm/Grid/Grid.js:234:29
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
div
Grid@webpack-internal:///./node_modules/@material-ui/core/esm/Grid/Grid.js:234:29
WithStyles@webpack-internal:///./node_modules/@material-ui/styles/esm/withStyles/withStyles.js:64:25
div
div
SomeTable@webpack-internal:///./src/components/SomeTable.tsx:42:86
Route@webpack-internal:///./node_modules/react-router/esm/react-router.js:464:29
Switch@webpack-internal:///./node_modules/react-router/esm/react-router.js:670:29
div
div
Router@webpack-internal:///./node_modules/react-router/esm/react-router.js:93:30
BrowserRouter@webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:59:35
ThemeProvider@webpack-internal:///./node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:44:18
div
App@webpack-internal:///./src/pages/App.tsx:40:86

**Comment by wdh2100** [comment]
sorry 😭 

fixed 3.7.6
ref : https://github.com/gregnb/mui-datatables/issues/1652
