### ISSUE TITLE
What do `index` and `dataIndex` refer to?

### ISSUE THREAD

**Issue by raphael10-collab** [gregnb/mui-datatables#1689]
My objective is to link the trash icon selection with the correspondent action in a redux store.
In order to understand how to map in a one-to-one fashion the row indexes in mui-datatables with the indexes in the redux store and reducers, I've put a console.log in `onRowsDelete` function within `options`

        const table_options = {
          filterType: 'checkbox',
          responsivel: 'vertical',
          onRowSelectionChange: onRowSelectionChange,
          selectableRows: 'single',
          onRowsDelete: (e) => {
            console.log(e);
          },
          customToolbar: () => {
            return (
              <CustomToolbar />
            );
          }
        }

       return (

              <MuiThemeProvider theme={theme}>
                <MUIDataTable
                  title={"Information Pieces"}
                  columns={columnsList}
                  data={table_data}
                  options={table_options}
                />
              </MuiThemeProvider>
       )

This is the output of the `console.log` :  

![image](https://user-images.githubusercontent.com/70313067/112837002-9fc8ce00-909b-11eb-87ad-466acc88e349.png)

What do `index` and `dataIndex` refer to?

**Comment by BabakYaghoobi** [comment]
The `Index` refer to your table_data data array object

**Comment by raphael10-collab** [comment]
Thank you very much @BabakYaghoobi . This information was very helpful
