### ISSUE TITLE
Using TableSortLabel as sort indication

### ISSUE THREAD

**Issue by dmtrKovalenko** [gregnb/mui-datatables#17]
Material-ui has an awesome control for sorting displaying - [TableSortLabel](https://material-ui-next.com/api/table-sort-label/), I cannot see any reason to not use it for sorting.

**Comment by gregnb** [comment]
Thank you for the suggestion, but I prefer what is there right now.

**Comment by dmtrKovalenko** [comment]
@gregnb I'm sorry but current sorting control is really weird (from the material design prospective). As it is public package and it depends peerly to material-ui maybe it needs to add an ability to use all material-design sorting controls, or let users choose?

**Comment by gregnb** [comment]
@dmtrKovalenko As you can probably see from the import at the top I was using TableSortLabel at one point. My biggest beef with it using it was no initial state to let a user know that it is a sortable column.  I'm not trying to take liberties with the spec, but it really feel odd every time I looked at it.  But, you're right.  If i'm going to claim this is a material-ui package then as much as it bothers me I need to undo that.

I wish there was a nice compromise in this situation I really did feel that it was helpful to a icon that could show an initial state (this is sortable) then the up/down direction.  

<img width="1449" alt="screen shot 2018-03-24 at 6 55 02 am" src="https://user-images.githubusercontent.com/19170080/37863178-777d9f54-2f30-11e8-965c-c5181eae0bb0.png">
