### ISSUE TITLE
resizableColumn doesn't work properly and add toolbar to trigger 

### ISSUE THREAD

**Issue by riorinald** [gregnb/mui-datatables#171]
hello, i want to resizableColumns in my data but it doesn't show properly. i get the data from async componentDidMount to my api with axios then set state.
maybe because react render first with empty data but this resizable will work if i resize the browser window
![image](https://user-images.githubusercontent.com/41993762/44702880-aa73ee80-aabf-11e8-8e02-0260a6f91431.png)

```
class Col extends Component {
    constructor() {
        super();
        this.state = {
          switched : false,
          datax:[''],
        this.apiUrl = 'http://localhost:1234';   
      }
      async componentDidMount() {
        var _ = require('lodash');
        const response = await axios.get(`${this.apiUrl}/cso/get`);
        const toarr = response.data.map(_.values);
        for (var i = 0; i < toarr.length; i++) {
            toarr[i] = toarr[i].splice(2,11);
          }
        this.setState({
          datax: toarr,
        });
        console.log(toarr);     
      }

```

p.s pardon me i'm new in react,
## Expected Behavior
then i try to set toolbar from customize-toolbar examples to trigger re render data and set a props resizableColumns : true and i confused to implement the props
```
const defaultToolbarStyles = {

};

class CustomToolbar extends React.Component {
    constructor(props) {
        super(props);
        this.handleClick = this.handleClick.bind(this);
        this.state = {nilai:false};
    }
handleClick = event => {
        this.setState({ nilai: event.target.checked});
        console.log("click!",event.target.checked);
      }

  render() {
    return (
      <React.Fragment>
        <Tooltip title={"custom icon"}>
        <Switch
          onChange={this.handleClick}
          color="primary"
        />
        </Tooltip>
      </React.Fragment>
    );
  }
}
```
![image](https://user-images.githubusercontent.com/41993762/44703727-ef4d5480-aac2-11e8-8523-23f3bfda0069.png)

how can i get the switch checked to trigger resizeableColumns function works ?
## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   1.5.1      |
| MUI-datatables  |     2.0.0-beta-23    |
| React        |    16.4.2     |
| browser      |    Chrome     |
| etc          |         |

**Comment by gregnb** [comment]
It is most likely due do the delay in the async data coming and then the resize not running on update. Let me look into this. Thanks for raising the issue

**Comment by gregnb** [comment]
Try the latest version this issue should be resolved
