### ISSUE TITLE
Option to disable selection on certain rows

### ISSUE THREAD

**Issue by brianpmaher** [gregnb/mui-datatables#172]
I'd like to have the ability to disable selection on certain rows in the data tables.  I could think of a couple of ways to accomplish this:

1. A "isSelectable" function passed to options that returns a boolean and evaluates for each row
2. A list passed to options of enabled or disabled rows
3. A render function passed to options overriding the format of the select column

I would think that option 1 would be fairly simple and 3 would be the most flexible.  2 seems like a hack...

**Comment by brianpmaher** [comment]
If we pass a list, I'd assume we'd pass a list of data indices?

**Comment by zhdanouskikh** [comment]
I think it's a good idea to have "isSelectable" function for each column and pass the whole row data in it. It should return true or false. By default this function return true.

**Comment by gregnb** [comment]
this feature is now available via option:

```
isSelectable: (dataIndex) => {
    //prevents selection of row with title "Attorney"
    return data[dataIndex][1] != "Attorney";
}
```
