### ISSUE TITLE
Apply filters only on server-side

### ISSUE THREAD

**Issue by johninoak** [gregnb/mui-datatables#1731]
## Expected Behavior
When serverSide option is set to true, applyNewFilters function shouldn't apply filters on client-side but let the filters to be applied on server-side. Only chips should be displayed.

## Current Behavior
Currently client-side filtering is applied before server-side filtering. This causes the content of the data table to change twice; first time it displays wrong data (client-side filtering applied) and second time it displays correct data (server-side filtering applied).

## Steps to Reproduce (for bugs)
I followed this example https://github.com/gregnb/mui-datatables/blob/master/examples/serverside-filters/index.js along with **server-side pagination**. The issue is in handleFilterSubmit function where client-side filtering (i.e. applyNewFilters) MUST be applied before server-side filtering to resolve the final filters sent to the server-side for filtering.

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI-datatables  | 3.7.7        |

**Comment by brownp2k** [comment]
You could override the filterOptions [logic](https://github.com/gregnb/mui-datatables/blob/7558e7393b6ee4b21c9481613429efcdbe7a6ddc/examples/customize-filter/index.js#L137) method to return false.  This effectively disables client-side filtering, but it is still called (way more times than it should be - #1733).

**Comment by johninoak** [comment]
Thanks, it seemed to work.

There's still one annoying thing when using server-side filtering with logic method set to return false. When invoking applyNewFilters method, the filter dialog is closed and chips are added, BUT only after that we can make the request to backend to get the filtered data. I think it should happen vice versa i.e. getting the data first and then closing the dialog and adding chips. Yes, it works both way and is more a matter of user experience.
