### ISSUE TITLE
Column filter to display options based on object property

### ISSUE THREAD

**Issue by sitjohnny** [gregnb/mui-datatables#1732]
So I am trying to get the filter dialog option to work for one of my columns. Right now, my data looks like this: 
```
[
    { id: 1, name: "Test Name 1", description: "Test Description",  access: { type: "View", id: 1},  
    { id: 2, name: "Test Name 2", description: "Test Description",  access: { type: "Request", id: 2}
]
```

The question comes from the `access` column. In my columns array, this is what the object looks like: 

```
{
        name: "access",
        label: "Access",
        options: {
            filter: true,
            sort: true,
            empty: true,
            customBodyRender: (value) => (
                <AccessButton type={value.type} id={value.id} />
            ),
        },
    }
```
So because it is reading in the `access` property in the object, the filter doesn't work and it just shows [object Object]. I want the filter to show whatever is under `type`. However in my `access` object, I need both properties and can't just use `access.type` for `name`. How do I set it up if possible so that I can do just that?

## Expected Behavior

When clicking on the filter button, the `Access` column should display all the options under `access.type`

## Current Behavior

It displays only `[object Object]`

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.11.3    |
| MUI-datatables  |     3.7.6    |
| React        |    17.0.1     |
| browser      |    chrome     |
| etc          |         |

**Comment by sitjohnny** [comment]
This is solved by using the `tableMeta` parameter from the `customBodyRender`, where we can access the data of the whole row.

**Comment by eriksabol** [comment]
@sitjohnny could please paste some working example of how did you solve filtering problem with tableMeta parameter? I am quite struggling with it and no matter what I try the result is always [object Object] which is quite frustrating.

**Comment by juanvillans** [comment]
@eriksabol @sitjohnny how you solved it? Please, al also get [object object]
