### ISSUE TITLE
The prop `onChangePage` of `ForwardRef(TablePagination)` is deprecated

### ISSUE THREAD

**Issue by MrRainesE** [gregnb/mui-datatables#1759]
Failed prop type: The prop `onChangePage` of `ForwardRef(TablePagination)` is deprecated. Use the `onPageChange` prop instead.

| Tech         | Version |
|--------------|---------|
| Material-UI  |  3.7.7       |
| MUI-datatables  | 4.12.3        |
| React        |   17.0.2      |
| browser      |  chrome       |
| etc          |         |

**Comment by joaomantovani** [comment]
Facing the same problem

**Comment by joaomantovani** [comment]
Workarounds:
- https://github.com/gregnb/mui-datatables/pull/1748#issuecomment-897861778
- https://github.com/mbrn/material-table/pull/2937#issuecomment-879017952

**Comment by MrRainesE** [comment]
thanks @joaomantovani
