### ISSUE TITLE
Can't resolve '@material-ui/icons/Clear in mui-datatables/dist

### ISSUE THREAD

**Issue by TheLogan** [gregnb/mui-datatables#1791]
## Expected Behavior
This happens when running ``yarn start``

## Current Behavior
My project attempts to run but crashes at some point during startup with above-mentioned error
I can see that MUI-Datatables expects to fetch icons from ``@material-ui/icons/`` however the version of Material UI that I've added has them in ``@mui/icons-material/``, as a test I went through ``/node_modules/mui-datatables/dist/index.js`` and replaced all paths for mui icons with the actual path, and now it runs as expected, my guess would be that MUI icons at some point changed their install path and that then breaks mui-datatables.

## Steps to Reproduce (for bugs)
1. create react app
2. add Material UI
3. add mui icons,
4. add mui-datatables,
5. run start

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |      ^5.0.3   |
| MUI  Icons |      ^5.0.3   |
| MUI-datatables  |     ^3.7.8    |
| React        |     ^17.0.2    |

**Comment by kvlknctk** [comment]
C'mon!

**Comment by the-noob** [comment]
Just upgraded to 4.0 but still getting this
```
....node_modules/mui-datatables/dist/index.js
Module not found: Can't resolve '@mui/icons-material/Clear' in '/home/...../node_modules/mui-datatables/dist'
```

**Comment by riversoftFIN** [comment]
There still seems to be some references to mui legacy styles. Installing @mui/styles seems to have fixed it for me. Docs: https://mui.com/styles/basics/

**Comment by saurabhjindal-SF** [comment]
@the-noob  run yarn add @mui/icons-material

**Comment by the-noob** [comment]
why should I add dependencies that I don't use ?

**Comment by ashfaqnisar** [comment]
@TheLogan the #1772 is merged, this should fix the issue. So, Can you close this issue ?

**Comment by TheLogan** [comment]
Thank you :)
