### ISSUE TITLE
Peer dependencies warning 

### ISSUE THREAD

**Issue by noygal** [gregnb/mui-datatables#180]
Note: I've change the issue subject, please read comments below.

## Expected Behavior
To bundle the code.

## Current Behavior
Getting an error

```
Cannot resolve dependency '@material-ui/icons/FileDownload'
```

## Steps to Reproduce (for bugs)

1. Install 3.0.0 version
2. Bundle application

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.0.0     |
| MUI-datatables  |    latest     |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by noygal** [comment]
Working on version 28 (I've tested with 27).

There's still a peer dependencies warning, but everything runs well:

```
npm WARN mui-datatables@2.0.0-beta-28 requires a peer of @material-ui/core@^1.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN mui-datatables@2.0.0-beta-28 requires a peer of @material-ui/icons@^2.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by gregnb** [comment]
This should be solved in the latest version
