### ISSUE TITLE
Add @mui/styles as peerDependency

### ISSUE THREAD

**Issue by thefat32** [gregnb/mui-datatables#1820]
With the migration to MUI V5 it was necessary to use `@mui/styles` package to keep using `createStyles` and `makeStyles` utils. It should be added as a peerDependency.

**Comment by maganezf** [comment]
#1826 UP

**Comment by jalaluddin94** [comment]
I was just facing this issue too bcause MUI is upgrading, so I need to install @mui/styles package too. But when I check using 
`npm list mui-datatables` 
there is no peerDependency to @mui/styles.

**Comment by msd026** [comment]
This should not be a correct fix. @mui/styles is deprecated and is creating issues with the newer version of react. 

TypeError: Cannot read property 'down' of undefined
    at defaultTableStyles (/path-from-root/node_modules/mui-datatables/dist/index.js:246:2212)

**Comment by Fullbusters** [comment]
@thefat32 in release 4.1.0 @mui/styles was removed at all from project, please update your version, and close issue if all is good now

**Comment by thefat32** [comment]
As @Fullbusters pointed, this was solved in #1862. Thank you!

Closing this
