### ISSUE TITLE
Text is not centered when data is empty

### ISSUE THREAD

**Issue by frmachao** [gregnb/mui-datatables#1823]
## summary 
- Text is not centered when data is empty

## screenshots
![Untitled-2](https://user-images.githubusercontent.com/22849231/144073301-4c8ee298-aee6-4d78-98b3-fd72c450cd40.gif)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.12.0    |
| MUI-datatables  |   3.8.2      |
| React        |  16.13.0       |
| browser      |      chorme 96.0   |
| etc          |         |

**Comment by ashfaqnisar** [comment]
Hey @frmachao buddy, Can you close the issue as the PR was merged.

**Comment by Marvin3Benz** [comment]
Hi, I am using v4.2.2 mui-datatables, but this issue is still there. I suppose you forgot to merge it into v4.
https://github.com/gregnb/mui-datatables/pull/1825

In v4, there is no attribute "isEmpty" to detect when no dataset in mui-datatables, and the text will not align center.

Thanks

**Comment by SFaraji** [comment]
This issue is still a thing and the text is not aligned on the responsive view. 

Cheers,
