### ISSUE TITLE
MUIDataTableViewCol style not getting set from theme

### ISSUE THREAD

**Issue by gesamples** [gregnb/mui-datatables#1829]
## Expected Behavior

![image](https://user-images.githubusercontent.com/77859524/145621570-0f2101dd-0dba-4154-8de7-d20821a77b56.png)
The above code should force the column filtering pop out to have an exaggerated padding.

## Current Behavior

The style seems to be getting overwritten by something in MuiFormControl
![image](https://user-images.githubusercontent.com/77859524/145621895-ad716a2a-6c3d-4f2a-b288-24465d6dcd3b.png)

## Steps to Reproduce (for bugs)

1. run create-react-app to stand up a new react project
2. copy and paste code from below and render it in App.js
        import { ThemeProvider } from "@mui/styles";
        import MUIDataTable from "mui-datatables";
        import Box from '@mui/material/Box';
        import Paper from '@mui/material/Paper';
        import { createTheme } from '@mui/material/styles';
        
        export default function DataTable(props) {
          let { data, columns, tableConfig, create } = props;
          let theme = createTheme({
            overrides: {
              MUIDataTable: {
                responsiveScroll: {
                  maxHeight: 'none',
                },
              },
              MUIDataTableViewCol: {
                root: {
                  paddingTop: '100px !important'
                }
              }
            },
          });
          let options = {
            ...tableConfig.options,
            enableNestedDataAccess: '.'
          }
          return (
            <Box sx={{ height: '100vh', width: '100%', paddingTop: '10px' }}>
              <Paper sx={{ width: '100%', mb: 2 }}>
                <ThemeProvider theme={theme}>
                  <MUIDataTable
                    title={tableConfig.title}
                    data={data}
                    columns={columns}
                    options={options}
                  />
                </ThemeProvider>
              </Paper>
              {create}
            </Box>
          )
        }

## Your Environment

|--------------|---------|
| Material-UI  |4.12.3         |
| MUI-datatables  | 4.0.0        |
| React        |17.0.2         |
| browser      | chrome        |
| etc          |         |

**Comment by verbeckii** [comment]
Can you set other properties via theme? I can't make any effects changing my theme styles

**Comment by gesamples** [comment]
Thanks! That was exactly what I needed.
