### ISSUE TITLE
Serverside Rendering work only for the first page not for next page

### ISSUE THREAD

**Issue by ayoubgm** [gregnb/mui-datatables#1832]
## Expected Behavior

The table must simply display the data of the next page must it shows empty data for the next pages

## Current Behavior

The table display only first page data not the next pages, i check props that i am passing but the data is there but nothing is show.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |4.11.0|
| MUI-datatables  |3.7.7|
| React        |16.13.1|
| browser      |         |
| etc          |         |

**Comment by phonganhhung9xtb** [comment]
Me too, when next page table not show data

**Comment by phonganhhung9xtb** [comment]
@ayoubgm let set serverSide in options props, not datatables props

**Comment by ayoubgm** [comment]
Yes i set serverSide option to true and it works perfectly

**Comment by Saran-coder90** [comment]
But filter won't work?
