### ISSUE TITLE
App crashing while loading table

### ISSUE THREAD

**Issue by farukEncoded** [gregnb/mui-datatables#1852]
![image](https://user-images.githubusercontent.com/54427003/152634263-ce760470-2cbd-4662-921c-95cbef58872d.png)

**Comment by ashfaqnisar** [comment]
Hey @farukEncoded, which version of mui-datatables and material ui are you using ?

**Comment by farukEncoded** [comment]
> Hey @farukEncoded, which version of mui-datatables and material ui are you using ?

"@material-ui/core": "^4.11.0",
"mui-datatables": "^3.7.7",

**Comment by ashfaqnisar** [comment]
Hey @farukEncoded,  would  you be provide the columns, options and data or sample code sand box if possible ?

**Comment by farukEncoded** [comment]
> Hey @farukEncoded, would you be provide the columns, options and data or sample code sand box if possible ?

I found the issue, I was passing an object instead of an array as `data` prop in the table, and that was crashing the page.

**Comment by ashfaqnisar** [comment]
That's great!, As the issue was resolved, can you close this issue.
