### ISSUE TITLE
All row selection does not include dataIndex

### ISSUE THREAD

**Issue by brianpmaher** [gregnb/mui-datatables#188]
Clicking the checkbox in the table header calls the `onRowSelected` callback without passing the `dataIndex` for each row.

## Expected Behavior

`onRowSelected` callback should be given an array of current and all selected rows with the `dataIndex` property in addition to the `index` property.

## Current Behavior

`onRowSelected` callback is given an array of rows for the current and all selected rows with only the `index` property (the `dataIndex` property is missing).

## Steps to Reproduce (for bugs)

1. In any example
2. Setup a `onRowSelected` callback in the `options` object
3. Put a breakpoint or `console.log` statement in the callback
4. Click the "select all" checkbox on the table header/toolbar area
5. Note that the rows given to the `onRowSelected` callback does not contain the `dataIndex` property for each row.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    1.4.3     |
| MUI-datatables  |    2.0.0-beta20     |
| React        |   16.4.1      |
| browser      |    Chrome 68.0.3440.106     |

**Comment by gregnb** [comment]
I was looking at this one the other night by pure chance and noticed the issue as well. I couldn't quickly track down a fix but if anyone wants to take this up I'd be happy to accept a PR

**Comment by brianpmaher** [comment]
I noticed that this is the same case with the `onCellClick` callback.  We're only being given the col and row index, not the data index.

**Comment by gregnb** [comment]
Yep you are correct. There is another ticket related to that. Just need to create one function to return that data and use it across the board so people have the table information

**Comment by gregnb** [comment]
This should be addressed in the latest version along with onCellClick being updated
