### ISSUE TITLE
Sorry, no matching records found upon onChangePage & onChangeRowsPerPage

### ISSUE THREAD

**Issue by mabc224** [gregnb/mui-datatables#189]
I have implemented custom `onChangePage` & `onChangeRowsPerPage` to get data from server. I am getting `Sorry, no matching records found` when above ents occur. Request is successfully inititated and got data with some seconds, State is updating and i am getting data in it, but component is not updating it, except the case of default first page, which have load data on `componentDidMount`.

## Expected Behavior
It should re-render data-table with updated data upon event change.

## Current Behavior
Here it is a demo, what I am getting.
[https://codesandbox.io/s/7z6lp1xn76](https://codesandbox.io/s/7z6lp1xn76)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  1.2.0       |
| MUI-datatables  |   2.0.0-beta-28      |
| React        |   16.4.2      |
| browser      |   chrome      |

**Comment by gregnb** [comment]
Look at the example on server side

**Comment by mabc224** [comment]
I just did it according to sample which you refer to me.
`https://codesandbox.io/s/ql4ly6ry99`
Is there a way to use built-in search capability while using server-side page change, to search for any record from currently displayed records?

**Comment by gregnb** [comment]
There is no support for that and to be honest I gotta say at this time I won't be supporting that. It becomes confusing. We're putting it into serverSide mode so I'm telling a user, "Everything will be handled by the server" but then if we have additional toggles for each feature I'm not sure how clean this API would read

**Comment by michelfperez** [comment]
Any solution for this problem? I'm getting the same error when I'm changing page and using server side. I implemented exactly like the example, my data is returned but the grid keep displaying no matching records

**Comment by patorjk** [comment]
You may want to open a new issue. Also, can you create a codesandbox to show the problem?

**Comment by Brayan008** [comment]
If you have not been able to solve this problem. Use **"serverSide: true"** in your MuiDataTable options and it will work.
