### ISSUE TITLE
Feature Request: more fine grained pagination options

### ISSUE THREAD

**Issue by JordanKadish** [gregnb/mui-datatables#19]
## Issue

My db has tons of entries, and I'd like to be able to skip pages similar to how sites like Amazon have numbers between their next/previous page options
Example:
at the bottom of the page have:
< 1,a,b...c,d,96 >
where 
     a and b are 10 and 5 pages back from current page respectively (or disappear when <15 pages in)
     c and d are 5 and 10 pages ahead of current page respectively (or disappear when <15 pages from the end, being the 6th page)
## Your Environment

| Tech         | Version |
|--------------|---------|
| mui-datatables  |    1.0.9     |
| node        |    9.x     |
| OS      |     Linux    |

**Comment by JordanKadish** [comment]
Forgot to add for clarity: in the example, < and > are the current icons

**Comment by gregnb** [comment]
Ok, just to be clear here is what Amazon currently looks like:

<img width="1278" alt="screen shot 2018-03-23 at 9 23 20 pm" src="https://user-images.githubusercontent.com/19170080/37858805-c19f5078-2ee0-11e8-8cfd-2beb048141f1.png">

What mui-datatables currently presents:

<img width="1003" alt="screen shot 2018-03-23 at 9 26 04 pm" src="https://user-images.githubusercontent.com/19170080/37858813-e4c35d2e-2ee0-11e8-9fe0-ee158f958b2b.png">

So doing this feature is more a design question. Where do we shift things? Maybe the row status (ie: 1-10 of 30) shifts all the way to the left and then inside it could list 5 numbers. I'm not sure, if you have a design idea for this it would be helpful

**Comment by JordanKadish** [comment]
I think rowes per page (along with the relevant count) should go on the far left, with the arrows/numbers in the center. Then you'd have space for a company logo or something in the bottom right ;)

**Comment by gregnb** [comment]
Ok I'm thinking along those lines as well. I'll add this to the todo items list

**Comment by gregnb** [comment]
This can now be done by the user with the customFooter override where a user can create a pagination to their own liking
