### ISSUE TITLE
Select all checkbox does not only select filtered list

### ISSUE THREAD

**Issue by brianpmaher** [gregnb/mui-datatables#192]
When selecting the "select all" checkbox in the header, all rows are selected, not just the ones we may have filtered down.  This is not what I'd expect from a select all checkbox.

## Expected Behavior

When filtering rows down using search or filters (or both) and selecting the "select all" checkbox in the header, only select the rows that are filtered down.

## Current Behavior

Select all checkbox selects all rows, even those excluded by a search or filter.

## Steps to Reproduce (for bugs)

1. Navigate to any example
2. Filter down the list to some small number
3. Click the select all checkbox in the header
4. Note how many columns are selected in the select toolbar message

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    1.4.3     |
| MUI-datatables  |    2.0.0-beta-20     |
| React        |     16.4.1    |

**Comment by gregnb** [comment]
Great, thanks for filing the issue

**Comment by RickyCh** [comment]
Hi. Any update on this issue?

**Comment by RickyCh** [comment]
> Great, thanks for filing the issue

Hi. Any update on this issue?

**Comment by gregnb** [comment]
I have a PR I've just created that should resolve this issue. Looking to merge it after a review tomorrow.
