### ISSUE TITLE
renderExpandableRow keeps rerendering when row expanded

### ISSUE THREAD

**Issue by maegi90** [gregnb/mui-datatables#1935]
## Expected Behavior
options->renderExpandableRow renders a single time

## Current Behavior
options->renderExpandableRow keeps rerendering when a row is expanded

## Steps to Reproduce (for bugs)
I tried the example from the repo, which shows the same behavior. 
I simply added a console.log('expanded') to the renderExpandableRow, which then keeps loggingwhen the row is expanded. 

`renderExpandableRow: (rowData, rowMeta) => {
       console.log('expanded')
        const colSpan = rowData.length + 1;
        return (
          <TableRow>
            <TableCell colSpan={colSpan}>Custom expandable row option. Data: {JSON.stringify(rowData)}</TableCell>
          </TableRow>
        );
      },`

## Your Environment

| Tech         | Version |
|--------------|---------|
| @mui/material  |5.8.7|
| MUI-datatables  |4.2.2|
| React        |18.2.0|
| browser      |chrome|

**Comment by anishkumar23-01** [comment]
@maegi90  how you fixed this issue?
