### ISSUE TITLE
Error inappropriately thrown

### ISSUE THREAD

**Issue by ccurtin** [gregnb/mui-datatables#196]
https://github.com/gregnb/mui-datatables/blob/5697e78c47d809a4e978f4c90c75b0e1c99caf89/src/MUIDataTableBody.js#L51-L59

**This happens when I**:
  1) set my rowsPerPage to say `10`
  2) have multiple pages of results, let's say `55` rows, so 6 pages.
  3) click the "goToLastPage" button and land on page 6
  4) type something into the search input, maybe a weekday name like "Sunday"
  5) The issue is that the error above is thrown whenever the number search results match or extend the `rowsPerPage`, so I type "Sunday" and get_(or should get)_ 18 matches but instead the error is thrown because I guess the component re-renders where the `page` is greater than `totalPages` before it sets `page` equal to `totalPages`.

This is only true when you are initially on a page that exceeds the pages for matched search results prior to searching. In our example above it would be anything after page 2.

I hope I explained it well enough!

I have temporarily commented this exception out within my project but when I have time would like to 
revisit it.

**Comment by gregnb** [comment]
Thanks for this detailed explanation. I'll try to address it when I get some free time.

**Comment by gabrielliwerant** [comment]
@ccurtin I tried to replicate this issue and could not. The issue was posted a while ago, so it's possible it was solved in the mean time. Can you confirm that this is no longer an issue in the latest build?

**Comment by gabrielliwerant** [comment]
Closing, as this is likely an old issue that has since been fixed in later releases.
