### ISSUE TITLE
How does storageKey/LocalStorage (getItem and setItem) work in MUI Datatable?

### ISSUE THREAD

**Issue by Shreeabcd** [gregnb/mui-datatables#1962]
Hi,
If someone can help me understand How does storageKey/LocalStorage (getItem and setItem) work in MUI Datatable that would be really great?

What I am trying to achieve is lets say I have a column with name:"title", display:"false". 
Now by default "title" will be unchecked in viewColumns. When I check that checkbox, "title" should get added in localstorage apart from getting added in the table column. When I log back in, then I should still see "Title" added in the table . It should not disappear just because I logged out of my session. How do I localstorage.getItem here? What does storageKey do?

P.S - I am able to persist that column for that session only using onViewColumnChange function.

**Comment by Shreeabcd** [comment]
I was able to figure this out myself. Here is the code . Hoping it will help someone else.

import React, { useState, useEffect } from 'react';
import MUIDataTable from 'mui-datatables';




function App() {
	const [tableState, setTableState] = useState({});

	useEffect(() => {
		const storedData = localStorage.getItem('my-table-state');

		if (storedData) {
			setTableState(JSON.parse(storedData));
		}
	}, []);

	useEffect(() => {


		localStorage.setItem('my-table-state', JSON.stringify(tableState));
	}, [tableState]);


	const columns = [
		{
			name: 'Name',
			options: {
				filter: false,

				display: useEffect(() => { }, [])


			}
		},
		{
			name: 'Title',
			options: {
				filter: false,
				// display:true

			}
		},
		{ name: 'Location', options: { filter: true } },
		{ name: 'Age', options: { filter: true } },
		{ name: 'Salary', options: { filter: true } },
	];

	const data = [
		['Gabby George', 'Business Analyst', 'Minneapolis', 30, 100000],
		['Aiden Lloyd', 'Business Consultant', 'Dallas', 35, 200000],

	];

	return (
		<MUIDataTable
			title="Employee List"
			data={data}
			columns={columns}
			options={{
				filterType: 'checkbox',
				storageKey: 'my-table-state',
				draggableColumns: {
					enabled: true
				},
			}}
			state={tableState}
			setState={setTableState}
		/>
	);
}

export default App;

**Comment by filipe-alves-oliveira** [comment]
Thanks for the help it worked for me too, I just have a question I used your solution to persist the filtered data I want, but when I change the page and come back the data persisted but the filter did not. Did you understand? can you help?
