### ISSUE TITLE
how can i define style in column  

### ISSUE THREAD

**Issue by Sanjayjbsl** [gregnb/mui-datatables#197]
custom style in column like my last column is status and i have to show status in badge completed/pending  etc....

**Comment by DanielGarciaGuillen** [comment]
One way you can do this is by using the customBodyRender property for the columns to pass whatever you want.
For example, for the status column you will do something like this:

```
name: 'Status', 
      options: {    
        customBodyRender: status => <StatusBadge status={status}} />,
      },
```

Then you can create a component called StatusBadge that depending on the status will render whatever you want.

```
const StatusBadge = ({status}) => (
  <React.Fragment>
    {status == "completed" && (
      <p> Completed </p>
    )}
    {status == "pending"&& (
      <p> Pending </p>
    )}
  </React.Fragment>
);
```
