### ISSUE TITLE
Is there anyway I could change the icons in the action panel?

### ISSUE THREAD

**Issue by susmita-vps** [gregnb/mui-datatables#198]
I would like to change the 'export to csv' icon to a standard download icon. Currently it uses the download from cloud icon. Thanks.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gregnb** [comment]
Not currently but I am working on changing the API around a bit to allow for more flexibility

**Comment by susmita-vps** [comment]
Hi Greg, for a short-term is it possible to change the download icon to a standard one (with a simple downarrow) rather than the "cloud_download"? Thanks.
