### ISSUE TITLE
How to create a custom MUI-Datatables search box with outlined style

### ISSUE THREAD

**Issue by appsnay** [gregnb/mui-datatables#1988]
Default UI Search Box is :
![image](https://user-images.githubusercontent.com/19705308/213188433-76b2c195-b736-4694-8233-f099ce3e56f4.png)

And want to make this style :
![image](https://user-images.githubusercontent.com/19705308/213188610-3fd3633e-7838-4ed9-9741-885ebf5ccb04.png)

How to make The TextField or Input with outlined style.

Please visit my question in this link :
https://stackoverflow.com/questions/75123509/how-to-create-a-custom-mui-datatables-search-box-with-outlined-style

## My Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |5.11.4|
| MUI-datatables  |4.3.0|
| React        |18.2.0|

**Comment by TBenton-eb** [comment]
You can create a custom search
![image](https://user-images.githubusercontent.com/88386722/213317164-f1a80656-52a8-4389-8b6e-63f522b15918.png)

Check those out in the docs https://github.com/gregnb/mui-datatables

**Comment by appsnay** [comment]
There is no example? for this API?

> You can create a custom search ![image](https://user-images.githubusercontent.com/88386722/213317164-f1a80656-52a8-4389-8b6e-63f522b15918.png)
> 
> Check those out in the docs https://github.com/gregnb/mui-datatables

**Comment by appsnay** [comment]
The solution has been solved already answered in the following link:
https://stackoverflow.com/questions/75123509/how-to-create-a-custom-mui-datatables-search-box-with-outlined-style/75169152#75169152
