### ISSUE TITLE
createMuiTheme() and responsive styling

### ISSUE THREAD

**Issue by jeremysgitty** [gregnb/mui-datatables#202]
Hi Greg

Nice work on this by the way.

General question here, I haven't really been able to figure out in combination with Material Docs and yours;

How to style the responsive parts of the table.  I am successfully targeting items as instructed via the _crerateMuiTheme_ and using _MUIDataTableBodyCell_ and _MUIDataTableHeadCell_ for example.

Though how do I target the same items in their responsive modes?  For example with the **cellStacked** property applied?

Is there a better way to do it other than using the __crerateMuiTheme__?

Sorry for being so general though pulling my hair out as of late, and would love to keep using this.

Cheers

**Comment by jeremysgitty** [comment]
In looking deeper at the code I realised what I was doing wrong.

Didn't really understand the 'root' and other parts of the css keys that could be used.

Shoulda done dome more research, but sometimes all it takes is a different approach and maybe some coffee.

Thanks

**Comment by djkingh01** [comment]
What did you discover .. I am trying the same thing using theme.breakpoints.down("sm") but its not applying?

**Comment by djkingh01** [comment]
Got it while looking through the code. 

theme.overrides["MUIDataTableBodyRow"] =  {
    responsiveStacked: {
        [theme.breakpoints.down("sm")]: {
            '&:nth-child(odd)': {
                backgroundColor: 'blue'
            }
        }
    }
}
