### ISSUE TITLE
serverSide not working in 2.0.0-beta.32

### ISSUE THREAD

**Issue by allenjoy123** [gregnb/mui-datatables#206]
## Expected Behavior
None of the serverSide features are working - search, sort etc. Each of these functions would generally send a request to the server when serverSide option is set to true. 

## Current Behavior
None of the request are sent to server. I checked the code for MuiDatatable.js . I noticed that the function setServerRequest is missing. I believe wrong code got promoted in this version 2.0.0-beta.32

## Steps to Reproduce (for bugs)
Upgrade to version beta.32 

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.1.2     |
| MUI-datatables  |     2.0.0-beta.32    |
| React        |    16.5.2     |
| browser      |    chrome     |
| etc          |         |

**Comment by gregnb** [comment]
How are you using it? The callback feature has been changed maybe you aren't using the updated one? I had to make a breaking change

**Comment by gregnb** [comment]
onServerRequest has been renamed to onTableChange

**Comment by allenjoy123** [comment]
Thanks. I didn't see the change in callback feature. I will update that.
I wanted to get with you with regards exposing the search component so as to be able to add a search button myself. My users requested a more controlled way to search. Any suggestions or plans to expose the search so I can customize it?

**Comment by gregnb** [comment]
I'm trying to find some time to get to all these items but my full time job has been very demanding as of late

**Comment by allenjoy123** [comment]
Sure. appreciate your willingness to help.
