### ISSUE TITLE
How to download/export only filtered data ?

### ISSUE THREAD

**Issue by revskill10** [gregnb/mui-datatables#207]
## Expected Behavior

When i filtered data, then the download/exported data should only display the filtered data.
## Current Behavior

When i filtered data, then the download/exported data still display ALL the data.

**Comment by gregnb** [comment]
I have a PR open for this when merged will resolve the issue. Will review some more before completing

**Comment by gregnb** [comment]
This is now been resolved

**Comment by Pczek** [comment]
Still doesn't work for me. Just upgraded from `2.0.0-beta-41` to `2.0.0-beta-50`. This issue still exists for me. Doesn't matter if I use the search or the actual filter dialog. It would be cool to have the same behavior for the free text search ✌️ 

Love the package, saves me a lot of work. Keep up the good work guys! 🙌

**Comment by Pczek** [comment]
@gregnb Should I open a new ticket or will you reopen this one?

**Comment by omriza5** [comment]
@gregnb Its not working for me, i'm using version 4.2.2.

Edit:
Managed to to download the filtered data by adding the following object to options:
 downloadOptions: {
      filterOptions: {
        useDisplayedColumnsOnly: true,
        useDisplayedRowsOnly: true,
      },
    }
