### ISSUE TITLE
onSearchOpen callback (similar to current onSearchClose only triggering when the search icon is clicked)

### ISSUE THREAD

**Issue by apercas** [gregnb/mui-datatables#210]
## Expected Behavior
As we already have `onSearchClose` (see https://github.com/gregnb/mui-datatables/issues/145) I think we can also use a similar callback for when a user opens the search dialog and `showSearch` is true.

## Current Behavior
The searchbox is opened offering a "value has changed" and "box has been closed" callback, but not for "box has been opened"

Thank you very much :)

**Comment by gregnb** [comment]
Sure, would you like to submit a PR for this?

**Comment by apercas** [comment]
Will do.
