### ISSUE TITLE
Tooltip is not visible for filter and viewColumn icons.

### ISSUE THREAD

**Issue by RickyCh** [gregnb/mui-datatables#211]
Tooltip works fine with Search, Print and download icons. But when the mouse hovers over filter icon, tooltip does not show up.

## Expected Behavior

Cursor hovers over filter icon, tooltip like "Filter Table" should show up.
## Current Behavior

Cursor hovers over filter icon, tooltip does not show up.

Example: https://codesandbox.io/embed/xowj5oj8w?autoresize=1&hidenavigation=1
## Steps to Reproduce (for bugs)

1. Move cursor on filter icon
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gregnb** [comment]
Seems to show up for me? What browser are you using?

![screen shot 2018-10-13 at 9 48 22 am](https://user-images.githubusercontent.com/19170080/46906156-25a52e80-cecd-11e8-9e84-f75bb9f635e1.jpg)

**Comment by RickyCh** [comment]
Hi. Thanks for your quick response. I am using Firefox 62.0.3 (64-bit), which cannot see the filter tooltip. 

But I just tried it with Chrome 69.0.3497.100, it works fine. Looks like some browser compatibility issue.

**Comment by PeterWolf91** [comment]
Hi everyone,
issue still exists in Firefox 63.0.03 for me.

@gregnb : By looking at your code in "mui-datatables/src/MUIDataTableToolbar.js" I see that you sometimes nest the Tooltip inside of IconButton and sometimes not. Can you please try for the Firefox users the following idea:

```jsx
{options.viewColumns ? (
            <MUIPopover refExit={this.setActiveIcon.bind(null)} container={tableRef}>
              <MUIPopoverTarget>
                <IconButton
                  aria-label={viewColumns}
                  classes={{ root: this.getActiveIcon(classes, "viewcolumns") }}
                  onClick={this.setActiveIcon.bind(null, "viewcolumns")}>
                  <Tooltip title={viewColumns}>
                    <ViewColumnIcon />
                  </Tooltip>
                </IconButton>
              </MUIPopoverTarget>
              <MUIPopoverContent>
                <MUIDataTableViewCol
                  data={data}
                  columns={columns}
                  options={options}
                  onColumnUpdate={toggleViewColumn}
                />
              </MUIPopoverContent>
            </MUIPopover>
          ) : (
            false
)}
```

to:

```jsx
{options.viewColumns ? (
            <MUIPopover refExit={this.setActiveIcon.bind(null)} container={tableRef}>
              <MUIPopoverTarget>
                <Tooltip title={viewColumns}>
                  <IconButton
                    aria-label={viewColumns}
                    classes={{ root: this.getActiveIcon(classes, "viewcolumns") }}
                    onClick={this.setActiveIcon.bind(null, "viewcolumns")}>
                      <ViewColumnIcon />
                  </IconButton>
                  </Tooltip>
              </MUIPopoverTarget>
              <MUIPopoverContent>
                <MUIDataTableViewCol
                  data={data}
                  columns={columns}
                  options={options}
                  onColumnUpdate={toggleViewColumn}
                />
              </MUIPopoverContent>
            </MUIPopover>
          ) : (
            false
)}
```

If this works for the viewColumns icon, it can be applied simultaneously for the filter icon as well. I would appreciate a short feedback. Thanks in advance.
