### ISSUE TITLE
CustomHeadRender does NOT render a component

### ISSUE THREAD

**Issue by hwatersiv** [gregnb/mui-datatables#213]
Thank you greg for creating this table to do really enjoy MUI-datatables it has made my life crazy easier.

The customHeadRender for the tables does not except a component as an argument. It currently is only accepting a string. 

The documentation says "Function that returns a string or React component. Used as display for column header. function(value, tableMeta, updateValue) => string|`"

I checked the module and added the '| ReactNode ' and tried to run it with a component without any luck,

## Expected Behavior
A component passed to the customHeadRender function should render a the component

## Current Behavior
customHeadRender when passed a component errors.

## Steps to Reproduce (for bugs)

1. Setup columns with at least one column with the customHeadRender option. with the following:
```
customHeadRender: (value: any, tableMetaData: any, updateValue: any) => (
                        <Input
                               defaultValue="Hello world"
                               className={classes.input}
                               inputProps={{
                                      'aria-label': 'Description',
                               }}  />
),
```

2. Setup data(rows) and options as normal for basic use of MUI-datatables.
3. Start the app.
4.  ---> Error: Type 'Element' is not assignable to type 'string'.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.2.0     |
| MUI-datatables  |    2.0.0-beta-32     |
| React        |    16.5.2     |
| browser      |    Chrome 69.0.3497.100     |
| etc          |    Typescript 3.1.1    |

**Comment by gregnb** [comment]
Ok let me look into this bug. Thanks for submitting

**Comment by diegochavez** [comment]
What that you mean with all data? the values? from the example table on column Salary you want all the values? I think you can get directly the values from data.map(item = item[indexOfColumn])?

**Comment by hwatersiv** [comment]
Sorry for the late reply all. I'd like to update everyone with this issue. I have tried this with the following ways:

```
customHeadRender: (value: any, tableMeta: any) => <div>custom Thing here</div>


customHeadRender: (value: any, tableMeta: any) => (<TableCell>custom Thing here</TableCell>)


customHeadRender: (value: any, tableMeta: any) => {
                        console.log("tableMeta head", tableMeta)
                        let i = 0;
                        return <TableCell key={i++} component="th">{value} custom Thing here</TableCell>
                    },
```

All of these failed  but the one that did work is @revskill10 's solution. I would say that this has resolved the issue. Sorry again for taking so long to get back to you all. Thanks for all of you for looking into it.

**Comment by gabrielliwerant** [comment]
Added PR to help address confusion around this issue here: https://github.com/gregnb/mui-datatables/pull/575
