### ISSUE TITLE
Expandable / child rows

### ISSUE THREAD

**Issue by patorjk** [gregnb/mui-datatables#214]
This project looks pretty cool. I was reading over the documentation but didn't see anything on expandable rows*. Is this something I missed, and if not, does this project plan to add expandable rows in the future?

* Example from jQuery DataTables project: https://datatables.net/examples/api/row_details.html

**Comment by gregnb** [comment]
hey @patorjk thanks for the feedback. As it stands right now I'm not so sure if I would add something like this but I'll add a community feedback tag and see what people think

**Comment by patorjk** [comment]
Sounds good. There's been discussion about it for the Angular2 datatable [1,2], though I can't tell if they've added it for it or not. If you decided to green-light it but don't have time yourself, let me know and I could look into creating a PR.

[1] https://github.com/angular/material2/issues/6095
[2] https://github.com/angular/material2/issues/5936

**Comment by marjan2k** [comment]
Something like this will be really helpful

**Comment by KamilKafara** [comment]
In my opinion will be really helpful, i will waiting for it ;)

**Comment by DTupalov** [comment]
Yes, this feature would be helpful. Right now we have tasks, that need expandable rows.

**Comment by Aaron-Lei** [comment]
There is an urgent need for this expandable table. Many thanks！！！

**Comment by rahulgupta97** [comment]
Great project! I have found it to be very useful and scalable. I do agree with the others on this one, having the ability to display data in a hierarchy manner while being able to still search/filter/export would be very helpful!

**Comment by gregnb** [comment]
I've added this feature in the latest release (beta-44) and the example usage is here:

https://github.com/gregnb/mui-datatables/blob/master/examples/expandable-rows/index.js

Thanks for everyone's patience

**Comment by MorganRoux** [comment]
Hello eveyone and congratulations for this repository :)
@gregnb , in your example the expandable row expands to just one more row. Is it possible to render multiples child instead of just one ?
An application would be using packages : rows are representing packages and when you expand them you see what there is inside the package.
Thank you for your help !
