### ISSUE TITLE
Feature Request: Filter supports partial match

### ISSUE THREAD

**Issue by RickyCh** [gregnb/mui-datatables#215]
## Expected Behavior

When a user selects a filter option, it will use partial match for the content in that column.

For example, filter option "apple" is selected for column "Items",  row with value "apple,orange,cherry" will also show up in the filtered result.

Would by very useful for use case like "Filter by Tag". For example, each row contains "Tag" field, a user can easily find records with a specific tag.

## Current Behavior

Currently, filter uses exact match to perform filter operation.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by VagnerNico** [comment]
I have a similar problem on my application, so cloned the repository and make tiny changes to filter logic that didn't brake actually existing tests, how can i contribute with this amazing project?

**Comment by gabrielliwerant** [comment]
@VagnerNico Thanks for your offer and your interest in the project!

There is a PR up here that I'm trying to get into the project which would provide the ability to add custom filters: https://github.com/gregnb/mui-datatables/pull/578. The addition of custom filter logic and filter names sounds like it might provide all the necessary functionality requested here.

My advice is to wait until this feature makes it into the project and see if it will satisfy your use case. If not, at that, point, you can open up a PR with your changes against the `master` branch.

**Comment by gabrielliwerant** [comment]
Custom filter logic is now possible in `2.4.0` via `filterOptions: { logic: function }`.
