### ISSUE TITLE
Sorting not working properly with real api

### ISSUE THREAD

**Issue by mehmetboraezer** [gregnb/mui-datatables#218]
## Expected Behavior

Hello, I expect configure the sort mechanism in **onTableChange** callback (with **sort action**) for real api. 

## Current Behavior

- Trigger api call from **onTableChange** callback (when come with **sort action**).
- Update data variable via `this.setState({data})` after get the new data from API.
- The table lose order direction (and symbol).
- When I click again to same column, it try again with same direction (not opposite). 

## Steps to Reproduce
I create reproduce demo on codesandbox -> https://codesandbox.io/s/pmypxp4l8x

1. Go to the codesandbox link
2. Open console
3. Try to use sorting via browser on any column
4. You can see issue from console logs and selected column behavior

### PS:

Now I'm also having the same issue **filter** feature. I guess somehow the table state is lost.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |      3.1.2   |
| MUI-datatables  |    2.0.0-beta-32     |
| React        |      16.5.2   |
| browser      |   Google Chrome OSX 69.0.3497.100 (Official Build) (64-bit)      |
| etc          |  -     |

**Comment by gregnb** [comment]
This is indeed a bug. Thanks for reporting I'll try to get to it when I have some time but I'll slap a tag on here incase anyone can pitch in

**Comment by gregnb** [comment]
Should have this resolved shortly. Pushed up a PR to fix this issue

**Comment by gregnb** [comment]
Published in the latest

**Comment by mehmetboraezer** [comment]
Yes it works, thank you @gregnb 👍

**Comment by ketankanhasoft** [comment]
Hello I am getting same issue used 2.0.0-beta-37
