### ISSUE TITLE
How to manage input value in column?

### ISSUE THREAD

**Issue by vantsymbalenko** [gregnb/mui-datatables#219]
I have case when one of the columns must be controled input... 
CodeSandbox - https://codesandbox.io/embed/wqrmj7410k
What is the best approach to manage value of this input?

**Comment by gregnb** [comment]
https://codesandbox.io/s/j7y248799y

How about that?

**Comment by vantsymbalenko** [comment]
> https://codesandbox.io/s/j7y248799y
> 
> How about that?

sorry but I don't see any changes only in dependencies was add lodash

**Comment by gregnb** [comment]
Ah damn, ok let me work on this example again. Sorry about that. I'll have some time this weekend

**Comment by aflansburg** [comment]
I was able to achieve this with customBodyRender in a column:
```
customBodyRender: (value, tableMeta, updateValue) => {
  return (
    <div>
      <input
        type="number"
        onBlur={event => {
          updateValue(event.target.value);
          // then you could call some function to update your state somewhere
          this.someFunctionToUpdateState({})
        }}
      />
    </div>
  );
}
```
The only issue is that I am unable to sort the table and have those input values stay in the correct row - I had it working at one point but something blew up and I must have obliterated my solution. I've tried setting `defaultValue` in the input prop, but no luck.

**Comment by gabrielliwerant** [comment]
@aflansburg The problem is that your inputs need a `value` or they will not be sorted properly, as there will be nothing to sort them on. I have a PR up with an updated example of some form inputs being added to a table.

**Comment by aflansburg** [comment]
@gabrielliwerant Yeah thanks, I just noticed that - so I was using onBlur as the onChange method causes rerendering of every row so typing in the input element was a bit laggy. If I can figure out a way to prevent rows without changed inputs from re-rendering it should kill the lag. I've moved to using a ref which seems to have helped so my component looks more like this now - in case anyone else comes across a similar use case:

```
<input
  ref={input}
  style={{ width: 60 }}
  type="number"
  value={requested || value}
  onChange={event => {
    updateValue(input.current.value);
    this.updateSomeArray({});
  }}
/>
```
