### ISSUE TITLE
More control over MUIDataTableToolbarSelect popping up...

### ISSUE THREAD

**Issue by JordanKadish** [gregnb/mui-datatables#22]
## Issue

I'd like to be able to change the top bar that renders when a row is selected (containing a trashbin icon and "x rows selected"), so instead of showing a delete icon, it will show a custom button I've made to do my own function. In other words, the onRowsSelect function should allow developers more control over what shows up when a checkbox is ticked.
 My reason for this:
  If I have users using this table, I'd like to prevent them from seeing/being able to delete rows in the table, but instead have my own options of what should happen when a row is selected. 

## Your Environment

| Tech         | Version |
|--------------|---------|
| mui-datatables  |    1.1.2     |
| node        |     9.2.1    |
| OS      |   Linux      |

**Comment by gregnb** [comment]
Hey @JordanKadish thanks the feedback. Your request aligns with another ticket #14 to allows developers controlled components. I'm first going to start by providing the callbacks so developers can at least build controlled components.

After that, I want combine tickets like these to see which customization of UI can be done in a way that makes sense to give even greater control.

**Comment by gregnb** [comment]
Closing this ticket because this is being looked at in #47 so follow there
