### ISSUE TITLE
How to fork and create Table export in pdf, xml and other format.

### ISSUE THREAD

**Issue by Preetam79** [gregnb/mui-datatables#225]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gregnb** [comment]
Out of scope for this library. Generating PDF's and Excels in the client is a big task. I'm not looking to bloat the library to that extent.
