### ISSUE TITLE
Please enable Download options for multi select rows in pdf, excel format.

### ISSUE THREAD

**Issue by Preetam79** [gregnb/mui-datatables#226]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gregnb** [comment]
Out of scope for this library. Generating PDF's and Excels in the client is a big task. I'm not looking to bloat the library to that extent.

**Comment by shawnmitchell** [comment]
@gregnb, Seems like the library could provide a prop for a callback that would pass the data back to an external library to handle the conversion. Would you be open to a pull request?

**Comment by gabrielliwerant** [comment]
@shawnmitchell There is a PR in progress here https://github.com/gregnb/mui-datatables/pull/501 that is working toward exposing a callback for the download option. Might want to see how that plays out first.

If you're stuck in the mean time, you can use the `customToolbar` option to provide your own download option.
