### ISSUE TITLE
When serverSide is true and using pagination, not able to override filterData values

### ISSUE THREAD

**Issue by hurt426** [gregnb/mui-datatables#227]
## Expected Behavior

When serverSide is true and using pagination, I should be able to override the filterData arrays so that I can filter the table with values that are not showing on the current page. I should be able to fill those values with a collection of distinct values that I retrieve from my datasource.

## Current Behavior

The filterData values are being filled only with data displayed from the current data values. If using serverSide pagination, there are most likely values that should be included in the filter lists that are not showing on the current page.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by Dragomir-Ivanov** [comment]
@hurt426 
So basically what we need is, a way to supply our own `filterData` instead of auto-generated from `mui-datatables`, right?

Maybe I can try add this.

**Comment by Dragomir-Ivanov** [comment]
Maybe `columns->options->filter` instead of only `true/false` can accept array of strings and generate the filter menu from these strings. How does it sounds @gregnb ?

**Comment by gregnb** [comment]
This is now available in the latest release. There are two column options `filterList` and `filterOptions`.  I have removed the `filterList` from the root level options and now they must be provided per column.

Look at the README for an example. Thanks for all your patience.

**Comment by loretoruiz** [comment]
Hello friends how are you ? I am using mui-datatables, I am adapting it to the React Hooks, I already bring data from my server and I am testing the paging but the paging buttons do not enable them and I do not know why? If you recognize the number of pages that I bring from my API ... if you can help me, I appreciate it. I leave you my source code.

**Comment by loretoruiz** [comment]
import React, { useState, useEffect } from "react";
import ReactDOM from "react-dom";
import reqwest from "reqwest";
import { CircularProgress, Typography } from "@material-ui/core";
import MUIDataTable from "mui-datatables";

export default function Example(props) {
  const [page, setPage] = useState(1);
  const [count, setCount] = useState(1);
  const [data, setData] = useState([["Loading Data..."]]);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    getData();
  });

  // get data
  const getData = (page = 1) => {
    setIsLoading(true);

    reqwest({
      url: `http://localhost:3000/api/musers/${page}`,
      method: "get",
      type: "json",
    }).then((data) => {
      setCount(data.total);
      setData(data.data);
      setIsLoading(false);
    });
  };

  const changePage = (page) => {
    setIsLoading(true);
    getData(page);
    setPage(page);
    // this.xhrRequest(`http://localhost:3000/api/musers/${page}`).then((res) => {
    //   this.setState({
    //     isLoading: false,
    //     page: page,
    //     data: res.data,
    //     count: res.total,
    //   });
    // });
  };
  /*********************** Cargar data ************************ */

  /*********************************************************** */

  const columns = ["ID_Users", "FirstName", "LastName", "Email"];
  //   const { data, page, count, isLoading } = this.state;

  const options = {
    filter: true,
    filterType: "dropdown",
    responsive: "stacked",
    serverSide: true,
    count: count,
    page: page,
    searchBox: true,
    pagination: {
      next: "Next Page",
      previous: "Previous Page",
      rowsPerPage: "Rows per page:",
      displayRows: "off",
    },
    onTableChange: (action, tableState) => {
      console.log(action, tableState);
      // a developer could react to change on an action basis or
      // examine the state as a whole and do whatever they want

      switch (action) {
        case "changePage":
          changePage(tableState.page);
          alert(page);
          break;
      }
    },
  };
  return (
    <div>
      <MUIDataTable
        title={
          <Typography variant="title">
            ACME Employee list
            {isLoading && (
              <CircularProgress
                size={24}
                style={{ marginLeft: 15, position: "relative", top: 4 }}
              />
            )}
          </Typography>
        }
        data={data}
        columns={columns}
        options={options}
      />
    </div>
  );
}
