### ISSUE TITLE
Would it be possible to get a new release?

### ISSUE THREAD

**Issue by GeeWee** [gregnb/mui-datatables#229]
We're getting quite a few outdated typography errors in our console.
The issue seems to have been fixed with #209, but no version has been released since.

Would it be possible to get a new release on npm?

**Comment by phelion** [comment]
I have the same problem, I'm waiting for that update very much too:)

**Comment by gregnb** [comment]
Take care of it today guys

**Comment by gregnb** [comment]
Try now guys

**Comment by JReinhold** [comment]
Hmm. that's weird. Just updated to mui-datatables@2.0.0-beta-33, and I haven't received the changes made to Typography made in #209, even though I have the changes made in package.json by that same PR.

To clarify, the content of `node_modules/mui-datatables/package.json` is:
```json
...
"devDependencies": {
    "@material-ui/core": "^3.2.0",
...
},
"peerDependencies": {
  "@material-ui/core": "^3.2.0",
...
```
which is the change introduced in #209.
However when I search for the offending variant `subheading` in the distributed file `node_modules/mui-datatables/dist/index.js` I still get plenty of results, which should have been removed by the PR.

Any idea of what's going on?

my `package.json`:
```json
"dependencies": {
		"mui-datatables": "^2.0.0-beta-33"
}
```
and my `yarn.lock`:
```
mui-datatables@^2.0.0-beta-33:
  version "2.0.0-beta-33"
  resolved "https://registry.yarnpkg.com/mui-datatables/-/mui-datatables-2.0.0-beta-33.tgz#2f1221aca86904f3db4483d9a8f96f5d514278fe"
  dependencies:
    classnames "^2.2.5"
    lodash.clonedeep "^4.5.0"
    lodash.get "^4.4.2"
    lodash.memoize "^4.1.2"
    lodash.merge "^4.6.0"
    prop-types "^15.6.0"
    react-to-print "^1.0.10"
```

**Comment by phelion** [comment]
It doesn't work for me neither

**Comment by gregnb** [comment]
Yes, this is what happens when you publish without building first. It's too early in the morning for me LOL.

-34 published. Try again guys. Sorry

**Comment by phelion** [comment]
Nice, now it's working, thank you! :)

**Comment by Legogris** [comment]
@gregnb Same problem with current `2.0.0-beta-39`:
```
Warning: Failed prop type: You are using a deprecated typography variant: `subheading` that will be removed in the next major release.
Please read the migration guide under https://material-ui.com/style/typography#migration-to-typography-v2
    in Typography (created by WithStyles(Typography))
    in WithStyles(Typography) (created by l)
...
```
Verified that it's mentioned nowhere in sourcecode but in index.js of tgz on npm.

**Comment by GoktuqCan** [comment]
@gregnb Same problem mentioned by @Legogris remains in current `2.0.0-beta-45`
