### ISSUE TITLE
Error loading array of objects - Bug or New Feature needed?

### ISSUE THREAD

**Issue by tolyan28** [gregnb/mui-datatables#23]
## Config
import React from 'react';
import ReactDOM from "react-dom";
import MUIDataTable from "mui-datatables";

class App extends React.Component {

  render() {

    const columns = ["Name", "Title", "Location", "Age", "Salary"];

    const data = [
      {name: "Gabby George", title: "Business Analyst", location: "Minneapolis", age: 30, salary: "$100,000"}      
    ];

    const options = {
      filterType: 'dropdown',
      responsive: 'stacked'
    };

    return (
      <MUIDataTable 
        title={"ACME Employee list"} 
        data={data} 
        columns={columns} 
        options={options} 
      />
    );

    //return <div>a</div>;

  }

}

ReactDOM.render(<App />, document.getElementById("root"));

## Issue
First of all - Thanks for the great component! Works very well with data as array of strings (as documentation says). However I'm very surprised that it doesn't work with array of objects loaded from the back-end. 
"Uncaught (in promise) TypeError: e.map is not a function"

I was able to create a simple MUI table component that works fine with array of data. However yours is way more advanced and I would love to use it for my project. 
Is this a bug or I'm missing something as I'm still learning react? Or it's simply not implemented yet as both - documentation and examples specifically say array of simple strings. Do I really need to convert my data to array of simple strings? 

## Your Environment

| Tech         | Version |
|--------------|---------|
| mui-datatables  |       1.1.2  |
| node        |     6.11.13    |
| OS      |      Win7   |

**Comment by gregnb** [comment]
hey @tolyan28 thanks for the feedback. What you should do is the following:

```
const columns = ["Name", "Title", "Location", "Age", "Salary"];

const data = [
  ["Gabby George", "Business Analyst", "Minneapolis", 30, "$100,000"]
];

const options = {
  filterType: 'dropdown',
  responsive: 'stacked'
};

return (
  <MUIDataTable 
    title={"ACME Employee list"} 
    data={data} 
    columns={columns} 
    options={options} 
  />
);

//return <div>a</div>;
```

The data prop can only take in an array of arrays

**Comment by tolyan28** [comment]
@gregnb - thanks for reply! I know that and it works great that way. I have modified it to feed the structure similar to what I have. It's too bad - I would think it would be a very viable feature. But at least now I know I don't miss anything.

**Comment by whimsicaldreamer** [comment]
@gregnb I know this issue is closed but I am having problem pulling in data saved in the react state.

```render() {
        const columns = [
            {
                name: "name",
                label: "Applicant Name",
                options: {
                    filter: true,
                    sort: true,
                    customBodyRender: (value, tableMeta, updateValue) => {
                        return (
                            <Applicant
                                value={value}
                                index={tableMeta.columnIndex}
                                change={event => updateValue(event)}
                            />
                        )
                    }
                }
            },
            {
                name: "applicationId",
                label: "Application Id",
                options: {
                    filter: true,
                    sort: false,
                }
            },
            {
                name: "dob",
                label: "D.O.B",
                options: {
                    filter: true,
                    sort: false,
                }
            },
            {
                name: "mobile",
                label: "Mobile",
                options: {
                    filter: true,
                    sort: false,
                }
            },
            {
                name: "applicationDate",
                label: "Application Date",
                options: {
                    filter: true,
                    sort: false,
                }
            },
        ];

        const data1 = [
            {
                applicationId: "6GDIpvXwu",
                applicationDate: 1552060981517,
                name: "Test",
                gender: "Male",
                dob: "2019-03-06",
                fname: "aass",
                mname: "dsd",
                address: "fdgd",
                district: "dfgfd",
                state: "sdfsd",
                pin: "",
                email: "",
                mobile: "dfgdfgfd",
                photo: "53e2873c-45a0-426e-ae0d-628a9ef3e3bd.jpg",
                birthCertificate: "4e5944bc-c74c-4f53-9d26-15450eb47d4e.png",
                "$loki": 1
            }
        ];

        const options = {
            filter: false,
            print: false,
            download: false,
            selectableRows: false,
            viewColumns: false
        };

        return (
            <Fragment>
                <div className="tableList">
                    <MUIDataTable
                        title={"Applicant List"}
                        columns={columns}
                        data={data1}
                        options={options}
                    />
                </div>
            </Fragment>
        )
```

The above snippet with hard coded data works fine. But as soon as I pull in the data from the state(fetched from api which returns json) it breaks. I keep getting: `TypeError: t is null`
