### ISSUE TITLE
How do I show all rows?

### ISSUE THREAD

**Issue by sidney61498** [gregnb/mui-datatables#234]
I've just been and searching and can't seem to find any solution.

**Comment by serv** [comment]
What happens when you disable `pagination` by setting it false?

**Comment by sidney61498** [comment]
It shows the set value of "rowsPerPage" option.

**Comment by sidney61498** [comment]
What can I do so that the page scrolls when I scroll on the table.

**Comment by JReinhold** [comment]
Based on this comment: https://github.com/gregnb/mui-datatables/issues/65#issuecomment-390922124 it seems that the only way to do it, is setting `rowsPerPage` to a ridiculously high number.

**Comment by sidney61498** [comment]
Thanks. ❤

**Comment by sidney61498** [comment]
close #234

**Comment by jlei523** [comment]
Override this with createMuiTheme
```

   MUIDataTable: {
      responsiveScroll: {
        maxHeight: "100%"
      }
    },
```

**Comment by JReinhold** [comment]
As of [V2.10.0](https://github.com/gregnb/mui-datatables/tree/2.10.0) it is now possible to use the prop `responsive="scrollFullHeight"` to make the table full height and a scroll behavior at the same time. That should fix the issue.

See https://github.com/gregnb/mui-datatables/pull/867
