### ISSUE TITLE
How use a colunm title different of colunm name

### ISSUE THREAD

**Issue by henfreire** [gregnb/mui-datatables#237]
I want use a different name for title and name. That are possible?

Something like: 
	const column = [
		{
            name: 'columnName',
            title: 'Column Title',
			options: {
				filter: true,
				sort: true,
				display: true
			}
		}
}
]

**Comment by Kadrian** [comment]
I have the same issue. Tried `customHeadRender`, but that's way too much when I simply want to replace the text

**Comment by henriquefreire** [comment]
Thank you. It worked.

**Comment by Kadrian** [comment]
How did you make it work?

**Comment by gregnb** [comment]
this is available by using the `label` property: 

```
    const columns = [
      {
        name: "name",
        label: "Name",
    ];
```
