### ISSUE TITLE
Horizontal Scroll Bar is Missing in Chrome

### ISSUE THREAD

**Issue by RickyCh** [gregnb/mui-datatables#240]
In Chrome, when the table responsive is set to "scroll", the horizontal scroll bar within the table is missing.

## Expected Behavior

Firefox(60.2.2esr (64-bit)) works fine with horizontal scroll bar. 
So the expected behavior in Chrome would be when a user clicks on the table, the horizontal scroll bar within the table shows up.
## Current Behavior

In Chrome, when I tried to scroll the table horizontally, I cannot make the horizontal scroll bar show up.
## Steps to Reproduce (for bugs)

1. Set table responsive to "scroll"
2. Open the website with Chrome.
3. Try to scroll the table horizontally.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     2.0 beta 36    |
| MUI-datatables  |         |
| React        |         |
| browser      |    Chrome Version 70.0.3538.77 (Official Build) (64-bit)    |
| etc          |         |

**Comment by evanega3** [comment]
Hey, everybody, can you give us an update on this? I have the same issue.

**Comment by gregnb** [comment]
Can anyone verify if this is still an issue?

**Comment by yeahoffline** [comment]
table width with responsive does not work it seems. Same issue with chrome and safari

**Comment by andresf01** [comment]
In 2.0.0-beta-52 version the scroll is working fine

**Comment by shubhamk54** [comment]
The issue persists in v: 2.0.0-beta.58, any updates would be helpful,
meanwhile, I'm digging down, will update the solution if I had.

**Comment by gabrielliwerant** [comment]
@shubhamk54 That version of the library is no longer supported. Try upgrading and seeing if that helps.

**Comment by artivilla** [comment]
If the number of columns in my table take up more space than the table container, I'm applying the `  responsive: 'scrollFullHeight',` and `MUIDataTable { responsiveScrollFullHeight: { overflowX: 'scroll' } }` styles to get the table to scroll horizontally. Is there a way to persist the scroll bar to indicate the table can scroll.

**Comment by gabrielliwerant** [comment]
@artivilla Do you mean, show a scroll bar even when the table cannot actually scroll? If so, try `overflow-x: scroll`.

**Comment by gabrielliwerant** [comment]
This issue is old and likely out of date since responsive options have changed quite a bit. Closing this issue.
