### ISSUE TITLE
Title duplicated on the extreme left

### ISSUE THREAD

**Issue by giovanisleite** [gregnb/mui-datatables#241]
The table title appears duplicated because of this two pieces of code([here](https://github.com/gregnb/mui-datatables/blob/d7bcb0191e22973729d4ec964b3ac1d5725e67bc/src/MUIDataTable.js#L23) and [here](https://github.com/gregnb/mui-datatables/blob/d7bcb0191e22973729d4ec964b3ac1d5725e67bc/src/MUIDataTable.js#L837)):

```javascript
 caption: {
    position: "absolute",
    left: "-1000px",
},
```

```javascript
<caption className={classes.caption}>{title}</caption>
```

## Expected Behavior
This second appearance of the title shouldn't happen

## Current Behavior
I suggest the removal `caption-title piece` and I would be happy to do it, but before I want to understand why it is there (maybe there is a reason and needs a more complex solution).

## Steps to Reproduce (for bugs)

1. Just zoom-out the table

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.1.4     |
| MUI-datatables  |    2.0.0-beta-36     |
| React        |   16.4.1      |
| browser      |    chrome & firefox     |

**Comment by gregnb** [comment]
It is there for accessibility purposes so when a screen reader goes over the table it has a caption to read. I think a compromise to this is to set the position even further. I'm going to move it to -3000

**Comment by giovanisleite** [comment]
Thanks, @gregnb

**Comment by yaminyaylo** [comment]
this cause issue has an issue in Firefox scroll
<img width="1258" alt="Screenshot 2021-12-06 at 20 48 59" src="https://user-images.githubusercontent.com/1785530/144904358-876dff25-4e48-41da-9d5f-59d6f7f03d06.png">

**Comment by giovanisleite** [comment]
A good approach to solve this can be the strategy used by @joshwcomeau on this [snippet (https://www.joshwcomeau.com/snippets/react-components/visually-hidden/)](https://www.joshwcomeau.com/snippets/react-components/visually-hidden/)

**Comment by yaminyaylo** [comment]
> snippet (https://www.joshwcomeau.com/snippets/react-components/visually-hidden/)

thanks a lot, 
in my case, I've just fixed it by adding
`
top: 0
`
for MUIDataTable override file.

<img width="637" alt="Screenshot 2021-12-06 at 21 09 22" src="https://user-images.githubusercontent.com/1785530/144907093-11d46d9b-116f-4a47-b71b-0598b660b38a.png">
g
