### ISSUE TITLE
[Bug][Per page] Page is greater than the total available

### ISSUE THREAD

**Issue by DTupalov** [gregnb/mui-datatables#242]
There is an exception, when I try to change "per page" option in the MUITable at the last page (data length equals to 29, and we change per page from 10 items to 15 items, and expect total 2 pages, but got the exception: ```Provided options.page of `2` is greater than the total available page length of `1` ```)
Btw, if data length equals to 30, there are no exceptions in this case.

Such problem already have been solved at #48, but seems not at all.
 

## Expected Behavior

We don't have an exception, and can see 2 pages with our data

## Current Behavior

We have exception on display ```Provided options.page of `2` is greater than the total available page length of `1` ```

## Steps to Reproduce (for bugs)

Live example: https://codesandbox.io/s/6vlml849zk

1. Go to last page (page number 3)
2. Change option "per page" from "10" to "15"
3. Boom!

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    1.4.0     |
| MUI-datatables  |     ^2.0.0-beta-32    |
| React        |    16.5.0     |
| browser      |    Chrome     |

**Comment by gregnb** [comment]
Ok, thanks for noting the bug. Would you like to work on the issue and send in a PR?

**Comment by DTupalov** [comment]
@gregnb I can try to solve this problem :)

**Comment by DTupalov** [comment]
@gregnb when this bugfix will be release? I need it in my project, thx )
