### ISSUE TITLE
[Feature Request] Fixed Header

### ISSUE THREAD

**Issue by GeeWee** [gregnb/mui-datatables#243]
I'd like to be able to use mui-datatables with a fixed header that stays at the top while the body can scroll independently of it.

I'd be willing to submit a PR if it would be accepted. The feature would probably be implemented through something like this: https://codepen.io/nikhil8krishnan/pen/WvYPvv
(e.g. making another table, just for the header row and positioning that at the top. It's a little ugly but it seems to be the way to do it when using tables)

Would a PR like this be accepted?

**Comment by DTupalov** [comment]
I think it's already done in #235, just waiting new release

**Comment by GeeWee** [comment]
Looks like it! Halleluja!

**Comment by GeeWee** [comment]
Actually, it seems like #235 only fixes the Header, but I need the Toolbar to be fixed as well - I guess I'll keep this open for now.

**Comment by gregnb** [comment]
It's been released. if you want to open a ticket about having a fixed toolbar please open that separate as the fixed header is now implemented.

**Comment by aneekroy** [comment]
Is the fix working because when I added the fixedHeader option in the demo tables it is still not working as expected

**Comment by tonymckendry** [comment]
Not working for me either.

**Comment by gregnb** [comment]
Please try using the latest release it should now be resolved re: fixedHeader option

**Comment by tonymckendry** [comment]
@gregnb I'm on version 2.0.0-beta-43. I have my datatable component inside a scrollable div but when I scroll, the header and toolbar scroll off of the top of the screen still. Am I missing something?

**Comment by tonymckendry** [comment]
@gregnb apologies as it seems to be working now (not really sure what the deal was). With it enabled I am having a really hard time adjusting the height of the scrollable area of the component - I may just not be targeting the right thing with my style overrides. If I do this: 
```
const theme = {
    overrides: {
        MUIDataTable: {
            responsiveScroll: { height: scrollHeight }
        }
    }
}
```

I can make the scrollable area shorter than the default height by setting it to a small number, but any number that is larger seems to have no effect

**Comment by tonymckendry** [comment]
Seems that there is a maxHeight style of 499px applied to the `responsiveScroll` for some reason. Overriding the maxHeight fixes my issue. Might I suggest removing that style? I'd be happy to do a PR, unless there's some good reason for it.

**Comment by gregnb** [comment]
There needs to be some fixed height for a scroll bar to show

**Comment by tonymckendry** [comment]
Maybe some logic to set the maxHeight to the same as the height? It seems wrong to arbitrarily lock that value at 499px.

**Comment by mocabi** [comment]
@tonymckendry Replacing 'height' with 'maxHeight' did a trick for me.

const theme = {
    overrides: {
        MUIDataTable: {
            responsiveScroll: { **maxHeight**: scrollHeight }
        }
    }
}
