### ISSUE TITLE
Upgrade Typography to v2

### ISSUE THREAD

**Issue by nikhilem** [gregnb/mui-datatables#245]
## Expected Behavior

Since `Typography` implementation was upgraded to v2 in Material UI v3.2.0, we get deprecation warnings because of `Typography` components with old variants used within MUI-Datatables

## Current Behavior

This should be fixed by using new variants of `Typography` as described [here](https://material-ui.com/style/typography/#migration-to-typography-v2)

## Steps to Reproduce (for bugs)

Upgrade to latest version of Material UI to see deprecation warnings being logged in the console

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     3.3.2    |
| MUI-datatables  |     2.0.0-beta-24    |
| React        |    16.5     |
| Browser      |     Chrome    |

**Comment by ajzeigert** [comment]
Could this be done by simply replacing all of the old references with the v2 references? Or would that break backward compatibility?

**Comment by gregnb** [comment]
I will bring this change in when I prep the last beta release for mui-datatables

**Comment by gregnb** [comment]
I've decided to merge in a PR that brings us towards this move. There is still some edits that need to be made though
