### ISSUE TITLE
Table headers block toolbars or other dropdowns

### ISSUE THREAD

**Issue by hwatersiv** [gregnb/mui-datatables#247]
## Expected Behavior

Toolbars should expand over the headers to the table
## Current Behavior

Table headers appear over dropdowns
## Steps to Reproduce (for bugs)

1. Create a custom toolbar with a dropdown and populate options that exceed the well below the header
2. Populate some data with headers.
3. Open the dropdown. 
4. Observe the drop down appears behind the the headers

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     3.3.2    |
| MUI-datatables  |     2.0.0-beta-37    |
| React        |    16.6.0     |
| browser      |    Chrome  69.0.3497.100   |
| etc          |    Typescript   2.0.4   |

![headeroverlap](https://user-images.githubusercontent.com/6393400/47756205-67b8c900-dc5e-11e8-9b28-df6a56b0298d.png)

**Comment by gregnb** [comment]
Just give your dropdown a higher zIndex then the header columns

**Comment by hwatersiv** [comment]
well it seems I am a moron. I thought I tried this and previous cases did not work (guess it wasn;t higher than the header). What  did do was max the z-index for 64 chrome (2147483647). worked as you said. Thanks, sorry for wasting your time.

**Comment by mrantry** [comment]
I'm running into a similar problem, but unfortunately I don't control the component that is being overlapped. Is there a way to control the z-index of the header directly?
<img width="1280" alt="Screen Shot 2021-03-11 at 9 21 38 AM" src="https://user-images.githubusercontent.com/23426633/110811077-fc2e8f80-824b-11eb-9aea-6bf5ec354bd4.png">

**Comment by DaniGB1** [comment]
If it is a React Select add the following style, it worked for me

<Select
  styles={{
    // Fixes the overlapping problem of the component
    menu: provided => ({ ...provided, zIndex: 9999 })
  }}
  value={selectedOption}
  onChange={evt => onSelectChange(evt, index)}
  options={options}
/>
