### ISSUE TITLE
Filter toolbar rerenders after first change

### ISSUE THREAD

**Issue by ocetnik** [gregnb/mui-datatables#252]
Filter toolbar rerenders after first change

## Expected Behavior
After select first option in a filter is toolbar not closed and reopened.

## Current Behavior
After select first option in a filter is toolbar closed and reopened. After selecting some other opinions works correctly.

## Steps to Reproduce (for bugs)
Check https://codesandbox.io/s/wy2rl1nyzl

1. open filter
2. select some option
3. filter toolbar is closed and reopened
4. select some other option
5. filter toolbar is not closed and reopened

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   3.2.2      |
| MUI-datatables  |    2.0.0-beta-35     |
| React        |     16.4.0    |
| browser      |     Chrome 70    |

**Comment by gregnb** [comment]
Thanks for finding the issue. I'm really busy at the moment and would love some help solving this one
