### ISSUE TITLE
Styling based on data content

### ISSUE THREAD

**Issue by murraypurves** [gregnb/mui-datatables#256]
Is it possible to set the styling of individual cells based on their content?

In my specific use case, I would like to be able to set the color of data cells (and/or their text) based on their value, e.g. a traffic-light style denoting 'good' (green), 'ok' (orange), 'bad' (red). The data/style requirement would not change once the data is loaded.

I have tried to do it through `createMuiTheme` but to no avail - is it possible to do?

**Comment by DTupalov** [comment]
You can use [`customBodyRender`](https://github.com/gregnb/mui-datatables#column-options), which receives value of current cell, and you can return your own Component

See the example
https://codesandbox.io/embed/xrvrzryjvp?autoresize=1&hidenavigation=1

**Comment by murraypurves** [comment]
Thank you so much! This is working for me now (at least when I work out how set the background of the whole cell, not just the text).

**Comment by raviteja8k** [comment]
@murraypurves Can you share your code on how you set text color based on cell value. Thanks.

**Comment by murraypurves** [comment]
@raviteja8k I used `customBodyRender` as described above to return a cell component that changes the text background based on the cell value.

The component:

```jsx
class QualityCell extends Component {
  static propTypes = {
    value: PropTypes.string.isRequired,
    index: PropTypes.number.isRequired,
    change: PropTypes.func.isRequired
  };

  render() {
    const { value, index, change } = this.props;
    const colors = {
      "green": "#00ff00",
      "yellow": "#ffff00",
      "red": "#ff0000",
      "grey": "#B0B0B0"
    }

    let backgroundColor = colors.grey;
    if (value === "good") {
      backgroundColor = colors.green;
    } else if (value === "ok") {
      backgroundColor = colors.yellow;
    } else if (value === "bad") {
      backgroundColor = colors.red;
    }

    return (
      <p
        value={value}
        onChange={event => change(event.target.value, index)}
        style={{ backgroundColor: backgroundColor }}>{value}</p>
    )
  }
}
```

And the relevant column in the datatable:

```jsx
{ name: "quality",
        options: {
          customBodyRender: (value, tableMeta, updateValue) => {
            return (
              <QualityCell
                value={value}
                index={tableMeta.columnIndex}
                change={event => updateValue(event)}
              />
            )
          }
        }
      },
```

**Comment by raviteja8k** [comment]
@murraypurves Thanks for the code. Mine was bit primitive with multiple return() 's but updated the code based on yours.

**Comment by giancarlobianchi12** [comment]
> @raviteja8k I used `customBodyRender` as described above to return a cell component that changes the text background based on the cell value.
> 
> The component:
> 
> ```js-jsx
> class QualityCell extends Component {
>   static propTypes = {
>     value: PropTypes.string.isRequired,
>     index: PropTypes.number.isRequired,
>     change: PropTypes.func.isRequired
>   };
> 
>   render() {
>     const { value, index, change } = this.props;
>     const colors = {
>       "green": "#00ff00",
>       "yellow": "#ffff00",
>       "red": "#ff0000",
>       "grey": "#B0B0B0"
>     }
> 
>     let backgroundColor = colors.grey;
>     if (value === "good") {
>       backgroundColor = colors.green;
>     } else if (value === "ok") {
>       backgroundColor = colors.yellow;
>     } else if (value === "bad") {
>       backgroundColor = colors.red;
>     }
> 
>     return (
>       <p
>         value={value}
>         onChange={event => change(event.target.value, index)}
>         style={{ backgroundColor: backgroundColor }}>{value}</p>
>     )
>   }
> }
> ```
> 
> And the relevant column in the datatable:
> 
> ```js-jsx
> { name: "quality",
>         options: {
>           customBodyRender: (value, tableMeta, updateValue) => {
>             return (
>               <QualityCell
>                 value={value}
>                 index={tableMeta.columnIndex}
>                 change={event => updateValue(event)}
>               />
>             )
>           }
>         }
>       },
> ```

Thts ok ! But, if this values, as color and more, came from backend, how can I access to these values ? I can set only the value of the cell but not more data like color or other

**Comment by gabrielliwerant** [comment]
@giancarlobianchi12 You could create a separate metaData object that maps to each cell via the data index of the row:

```
const metaData = {
  '0': [{ color: 'green', tag: 'helpful' }, { color: 'blue', tag: 'question' }, ... ],
  '1': [{ color: 'green', tag: 'helpful' }, { color: 'blue', tag: 'question' }, ... ],
  '2': [{ color: 'green', tag: 'helpful' }, { color: 'blue', tag: 'question' }, ... ],
  '3': [{ color: 'green', tag: 'helpful' }, { color: 'blue', tag: 'question' }, ... ],
};

const data = [
  ["Gabby George", "Business Analyst", "Minneapolis", 30, "$100,000"],
  ["Aiden Lloyd", "Business Consultant", "Dallas",  55, "$200,000"],
  ["Jaden Collins", "Attorney", "Santa Ana", 27, "$500,000"],
  ["Franky Rees", "Business Analyst", "St. Petersburg", 22, "$50,000"],
];

...

// metaData[0][1] corresponds to dataIndex 0, column 2 (first row, second column cell)
```

**Comment by lucbas** [comment]
Hi

Is it possible to style the entire row or other cells in the row based on the content of a specific cell?

For example, I would like to apply other styles to a row where the status cell equals “Alert”. 

Thank you all! 👍🏼😄

**Comment by gabrielliwerant** [comment]
@lucbas `customRowRender` is probably what you want. It provides the data for the entire row, which you can use to check each cell, and then style the custom row component accordingly.
