### ISSUE TITLE
Default sort not working if serverSide is set true.

### ISSUE THREAD

**Issue by geekashu** [gregnb/mui-datatables#257]
I do not want to write a custom sort function for my remote API. Currently, it seems I am not allowed to do the default sorting in ascending or descending order when serverSide is true. The problem seems to be at this line. https://github.com/gregnb/mui-datatables/blob/4dd2cf79088680e2d8e9088c7fce1df9f4dfd204/src/MUIDataTable.js#L519

Can we enable the default sort option so that it should work for simple sorting unless and until specifically caught by `sort` table action via `onTableChange`?

**Comment by gregnb** [comment]
As it stands now I don't think so because it would be confusing to say that the table is going into serverSide mode meaning all the sorting/filtering is the responsibility of a remote API but to then have this grey area where certain features aren't serverSide
