### ISSUE TITLE
Render without Card?

### ISSUE THREAD

**Issue by kylane** [gregnb/mui-datatables#258]
Seems to be no option to render the component without a Card?

## Expected Behavior

Would like an option to customize the base component to even be a react fragment to render inline inside other cards etc.
## Current Behavior

Can only render with its own card

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  3.2       |
| MUI-datatables  |   2.0.0-beta-37      |
| React        |   16.3.2      |
| browser      |   any      |
| etc          |         |

**Comment by gregnb** [comment]
I'll add this feature. it will be a new option called `paper` and default true

**Comment by marco270** [comment]
I see that the implementation uses the Paper Material UI Component. Wouldn't it be better to have an elevation option? Where 0 = no elevation and no shadow. Default should be 4

**Comment by gregnb** [comment]
In the latest version there is now an option called `elevation` which you can set to 0 to hide the default elevation provided to the Paper component.
