### ISSUE TITLE
Is there a feature to reverse the filters? 

### ISSUE THREAD

**Issue by sidney61498** [gregnb/mui-datatables#262]
## Expected Behavior
For example I have a column: Trainings Attended and I want to see those who hasn't attended the English Proficiency training yet. Is there a workaround where when I filter the English Proficiency training it will show the rows where it doesn't have English Proficiency training?

**Comment by gabrielliwerant** [comment]
As of `2.4.0` you can create custom filter logic per column via `filterOptions: { logic: function }`.
