### ISSUE TITLE
How can I add buttons in the MUITableFooter without losing Pagination and Count

### ISSUE THREAD

**Issue by nathpree** [gregnb/mui-datatables#265]
Dear Author,

I want to add a button in the MUI Table footer without losing the existing pagination and count features.Could you please provide me suggestions or directions. CustomFooter overides the existing feature totally. I want to extend the MUIDataTablePagination and add extra buttons.
I plan to implement this button by myself, which will redirect the user with all table data to a different page.

Regards,

Preetam

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by nathpree** [comment]
I want the behavior similar to the customToolbar but in the CustomFooter.

**Comment by DTupalov** [comment]
@nathpree there is no way to set customFooter and save existing pagination. But you can reproduce it with passed functions and components from material-ui, example:

```js
customFooter: (count, page, rowsPerPage, changeRowsPerPage, changePage) => (
  <TableFooter>
    <TableRow>
      <TablePagination
        count={count}
        rowsPerPage={rowsPerPage}
        page={page}
        onChangePage={(_, page) => changePage(page)}
        onChangeRowsPerPage={event => changeRowsPerPage(event.target.value)}
        rowsPerPageOptions={[10, 15, 100]}
      />
    </TableRow>
  </TableFooter>
);
```

see more documentation about customizing `TablePagination` here
https://material-ui.com/demos/tables/#custom-table-pagination-action

**Comment by nathpree** [comment]
@DTupalov  Thank you very much for your suggestions. It works.
https://codesandbox.io/s/1opz3jp7ql

**Comment by beerwin** [comment]
@nathpree You can remove the extra TableCell around the pagination, as it supplies its own. That way you can drop the styling as well.

**Comment by Mohammad-Eshtaiwi** [comment]
> @DTupalov Thank you very much for your suggestions. It works. https://codesandbox.io/s/1opz3jp7ql

Thank you
