### ISSUE TITLE
[Enhancement][RFC] Pass function for managing selected rows in customToolbarSelect 

### ISSUE THREAD

**Issue by DTupalov** [gregnb/mui-datatables#266]
We have opportunity to use `mui-datatables` as controlled component to set selected rows with `rowsSelected` and `onRowsSelect`. Either I can use it in uncontrolled `mui-datatables`, when I select rows and it keeps in state of component. But if I use `customToolbarSelect`, and receive my selected rows, I don't have any chance to manage those selected rows except to make component from uncontrolled without `rowsSelected` to controlled with `rowSelected`. But it is antipattern, for example, React give a warning in console, if you change `defaultValue` to `value` in one lifecycle on `input` element.

So, I propose to pass some function, e.g. `setSelectedRows` to `customToolbarSelect`, that will give us opportunity to manage selected rows in uncontrolled component.

```js
options: {
  customToolbarSelect: (rowsSelected, setSelectedRows) => {
    // do something with rowsSelected
    ...
    // then flush selected rows
    setSelectedRows([]);
  }
}
```

## Expected Behavior

I can manage selected rows (e.g. flush them), when using `customToolbarSelect` in uncontrolled component

## Current Behavior

I can't do anything with selected rows, when using `customToolbarSelect` in uncontrolled component
## Steps to Reproduce (for bugs)

Official example with `customToolbarSelect`
https://codesandbox.io/embed/545ym5ov6p

1. Select row
2. Click on any icon
3. You can't flush selections, or do anything with it, except to make component controlled and pass to it `rowsSelected`. But it is antipattern.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    1.4.0     |
| MUI-datatables  |   2.0.0-beta-38     |
| React        |    16.5.0     |
| browser      |   Chrome      |

**Comment by gregnb** [comment]
Sounds very reasonable. If you want to take this PR up with unit tests I'm more than happy to accept

**Comment by DTupalov** [comment]
OK, I'm in :)
