### ISSUE TITLE
[Bug] Option rowsPerPage flush when using controlled selected rows

### ISSUE THREAD

**Issue by DTupalov** [gregnb/mui-datatables#267]
When using `mui-datatables` with controlled selected rows (pass `rowsSelected` and `onRowsSelect`) there is problem, when we change rows per page and then select row, option rows per page sets to default value 

## Expected Behavior

Rows per page don't flush to default values

## Current Behavior

Rows per page flush to default values

## Steps to Reproduce (for bugs)

Live example: https://codesandbox.io/embed/pm225rwwjx

1. Change rows per page from 10 to 15
2. Select some row with checkbox
3. Boom! Rows per page flush to default value - 10

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    1.4.0     |
| MUI-datatables  |   2.0.0-beta-38     |
| React        |    16.5.0     |
| browser      |   Chrome      |

**Comment by DTupalov** [comment]
There is a workaround to fix this problem.
You can pass rowsPerPage and onChangeRowsPerPage, and component mui-datatables will use them. 

Example
https://codesandbox.io/embed/jjo6wr45r3

**Comment by gabrielliwerant** [comment]
This issue has been fixed and should no longer be present in `2.4.0`.
