### ISSUE TITLE
Render without Toolbar when no options are true?

### ISSUE THREAD

**Issue by kylane** [gregnb/mui-datatables#268]
When all options for the toolbar are set to false, the toolbar still renders as empty and takes up alot of dom space.

## Expected Behavior

If all toolbar options are false, then no toolbar should render - or a prop to disable it should be available.
## Steps to Reproduce (for bugs)

![screen shot 2018-11-12 at 4 15 29 pm](https://user-images.githubusercontent.com/8296041/48329955-a5721480-e696-11e8-9864-3ea075a42599.png)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  3.2       |
| MUI-datatables  |  2.0.0-beta-37       |
| React        |  16.3.2       |
| browser      |     Any    |
| etc          |         |

**Comment by gregnb** [comment]
Do you wish to submit a PR for this?

**Comment by kylane** [comment]
Ill give it a go @gregnb - never submitted one before, but always willing to have a go :)

**Comment by jlei523** [comment]
Would love this!

**Comment by jlei523** [comment]
As a workaround, you can just do this with createMuiTheme

`const theme = createMuiTheme({
  overrides: {
    MuiToolbar: {
      root: {
        display: "none"
      }
    }
  }
});`

**Comment by heinekeg** [comment]
To hide just the datatable toolbar
`const theme = createMuiTheme({overrides: { MUIDataTableToolbar: { root: { display: 'none' } } }})`

**Comment by gabrielliwerant** [comment]
It's been quite a while, so I opened a PR for this here: https://github.com/gregnb/mui-datatables/pull/564.

**Comment by gabrielliwerant** [comment]
Fixed in latest `2.0.0-beta.59`.

**Comment by phanvantien270290** [comment]
I found a way to hide it in the elements you want
required Material v5+;
`
const ListViewWrapper = styled(MuiDataTables)(({ theme}) =>
({
    '& .MuiToolbar-root': {
        display: "none"
    }
})

  const ListView: React.FC<IListView> = (props) => {
      return <ListViewWrapper {...props} />
  }
);
`

**Comment by smooth-lee** [comment]
The above didn't work for me in the latest version, so here's how I solved it.

`<MUIDataTable
          title={''}
          columns={columns}
          data={data}
          components={{
            TableToolbar(props) {
              return null;
            },
          }}/>`
