### ISSUE TITLE
Use MUI breakpoint tools

### ISSUE THREAD

**Issue by mpareja** [gregnb/mui-datatables#269]
The responsive breakpoints are hard-coded rather than relying on MUI Theme breakpoints. This results in off-by-one incongruencies.

## Reproduction

Let's say I want to hide the table and use cards for mobile. I might use the following styles which build on the MUI configured breakpoints:

Cards:
```
  cards: {
    [theme.breakpoints.up('md')]: { // generates: @media (min-width: 960px)
      display: 'none'
    }
  }
```
Table:
```
  table: {
    [theme.breakpoints.down('sm')]: { // generates: @media (max-width: 959.95px)
      display: 'none'
    }
  }
```

## Expected

At 960px, the desktop table is shown. 

## Unexpected

At exactly 960px, the table is shown but in the non-desktop view.

## Recommendation

Instead of using hard-coded styles ([example](https://github.com/gregnb/mui-datatables/blob/master/src/MUIDataTableBodyRow.js#L10) that specifies `max-width: 960px`), consider using the breakpoint tools provided by MUI to avoid off-by-one breakpoint errors.

**Comment by gregnb** [comment]
Agreed. Would gladly accept a PR for this fix if you wish to submit one

**Comment by mpareja** [comment]
Sure thing. I'll look to do it later tonight.

**Comment by mpareja** [comment]
Hi @gregnb, how important is it to you that we keep the `screen` portion of the media queries intact?

The MUI breakpoint queries don't include the `screen` predicate.
