### ISSUE TITLE
You introduced a console.log

### ISSUE THREAD

**Issue by Primajin** [gregnb/mui-datatables#270]
## Expected Behavior
no console.log output

## Current Behavior
logs stuff into the console

![screenshot 2018-11-12 at 15 29 57](https://user-images.githubusercontent.com/1742115/48353611-2548b080-e690-11e8-8145-26a9265cb4cb.png)

## Steps to Reproduce (for bugs)
I upgraded from `2.0.0-beta-36` to `2.0.0-beta-38` - now there is console logs.

## Your Environment
While I couldn't find any console log on the github code, there is one in the compiled code on npm - which is very weird assuming you publish what you commit.

![screenshot 2018-11-12 at 15 29 38](https://user-images.githubusercontent.com/1742115/48353724-6f319680-e690-11e8-96d7-acfcd7ef37b0.png)

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.4.0     |
| MUI-datatables  |    2.0.0-beta-38     |
| React        |    16.5.2     |
| browser      |    Chrome Canary 72.0.3608.0     |
| etc          |         |

**Comment by gregnb** [comment]
Upgrade to -39

**Comment by Primajin** [comment]
aha, was not aware of that version.

![screenshot 2018-11-12 at 15 57 46](https://user-images.githubusercontent.com/1742115/48355275-ec123f80-e693-11e8-8a29-61b002be4e73.png)
![screenshot 2018-11-12 at 15 59 15](https://user-images.githubusercontent.com/1742115/48355276-ec123f80-e693-11e8-93e3-0772ce45c7a8.png)

**Comment by Primajin** [comment]
Also I'm getting

`Module not found: Error: Can't resolve '@material-ui/icons/FileDownload' in '/builds/code/product/om-web/node_modules/mui-datatables/dist'` in my CI now with 39

**Comment by younes0** [comment]
Should be '@material-ui/icons/GetApp'

**Comment by gdegas** [comment]
I'm sorry probably noob question but how do i upgrdate to beta-39. I'm getting error that version does not exist from npm logs when running `npm i mui-datatables@2.0.0-beta-39`

**Comment by Primajin** [comment]
@gdegas It worked for me by just manually bump the version in my package.json and re-run `npm i`

**Comment by gdegas** [comment]
@Victor-R I am now getting that same issue. Did you end up figuring out how to solve it by any chance?

**Comment by Victor-R** [comment]
> @Victor-R I am now getting that same issue. Did you end up figuring out how to solve it by any chance?

I tried to update my material-ui/icons, but did not solve the problem :/ So I'm still on the beta-38 with the console messages unfortunately...

**Comment by gregnb** [comment]
Can you upgrade to -39 ?

**Comment by Victor-R** [comment]
> Can you upgrade to -39 ?

I did update, but I'm getting the same Error of @Primajin so I downgraded

**Comment by gregnb** [comment]
Sec, looking into it now

**Comment by gregnb** [comment]
I can't figure out how you guys are getting this error?
```
 greg@gregs-Air  ~/misc-repos/test  npm install mui-datatables --save
 greg@gregs-Air  ~/misc-repos/test  grep -Hr FileDownload node_modules/mui-datatables
 greg@gregs-Air  ~/misc-repos/test 
```

**Comment by gregnb** [comment]
Try the following:

```
mkdir test
npm init
npm install mui-datatables --save
```

and look for any `FileDownload` references in node_modules/ I can't find it.  Can you guys try `rm -rf node_modules` next step? and then reinstall

**Comment by gdegas** [comment]
I did that and was getting the same error. I removed `node_modules` and reinstalled, still was getting same error.

**Comment by gregnb** [comment]
Can you post up the contents of dist/ for mui-datatables up here? i'm really just confused at this point

**Comment by gregnb** [comment]
I'm going to push up a build. So many things going on at this moment for me that I realized I never released a -39. Sorry for the confusion. Coming up.

**Comment by hutch120** [comment]
> Can't resolve '@material-ui/icons/FileDownload'

After running `ncu` (npm-check-updates) it didn't pickup this update. 😲 

Deleting `mui-datatables` from packages.json, then running `npm i --save mui-datatables` fixed issue.

**Comment by AirborneEagle** [comment]
I am running into this.  My application will not even compile because the module is not found.
I am on beta-43.
we need to update the referenced icon.
see this:
https://github.com/mui-org/material-ui/issues/12344

**Comment by AirborneEagle** [comment]
Never-mind. after further digging, I found that there is a beta 55 which works
https://github.com/gregnb/mui-datatables/issues/103

**Comment by Primajin** [comment]
There should definitely an easier way to know what the latest version is without any digging. @gregnb can you check that you released the latest version in github and npm?

**Comment by GoktuqCan** [comment]
I had the same issue updating from ''2.0.0-beta-54" to "2.0.0-beta.58" with **npm update** but after run this command version downgraded to "2.0.0-beta-9". I changed it by hand but didn't affected because **package-lock.json** also downgraded and not changing with it. @gregnb I guess the problem is at first you used '**-**' character after "beta" then, used '**.**' instead.

Solution: 
1. Remove mui-datatables from package.json then run npm install(for also deleting from package-lock.json)
2. Run npm install mui-datatables
