### ISSUE TITLE
Define Default Sorting

### ISSUE THREAD

**Issue by drdouglasghd** [gregnb/mui-datatables#273]
Is there a way to define a default sort?

**Comment by gregnb** [comment]
What do you mean? a default sort order or a default sorting function?

**Comment by drdouglasghd** [comment]
I have an integer column, and I want the initial/default sort of the table to be on that column in asc order. 

Is there a way to set a default sort... or maybe I pre-sort the data prior to passing it to the datatable?

**Comment by tchari** [comment]
@drdouglasghd I think you can do something like this:
```
const columns = [
{ name: 'ColA', options: { sortDirection: 'asc' } },
{ name: 'ColA', options: { sortDirection: 'asc' } },
{ name: 'ColA', options: { sortDirection: 'asc' } },
];
```

**Comment by drdouglasghd** [comment]
![screenshot 2018-11-19 16 06 26](https://user-images.githubusercontent.com/101195/48740544-14aab400-ec15-11e8-9e58-abef8caa1b9b.png)

If we do that, it marks the column as sorted... but doesn't sort the data. So this works if your data is presorted in this order.

**Comment by KryQ** [comment]
Can confirm it only appears sorted but isn't. This method doesn't call customSort method either.

**Comment by gregnb** [comment]
That's correct. The method is not being called. Anyone want to take this up as PR?

**Comment by apercas** [comment]
Hi, I'll be adding this PR.

**Comment by gregnb** [comment]
This issue should be resolved

**Comment by cmfcmf** [comment]
> This issue should be resolved

Yup, works fine for me 👍
