### ISSUE TITLE
Extends selectableRows to have 'single', 'multiple' or 'none'  options

### ISSUE THREAD

**Issue by rnugraha** [gregnb/mui-datatables#274]
Extends selectableRows options to have 'single', 'multiple' or 'none' so that there are more options to select a row.

## Expected Behavior
In the component's options, one should be able to set

|Name|Type|Default|Description
|:--:|:-----|:--|:-----|
|**`selectableRows`**|string|''multiple'|Configure row selection. Options: 'single', 'multiple' or 'none'.

When "single" is selected: 
- It will not render checkboxes
- Rows are selectable but only single selection
- Selected row is highlighted

When "multiple" is selected: 
- It will render checkboxes
- Rows are selectable
- Selected row is highlighted

When "none" is selected: 
- It will not render checkboxes
- Rows are not selectable

## Current Behavior
There are only two options if rows are selectable or not. If it is selectable it will display checkboxes and it implies multiple selections only.

**Comment by marco270** [comment]
I also agree with this behavior

**Comment by Psykar** [comment]
I'd like to take this one step further, and have it accept a function.
`(rowIndexes, data) => []bool`
Where each row in the return value specifies if that row is selectable or not.

**Comment by Psykar** [comment]
Actually, probably a duplicate of https://github.com/gregnb/mui-datatables/issues/274

**Comment by gregnb** [comment]
> When "single" is selected:

It will not render checkboxes
Rows are selectable but only single selection
Selected row is highlighted

I'm not sure I follow? what would we show instead of a checkbox here? radio button?

**Comment by simonkaspersen** [comment]
Second this. 
When "single" is selected, it would be nice with no checkboxes, only highlight selected row.

**Comment by gabrielliwerant** [comment]
This issue has been addressed, as `selectableRows` now has the options listed here, except that for `'single'`, checkboxes are rendered on the rows (but only one is selectable at a time). It is important for UX reasons to present an indication that a user can select a row, hence the checkboxes showing by default.

However, selection on row click will become available via this PR, if you want to follow it: https://github.com/gregnb/mui-datatables/pull/607. When it does, you can override styles to hide the checkboxes, hence achieving the functionality for `'single'` described here.
