### ISSUE TITLE
Why does selected row index changed when do sorting

### ISSUE THREAD

**Issue by Aaron-Lei** [gregnb/mui-datatables#282]
## Expected Behavior

    All data is from browser side, Assuming  there are 3 rows data.
    Example: 
    Row 1: Aaron   20
    Row 2: Bob      25
    Row 3: Danny  30
    
    For example, If I tick only one checkbox(e.g. row 1) and then sort the rows in a different way, the selected checkbox should be bind with row (Aaron 20).

    I‘m confused, the demo [https://codesandbox.io/s/wy2rl1nyzl](url) works fine, my code was the same with that, but doesn't work the same.
## Current Behavior

    The only one checked checkbox was bind with different row data each time
## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   3.1.0     |
| MUI-datatables  |    ^2.0.0-beta-39     |
| React        |    16.5.2     |
| browser      |    Chrome Version 70.0.3538.102     |
| etc          |         |

`const options = {
            filterType: 'dropdown',
            download: false,
            print: false,
            rowsPerPageOptions: [10, 20, 30],
        }; 
return (
            <MUIDataTable
                data={data}
                columns={columns}
                options={options}
            />
        )`

**Comment by Aaron-Lei** [comment]
@gregnb

**Comment by gregnb** [comment]
Try the latest version let me know if this issue is still ongoing

**Comment by bar7b** [comment]
> Try the latest version let me know if this issue is still ongoing

Tried with ^2.0.0-beta-43 still doesn't work... Looks like the last version without this issue is ^2.0.0-beta-35.

**Comment by jayeshkorat18** [comment]
Same issue with version "2.12.0"
