### ISSUE TITLE
Is it possible to customize filter for specific column?

### ISSUE THREAD

**Issue by alxbbnk** [gregnb/mui-datatables#283]
Hello,
how is it possible to customize filter for  specific column?

For example: for columns with numbers i want to use range control, for dates: date picker  

Thanks!

**Comment by lukas-zech-software** [comment]
would this PR solve your problem?
https://github.com/gregnb/mui-datatables/pull/303

**Comment by KaRkY** [comment]
Yes this solves my usecase.

**Comment by gabrielliwerant** [comment]
Yes, this exists in `2.4.0` via `filterOptions: { logic: function }`.
