### ISSUE TITLE
Table no longer works

### ISSUE THREAD

**Issue by JordanKadish** [gregnb/mui-datatables#29]
## Issue

I've just updated to material-ui beta 40 and react 16.3.1, and now none of the buttons (filter table dropdown, columns dropdown) work, and the trashcan icon on rows selected is not correctly aligned
## Your Environment

| Tech         | Version |
|--------------|---------|
| mui-datatables  |     1.1.3    |
| node        |    latest     |
| OS      |    Arch Linux     |

**Comment by gregnb** [comment]
Doesn't seem to be an issue for me locally and here's a forked code sandbox with 1.1.3 and 16.3

https://codesandbox.io/s/xvqkyn6kw4
