### ISSUE TITLE
Feature request: Export child components in module

### ISSUE THREAD

**Issue by Legogris** [gregnb/mui-datatables#291]
When doing `customHeadRender` on a column, right now to get consistent styling one needs to reimplement the styling done in MUIDataTableHeadCell. It woould be great if other components than the root component could be exported.
@gregnb LMK if you think this is a good idea and I could make a PR.

**Comment by diegochavez** [comment]
Please do! I can help with it :smiley: my use case is because I'm using react-intl and is easier to compose with the custom render and reuse the sorting button for example, because I just want to render the translated column text

**Comment by gregnb** [comment]
This is now available in the latest release
