### ISSUE TITLE
Only search data in specific columns or customize search function?

### ISSUE THREAD

**Issue by alexxbull** [gregnb/mui-datatables#294]
## Expected Behavior
I would like for the searched text to be tested only in one (or more) columns. Basically, the ability to specify if a column's data is included or excluded from a search. The output would be only rows in the searchable columns who's data contains the searched text are rendered. 

Alternatively, if we could customize the search function to use a custom function that returns a Boolean indicating if a row should be rendered or not would also fulfill this request. The custom function would ideally receive all row data.  

## Current Behavior
This is a guess, but it seems the current search functionality will search all the data in each column and if any data in those columns contains the searched text, then that row is rendered.

**Comment by gregnb** [comment]
Sorry for the delayed response. I'm going to add a feature like this via the options prop called `customSearch(tableData: array, searchQuery: string) => array` when called will be provided the current table data and will expect the returned table data.

@loganasherjones is also going to add a new filtertype called `textField` so if a user wanted to search from the filter columns that would be possible as well for targeted searches.

**Comment by terapepo** [comment]
@gregnb Is this already implemented or there is an example for it? I tried testing with this options but I don't see anything:
`const options = {
  filterType: 'dropdown',
  selectableRows: false,
  print: false,
  download: false,
  sortFilterList: false,
  customSearch: (tableData, searchQuery) => {
    console.log(tableData, searchQuery);
    return tableData;
  },
};`

**Comment by gregnb** [comment]
Support for custom searching has been added although the approach is slightly different from what was discussed here. Example: https://github.com/gregnb/mui-datatables/blob/master/examples/customize-search/index.js

**Comment by eminence88th** [comment]
> Support for custom searching has been added although the approach is slightly different from what was discussed here. Example: https://github.com/gregnb/mui-datatables/blob/master/examples/customize-search/index.js

Is this a server-side custom search sir? Please I need your help.

**Comment by patorjk** [comment]
@eminence88th see the examples folder, there are several server-side examples: 

https://github.com/gregnb/mui-datatables/tree/master/examples

A custom server-side search can occur by setting serverSide to true. The deboucneSearchRender plugin (https://github.com/gregnb/mui-datatables#plug-ins) is also very useful for server-side search.
