### ISSUE TITLE
Support for latest version?

### ISSUE THREAD

**Issue by jon64digital** [gregnb/mui-datatables#295]
Hi,

Sorry if this is a repeat question but I searched issues and couldn't find an answer.

I'm coming to Material-UI for the first time and found this library, it looks awesome but says it supports "V1", but Material-UI is on version 3.6.0. Does that mean it won't work and if so is there an update planned to bring it up to date?

Thanks.

**Comment by juddey** [comment]
Hey John, It should work. I've just been using it with matierial 3.6

material-ui itself did some strange things with versioning (like went .20 -> 1 -> 2 -> 3) in very quick order and so the readme just hasn't caught up yet.

**Comment by jon64digital** [comment]
Thanks, that's great.
