### ISSUE TITLE
customSort defaults to "asc" on first two column clicks

### ISSUE THREAD

**Issue by ShaggyKris** [gregnb/mui-datatables#296]
When using customSort option, clicking on a column will pass "asc" as the order prop for the first two clicks.

## Expected Behavior
Order prop in customSort will begin as "desc", and subsequently switch between "asc" and "desc".

## Current Behavior
Order prop in customSort begins as "asc" on first click, continues to be "asc" on second click (even with arrow swapping positions), and by third click it will finally become "desc".

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   3.2.0      |
| MUI-datatables  |   2.0.0-beta-41     |
| React        |     16.5.2    |
| browser      |     Chrome 70.0.3538.110 (Official Build) (64-bit)    |

**Comment by marco270** [comment]
Possible dup of #263

**Comment by ShaggyKris** [comment]
> Possible dup of #263

It is a duplicate, but that issue looked like it was marked as resolved, which I am here to report on that it was not.

**Comment by Legogris** [comment]
@gregnb Looks like my fix for that wasz not included in the release of `2.0.0-beta-41`?

**Comment by ideoclickVanessa** [comment]
This seems to work correctly after updating to `2.0.0-beta-43`
