### ISSUE TITLE
Customize row theme based on data

### ISSUE THREAD

**Issue by CaldeDaniele** [gregnb/mui-datatables#304]
Hi,
I already use the customization of the theme like this:
`var theme = createMuiTheme({
      overrides: {
        MUIDataTableBodyCell: {
          root: {
            fontSize: ".9rem",
            fontWeight: "bold",
          }
        },
        MUIDataTableBodyRow: {
          root: {
          }
        }
      },
    });`

but now I need to customize the row based on content like : column "date_end" is different from "" so backgroundColor: red.. I have found how do it possible based on the index but not we the data. Someone can help me? Thanks

**Comment by AdminCortex** [comment]
@CaldeDaniele , did you find a way to change the background color based on the data in the grid. Appreciate if you can provide some insights

**Comment by CaldeDaniele** [comment]
@AdminCortex take a look at this https://github.com/gregnb/mui-datatables/pull/307
