### ISSUE TITLE
Vertical scroll of table content

### ISSUE THREAD

**Issue by mocabi** [gregnb/mui-datatables#310]
How to add a vertical scroll to a table content by keeping columns header and table footer intact? I was able to put a div around table with overflow-y but this scrolls the whole table and navigation to header/footer becomes unusable.

**Comment by mocabi** [comment]
Looks like 'fixedHeader' option solves the issue.

**Comment by younes0** [comment]
set `responsive: scroll ` plugin option and add style `.MUIDataTable-responsiveScroll { max-height: auto;}`

**Comment by JReinhold** [comment]
As of [V2.10.0](https://github.com/gregnb/mui-datatables/tree/2.10.0) it is now possible to use the prop `responsive="scrollFullHeight"` to make the table full height and a scroll behavior at the same time. That should fix the issue.

See https://github.com/gregnb/mui-datatables/pull/867
