### ISSUE TITLE
Initialize table with correct dataIndex

### ISSUE THREAD

**Issue by fantapop** [gregnb/mui-datatables#311]
https://github.com/gregnb/mui-datatables/blob/68e523e1f1c61170ce6f58ffd8a168a752d181e5/src/MUIDataTable.js#L338

I'm unable to figure out which cell was clicked.  It appears that dataIndex is always equal to rowIndex.  I assume this is the culprit.

**Comment by fantapop** [comment]
oh sorry, I was assuming data index was the column index.  Is there a way to get the column that a click came in from?  I'm using the onClick functionality of the row as a link and the checkbox for row deletion.  When I click the checkbox onClick fires for the row and I need to identify that its coming from the first column so I can ignore the action.  I have it currently working by looking for target type check box but it would be nicer to do something more straightforward.

**Comment by gabrielliwerant** [comment]
`onCellClick` will tell you which column the click is coming from.
