### ISSUE TITLE
Responsive issue : if we have 9 columns after width 980 to 1200 approx

### ISSUE THREAD

**Issue by GurdeepCS** [gregnb/mui-datatables#312]
I have 9 columns and responsive: "stacked". at certain screen width the columns on the right hand side goes beyond the card. In my case from 960 to 1540. 

## Expected Behavior
either it should include scroll between this range or there should be other display scenario.
## Current Behavior
Between this range it goes beyond the card.
## Steps to Reproduce (for bugs)
1. create a datatable with around 9 cols
2. Toggle device toolbar
3. switch to responsive from the available device list
4. extend and reduce the width

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |  mui-datatables@2.0.0-beta-8       |
| React        |    reactify@4.0.0     |
| browser      |     chrome    |
| etc          |         |
![responsive_issue](https://user-images.githubusercontent.com/45822500/49928175-983e8480-fee5-11e8-8fb1-ae4a3a86ba08.png)

**Comment by cristianPerez** [comment]
Hello [GurdeepCS](/GurdeepCS) any advance in this issue?

**Comment by Badbreaddead** [comment]
Any progress here? My tables just go out of page boundaries if content in a cell is just too wide

**Comment by brymon68** [comment]
Having the same problem as well

**Comment by vcfelix** [comment]
Please give us a solution for this issue. Thanks

**Comment by Majoros** [comment]
Having the same issue, looking around i found this. looks like 960 is actually hard coded. https://github.com/gregnb/mui-datatables/blob/0debb9bf264bc058c17e958b89c6dda65b1bbec3/src/MUIDataTableBody.js

looking into a fix.

**Comment by chrisella** [comment]
I am experiencing the same issue with the same version of mui-datatables, we have 11 columns and they spill over the end above 960px.

**Comment by enlznep** [comment]
Any updates on this?

**Comment by gabrielliwerant** [comment]
PR up here https://github.com/gregnb/mui-datatables/pull/772. Will be in the next release,

**Comment by gabrielliwerant** [comment]
Should be fixed in `2.6.4`.
