### ISSUE TITLE
Wrong material-ui proptype for title

### ISSUE THREAD

**Issue by vict0rsch** [gregnb/mui-datatables#313]
## Current Behavior

I get this error rendering the table : 
```
Warning: Failed prop type: Invalid prop `variant` of value `h6` supplied to `Typography`, expected one of ["display4","display3","display2","display1","headline","title","subheading","body2","body1","caption","button"].
```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   1.4.0      |
| MUI-datatables  |    2.0.0-beta-41     |
| React        |     16    |
| browser      |    Chrome     |

**Comment by BetaAI** [comment]
I had the same problem. Apparently Material UI [spec](https://material-ui.com/style/typography/#migration-to-typography-v2) has changed. Updating @material-ui/core to 3.6.2 solved it.

**Comment by Badbreaddead** [comment]
Please fix these annoying warning. Minor, but fast to do

**Comment by jsnavarroc** [comment]
This error is annoying, and the project I can not install
@ material-ui / core 3.6.2 --> please correct it

**Comment by gregnb** [comment]
Add this to your theme:

https://material-ui.com/style/typography/#strategies
