### ISSUE TITLE
fixedHeader option is not working 

### ISSUE THREAD

**Issue by aneekroy** [gregnb/mui-datatables#315]
The fixHeader option is not working even with vertical scroll of the table component is done

## Expected Behaviour

   While vertical scroll of the table elements is done, the header should remain fixed and stick to it's position.

## Current Behavior

    The header scrolls up alongwith the table element.

## Steps to Reproduce (for bugs)

   https://codesandbox.io/s/mmqyr28q6p
code for changing the fixing the header option
    const options = {
      filterType: "dropdown",
      responsive: "scroll",
      fixedHeader: true
    };

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     3.6.2    |
| MUI-datatables  |      mui-datatables@2.0.0-beta-41   |
| React        |      16.6.3   |
| browser      | Google Chrome 70.0.3538.110       |
| etc          |         |

**Comment by gregnb** [comment]
Thanks for filing this issue. Please try using the latest release it should now be resolved

**Comment by pashpashpash** [comment]
Looks like it's still not working

**Comment by gabrielliwerant** [comment]
@pashpashpash If there is an issue with the `fixedHeader` option, please open a new issue with steps to reproduce and ideally a minimal example in codesandbox for demonstration purposes.

**Comment by Flavyoo** [comment]
Is there a way to have the fixed header be placed below a navigation bar? I think it is working, but since it gets fixed at the top, you can't see it because the navigation bar is covering it.

**Comment by ClaireSH** [comment]
It worked by adding this option too.
const options = {
    fixedHeader: true,
    responsive: 'scroll',
}

mui-datatable version : ^4.0.0
