### ISSUE TITLE
onRowsSelect doesn't fire

### ISSUE THREAD

**Issue by tjaskula** [gregnb/mui-datatables#32]
## Config

https://codesandbox.io/s/lplo7l6q09

## Issue

Checking checkboxes doesn't fire `onRowsSelect` event.

## Your Environment

| Tech         | Version |
|--------------|---------|
| mui-datatables  |    1.1.5     |
| node        |         |
| OS      |         |

**Comment by gregnb** [comment]
@tjaskula the callbacks are a part of the options. 

try looking at this example https://github.com/gregnb/mui-datatables/blob/master/examples/selectable-rows/index.js

**Comment by tjaskula** [comment]
Thanks. No issue

**Comment by gregnb** [comment]
No problem!
