### ISSUE TITLE
Issue when number of search results is less than the current page

### ISSUE THREAD

**Issue by lrtibbetts** [gregnb/mui-datatables#326]
## Expected Behavior

If I navigate to a later page in my table and search for something with fewer matching results than the current page, e.g. 20 results when I am currently on page 3 (20 results per page), the application should not crash.

## Current Behavior

My application currently crashes in the situation described above with the following error: "Provided options.page of `2` is greater than the total available page length of `1`." 

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  | 3.7.0         |
| MUI-datatables  | 2.0.0-beta-42         |
| React        | 16.7.0        |
| browser      | Chrome        |

**Comment by gregnb** [comment]
Great thanks for sharing! I will look into this today

**Comment by gregnb** [comment]
Try the latest version this issue should be resolved
