### ISSUE TITLE
The z-index of the checkbox header is the same as the z-index for every row, so when you have a scrollable table the checkbox for the rows overlaps the header checkbox.

### ISSUE THREAD

**Issue by KristenKatona** [gregnb/mui-datatables#327]
When you have an MUIDataTable with responsive: "scroll", pagination: false and selectableRows left as true,  and then you scroll up in the table, the checkboxes in the rows overlap the header checkbox. (The other column titles are "sticky" and don't get overlapped like that by the rows.)

The checkbox in the header should behave as the other column headers. i.e. the z-index of the row checkboxes should be lower than that of the z-index of the select all header checkbox. The fixedHeader class in MUIDataTableSelectCell.js should only be used for the header select column, not all the row select columns. 

## Steps to Reproduce (for bugs)

1. Create a scrollable MUIDataTable that has selectable rows. i.e. responsive: "scroll", selectableRows: true, pagination: false
2. Scroll in the table and see the header checkbox gets overlapped by the row checkbox. 

## Your Environment

| Tech                    | Version                  |
|-----------------|-------------------|
| Material-UI          |     3.5.1                   |
| MUI-datatables  |      2.0.0-beta-41   |
| React                   |       16.6.3               |
| browser               |     Chrome              |

**Comment by gregnb** [comment]
@KristenKatona Thanks for filing this issue. Please try using the latest release it should now be resolved

**Comment by allenjoy123** [comment]
> @KristenKatona Thanks for filing this issue. Please try using the latest release it should now be resolved

There seems to be a new related issue where after scrolling up 3 rows, the checkbox is becoming disabled for subsequent rows.
