### ISSUE TITLE
Deprecation warning for subheading typography variant

### ISSUE THREAD

**Issue by mking42** [gregnb/mui-datatables#333]
## Expected Behavior
No deprecation warning (Error) in console.

## Current Behavior
Deprecation warning (Error) in console about the use of subheading typography variant.

> Warning: Failed prop type: Material-UI: you are using a deprecated typography variant: `subheading` that will be removed in the next major release.
> Please read the migration guide under https://material-ui.com/style/typography#migration-to-typography-v2.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.8.1     |
| MUI-datatables  |    2.0.0-beta-44     |
| React        |   16.7.0      |
| Browser | Chrome |

https://github.com/gregnb/mui-datatables/search?q=subheading&unscoped_q=subheading

**Comment by dafrie** [comment]
This was apparently already addressed with PR #277, but somehow after the reorganization of the component files, the TableBody component now is missing this change in the variant prop of the Typography component.
I submitted a new PR #345 containing the necessary change...
