### ISSUE TITLE
Download CSV downloads all columns instead of just visible columns

### ISSUE THREAD

**Issue by seseals** [gregnb/mui-datatables#334]
## Expected Behavior
When deselecting a column to be viewed, the downloaded CSV should not contain that column

## Current Behavior
Hiding columns does not remove the column from the download and all columns are in the CSV.  Setting the column options download: false from the beginning removes the column, but setting it through the UI using onColumnViewChange does not seem to be reflected when downloading.

## Steps to Reproduce (for bugs)
https://4wx7k87729.codesandbox.io/

1. Load sandbox
2. Hide one of the columns, see that it visually disappears
3. Check the console and see that it changed options.download to false for that column.
4. Download CSV
5. Open CSV and see that the column that was changed to not download is still downloaded.

Further testing: Changing the template code to download: false from the beginning works, it's just changing it through the UI doesn't seem to work.

## Your Environment
All listed in codesandbox.io

**Comment by gabrielliwerant** [comment]
I would not expect download to mirror visibility, as it does not do this for pagination either. Hiding data is a view option, downloading is a comprehensive data option.

That being said, there is now a callback to influence what gets downloaded via `onDownload`. You should be able to use that to help customize what gets downloaded.

**Comment by dbansch** [comment]
@gabrielliwerant I tried to create an onDownload function, but I can't get it to work.  The on download example in mui-datatables/examples/on-download/index.js does not work either.  The csv output is the same with and without the onDownload function.  Do you have an example of an onDownload function that works?

**Comment by gabrielliwerant** [comment]
@dbansch I'm not sure what you mean, the example works fine; the output is different, as specified in the function (it adds a footer and it changes a column name as compared to without the function).

`onDownload` is a callback that provides the functions necessary to let you create whatever download you wish. You have to decide what you want it to do and then input the data you want. See the documentation and the implementation example.

**Comment by gabrielliwerant** [comment]
Additional options now exist to determine downloaded output as of `2.7.0`. See release notes for more information.
