### ISSUE TITLE
Filter Logic

### ISSUE THREAD

**Issue by loganasherjones** [gregnb/mui-datatables#349]
Thanks again for a great library!

## Expected Behavior

Right now, all the filters are applied using `or` logic. It would be nice if we could change that to `and` logic easily. My use case looks something like, "I'd like to filter where all the status is 'error' and the e-mail looks like 'blah'"

The way I think I would implement this is with another option i.e. `filterLogic` which would have a default of `or` to keep the default behavior, and an enum of `["or", "and"]`. I'm open to other suggestions of course!

**Comment by Maaartinus** [comment]
A related and simpler FR (apologies for misusing this thread): Negated filters. Filter where the status is not "OK". Multiselect does it, but it doesn't convey the meaning clearly and there may be too many checkboxes to check.

**Comment by gabrielliwerant** [comment]
Custom filter logic is available per column as of `2.4.0` via `filterOptions: { logic: function }`. If you are referring to what happens *between* columns, the default is `AND` as this conforms best to expected UX behavior.

**Comment by gabrielliwerant** [comment]
Closing as resolved (by new feature).
