### ISSUE TITLE
Different filter types for different columns

### ISSUE THREAD

**Issue by loganasherjones** [gregnb/mui-datatables#350]
Thanks again for the great library. I'd be interested in creating a PR for this functionality.

## Expected Behavior

I would like to be able to use a dropdown for some columns, and the `textField` for other columns. Right now, this is set on the over all `MUIDataTable` `options` prop. I would like to be able to specify for a specific column which filterType to use. 

My proposal is to use the main `filterType` by default, but search the column options for `filterType` if it exists, and use that as an override.

**Comment by iamvishalbisht** [comment]
Hi, 

I also have the exact same requirement. Please let me know how can i achieve multiselect on some particular columns while having default dropdown on others.

**Comment by gabrielliwerant** [comment]
This behavior should be possible in later versions (`2.8.0` as of writing this). Closing this as resolved!
