### ISSUE TITLE
Expandable row is not working for me. 

### ISSUE THREAD

**Issue by rohitjogson** [gregnb/mui-datatables#352]
I just add 
1. expandableRows
2. renderExpandableRow

in option as you shown in example but its not working and i need this urgently.

**Comment by gregnb** [comment]
Please share how you are using the library and I can take a look

**Comment by rahulgupta97** [comment]
>I just add  ...

@rohitjogson 

Make sure your “options“ variable is defined in the render() function. 

I removed the input arguments and did something basic to test functionality: 

renderExpandableRow: () => {
     return(
         <TableRow>
               <TableCell>{‘Hello’}</TableCell>
               <TableCell>{‘World’}</TableCell>
         </TableRow>
     );
}

You can also use a map function for JSON data in this case as well:

renderExpandableRow: () => {
     return(
       this.state.tabledata.map(element => {
         <TableRow>
               <TableCell>{element.min}</TableCell>
               <TableCell>{element.sec}</TableCell>
         </TableRow>
    );
  })
}

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rahulgupta97** [comment]
@gregnb No matter what I define in my renderExpandableRow() method, I get the same child rows repeated for each expandable row. For example, if I write:

renderExpandableRow: () => {
  return(
    <TableRow>
      <TableCell>{“Hi”} </TableCell>
    </TableRow>
  );
}

For every one of my expandable rows, my child row shows a “Hi” cell.

I have unique child data for all of my parent rows. How can I go about implementing that?

Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gregnb** [comment]
@rahulgupta97 Please take a look at this example here:

https://github.com/gregnb/mui-datatables/blob/master/examples/expandable-rows/index.js#L84

You will see there are two arguments passed. `rowData` and `rowMeta` which will provide you with the data for that row

```
      renderExpandableRow: (rowData, rowMeta) => {
      }
```

**Comment by rahulgupta97** [comment]
>@rahulgupta97 Please take a look at this example here: ...

@gregnb 

Ah, got it. Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by simonkaspersen** [comment]
Is it any way to return the whole row item in `rowData`? Not all metadata is displayed in the table, but want to show them once the row is expanded.

**Comment by simonkaspersen** [comment]
It looks like `data[rowMeta.dataIndex]` returns correct item.
