### ISSUE TITLE
TypeError: Cannot read property 'customHeadRender' of undefined

### ISSUE THREAD

**Issue by jkeruzec** [gregnb/mui-datatables#353]
I have some issue displaying table with latest version of mui-datatables : 

``` js
Uncaught (in promise) TypeError: Cannot read property 'customHeadRender' of undefined
    at index.js:1994
    at Array.map (<anonymous>)
    at t.p.rawColumns (index.js:1991)
    at t.p.buildColumns (index.js:2003)
    at t.value (index.js:2341)
    at t.value (index.js:2283)
    at t.value (index.js:2278)
    at callComponentWillReceiveProps (react-dom.development.js:13194)
```

![image](https://user-images.githubusercontent.com/3499632/50757603-29dcb000-1260-11e9-8372-a6e4655ba166.png)

Can you check this ?

edit: issue starts with version 48

**Comment by gregnb** [comment]
Can you post how you are using it?

**Comment by jkeruzec** [comment]
I don't use customHeadRender in my code, I've no trace of it. 
I also tried in -49 this morning but no success

**Comment by gregnb** [comment]
Any chance you can share how you using the library?

**Comment by gregnb** [comment]
I know where the issue is and releasing a fix within next 10 minutes. Thanks for reporting the issue

**Comment by jkeruzec** [comment]
Ok great, I was searching for the bug in src code .. somehow it's when you have state columns that's not empty ^^ but I didn't found why ... :/ 

Thanks anyway ^^

**Comment by gregnb** [comment]
try -50 just released

**Comment by jkeruzec** [comment]
@gregnb Working fine ! 
Thanks
