### ISSUE TITLE
Cannot use expandable rows if selectable rows is disabled

### ISSUE THREAD

**Issue by cw0** [gregnb/mui-datatables#357]
## Expected Behavior

Setting expandableRows: true should enable row expansion

## Current Behavior

Setting expandableRows: true only shows expansion controls if selectableRows: true.
In my use case, I don't need the checkboxes for row selection, but would like the ability to see more details when selecting a row. All of my data is read only. Is there any method exposed to open the expandableRow programmatically like on a row click event?
## Steps to Reproduce (for bugs)

1. in options set expandableRows: true, selectableRows: false

**Comment by rm-hull** [comment]
@cw0 - one possible workaround for this is to add a theme that hides the checkboxes:

```javascript
const getMuiTheme = () => createMuiTheme({
  overrides: {
    MUIDataTableSelectCell: {
      checkboxRoot: {
        display: 'none'
      }
    }
  }
});
```

and then wrap the table with a provider:

```javascript
    <MuiThemeProvider theme={getMuiTheme()}>
      <MUIDataTable
        title="Audit Log"
        data={rows}
        columns={columns}
        options={options} />
    </MuiThemeProvider>
```

**Comment by PedroBern** [comment]
@rm-hull great solution, thanks.

Another problem with expandable rows is it's not displaying on small screen. Only on desktop size screens.

When you come to a small, it just stop working.

@rm-hull any idea how to solve this?

**Comment by gregnb** [comment]
This issue has been resolved in beta-53. Please let me know if there are any further problems
