### ISSUE TITLE
Question: Hide column from Print

### ISSUE THREAD

**Issue by rulgf** [gregnb/mui-datatables#358]
Hi,
Anyone knows if there's a way to hide a column so it doesn't show in the print file? Something like the `download` column option

BTW, amazing component! Thanks!

**Comment by giovannirosa** [comment]
Hi, I'm also interested.

I have a column for Delete & Edit that should not be printed. I'll try some hacks and advise if find anything.

I'm also amazed by this component, high end stuff.

**Comment by gregnb** [comment]
This is now available as a column option `print` example: https://github.com/gregnb/mui-datatables/blob/master/examples/hide-columns-print/index.js
