### ISSUE TITLE
wrong interacting style with the delete icon

### ISSUE THREAD

**Issue by winjeysong** [gregnb/mui-datatables#360]
## Expected Behavior
when interacting, background of delete icon should be circle.

## Current Behavior

![image](https://user-images.githubusercontent.com/22495161/51019243-342ae100-15b5-11e9-863d-581bcc6bedd8.png)

## Steps to Reproduce (for bugs)

1. multi select rows
2. hover above the delete icon

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.8.2     |
| MUI-datatables  |   2.0.0-beta-50      |
| React        |    16.7.0     |
| browser      |    chrome 71.0.3578.98     |

**Comment by gabrielliwerant** [comment]
Closed here https://github.com/gregnb/mui-datatables/pull/586
