### ISSUE TITLE
Crashes on componentDidUpdate when  resizableColumns: true

### ISSUE THREAD

**Issue by fantapop** [gregnb/mui-datatables#362]
It seems this commit is causing my table to crash when I open a modal overtop of it:

https://github.com/gregnb/mui-datatables/commit/1cb5cd9ee85248fff8600dd2cfc92d26ceea5a10

I'm not exactly sure whats going on but after this commit, ```updateWidths``` is called on componentDidUpdate and for some reason some items in cellsRef are null which causes the style.width access to blow up.

```
  updateWidths = () => {
    let lastPosition = 0;
    const { resizeCoords, tableWidth, tableHeight } = this.state;

    Object.entries(resizeCoords).forEach(([key, item]) => {
      let newWidth = Number(((item.left - lastPosition) / tableWidth) * 100).toFixed(2);
      item.percent = newWidth;
      lastPosition = item.left;

      const thCell = this.cellsRef[key];
      thCell.style.width = newWidth + '%';     // <<< crash here
    });
  };
```

I don't know what the significance is but I can only get this to repro when I've wrapped the table in a MUIThemeProvider, i.e.
```
     <MuiThemeProvider theme={this.getMuiTheme()}>
          <MUIDataTable title={'ACME Employee list'} data={data} columns={columns} options={options} />
        </MuiThemeProvider>
```

I was able to create a pretty simple repro case from the example/resizable-columns/index.js example.

## Steps to Reproduce (for bugs)

[![Edit pmlop538vq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pmlop538vq)

1. Click the button underneath the table that says: "Click here to crash me"

## Your Environment

All latest, see codesandbox

**Comment by gregnb** [comment]
This issue has been resolved in beta-53. Please let me know if there are any further problems
