### ISSUE TITLE
disable rowsPerPageOptions or feed it less than 3 values

### ISSUE THREAD

**Issue by aishmitk** [gregnb/mui-datatables#365]
How can I disable rowsPerPageOptions? I tried messing with the custom footer but it did not work for me.

Thus far the only thing that has worked is to feed rowsPerPageOptions an nonarray value, which I do not prefer because it results in an error.

What I am looking for is to have there be no options to change the amount of rows, so even if I try putting just `rowsPerPageOptions: [5]` I end up getting the dropdown having the values of [5,15,100].

**Comment by KristenKatona** [comment]
I second this request. It would be nice to have the option to disable this feature when/if desired using some method other than forcing it to throw an error.

**Comment by jcoquet** [comment]
I think it comes from the use of lodash.merge to merge the defaultOptions with the options prop (https://github.com/gregnb/mui-datatables/blob/master/src/MUIDataTable.js#L217).
I'm using the same solution as @aishmitk .
Is there a better way to merge options or should we add a boolean prop like 'showPerPageSelector'...

**Comment by jaksco** [comment]
I think this can be done by using customFooter. I'm trying to figure this out too. Something like this but I don't know how to get it to work

```
customFooter: (count, page, rowsPerPage, changeRowsPerPage, changePage) => {
        return (
          <MuiTableFooter>
            <MuiTableRow>
              <MuiTablePagination
                className={classes.root}
                classes={{
                  caption: classes.caption,
                  toolbar: classes.toolbar,
                  selectRoot: classes.selectRoot,
                }}
                count={count}
                page={page}
                labelRowsPerPage={textLabels.rowsPerPage}
                labelDisplayedRows={({ from, to, count }) => `${from}-${to} ${textLabels.displayRows} ${count}`}
                backIconButtonProps={{
                  'aria-label': textLabels.previous,
                }}
                nextIconButtonProps={{
                  'aria-label': textLabels.next,
                }}
                onChangePage={this.handlePageChange}
              />
            </MuiTableRow>
          </MuiTableFooter>
        );
      },

**Comment by GioLogist** [comment]
+1 to disable !

**Comment by abewartech** [comment]
Same here

**Comment by beerwin** [comment]
+1, as it is really annoying

**Comment by sseekamp0** [comment]
Hi!
The following works to remove the rows per page option, however I still receive a large warning in my console. Is there anyway to avoid assigning a boolean value when an array is expected?

`const options = {
      rowsPerPageOptions: false,
    }; 
 
    return (
        <MuiThemeProvider theme={getMuiTheme()} >
           <MUIDataTable
            title={"Results"}
            options={options}
          />
        </MuiThemeProvider>
    );
  }
}`


Warning received in console: Warning: Failed prop type: Invalid prop `rowsPerPageOptions` of type `boolean` supplied to `TablePagination`, expected `array`.

**Comment by gabrielliwerant** [comment]
@sseekamp0 The way this should be working now is the way it works in material-ui, which is to send it only one option or an empty array. In either case, it will disable the selection. No need to use `false` here. Give that a try and see if it works for you.

**Comment by sseekamp0** [comment]
@gabrielliwerant unfortunately, assigning [] to rowsPerPageOptions results in the picker being enabled with the default values 10, 15, 100. When assigning false the picker is disabled, but I receive the warning I posted earlier.

`const options = {
rowsPerPageOptions: false,
};`

results in:
![image](https://user-images.githubusercontent.com/48028463/64258804-8080b380-ceed-11e9-941f-50cb2c072a33.png)

**Comment by gabrielliwerant** [comment]
@sseekamp0 Looks like this is a regression. The issue was solved in `2.5.0`, but a recent patch I wrote broke it again. I'm working on it now. FYI, `false` will continue to be unsupported, by empty array or array of one should work again, as per material ui convention.

**Comment by gabrielliwerant** [comment]
Should be closed again via https://github.com/gregnb/mui-datatables/pull/896 in `2.10.2`.

@sseekamp0 You should now be able to use `[]` to disable `rowsPerPageOptions` again.

**Comment by DrZanuff** [comment]
> @gabrielliwerant However, that will generate this error now:
> 
> ```
> Material-UI: The page size `100` is not preset in the `rowsPerPageOptions`. Add it to show the pagination select. 
> ```

To solve this problem, pass the pageSize prop initial value:
![image](https://user-images.githubusercontent.com/23051495/151351344-d56373f6-36b7-4e41-9928-83638d80c848.png)

**Comment by mikesil121** [comment]
I am a noob frontend developer. I also encountered some issue which I dont want to display the rowsPerPageOptions option. I discovered a way to remove it entirely, the label and dropdown. You can use can pass a false value like so `rowsPerPageOptions={false}`. Hope this helps in any way.
