### ISSUE TITLE
[Bug] Selectable index dismiss

### ISSUE THREAD

**Issue by Aaron-Lei** [gregnb/mui-datatables#366]
In selectable and client-side mode, first select several rows, after doing sorting, the selected indexes  no longer existed, but it worked all fine in version 2.0.0-beta-29, but now in version  2.0.0-beta-50 did not.

## Expected Behavior

1. When doing sorting or filtering, the selected checkboxes will remain;
2. Aftering doing sorting, the dataIndex(the original index of each row when first load the data to the memory) of the row do not change.
## Current Behavior

1. first select some rows, the checkboxes status of them are checked, but after doing sorting, the checkboxes status were all unchecked, it looks like the status of all rows' checkboxes return to default.
2. first load data to the memory, each row of has its own dataIndex, but aftering doing sorting, the dataIndex changed randomly
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.1.0     |
| MUI-datatables  |     ^2.0.0-beta-50    |
| React        |    16.5.2     |
| browser      |    chromeVersion 71.0.3578.98 (Official Build) (64-bit)     |
| etc          |         |

**Comment by gregnb** [comment]
Sorry about this bug. I've published -51 it was a result of accepting a PR to allow custom sorting that is not inplace but that causes other issues. I've reverted that change

**Comment by Aaron-Lei** [comment]
> Sorry about this bug. I've published -51 it was a result of accepting a PR to allow custom sorting that is not inplace but that causes other issues. I've reverted that change

Thanks for your quick reply, I just update it to ^2.0.0-beta-51, but it still has bug:
Reproduce:
1. first load a data list to table, for example 10 rows data;
2. select row 1, row 2;
3. do sorting, 
then although the checkbox  status remained, but it was bonded with other row randomly. That means, every time do a sorting, the original checkbox was bonded with different row randomly

**Comment by gregnb** [comment]
Try latest version

**Comment by Aaron-Lei** [comment]
> Try latest version
I just update to version 52, it works all fine.
Many thanks to your quick response, I will keep using the mui-datatables, and contribute to make it better and perfect.
