### ISSUE TITLE
OnCellClick DataIndex

### ISSUE THREAD

**Issue by AaronKauffman** [gregnb/mui-datatables#368]
When utilizing OnCellClick after a filter or sort has been applied to the table incorrect data is returned.

## Expected Behavior

OnCellClick should return the index within the source data of where you clicked. Much like in OnRowClick there is a dataindex value that will return an index value that allows you to pull that row of data from the source data populating the table. 
## Current Behavior

Currently OnCellClick will return the cell value you clicked on, the row and column index of where on the table it was clicked. The row and column index are only relevant to the current page you are looking at because its 0-#Columns or 0-#Rows being displayed which when trying to use this to access the data behind the table it doesnt help. 

## Suggested Behavior
If there was a dataindex that wasnt associated with table index but the actual data populating the table that would allow looking up of data values on a click. The current cell row and column clicked would be helpful if there was a way to look up other values of the current table give an index such as I click on cell with a column 2 and row 2 and then can have code that loops and grabs all row 2 values by looping the column index values. 

## Your Environment

MUI-Datatables: 2.0.0-beta-36

**Comment by macmorning** [comment]
Same here, can you please review #212 ?

**Comment by gregnb** [comment]
This issue should be resolved. Please upgrade to beta-53. onCellClick now provides dataIndex as well
