### ISSUE TITLE
Crashes when resizableColumns: true and viewColumns: true 

### ISSUE THREAD

**Issue by JoeKyy** [gregnb/mui-datatables#371]
## Expected Behavior

Active resizableColumns and use viewColumns enable/disable columns to view

## Current Behavior

Active resizableColumns and use viewColumns enable/disable columns to view crashes aplication

## Steps to Reproduce (for bugs)

1. Run app
2. Try to enable/disable columns

## Your Environment
https://codesandbox.io/s/8l7wxjk7ml

**Comment by gregnb** [comment]
This issue has been resolved in beta-53. Please let me know if there are any further problems
