### ISSUE TITLE
[BUG] Search bar doesn't show after filters 

### ISSUE THREAD

**Issue by alcmacys** [gregnb/mui-datatables#372]
I notice a bug in which the search bar disappears when doing a search then applying a filter. 

- When you perform a filter right after search the table displays results from search query + filters selected.
- When you clear the filter, the search bar goes away, while the table still displays results from your search query. 

This is confusing to the user as there's no UI indication of a search being applied to the data set.

## Expected Behavior

Search bar should persist when user does a search followed by a filter.

## Current Behavior

Search bar is hidden from view when user does a search followed by filter.

## Steps to Reproduce (for bugs)

1. Click on Search > Type in query
2. Click on filter > Select a filter for column(s)
3. Clear the filters (through Filter > Reset  or  removing breadcrumbs )
4. Notice dataset reflect what matches search query; however, with no UI indication of a search filter being applied.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    ^1.0.0-rc.0     |
| MUI-datatables  |     ^2.0.0-beta-52  |
| React        |  ^16.2.0       |
| browser      | Chrome - Version 70.0.3538.110 (Official Build) (64-bit) , Safari  - Version 11.1.2 (12605.3.8.1)   |
| etc          |         |

**Comment by domind** [comment]
Is this still valid? Not able to repeat this. Seems #1053 closed also this issue.

**Comment by gabrielliwerant** [comment]
@domind Nice catch, looks closed to me!
