### ISSUE TITLE
Request to allow regex in search and it would be great if we can target specific column like column name = search term format 

### ISSUE THREAD

**Issue by santoshbadal1111** [gregnb/mui-datatables#376]
I want regular expression support in datatable search. Also it would be fantastic if you can provide a function or something which can allow us to implement column = search_string functionality to target specific column during search.

**Comment by burgua** [comment]
@santoshbadal1111 duplicates https://github.com/gregnb/mui-datatables/issues/294 ?

**Comment by gregnb** [comment]
Support for custom searching has been added although the approach is slightly different from what was discussed here. Example: https://github.com/gregnb/mui-datatables/blob/master/examples/customize-search/index.js
