### ISSUE TITLE
set table MaxHeight for scrolling mode?

### ISSUE THREAD

**Issue by JRamos1993** [gregnb/mui-datatables#378]
It looks like the MaxHeight is hardcoded for 499px on the main component of the library. Is it possible to override this in any way?

## Expected Behavior
    Override the maxHeight so that the component could fill a big screen in scrolling mode.

## Current Behavior
    While in scrolling mode, the table maxHeight is set to 499px which looks really uncomfortable when using high resolution screens.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.8.3     |
| MUI-datatables  |     2.0.0-beta-50    |
| React        |    16.7.0     |
| browser      |    Google Chrome / Firefox     |
| etc          |         |

**Comment by samotoo** [comment]
Also having the same issue after upgrading from 2.0.0-beta-38 to 2.0.0-beta-52. I'm making use of the method mentioned in #367 to override the maxHeight style.

**Comment by gabrielliwerant** [comment]
This is possible via style overrides.

**Comment by JReinhold** [comment]
As of [V2.10.0](https://github.com/gregnb/mui-datatables/tree/2.10.0) it is now possible to use the prop `responsive="scrollFullHeight"` to make the table full height and a scroll behavior at the same time. That should fix the issue.

See https://github.com/gregnb/mui-datatables/pull/867
