### ISSUE TITLE
dataIndex undefined after sorting

### ISSUE THREAD

**Issue by antonpperez** [gregnb/mui-datatables#379]
## Expected Behavior
After sorting a table, dataIndex keeps reflecting the index on the original dataset

## Current Behavior
The callback onRowsSelect works well until the table is sorted. After that, records selected before the sorting will be *undefined* for the dataIndex value

## Your Environment
May be important that I am displaying +5k rows and with the following options:

```
options = {
            filter: false,
            print: false,
            rowsPerPage: 50,
            rowsPerPageOptions: [10,20,50,100],
            onRowsSelect: (currentRowsSelected, allRowsSelected) => {
                console.log(currentRowsSelected)
                console.log(allRowsSelected)
              }
          }
```

| Tech         | Version |
|--------------|---------|
| Material-UI  |     3.8.1    |
| MUI-datatables  |     2.0.0-beta-50    |
| React        |     16.6.3    |
| browser      |     Chrome    |

**Comment by antonpperez** [comment]
As an additional thing, may be related or not, the checkbox status dissapears after sorting (e.g. having 2 selected elements will be shown as unselected after sorting).
The internal status is kept though. When trying to mark as selected one of those that lost the visual indicator, nothing will happen in the UI but the item will be effectively marked as unselected at that point

**Comment by antonpperez** [comment]
I just tried tonload static data and for me the problem persists. The data is created inside of the component and is not being passed as a prop
The size of the list doesn't seem to be relevant either

**Comment by nugluke** [comment]
I think im facing the same issue
Selected rows indexes don't update after sorting data. So if i select some data and apply a filter after that selected rows stay ordered as the first view. 
Ex: If i selected the first row (**a**  index = 1, dataIndex= 1) , and then filter the data and select again the first row (**b** index = 1, dataIndex = 80) it will unselect the a item and put item b in selectedRow array.

**Comment by gregnb** [comment]
I will look into this issue today

**Comment by gregnb** [comment]
@antonpperez ? I have tried to reproduce this issue in -52 and I can not

**Comment by antonpperez** [comment]
I can confirm it works with the latest version
