### ISSUE TITLE
so,Is this only a local datatable manage?It don't support server side data filter and some other operations ?

### ISSUE THREAD

**Issue by JackZong** [gregnb/mui-datatables#38]
It don't support server side data filter and some other operations.And  It must provide all the data at the first time.Dont support data load dynamic.Am i right ? Thank you very much.In the future,If it will add feature to load data dynamic.

**Comment by gregnb** [comment]
Hey @JackZong you’re right as it stands today server side support is not finished. I’m cureently working on it and it should be ready soon. This will provide the ability to load in saved data

**Comment by gregnb** [comment]
hey @JackZong in the latest released i've added two SSR options: page and filterList
