### ISSUE TITLE
Is there any way to exclude a column from Search?

### ISSUE THREAD

**Issue by susmita-vps** [gregnb/mui-datatables#380]
Hi,

First of all, this is an awesome library and I love it. Having said that I do find certain limitations.
My last column is for deleting the row and I am passing the id to the standard Trash can Icon. But it is getting included in the search and causing confusion, for a single character search string. For example if I enter 'B', it returns all rows which have 'd' in the hidden ID field. 

It would be great if the options had a property called - search: 'false' , to be excluded from Search

**Comment by gregnb** [comment]
This is a great enhancement idea and I'll put it on the roadmap. Thanks for the feedback @susmita-vps

**Comment by gregnb** [comment]
This support is now available via the `searchable` property for columns
