### ISSUE TITLE
CSV export, escape " in column header name

### ISSUE THREAD

**Issue by jkeruzec** [gregnb/mui-datatables#385]
## Expected Behavior
Export table with header name that contains '"' character.

Opening CSV file will render correct column name.

## Current Behavior

I have this datatable : 
![image](https://user-images.githubusercontent.com/3499632/51668727-2583f700-1fc3-11e9-9908-539df357d8ef.png)

Creating this :
"Year";"4"";"6"";"8"";"12"";"Total"

Escaping should be like : 
"Year";"4""";"6""";"8""";"12""";"Total"

That is displaying correct header in Excel.

Same issue in row value also

See : 
https://stackoverflow.com/questions/17808511/properly-escape-a-double-quote-in-csv

**Comment by jkeruzec** [comment]
```
dqsdqsd
dsq
dqsdqsd
dqs
```

**Comment by gregnb** [comment]
@jkeruzec Wish to send a PR for this one? would love some help here

**Comment by jkeruzec** [comment]
Yeah for sure, I do this quickly as I can

**Comment by gregnb** [comment]
This has been released
