### ISSUE TITLE
Recurring errors flooding console

### ISSUE THREAD

**Issue by aishmitk** [gregnb/mui-datatables#387]
There are two errors which I have no idea how to fix that are thrown anytime a rerender happens:

![image](https://user-images.githubusercontent.com/24919332/51694974-ec05b880-1fcf-11e9-8a9f-5b5a7784130e.png)
I have looked at all the solutions as to how to remove the typography error, to which nothing has worked. Also, I am styling the paper like so: 

`
MUIDataTable: {
          paper: {
            boxShadow: "none"
          },
          responsiveScroll: {
            height: "305px"
          }
        },
`

This has been exactly how it is done in some examples, so I do not understand why it throws an error, because it works too!

**Comment by gregnb** [comment]
The typography issue should be addressed in beta-53. I will look into the other issue tomorrow

**Comment by iChaosren** [comment]
+1

**Comment by william-chu** [comment]
@aishmitk I think I was able to prevent the typography error by applying a custom theme to the table with this typography setting?

createMuiTheme({
  typography: {
    useNextVariants: true,
  },
  overrides: {...}

**Comment by iChaosren** [comment]
@william-chu 
I managed to do the same, but I can't remove the first error message regarding the: Fix the `paper` key
Without removing my styling that is...

If there's a similar solution for the first message I haven't found it.

**Comment by william-chu** [comment]
@iChaosren Hmm, I think I forced the removal of the box shadow on the table by targeting the MuiPaper class instead of MUIDataTable I had to force the override with !important

overrides: {
    MuiPaper: {
      root: {
        boxShadow: "none !important",
       },
    },

**Comment by iChaosren** [comment]
@william-chu 
Awesome!
Thanks!!!

**Comment by aishmitk** [comment]
Sweet, thanks a bunch
