### ISSUE TITLE
Custom encoding when downloading CSV

### ISSUE THREAD

**Issue by Andy1408** [gregnb/mui-datatables#399]
I have to export a csv file with special characters (accent marks) but due to utf-8 exporting Excel does not recognise them. Thanks in advance

**Comment by dom-at-forsharingtodu** [comment]
How to fix this?

**Comment by gabrielliwerant** [comment]
There is a `onDownload` callback which allows you to customize the output. Additionally, you can supply your own download option via `customToolbar`.
