### ISSUE TITLE
Question Material-ui-icons module not found

### ISSUE THREAD

**Issue by RaySheikh** [gregnb/mui-datatables#40]
Hi, 
I'm getting an error "material-ui-icons/clear" not found. After some research i found the material-ui-icons no longer exists. it has been changed to @material-ui/icons. Could this be related?

Thanks, 

Ray

**Comment by gregnb** [comment]
@RaySheikh I am not seeing that issue. look below

```
npm install material-ui-icons --save
npm WARN saveError ENOENT: no such file or directory, open '/Users/gnowakow/testing/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/gnowakow/testing/package.json'
npm WARN material-ui-icons@1.0.0-beta.36 requires a peer of material-ui@^1.0.0-beta.16 but none is installed. You must install peer dependencies yourself.
npm WARN material-ui-icons@1.0.0-beta.36 requires a peer of react@^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN material-ui-icons@1.0.0-beta.36 requires a peer of react-dom@^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN recompose@0.26.0 requires a peer of react@^0.14.0 || ^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN testing No description
npm WARN testing No repository field.
npm WARN testing No README data
npm WARN testing No license field.

+ material-ui-icons@1.0.0-beta.36
updated 1 package in 1.607s
```

**Comment by RaySheikh** [comment]
Thanks for getting back so fast. Perhaps its something else. Below is the error:
./node_modules/mui-datatables/dist/index.js
Module not found: Can't resolve 'material-ui/Checkbox' in 'C:\New folder\TrainingApps\Mui-datatables\ClientApp\node_modules\mui-datatables\dist'

look try to troubleshoot further.

**Comment by victorbueno** [comment]
@RaySheikh  Install exact version of the peer dependency 

`yarn add material-ui-icons@^1.0.0-beta.36`

**Comment by RaySheikh** [comment]
Thanks Victor that did it. I was using beta.42

**Comment by matteo1976** [comment]
I still have the problem
