### ISSUE TITLE
Multiple values in a column

### ISSUE THREAD

**Issue by jesper-bylund** [gregnb/mui-datatables#403]
## Expected Behavior
Adding more than one values to a column prints that value as a separate value, that can be used in filtering.

## Current Behavior
All values are concatenated into a single value (string).

## Steps to Reproduce (for bugs)
Replace a column value with an array of values.

Is this intentional? I've googled around and I can't find a single reference to anyone doing the same thing. The use case should be pretty simple: tags or categories. But I'm not seeing anyone doing this. Tips? Tricks? Ideas?

**Comment by raelmiu** [comment]
Yeah that's what I thought. But whatever I send in is concatenated and I can't follow the rendering, so I haven't found where or how it is concatenated or rendered.

**Comment by gabrielliwerant** [comment]
Is it possible to cobble together some screenshot or find an existing one that demonstrates the functionality you're looking for? It sounds to me like you want to be able to attach metadata to particular data which can be used in filtering. Is that correct, or is there something else?

**Comment by lakshmi-udaan** [comment]
@jesper-bylund Hey, did you find any resolution for the same?

**Comment by jesper-bylund** [comment]
@lakshmi-udaan not working on that project anymore I'm afraid.

**Comment by nasim-alizai-pgl** [comment]
@jesper-bylund 
please try this 
 ```
{
      name: 'vehicles',
      label: 'Vehicle Description',
      options: {
        customHeadLabelRender: (col) => (
          <Box sx={{ whiteSpace: 'nowrap' }}>{col.label}</Box>
        ),
        customBodyRender: (value) => (
          <Box sx={{ whiteSpace: 'nowrap' }}>
            {value.year +
              ' ' +
              value.make +
              ' ' +
              value.model +
              ' ' +
              value.color}
          </Box>
        )
      }
    },
```

**Comment by jesper-bylund** [comment]
Appreciate the effort, by I abandoned this project years ago. Thanks anyway. 🙏
