### ISSUE TITLE
Feature Request: custom values to filter on (not rendered value)

### ISSUE THREAD

**Issue by iKrushYou** [gregnb/mui-datatables#404]
I have some columns where I pass in more than just text (yes, I know I wasn't supposed to do that, but it works :))

I've got a cell that will render the status of the row into a `<Typography>` and sometimes it even adds a `<LinearProgress>` to the cell as well. When it comes to filtering...this poses a problem. I see that I can already pass in a list of options to display for the filters, but this doesn't help when it tries matching on the rendered value. 

Maybe, in addition to the `filterOptions` param, we could add a `filterValue` param which would return the value to be filtered (and **searched** on as well)

            {
                name: 'Status',
                options: {
                    filter: true,
                    customBodyRender: (value, tableMeta, updateValue) => {
                        return <Typography color={'textSecondary'}>{value}</Typography>
                    },
                    filterOptions: ['Powered On', 'Powered Off'],
                    filterValue: (value, tableMeta, updateValue) => {
                        return value
                    }
                }
            },

**Comment by erencay** [comment]
I'm having a similar problem right now, but I think `filterValue` might not be the best option. May be we could extend the usage of `filterOptions` with an object along side the array option. What you think @gregnb?

**Comment by ShiroYacha** [comment]
Well it seems like it's the only way because the `customBodyRender` does not always fire with the full row data... is there any workaround aside for this suggestion?

**Comment by gabrielliwerant** [comment]
Have you tried `filterList` in the column options?

**Comment by iKrushYou** [comment]
Hey @gabrielliwerant, thanks for the response. I'm currently looking at the [example](https://github.com/gregnb/mui-datatables/blob/master/examples/column-filters/index.js)
and [here](https://codesandbox.io/s/focused-dijkstra-r4bkk) and to be completely honest...I have no clue what `filterList` actually does. I'm not really seeing a change in the behavior in the table that would seem related to the input... Please show me what I'm missing because I'm sure I'm just being tired and missing something simple.

Thanks

**Comment by gabrielliwerant** [comment]
With custom filter names and filter logic, you should be able to do just about anything you want with filters (custom logic is coming). See https://github.com/gregnb/mui-datatables/issues/430. This issue might be a duplicate, but I'll change the label if not.

**Comment by gabrielliwerant** [comment]
Custom filter logic is now available in `2.4.0` via `filterOptions: { logic: function }`.
