### ISSUE TITLE
Rendering of filters

### ISSUE THREAD

**Issue by arturoribes** [gregnb/mui-datatables#407]
## Expected Behavior

When filters are rendered as chips, they should show the column name and not only the value. This is particularly noticeable when you have multiple yes/no columns, so you don't know which filter corresponds to which column (e.g. in case you want to remove it)

## Current Behavior

Chips show only the value of the filtered column

## Steps to Reproduce (for bugs)

Filter a column and watch the generated chip

**Comment by gabrielliwerant** [comment]
`customFilterListRender` is now available, as is custom rendering of filters in general in `2.6.0`. See documentation and examples for more information.
