### ISSUE TITLE
Table Height overflowing when 10 rows are showing

### ISSUE THREAD

**Issue by iKrushYou** [gregnb/mui-datatables#409]
Is there a way to get the height of the table to match up with the height of all the rows? It seems like when displaying 10 rows, the last one gets cut off and there's a slight bit of scrolling

https://codesandbox.io/s/k22kzo8zzv

**Comment by gabrielliwerant** [comment]
If you use responsive scroll, you can use the following to set a custom height:

```
const myTheme = createMuiTheme({
  overrides: {
    MUIDataTable: {
      responsiveScroll: {
        maxHeight: '580px'
      }
    }
});

<MuiThemeProvider theme={myTheme}>
      <MUIDataTable ... />
</MuiThemeProvider>
```

Bear in mind that if you have a horizontal scroll bar, it will take up some space at the bottom of the table, so you may want to test that condition to determine what your optimal table height should be.

**Comment by iKrushYou** [comment]
@gabrielliwerant Thanks for the response. I can confirm that this works [here](https://codesandbox.io/s/6yjmqv2xk3)

Will this be the accepted solution or is this just currently a workaround?

**Comment by iKrushYou** [comment]
Also, @gabrielliwerant i know this is out of place, but do you know off-hand how to override hovering over the row to show the cursor hand and /or overriding the active state to highlight darker when being pressed? (I can open a separate issue if need be)

**Comment by gabrielliwerant** [comment]
@iKrushYou I'm unsure of the exact intent, so I don't know whether or not my answer is the accepted solution. But as to your other question, here you go!

```
MuiTableRow: {
      root: {
        cursor: 'pointer'
      },
      hover: {
        '&$root': {
          '&:hover': {
            background: 'gray'
          }
        }
      }
    }
```

**Comment by iKrushYou** [comment]
thanks @gabrielliwerant 
that worked. Of course, it had to be on the `MuiTableRow` and not on the `MUIDataTableRow` as I was trying... 

My intention was to highlight on hover and highlight darker when pressing. Luckily, i was able to change the style to `&:hover:active` and it worked as exptected

**Comment by JReinhold** [comment]
As of [V2.10.0](https://github.com/gregnb/mui-datatables/tree/2.10.0) it is now possible to use the prop `responsive="scrollFullHeight"` to make the table full height and a scroll behavior at the same time. That should fix the issue.

See https://github.com/gregnb/mui-datatables/pull/867
