### ISSUE TITLE
Do not filter on `filterList` if `serverSide` is `true`

### ISSUE THREAD

**Issue by bericp1** [gregnb/mui-datatables#414]
## Expected Behavior

When the `serverSide` option is set to `true` and a `filterList` is provided for a specific column, `mui-datatables` should just render the chips in/below the toolbar but not do any filtering on the data itself.

## Current Behavior

When the `serverSide` option is set to `true` and a `filterList` is provided for a specific column, `mui-datatables` still filters the visible rows provided down to whatever rows contain a column value that matches a value in the `filterList` exactly.

As an example: I have a table which has a column that renders a comma separate list of U.S. states. My filter is a list of U.S. states. My server knows that when I tell it to filter by a state it should include all rows that have that state at least including any rows that also have other states. `mui-datatables` takes over the filtering even though `serverSide` is true and further filters down my already filtered results that came from the server to include incorrect results since it only accept exact matches (whereas some rows contain the correct state but among a comma-separate list of other states).

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   ` 3.5.1`     |
| MUI-datatables  |    `2.0.0-beta-53`     |
| React        |    `16.7.0`     |

**Comment by gregnb** [comment]
@bericp1 Thanks for filing the issue and I agree. Would you like to take this up and send in a PR?

**Comment by bericp1** [comment]
I'll certainly give it a shot if I find the time sometime later this week / this weekend 👍

**Comment by gregnb** [comment]
@bericp1 Good stuff 👍
