### ISSUE TITLE
Would like title to be a render prop

### ISSUE THREAD

**Issue by psdao1102** [gregnb/mui-datatables#419]
## Desired Behavior
either via the title prop, or an options prop, there should be a prop I can use to render a component instead of just the string title.

## Current Behavior
Only a string is available to use for the title

**Comment by psdao1102** [comment]
Also with a little guidance id be willing to submit a PR

**Comment by rcfish** [comment]
I believe this is existing behavior. This works for me.

`const title = (`
`  <React.Fragment>`
`    <Tooltip title="Add Something">`
`      <Button variant="fab" mini color="primary" >`
`        <AddIcon />`
`      </Button>`
`    </Tooltip>`
`  </React.Fragment>`
`)`

`return (`
`  <MUIDataTable`
`    title={title}`
`    data={data}`
`    columns={columns}`
`    options={options}`
`  />`
`);`

**Comment by gabrielliwerant** [comment]
@psdao1102 I concur with @rcfish, the functionality already exists. The code does not currently favor strings over components; either will work: https://github.com/gregnb/mui-datatables/blob/master/src/components/TableToolbar.js#L150.
