### ISSUE TITLE
Column's `customBodyRenderer` is evaluated only at `MUIDatatable` mount

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [gregnb/mui-datatables#421]
I would like to dynamically modify `customBodyRenderer` during the lifetime of the table. The purpose of this is I am providing search highlight for a column, where I change certain column rendering(replacing search term with `<span>`), for each search term.

**Comment by gregnb** [comment]
Where do you propose putting this change? Also consider this could become quite expensive

**Comment by Dragomir-Ivanov** [comment]
I kind of workaround it, so we can close this.
My workaround is that on each search term change, I inject a custom option in column definition, forcing `mui-datatables` to recalculate columns, and thus picking the new `customBodyRenderer` for the highlighted column.
Again, thanks for the awesome component :100:
