### ISSUE TITLE
className prop not being used

### ISSUE THREAD

**Issue by ashams1026** [gregnb/mui-datatables#427]
https://github.com/gregnb/mui-datatables/blob/caf05577c00193c03b2217d562b6604612ddc11f/src/MUIDataTable.js#L116-L117

It looks like somewhere down the line the use of className passed into MIUDataTable stopped being used.

**Comment by gregnb** [comment]
I believe because you can do most of the table styling through the MUI provider. Do you want to send in a PR to clean this up?

**Comment by ashams1026** [comment]
True! New to MUI, so I'm just getting the hang of styling. I was just confused at first cuz I couldn't get it to work, took me a bit to realize it wasn't going anywhere after passing it through props.

Can't quite make any contributions at the moment, unfortunately. Great work btw!

**Comment by seansean11** [comment]
I would actually be interested in getting this to work, so I submitted a PR #486 .  In our project, we would prefer to toggle different styles based on class overrides.
