### ISSUE TITLE
Is it possible to make custom component filter?

### ISSUE THREAD

**Issue by dafapramudya** [gregnb/mui-datatables#430]
## Expected Behavior

There is 4 filter type in mui-datatables: dropdown, checkbox, textField, and, multiselect. Is it possible to make custom filter component in mui-datatables?

For ex: I want to replace that 4 filter type with my own component(for ex: other library).

And, can i use different filterType on each column? for ex:

```
column: [
      {
        name: 'Username',
        options: {
          filter: false,
          sort: false,
          filterType: 'textField',
        },
      },
      {
        name: 'Date',
        options: {
          filter: true,
          sort: false,
          filterType: 'multiselect',
        },
      },
      {
        name: 'Age',
        options: {
          filter: true,
          filterType: 'dropdown',
          sort: false,
        },
      }
]
```

Thank you
## Current Behavior

I already tried this: [link](https://github.com/gregnb/mui-datatables/pull/303/files) but it's not working for me.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.8.2     |
| MUI-datatables  |    2.0.0-beta-53     |
| React        |    16.6.0     |
| browser      |    Chrome     |
| etc          |         |

**Comment by doc82** [comment]
Bump +1

**Comment by PresentProgrammer** [comment]
+1, would be great to have date picker as a filter.

**Comment by Stanley-Okwii** [comment]
Bump +1

**Comment by gabrielliwerant** [comment]
Custom filters are coming, and there's a PR open for it now: https://github.com/gregnb/mui-datatables/pull/578

**Comment by BingyuLiu** [comment]
Bump +1

**Comment by jsnavarroc** [comment]
it works for me, but I when do build production. it doesn't work before

![image](https://user-images.githubusercontent.com/28201235/59045062-f5881280-8844-11e9-8ab6-e7794f1e5f1f.png)

**Comment by jsnavarroc** [comment]
it works for me, but I when do build production. it doesn't work before
![image](https://user-images.githubusercontent.com/28201235/59046062-e013e800-8846-11e9-848f-1d1d6751dc6d.png)

**Comment by gabrielliwerant** [comment]
Yes, you can provide a different filter type for each column via `filterType` on the column options. As of `2.4.0` you can also set custom filter logic via `filterOptions: { logic: function }`.

**Comment by Stanley-Okwii** [comment]
@gabrielliwerant , I recently used customRowRender to build custom rows for the table. Despite including the filter option as a checkbox. I noticed that when I use custom rows, I lose the ability to selection given rows.

**Comment by gabrielliwerant** [comment]
@Stanley-Okwii Your issue doesn't sound like it pertains to custom filters. Can you please up a new issue with specific steps to reproduce your issue so that we may track it separately?

**Comment by Stanley-Okwii** [comment]
okay. cool

**Comment by gabrielliwerant** [comment]
It is now possible, as of `2.6.0`, to add custom rendering for filters, thanks to @Avd6977!

Use `filterOptions: { display: Component }` and `filterType: 'custom'` in the column options.

**Comment by rush2212** [comment]
> 

can you give a example
