### ISSUE TITLE
Deprecated: filterList must now be provided under each column option.

### ISSUE THREAD

**Issue by goalguy10** [gregnb/mui-datatables#432]
I am attempting to use the filterList option but I am getting an error:

Deprecated: filterList must now be provided under each column option. see https://github.com/gregnb/mui-datatables/tree/master/examples/serverside-options example

However I am following the above example exactly. The issue is also effecting the example linked. codesandbox below.

## Expected Behavior

list should be filtered by my filterList on default

## Current Behavior

List is not being filtered

## Steps to Reproduce (for bugs)

https://codesandbox.io/s/32znywpzk5

**Comment by gregnb** [comment]
Sorry please look at this example: https://github.com/gregnb/mui-datatables/blob/master/examples/column-filters/index.js

I will clean that warning up

**Comment by goalguy10** [comment]
Thank you @gregnb! That worked perfectly.
