### ISSUE TITLE
Expand all rows by default

### ISSUE THREAD

**Issue by QuynhNguyen** [gregnb/mui-datatables#433]
Is there a way to expand all rows by default?

**Comment by gabrielliwerant** [comment]
I don't believe so, but if you'd like to work on this as an option, I will review the PR.

**Comment by gabrielliwerant** [comment]
As of `2.7.0`, you can now set the expanded state of all rows in the options. See the release notes for more information.

**Comment by kitaroar** [comment]
I use this code in [options] to expand all rows by default
data is the array to display in table

```
rowsExpanded: data.map((el, i) => {return i}),
```
