### ISSUE TITLE
Accessing event property inside onRowClick

### ISSUE THREAD

**Issue by iKrushYou** [gregnb/mui-datatables#438]
Is it possible to provide access to the event property while inside the `onRowClick` function?

I am trying to access the event's `ctrlKey` and `metaKey` properties so that I can enable opening links in a new tab just as normal hyperlinks would function. I can do so using the regular onClick function seen [here](https://codesandbox.io/s/xozjww4xvq)

**Comment by gabrielliwerant** [comment]
I believe it is already accessible if you add it as the 3rd argument:

```
onRowClick = (rowData, rowMeta, e) => {
    const { ctrlKey, metaKey } = e;
    console.log(ctrlKey, metaKey);
}
```

**Comment by iKrushYou** [comment]
@gabrielliwerant honestly i hate myself for not trying this before posting... but I had read the source [here](https://github.com/gregnb/mui-datatables/blob/671461ca92d45ebe41f33a077cf43a9225fb1b70/src/components/TableBody.js) and didn't see event `onClick={options.onRowClick ? options.onRowClick.bind(null, row, { rowIndex, dataIndex }) : null}`

but I guess I don't quite 100% understand how functions work in ES6 yet

**Comment by gabrielliwerant** [comment]
Haha, no worries, it can be confusing to know which arguments are getting passed along!

**Comment by jdfx** [comment]
This doesn't work with typescript, the type doesnt include the event.
