### ISSUE TITLE
dist folder not updated

### ISSUE THREAD

**Issue by LesterLyu** [gregnb/mui-datatables#439]
After installing `"mui-datatables": "^2.0.0-beta-55"` from npm, `./node_modules/mui-datatables/dist` is not updated: 
![image](https://user-images.githubusercontent.com/7830679/53267503-7ade2180-36b1-11e9-8ee6-e396c3f96f14.png)
![image](https://user-images.githubusercontent.com/7830679/53267527-8a5d6a80-36b1-11e9-8dc6-e6f586bfc17d.png)

Only `package.json` is updated.

**Comment by LesterLyu** [comment]
Run `npm install mui-datatables@2.0.0-beta-54` make it update. I have no idea why I cannot modify `package.json` in my project and then run `npm install`.

**Comment by gregnb** [comment]
https://github.com/npm/npm/issues/20439

**Comment by LesterLyu** [comment]
Thanks for the info!
