### ISSUE TITLE
[BUG]Data as objects Error

### ISSUE THREAD

**Issue by Aaron-Lei** [gregnb/mui-datatables#443]
For example, when I use the last column for actions(buttons for adding,refreshing ..etc operations), the TypeError 'Cannot read property 'toString' of undefined' occurred. The code is as follows:

`import React from "react";
import ReactDOM from "react-dom";
import MUIDataTable from "mui-datatables";

class App extends React.Component {
  render() {

    const columns = [
      {
        name: 'name',
        label: 'Name'
      },
      {
        name: 'company',
        label: 'Company'
      },
      {
        name: 'city',
        label: 'City'
      },
      {
        name: 'state',
        label: 'State',
      },
      {
        label: 'Action',
        name: 'action',
        options: {
          customBodyRender: (value, tableMeta, updateValue) => {
            return <button>Add</button>
          }
        }
      }
    ]

    const data = [
      { name: "Joe James", company: "Test Corp", city: "Yonkers", state: "NY"},
     { name: "John Walsh", company: "Test Corp", city: "Hartford", state: "CT"},
     { name: "Bob Herm", company: "Test Corp", city: "Tampa", state: "FL"},
      { name: "James Houston", company: "Test Corp", city: "Dallas", state: "TX"},
    ];

    const options = {
      filterType: "dropdown",
      responsive: "scroll"
    };

    return (
      <MUIDataTable
        title={"ACME Employee list"}
        data={data}
        columns={columns}
        options={options}
      />
    );
  }
}

ReactDOM.render(<App />, document.getElementById("root"));`

But when I add action='anything' to the data structure, likes 
`const data=[{ name: "Joe James", company: "Test Corp", city: "Yonkers", state: "NY", action: "**anything**"}]`, It works fines, that means I have to change my data structure by adding the properties named the same as action columns names. It is not good specially in the case that the data is fetching from server-side, it can't to change server-side interfaces to meet the rules of mui-datatables.

Did that make sense to you? 
Any response will be appreciated.
@gregnb 

## Expected Behavior

The mui-datatables can avoid mapping the columns that not exist in the data structure
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gabrielliwerant** [comment]
I believe I have a workable solution. Ok if I take this? @gregnb

**Comment by gregnb** [comment]
@gabrielliwerant Sure Gabriel I would like to see what you come up with. Thanks!

**Comment by gregnb** [comment]
@Aaron-Lei so @gabrielliwerant has added a fix for this type of problem:

https://github.com/gregnb/mui-datatables/blob/master/examples/custom-action-columns/index.js

Please take a look into using the `empty` property for columns which are actions
