### ISSUE TITLE
Filter ranges

### ISSUE THREAD

**Issue by fuzunspm** [gregnb/mui-datatables#445]
Is it possible to define or create filters with ranges? Like selecting MIN MAX dates from the filter list or "bigger than this value" etc.. I searched through the docs and examples but couldn't find similar implementation of filters

**Comment by gregnb** [comment]
Someone once mentioned maybe a new filter type like a Slider but this was long ago. I haven't had any time to look into this

**Comment by iamvishalbisht** [comment]
Can we have range filter too ? example money table have lots of values, and if we can give range so those rows will be rendered ? is it possible ?

**Comment by Avd6977** [comment]
I was going to work on something like this, but for date ranges. @gregnb Would it be preferred to make a 'numberRange' and 'dateRange' and maybe 'dateTimeRange' option for filterType?

**Comment by gabrielliwerant** [comment]
There is a PR up now which will provide the ability to add custom filters and will therefore serve this use case. You can follow it here: https://github.com/gregnb/mui-datatables/pull/578. It's almost ready, and I've reached out to the author to see if he/she plans to finish it. If not, I'll finish it up for the next release.

**Comment by gabrielliwerant** [comment]
Custom filter logic is now available in `2.4.0` via `filterOptions: { logic: function }`.
