### ISSUE TITLE
customBodyRender not being called

### ISSUE THREAD

**Issue by brymon68** [gregnb/mui-datatables#449]
Similar issue to #134, but cleaning node_modules did not fix my issue. I am trying to render data in div via dangerouslySetHTML. This data coming back from the server is HTML and I need to stuff that data into a div and add to table to render with styling. 

## Expected Behavior

I expect customBodyRender to to be called. It is never called. I've added debugging statements and even removed references to HTMLObject and instead replaced with a console.log() which was still never executed. 

## Current Behavior
customBodyRender not executed

## Steps to Reproduce (for bugs)
Below is a toy example of customBodyRender not being called: 

`
    class NewAlertTable extends React.Component {
        constructor(props) {
            super(props);
            this.state = {
              columns: [{ 'name': 'fakedata', 'label': 'fakedata' }],
              data: []
            }
        }

    componentDidMount() {
        if (this.props.items.length > 0) {
         this.createColumns();
         const formatteddata = this.createData();
         this.setState({ data: formatteddata })
       }
     }

     createData = () => {
       const dataarray = [];
       this.props.items.forEach(function (element) {
       const dataitem = element.data_with_flair
          dataarray.push(dataitem)
        })
        return dataarray;
     }

      createColumns = () => {
        const columns = [];
        if (this.props.items.length > 0) {
          this.props.items[0].data.columns.forEach(function (element) {
            let columnobj = {
              name: element,
              label: element,
              filter: true,
              customBodyRender: (value, tableMeta, updateValue) => {
                console.log('hey')
                // return(<HTMLObject value={value} />);
              }
            };
            columns.push(columnobj);
          });
          this.setState({ columns: columns })
        }
      }

      render() {
       const options = {
          filter: true,
          filterType: 'dropdown',
        };
        return (
          <MUIDataTable
            // title={"Employeed List"}
            data={this.state.data}
            columns={this.state.columns}
            options={options}
          />
        )
      }
    }

    class HTMLObject extends React.Component {
      constructor(props) {
        super(props);
      }

      render() {
        const { value, index, change } = this.props;

        return (
          <div
            dangerouslySetInnerHTML={{ __html: value }}
            style={{ color: 'red' }}
          />
        );
      }
    }
`

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   latest |
| MUI-datatables  |   2.0.0-beta.56      |
| React        |    16.8.2     |
| browser      |         |
| etc          |         |

**Comment by brymon68** [comment]
This can be closed, apologies. Did not realize I needed to embed customBodyRender in options object.

**Comment by EduVencovsky** [comment]
How did you solved this? What do you mean by `I needed to embed customBodyRender in options object` ?
