### ISSUE TITLE
Filter type per column

### ISSUE THREAD

**Issue by terapepo** [gregnb/mui-datatables#453]
## Expected Behavior
Have a different filter for each column. I would like to pass to the options of the column, something to define which kind of filter it will use. Something like this [issue](https://github.com/gregnb/mui-datatables/issues/430#issue-412363951) 

## Current Behavior
Right now, you can only define the type of filter for the table but not for the column.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  3.9.2      |
| MUI-datatables  |   2.0  |
| React        |    16.8.3     |

**Comment by gabrielliwerant** [comment]
You can do this via the column option `filterType`.
