### ISSUE TITLE
How to get full rowData in customBodyRender? 

### ISSUE THREAD

**Issue by brymon68** [gregnb/mui-datatables#455]
I have a table that I generate columns and data for dynamically. The server provides me with the columns that I should build as well as the data. In one of the columns, I am using customBodyRender to render a <Button> with an onClick handler that will link to another part of the application based on an ID from the dame row. 

I would like to to receive the full row data (Specifically, receive the ID) from the row rather than just the individual cell value in customBodyRender. Is this possible? I tried inspecting the tableMeta value, but it does not contain rowData either. 

## Current Behavior
I only receive the individual cell value, not the entire rowData. 

| Tech         | Version |
|--------------|---------|
| Material-UI  |      latest   |
| MUI-datatables  |      latest   |
| React        |   latest      |
| browser      |         |
| etc          |         |

**Comment by brymon68** [comment]
This can be closed. I was able to get rowData once it fully populated

**Comment by neenu-n** [comment]
@brymon68 , I am facing the same issue. Could u please explain how u resolved this with an example?

**Comment by brymon68** [comment]
@neenu-n - I would recommend setting a breakpoint within customBodyRender. You will eventually only receive the cell data but after enough steps, you will see your entire rowData.

**Comment by cristian-eriomenco** [comment]
> @neenu-n - I would recommend setting a breakpoint within customBodyRender. You will eventually only receive the cell data but after enough steps, you will see your entire rowData.

What o_O?
