### ISSUE TITLE
How to onRowClick: rowData => this.redirectToForm(rowData)?

### ISSUE THREAD

**Issue by anhlu8** [gregnb/mui-datatables#456]
import React, { Component } from "react";
import { Link as RouterLink } from "react-router-dom";
import Link from "@material-ui/core/Link";
import MUIDataTable from "mui-datatables";

class DataTable extends Component {
   state={...}
   redirectToForm = props => (
       <RouterLink to="/edit-form" {...props}/>
     );
   render() {
        const options = {
           onRowClick: rowData => this.redirectToForm(rowData)
         };
    return (
        <Link .../> 
        <MUIDataTable .../>
    )
}

## Current Behavior
I want onRowClick, I'm redirected to a form page related to that row.
When I console.log(rowData) like below, it did console.log that row data.But I can't be redirected to another page.
const options = {
           onRowClick: rowData => console.log(rowData)
         };

## Your Environment

| Tech         | Version |
|--------------|---------|
| @material-ui/core  |    ^3.9.2     |
| MUI-datatables  |     ^2.0.0-beta-54    |
| React        |     ^16.8.1    |
| browser      |   Chrome Version 72.0.3626.119      |
| etc          |         | # @

**Comment by gregnb** [comment]
Sorry @anhlu8 what is your expectation? What are you trying to have happen from inside the onRowClick?

**Comment by anhlu8** [comment]
Hi @gregnb, I want: onRowClick, I'm redirected to page with the route /edit-form and all data from that row will be passed through.

**Comment by gregnb** [comment]
@anhlu8 if you can put up a minimal example in codesandbox I'll try to take a look tonight. thanks

**Comment by anhlu8** [comment]
Thanks @gregnb, here is the link: https://codesandbox.io/s/w7xyr41mrl
In my app, I made ajax call and pass data using react's context, but here in the codesandbox I just used your original sample data. I have comments on lines 24 & 25 explaining what I'm trying to do.

**Comment by gregnb** [comment]
@anhlu8 You should look into withRouter https://reacttraining.com/react-router/core/api/withRouter

Wrap your component in this HOC and then use the `history` prop that is provided todo something like this:

https://stackoverflow.com/questions/31079081/programmatically-navigate-using-react-router

```
onRowClick: (data) => this.props.history.push('/myUrl', 'params');
```

**Comment by anhlu8** [comment]
@gregnb, thank you very much! It worked!

**Comment by PratyushaTN** [comment]
@anhlu8 
I am looking for the same kind of solution..could you elaborate on how you solved this?

**Comment by fluxquantum** [comment]
@anhlu8 @gregnb Thanks for sharing your knowledge and use cases with the community. May I know if this approach will work if we wanted to mutate data on the current page?

For instance, I want onRowClick to update state variable within my component. So instead of just pushing to a new page I was trying to change the one I am currently in.

Example code snippet:

function ViolationLookupResultSet(props) {

    const options = {
        filter: true,
        filterType: "dropdown",
        resizableColumns: true,
        responsive: "standard",
        download: true,
        print: false,
        draggableColumns: {enabled: true, transitionTime: 1},
        selectableRows: 'none',
        rowsPerPageOptions: [5,10,25],
        onRowClick: (rowIndex) => {
            setIsLoading(true)
        }
    };
    
    const [isLoading, setIsLoading] = useState(false)
    let itemProps = props.itemProps[0]

    return (
        <div style={{display: 'table', tableLayout:'fixed', width:'100%'}}>
            <MUIDataTable data={itemProps} columns={columns} 
                options={options} 
                title="Results" 
            />
            <div>{isLoading}</div>
        </div>
    )
}

Thank you for your time.
