### ISSUE TITLE
Expandable rows do not collapse properly after column sorting

### ISSUE THREAD

**Issue by gabrielliwerant** [gregnb/mui-datatables#461]
## Expected Behavior
When an expandable row is opened, and then a column is sorted, thus changing the position of the expanded row, the row should properly collapse when triggered again.

## Current Behavior
Instead of the behavior above, the expandable row does not collapse. I know what the issue is, and I have an incoming PR that I will link here when ready.

## Steps to Reproduce (for bugs)
1. Use an expandable rows table, as in the `expandable-rows` example
2. Expand a row
3. Sort a column such that the position of the expanded row is altered
4. Attempt to collapse the row

## Your Environment
| Tech         | Version |
|--------------|---------|
| Material-UI  | ^3.2.0 |
| MUI-datatables | master#c85118d1aacb5236e5886493b72ca10d6a77c3f9 |
| React  | ^16.2.0 |

**Comment by gregnb** [comment]
Great nice catch. Thanks for fixing this one
