### ISSUE TITLE
Translating filter label 'All' break the filter

### ISSUE THREAD

**Issue by francois-travais** [gregnb/mui-datatables#464]
## Expected Behavior

`filterLabels` in `options` are translated, thus the label 'All' isn't 'All' but 'Tous' (all in French). When the `filterType` is `dropdown`, When selecting the 'All' filter, which is 'Tous' for me, no results are found.

## Current Behavior

I expect to be able to translate the filter label 'All' without breaking the feature.

## Steps to Reproduce (for bugs)

1. Set `options.textLabels.filter.all` to something else than `All`
2. Set `options.filterType` to `dorpdown`
3. Click on one of the filter in one of the column dropdown
4. Click on the filter 'All' of the same dropdown and nothing will be listed

Or simply try it out in this sandbox: https://codesandbox.io/s/jjq6y4j0zv
It's a fork of one the official example.

The problem comes from this line: https://github.com/gregnb/mui-datatables/blob/529307099c96ec5d983f6e4cf0f58a010ebe1c2c/src/components/TableFilter.js#L138

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  | 3.9.1 |
| MUI-datatables  | 2.0.0-beta-54 |
| React        |   16.8.2  |
| browser      |   FF 65.0.1     |
| etc          |         |

**Comment by gregnb** [comment]
Thanks for fixing this!
