### ISSUE TITLE
Question add/remove or modify Icons on selected rows

### ISSUE THREAD

**Issue by RaySheikh** [gregnb/mui-datatables#47]
Good morning, 

Is there a way to add new Icons when selecting a row. Currently there is a delete Icon. I'd like to add an edit or more info icon somewhere and pop a Modal to extract row information. It seems only way to extract row info is by selecting the row and using an `onRowsSelect` function. Is there another way to extract the row information and display it in a popup Modal? if so I can nest a custom button using `customRender ` function.

Thanks for all your work.
Ray

**Comment by gregnb** [comment]
Thanks for your suggestion. Let me think about this some more and get back to you

**Comment by gregnb** [comment]
So what I'm thinking is providing a property on options called `customToolbarSelect` which will look like so:

```
    const options = {
      filter: true,
      selectableRows: true,
      filterType: 'dropdown',
      responsive: 'stacked',
      rowsPerPage: 10,
      customToolbarSelect: (selectedRows) => <CustomToolbarSelect selectedRows={selectedRows} />
    };

    return (
      <MUIDataTable title={"ACME Employee list"} data={data} columns={columns} options={options} />
    );

```

And an example could look like this:

```
import React from "react";
import IconButton from "@material-ui/core/IconButton";
import Tooltip from "@material-ui/core/Tooltip";
import DeleteIcon from "@material-ui/icons/Delete";
import FilterIcon from "@material-ui/icons/FilterList";
import { withStyles } from "@material-ui/core/styles";

const defaultToolbarSelectStyles = {
  iconButton: {
    marginRight: "24px",
    top: "50%",
    display: "inline-block",
    position: "relative",
    transform: "translateY(-50%)",
  },
  deleteIcon: {
    color: "#000",
  },
};

class CustomToolbarSelect extends React.Component {

  handleClick = () => {
    console.log("click!", this.props.selectedRows); // a user can do something with these selectedRow values
  }

  render() {
    const { classes } = this.props;

    return (
      <div className={"custom-toolbar-select"}>
        <Tooltip title={"icon 2"}>
          <IconButton className={classes.iconButton} onClick={this.handleClick}>
            <FilterIcon className={classes.deleteIcon} />
          </IconButton>
        </Tooltip>
        <Tooltip title={"icon 1"}>
          <IconButton className={classes.iconButton} onClick={this.handleClick}>
            <DeleteIcon className={classes.deleteIcon} />
          </IconButton>
        </Tooltip>
      </div>
    );
  }

}

export default withStyles(defaultToolbarSelectStyles, { name: "CustomToolbarSelect" })(CustomToolbarSelect);
```

**Comment by RaySheikh** [comment]
This is great. Thank you for looking into this. This should definitely help when the onSelect option disappears in the mobile version.

Thank you!

Ray

**Comment by RaySheikh** [comment]
Will did option work in the stacked mobile version?
Thanks

**Comment by RaySheikh** [comment]
This is great. Thank you for looking into this. Just curious, will this work on the mobile stacked version?

Thanks!!

**Comment by gregnb** [comment]
Ok, download the latest version and in the examples folder I have an example of a custom toolbar for select

**Comment by RaySheikh** [comment]
This looks great. Thank you for getting this done!
Is there a way to select a row and pop the custom toolbar for the mobile stacked version?

Thanks, 

Ray

**Comment by NickToye** [comment]
Not meaning to want to re-open this, but I feel I need some clarification.  Say I have a column that is a reference number, and I want to display that in the customToolbarSelect component, so I would click a bunch of rows and it would display the reference numbers, rather than just say 3 rows selected.

I couldn't find any info about this.

**Comment by jakesyl** [comment]
One issue I see hear is a user cannot manually delete rows. Is that currently the case?
