### ISSUE TITLE
Body scrolling active when viewColumns toggle is open

### ISSUE THREAD

**Issue by william-chu** [gregnb/mui-datatables#472]
## Expected Behavior
Similar to the rowsPerPage option toggle, the body tag should be given a style of `overflow: hidden` to prevent the user from scrolling the background while selecting the columns to be viewed

## Current Behavior
When you open the viewColumns toggle menu, the body scrolls while the toggle is absolutely positioned in the fixed overlay. When there are multiple tables on a page, the placement of this menu's position should not move since it loses its position in context to the table it belongs to.

## Your Environment

| Tech         | Version |
|--------------|---------|
| @material-ui/core |    ^3.8.2    |
| MUI-datatables  |     2.0.0-beta-50    |
| React        |    ^16.3.1    |
| browser      |   Chrome  72.0.3626.119   |
| etc          |         |

**Comment by gregnb** [comment]
Could you post a video/gif of what you are seeing?

**Comment by william-chu** [comment]
@gregnb Here is a video of it, the rowsPerPage select menu seems to add the overflow: hidden style to the body tag which locks the background scrolling, but the viewColumns does not. https://drive.google.com/file/d/13-PyvFloiuDZ_KJrhiDgNWOs5FA9OQXL/view?usp=sharing

**Comment by gregnb** [comment]
@william-chu thanks for the video. Would you like to look into this issue? Maybe if we set a container

https://material-ui.com/api/popper/

we can inject it in the right place without it being fixed. 

also:
https://material-ui.com/utils/popper/

```
The children is Portal to the body of the document to avoid rendering problems. You can disable this behavior with disablePortal.
```

**Comment by william-chu** [comment]
@gregnb Thanks for the prompt response! I submitted a PR that should disable the body scroll when the filter/viewColumns buttons are selected by removing the container props on these popovers. https://github.com/gregnb/mui-datatables/pull/479
