### ISSUE TITLE
[Bug] with version beta-57 cannot read property 0

### ISSUE THREAD

**Issue by constashare** [gregnb/mui-datatables#476]
When I use the delete function for a few rows, an error is thrown stating cannot read property '0' of the array. But if I select all rows then it works just fine.

## Expected Behavior

The delete function should allow me to delete either one row or all selected rows.

## Current Behavior

Instead of being able to remove one or two rows from the table, an error is thrown stating cannot read property 0. 

## Steps to Reproduce (for bugs)

1. Update the package library to the latest version (beta-57).
2. Select a few rows.
3. Hit the delete button.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |      3.3.0  |
| MUI-datatables  |      2.0.0-beta-57   |
| React        |    16.5.2    |
| browser      |    Chrome
![muidatable-error](https://user-images.githubusercontent.com/18107884/54042798-01f2c580-4199-11e9-9338-6c581e31ef19.PNG)
     |
| etc          |         |

**Comment by gregnb** [comment]
Thanks for finding this issue. I just pushed up a fix to resolve it and it will be in this weekend's release

**Comment by constashare** [comment]
You're welcome.

**Comment by gregnb** [comment]
This should be resolved in the latest release
