### ISSUE TITLE
Custom Toolbar wraps to new line with wide content

### ISSUE THREAD

**Issue by rossknudsen** [gregnb/mui-datatables#485]
When we add an item to the custom toolbar that is too wide it causes the buttons to wrap down to the next line.

## Expected Behavior
When there is plenty of whitespace available to keep the button on the same line, it should not wrap to a new line.

## Current Behavior
Because the flex properties are set the way they are, there is wrapping.  Here is the relevant code:
https://github.com/gregnb/mui-datatables/blob/master/src/components/TableToolbar.js#L21-L27

Is there any reason why these properties are set this way?  How about something like this:

```
  left: {
    flex: '1 1 auto',
  },
  actions: {
    flex: '0 0 auto',
    textAlign: 'right',
  },
```

## Steps to Reproduce (for bugs)
https://codesandbox.io/s/l3143o787?fontsize=14

1. Took the code sandbox example from the documentation
2. Added a wide item as a custom toolbar

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  | ^3.9.2    |
| MUI-datatables  |  2.0.0-beta.56  |
| React        |  16.6  |
| browser      |   Chrome  |

**Comment by gregnb** [comment]
@rossknudsen No good reason. Can you send in a PR?

**Comment by rossknudsen** [comment]
No problem, [here](https://github.com/gregnb/mui-datatables/pull/493) you go.

**Comment by rossknudsen** [comment]
PR merged.  Thanks heaps.
