### ISSUE TITLE
Not able to see and use the checkbox when I reduce the table size to less than 960px.

### ISSUE THREAD

**Issue by KrishnaPayyavula** [gregnb/mui-datatables#495]
Not able to see and use the checkbox when I reduce the table size to less than 960px.

    Thank you very much for contributing to MUI-data tables by creating an issue! ❤️

When I reduce my screen size to less than 960px. I should able to get the check-box in the data table.

  When I reduce the screen size to less than 960px. I am not able to use checkbox functionality. 

1.Install all the MUI-Datatables and all its dependencies and use it in the component .
2.Pass some data to the data table.
3.Reduce the screen size to less than 960px
4.Unable to see the check in the datatable.

| Tech         | Version |
|--------------|---------|
| Material-UI  |  Latest   |
| MUI-data tables  |   ^2.0.0-beta.58 |
| React        |   ^16.6.3      |
| browser      |   Chrome      |
| etc          |         |

**Comment by andresf01** [comment]
Is #481 related with it?

**Comment by andresf01** [comment]
@KrishnaPayyavula It'll work if you override the theme
`
MUIDataTableSelectCell: {
    root: {
        '@media (max-width:959.95px)': {
             display: 'table-cell'
        }
    }
}
`

**Comment by KrishnaPayyavula** [comment]
@andresf01 

Thanks for the help. It's working fine now.

**Comment by gabrielliwerant** [comment]
Closing, as this issue was fixed in a recent release and should no longer be an issue.

**Comment by ericpyle** [comment]
@gabrielliwerant which version or commit was this fixed in? I'm still seeing it in v2.5.1. Notice how the checkbox column disappears when the window width is reduced:

![mui-datatables-issue-495](https://user-images.githubusercontent.com/1125565/61001504-5d8ab680-a325-11e9-863d-26f4ba381579.gif)

**Comment by gabrielliwerant** [comment]
@ericpyle It was fixed before that. It's not in `2.5.1` in clean examples from the codebase. The issue must be something particular to your situation. If you open a codesandbox, I will take a look.
