### ISSUE TITLE
Setting filtertypes at the column level

### ISSUE THREAD

**Issue by aneesha** [gregnb/mui-datatables#500]
Are filtertypes able to be implemented at the column level? I can only seem to set for the whole mui-datatables options level. It would be very useful to set at the column level as a table can contain many field types. 

Also can the textField filter allow entries such as >12, <20 and for ranges of values.

Regards

Aneesha

**Comment by guidouil** [comment]
I will need that to, especially for dates. But you will need to add a range or buttons like bigger or lower... this ain't a simple evolution I guess

**Comment by gabrielliwerant** [comment]
Closing, as this option exists as of `2.6.1`.
