### ISSUE TITLE
file download icon no longer available in core

### ISSUE THREAD

**Issue by spunkedy** [gregnb/mui-datatables#503]
https://github.com/mui-org/material-ui/issues/12344

Should this be a different icon now?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gregnb** [comment]
Please remove mui-databables, rm -rf package-lock.json and npm install mui-datatables. should resolve the issue
