### ISSUE TITLE
Reset search/filter programmatically

### ISSUE THREAD

**Issue by MBCSDave** [gregnb/mui-datatables#505]
Hi,

is it possible to reset search/filter by calling an internal function? In our case we can not combine both, so if a user searches something AND sets a filter afterwards, the search should be resetted and vice versa.

Thank you in advance

David

**Comment by dougllima** [comment]
Hi @gregnb
Any update on this? 
I'm looking forward to triggering search and filter programmatically from `customHeadRender`.
Probably there's a way and I'm missing it, but if it isn't an option and you think it's a valid feature I can implement it!

**Comment by gabrielliwerant** [comment]
I believe these both exist now.

- `filterList` in the column options affects which filters are currently applied to a particular column
- `searchText` in the main table options allows you to set a search term that resets the table to that term

**Comment by valentinalexeev** [comment]
Hi @gabrielliwerant, it seems that while you can directly update ```filterList``` of individual columns it is not possible to force the component to re-render after these changes.

In the code below ```tableColumnsRef``` is a ```React.useRef``` of the value passed to ```columns``` property of the ```MUIDataTable```.

```javascript
    function addDefaultFilters() {
        const tc = tableColumnsRef.current;
        if (tc) {
            tc[0].options.filterList = ['xxx'];
            tc[1].options.filterList = ['yyy'];
            tc[2].options.filterList = ['zzz'];
        }
    }
```

And I can see that the changes to the filters are not applied immediately but only after there is a change in the table data.

Is there a way to apply the filters manually without data change?

**Comment by gabrielliwerant** [comment]
If you want the component to re-render, then you need to store the values in state and update them via setState. There is an example of this in `column-options-update`.

Closing this issue, as functionality has existed for a while.
