### ISSUE TITLE
Question: Why does MUIDataTableBodyCell return 2 table cells

### ISSUE THREAD

**Issue by teadams** [gregnb/mui-datatables#51]
Hi, thank you for this wonderful project.

I'm wondering why the rendor of MUIDataTableBodyCell returns 2 table cells?  I see that you give them eys... but I can't find references to using these keys anywhere.  Thank you
`
class MUIDataTableBodyCell extends React.Component {
  render() {
    const { children, classes, columnHeader, options, ...otherProps } = this.props;
    return [
      <TableCell
        key={1}
        className={classNames({
          [classes.root]: true,
          [classes.cellHide]: true,
          [classes.cellStacked]: options.responsive === "stacked",
        })}>
        {columnHeader}
      </TableCell>,
      <TableCell
        key={2}
        className={classNames({
          [classes.root]: true,
          [classes.responsiveStacked]: options.responsive === "stacked",
        })}
        {...otherProps}>
        {children}
      </TableCell>,
    ];
  }
'
   |         |

**Comment by gregnb** [comment]
One is used for the responsive view and one is for the plain view
