### ISSUE TITLE
Search text box instead of search icon, without clicking icon

### ISSUE THREAD

**Issue by sanjana-ah** [gregnb/mui-datatables#510]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gabrielliwerant** [comment]
Not 100% sure what is being asked, but if you're looking to trigger a search without clicking the search icon, you can use `searchText` to update the search term however you wish.

**Comment by foxbit19** [comment]
Not sure if @sanjana-ah experimented the same issue but I'm not able to trigger a search updating `searchText` on runtime. I'm using a custom textbox outside the datatable.

**Comment by gabrielliwerant** [comment]
@foxbit19 There are known bugs with this feature at the moment. Try the `master` branch, as I just merged in https://github.com/gregnb/mui-datatables/pull/647, which should help. It will be in the next release.

**Comment by gabrielliwerant** [comment]
I believe this issue was resolved, so closing this unless there is an example which demonstrates otherwise.
