### ISSUE TITLE
weird `allRowsSelected` state after setting `rowsSelected` and clicking checkbox in context of filter

### ISSUE THREAD

**Issue by ericpyle** [gregnb/mui-datatables#514]
My app is setting `options.rowsSelected` to allow user to select checkboxes `onRowClick`. However, this is leading to weird behavior in `onRowsSelect` where `allRowsSelected` will have the right `dataIndex` but the wrong [row]`index` in the context of a filter.

In the console below, you can see the first `allRowsSelected` is fine after clicking the first checkbox the first time (`index: 0`), but then after setting `rowsSelected: [32]`, the next time I click the same checkbox to disable it, you can see that the same (`dataIndex: 32`) now has two indexes (`index: 32` and `index:0`).

![image](https://user-images.githubusercontent.com/1125565/54839316-a1837e00-4c98-11e9-8dfe-0f9fb9664e9c.png)

## Expected Behavior

Expected that after setting `rowsSelected` to `[32]`, clicking the checkbox again would result in `allRowsSelected` to be empty `[]` rather than having two duplicate `dataIndexes`.

## Steps to Reproduce (for bugs)

1. Apply a filter (via UI)
2. Click checkbox (where `dataIndex > 0`) and in `onRowsSelect` change app state (e.g. via redux) so that a `options.rowsSelected` eventually receives all the dataIndexes reported in allRowsSelected.
3. Click same checkbox and notice duplicates in allRowsSelected, rather than empty array.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  3.9.2       |
| MUI-datatables  |   2.0.0-beta.58      |
| React        |  16.3.0       |
| browser      | Chrome    |

**Comment by kliu4** [comment]
Have this been resovled? I have the same problem using version 2.0.0-beta.59
