### ISSUE TITLE
mui-datatables not compiling due to missing module

### ISSUE THREAD

**Issue by adriangabardo** [gregnb/mui-datatables#515]
The dist/index.js is importing an icon from MUI called FileDownload but it's not available anymore. Therefore, it's causing a compilation error due to the missing icon. When I changed it to another icon from MUI inside the dist/index.js file, my application compiled without errors.

## Expected Behavior
To render without problems.

## Current Behavior
Returns this error:
`./node_modules/mui-datatables/dist/index.js
Module not found: Can't resolve '@material-ui/icons/FileDownload' in '/home/adrian/Fingermark/cleanup/node_modules/mui-datatables/dist'`

## Steps to Reproduce (for bugs)

1. use mui-datatable
2. `npm install`
3. `npm start`

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.9.0     |
| MUI-Icons | 3.0.2 |
| MUI-datatables  |    2.0.0-beta.59     |
| React        |    16.6.3     |

**Comment by stevenpersia** [comment]
I'm in the same situation since this morning.

**Comment by adriangabardo** [comment]
@stevenpersia I dropped mui-datatables altogether and just used the Material UI components altogether, it's extremely simple. Shoot me a message if you want some help sorting it out.

**Comment by gregnb** [comment]
FileDownload is not in the latest release. @adriangabardo try deleting node_modules, package-lock.json and reinstalling. 

```
 gregn  ~/code/test-bug  grep -Hr FileDownload node_modules/mui-datatables/dist/index.js
 gregn  ~/code/test-bug  1 
```

**Comment by adriangabardo** [comment]
Not using the dependency anymore so can't test if that works. Thanks for the return though @gregnb.

**Comment by Slethael** [comment]
I had the same issue, and what I did was the following :

- Remove the mui-datatables entry from package.json
- npm cache clear --force && npm dedupe (picked from various SO threads)
- Remove node_modules folder and package-lock.json file
- npm install --save mui-datatables

And it started working again. Thanks for the tips @gregnb !

**Comment by stevenpersia** [comment]
Thank you for your fast answer @gregnb and for your proposal @adriangabardo. It works fine !

**Comment by jkeruzec** [comment]
Try this solution but I'm back with 2.0.0-beta-54 ....

**Comment by FrontendSSIT** [comment]
1.npm install
2. npm start
It worked.
