### ISSUE TITLE
Expand row from code

### ISSUE THREAD

**Issue by simonkaspersen** [gregnb/mui-datatables#518]
Is it possible to expand rows from code? 
I am currently loading data from server, and based on parameters I want to expand rows if they match.

## Expected Behavior

Expand row outside of the table
## Current Behavior

Only possible to expand in the built in expand, and on rowclick
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gabrielliwerant** [comment]
This is now possible as of `2.7.0`. See the release notes for more information.
