### ISSUE TITLE
Theme Override Works but Generates a Console Error

### ISSUE THREAD

**Issue by cwbuecheler** [gregnb/mui-datatables#519]
## Expected Behavior
Creating a theme override function in order to add some custom styling to mui-datatables should both work and not generate any console output.

## Current Behavior
The custom styling works correctly, but the following error is generated:

```error
Warning: Material-UI: you are trying to override a style that does not exist.
Fix the `paper` key of `theme.overrides.MUIDataTable`.
```

## Steps to Reproduce (for bugs)

Code Sandbox: https://codesandbox.io/s/n7l0r5m214

Edit 1 - Note: you have to click the "project view" slider for this sandbox to show anything. I don't know why. First time using this site.

Edit 2 - Oh, it's because I put the code in index.js, I bet. Oh well.

1. Create a table
2. Wrap it in a `MuiThemeProvider` component
3. Create some theme overrides, specifically overriding `MUIDataTable: { root: {} }`
4. Note that your overrides have worked
5. ... but check your console for an error

This is the code that causes the issue:

```es6
const theme = () =>
  createMuiTheme({
    overrides: {
      MUIDataTable: {
        paper: {
          width: '100%',
          maxWidth: '100%',
        },
      },
  });
```

**Note:** I tried overriding `root` instead of `paper`, but the styles don't get applied in that case.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   ^3.9.2      |
| MUI-datatables  | ^2.0.0-beta.56        |
| React        |  ^16.8.1       |
| browser      |  Google Chrome (latest)      |
| etc          |         |

**Comment by gabrielliwerant** [comment]
The way the jss compiles.

```
MUIDataTable: {
    paper: {
      width: '100%',
      maxWidth: '100%'
    }
  }
```
is looking for a class that will compile to something like this: `MUIDataTable-paper-[id]`. That class does not exist, and that is why you are getting the error.
