### ISSUE TITLE
Compatablity Issue?

### ISSUE THREAD

**Issue by teadams** [gregnb/mui-datatables#52]
I'm wondering if I have a compatibility issue.

Theses are the versions I have
    "material-ui": "^1.0.0-beta.47",
    "mui-datatables": "^2.0.0-beta-6",

I get the following error when I try to follow your example:
./node_modules/mui-datatables/dist/index.js
Module not found: Can't resolve '@material-ui/core/Checkbox' in 'C:\Users\tracy\resrent-interface-tracking-ui\node_modules\mui-datatables\dist'

Funny, I checked and my material-ui does have a Checkbox.

**Comment by gregnb** [comment]
You will need to upgrade to the latest version of material-ui which comes under @material-ui/core

**Comment by teadams** [comment]
I am also able to import Material UI checkbox into my project directly, so it's there.

It's weird it  failing on Checkbox and not on Paper, which is the first listed in the dist.

**Comment by gregnb** [comment]
Upgrade to the latest version of material-ui

```
npm install @material-ui/core
```

mui-datatables no longer depends on the beta and is now using the stable version release

**Comment by teadams** [comment]
Thanks you,  I did that. Now I get
./node_modules/mui-datatables/dist/index.js
Module not found: Can't resolve '@material-ui/icons/Clear' in 'C:\Users\tracy\resrent-interface-tracking-ui\node_modules\mui-datatables\dist'

Things move fast!

**Comment by gregnb** [comment]
also

```
npm install @material-ui/icons
```

**Comment by teadams** [comment]
that did the trick, thank you very much

**Comment by arjunvijayvargiya** [comment]
@gregnb can you please add those two steps of installation on readme
