### ISSUE TITLE
Searchbar closes on clicking Filter icon but not vice versa. Bad UX.

### ISSUE THREAD

**Issue by aliaanis** [gregnb/mui-datatables#528]
## Expected Behavior

   The searchBar is supposed to display what the user is search currently. If it closes , UX message is there is no searching going on.

## Current Behavior
   After entering some value in searchbar, on clicking Filter icon, search bar closes. But the opposite is not true.

|mui-datatables| ^2.0.0-beta.56|
|react|^16.8.3|
|@material-ui/core| ^3.9.2|
|@material-ui/icons|^3.0.2|

**Comment by gabrielliwerant** [comment]
This doesn't look like it is still an issue as of version `beta.59`.

![capture](https://user-images.githubusercontent.com/1779564/56450102-550b7c80-62f0-11e9-83d4-1ad4515f81d4.gif)

**Comment by gregnb** [comment]
Should be resolved upgrade to the latest version 2.0.0
