### ISSUE TITLE
Browser Issues

### ISSUE THREAD

**Issue by teadams** [gregnb/mui-datatables#53]
Are there browser considerations?  In Edge, it is absolutely beautiful.  In chrome, the table is on it's side. (attached)
![chrome](https://user-images.githubusercontent.com/9733826/40094161-67f478fa-5893-11e8-9c8e-e621977903b5.JPG)

**Comment by gregnb** [comment]
The screenshot looks fine to me I'm not sure what you mean by 'on its side' ?

**Comment by teadams** [comment]
Attached is the Edge screenshot.. the column names are across the top and each line of data is in a row.

In Chrome, the column names are on the left repeated over and over. (looks like a mobile view perhaps except I am on a browser).
![edge](https://user-images.githubusercontent.com/9733826/40094381-abf0c6d4-5894-11e8-89f6-cf94e5905e1c.JPG)

**Comment by gregnb** [comment]
Looks fine to me 

https://wy2rl1nyzl.codesandbox.io/

![screen shot 2018-05-15 at 11 11 00 pm](https://user-images.githubusercontent.com/19170080/40094478-504097c8-5895-11e8-8576-b6887b365471.jpg)

**Comment by teadams** [comment]
Yeah, I get the same as you in Chrome in the sandbox.

Is there something that toggles one of the views verses the other?

Thanks,
Tracy

**Comment by gregnb** [comment]
The only reason the 'stacked' view should trigger is if you get into the mobile breakpoint
