### ISSUE TITLE
How to access nested object properties in columns

### ISSUE THREAD

**Issue by raikusy** [gregnb/mui-datatables#531]
Hello, I am passing an array of objects in **data** prop. Those objects in the array have some nested objects. I need to access the nested object properties. How can I do that?
Demo data:
```javascript
const data = [
{
    id: 1,
    person: {
      name: "Bla"
    }
  },
  {
    id: 2,
    person: {
      name: "Lol"
    }
  }
]
```
Expected column:
```javascript
<MUIDataTable
title="Person List"
columns={
  [{
      name: 'id',
      label: 'ID',
      options: {
        filter: true,
        sort: true,
      }
    },
    {
      name: 'person.name',
      label:  'Person Name',
      options: {
        filter: true,
        sort: false,
      },
    },
  ]
}
data={history}
/>
```
So all I want is to show the person name in column. How can I do that? The `person.name` in above code doesn't work.

**Comment by MBCSDave** [comment]
I think the only way you have is to flatten your data structure.

**Comment by wdh2100** [comment]
var flattenObject = function(ob) {
  
  return Object.keys(ob).reduce(function(toReturn, k) {

    if (Object.prototype.toString.call(ob[k]) === '[object Date]') {
      toReturn[k] = ob[k].toString();
    }
    else if ((typeof ob[k]) === 'object' && ob[k]) {
      var flatObject = flattenObject(ob[k]);
      Object.keys(flatObject).forEach(function(k2) {
        toReturn[k + '.' + k2] = flatObject[k2];
      });
    }
    else {
      toReturn[k] = ob[k];
    }

    return Object.keys(toReturn).map(function(_) { return toReturn[_]; });
  }, {});
};

var data  = [
{
    id: 1,
    person: {
      name: "Bla"
    }
  },
  {
    id: 2,
    person: {
      name: "Lol"
    }
  }
];

var arrayValues = data.map( (_data) =>{return flattenObject(_data)});

console.log(arrayValues);

**Comment by raikusy** [comment]
@wdh2100 Hey! Thanks for your reply. I was able to flatten my object using your code. But problem is, in my real data there are many unused properties, which I don't want to show in columns. I want to show specific items in columns. How can I do that?

**Comment by raikusy** [comment]
Hey thanks for all the response. My problem is solved.
```javascript
function flattenObject(ob) {
  const toReturn = {};

  Object.keys(ob).map(i => {
    if (typeof ob[i] === 'object' && ob[i] !== null) {
      const flatObject = flattenObject(ob[i]);
      Object.keys(flatObject).map(x => {
        toReturn[`${i}.${x}`] = flatObject[x];
        return x;
      });
    } else {
      toReturn[i] = ob[i];
    }
    return i;
  });
  return toReturn;
}
```
I got data like:
```javascript
{
  id: 2,
  "person.name": "Lol"
}
```

**Comment by Gokhan1990** [comment]
i didnot like that how to use sub object without flatten

**Comment by CastilloCamila** [comment]
With option  enableNestedDataAccess: "." you can access to nested data

**Comment by pradeepdev001** [comment]
Just add <enableNestedDataAccess: '.',> in option object.
 For Example:
 
 const options = {
      filter: true,
      filterType: 'dropdown',
      responsive: 'vertical',
      enableNestedDataAccess: '.', // allows nested data separated by "." (see column names and the data structure above)
 };
    
    
Ref: [Link](https://github.com/gregnb/mui-datatables/blob/master/examples/data-as-objects/index.js)

**Comment by alitechprogramming** [comment]
> Just add <enableNestedDataAccess: '.',> in option object. For Example:
> 
> const options = { filter: true, filterType: 'dropdown', responsive: 'vertical', enableNestedDataAccess: '.', // allows nested data separated by "." (see column names and the data structure above) };
> 
> Ref: [Link](https://github.com/gregnb/mui-datatables/blob/master/examples/data-as-objects/index.js)

You are the hero, this solved the problem for me! Thank you very much!
