### ISSUE TITLE
how remove checkbox on each row

### ISSUE THREAD

**Issue by gangakrishh** [gregnb/mui-datatables#536]
how remove checkbox on each row if i'm using ```MUIDataTable```

**Comment by pdreddy** [comment]
const options = {
         
          selectableRows:false,
]

**Comment by gangakrishh** [comment]
@pdreddy thanks for response.

**Comment by ZeeshanSafdarZee** [comment]
Thanks @pdreddy

**Comment by haase1020** [comment]
I think the current syntax is `selectableRows: "none"`
