### ISSUE TITLE
How to add an Icon in column in MUI Data table

### ISSUE THREAD

**Issue by getinfyKiranreddy** [gregnb/mui-datatables#543]
I want to add an Icon in column and I have tired to add icon in options but It was not getting an Icon. Can anyone help me out 
Thanks

**Comment by MBCSDave** [comment]
Which kind of icon do you want to display? Inside the body cells or in the header?

**Comment by gabrielliwerant** [comment]
There is an example of how to do this here: https://github.com/gregnb/mui-datatables/blob/master/examples/custom-action-columns/index.js

**Comment by patelmilanun** [comment]
This button with `selectableRowsOnClick=true` option produce weird behavior.
If we click on the button it also selects the row which is not we want right!

**Comment by gabrielliwerant** [comment]
@patelmilanun This is consequence of how events work in the browser. If you want to prevent the click event of a button from traveling up the DOM tree (and activating the row click listener) then you have to stop the propagation of the event with `e.stopPropagation();`.

**Comment by patelmilanun** [comment]
> @patelmilanun This is consequence of how events work in the browser. If you want to prevent the click event of a button from traveling up the DOM tree (and activating the row click listener) then you have to stop the propagation of the event with `e.stopPropagation()`.

Thanks
