### ISSUE TITLE
Filtering Based on Multiple Values in Same Cell

### ISSUE THREAD

**Issue by DevelopmentByDavid** [gregnb/mui-datatables#546]
Hi there,

I think I have a use case that is not covered currently or I am overlooking something.

Currently, I have a column to hold "tags" for particular row entries displayed in the table.  I want to be able to filter based on each individual tag. 

Is there currently a way to do this? If there is not, then I would be happy to open a PR.  I just want to make sure that I am not overlooking a way that already exists to accomplish my use case. 

I have put pictures below to help give a better idea of what I want to do.

![image](https://user-images.githubusercontent.com/44346401/55679125-bd069f80-58ba-11e9-9bc5-ad6d19e82df7.png)

![Screenshot from 2019-04-06 22-25-17](https://user-images.githubusercontent.com/44346401/55679138-e293a900-58ba-11e9-8740-e08e504be251.png)

**Comment by emsies** [comment]
How did you manage to display several values in the one cell? im currently working on this and im stumped

**Comment by emsies** [comment]
How did you manage to display several values in the one cell? im currently working on this and im stumped

**Comment by DevelopmentByDavid** [comment]
Hi @emsies 
I used `customBodyRender` in the column options.  Example is found here https://github.com/gregnb/mui-datatables/blob/247b6703015edb404730ef39a9c83a760a3225b8/examples/component/index.js#L29-L37

Hope this helps!

**Comment by emsies** [comment]
fantastic, thank you!

**Comment by mohnda** [comment]
@DevelopmentByDavid can you please share how you display multiple tags as shown in your screenshot?

**Comment by DevelopmentByDavid** [comment]
@mohnda Yes!  Here is an [example](https://github.com/gregnb/mui-datatables/blob/master/examples/array-value-columns/index.js). 

Important bits: 

The tag column label:
```
// rest of column labels,
{
        name: 'Tags',
        options: {
            filter: true,
            filterType: 'multiselect',
            customBodyRender: (value) => {
                return value.map( (val, key) => {
                    return <Chip label={val} key={key} />;
                });
            }
        }
}
```

The tag data (which is the last column in this case):
```
["Gabby George", "Business Analyst", "Minneapolis", 30, "$100,000", ['nice', 'preferred']],
["Aiden Lloyd", "Business Consultant", "Dallas",  55, "$200,000", ['grumpy', 'second-choice']],
["Jaden Collins", "Attorney", "Santa Ana", 27, "$500,000", ['frequently-busy', 'leave-message']],
```



Hope this explains it!
