### ISSUE TITLE
How to format table head cell individually (cells with labels)?

### ISSUE THREAD

**Issue by dandrei** [gregnb/mui-datatables#547]
Hey everyone,

Using `mui-datatables` `2.0.0-beta.59` and I'm wondering: is there a way to format the table head cells individually (the label cells)?

Use case: I want to left-align the content of certain columns and right-align others. I can do that because I can display JSX in the table cells. But then the column title is out of alignment with the content.

I can only specify column labels as text. If I use JSX as a label, the app crashes if I click on the table head cell (might have to do something with the sorting arrow being added at that time).

Any solution? Thanks!

**Comment by gabrielliwerant** [comment]
Check out the `customize-columns` example here: https://github.com/gregnb/mui-datatables/blob/master/examples/customize-columns/index.js.

You can use `customHeadRender` to specify how each column header renders, like
```
customHeadRender: (columnMeta, updateDirection) => (
  <th key={2} onClick={() => updateDirection(2)} style={{ cursor: 'pointer' }}>
    {columnMeta.name}
  </th>
)
```

**Comment by dandrei** [comment]
Thanks @gabrielliwerant 

That does change how the cell is rendered. But some functionality is lost (arrow showing sort direction doesn't appear).

**Comment by gabrielliwerant** [comment]
Correct, if you choose to customize it, you will have to provide your own icons and transition behavior, but if you look under the hood at how it's implemented in the library, it may give you some ideas.

**Comment by dandrei** [comment]
Turns out it was really easy to do:

    customHeadRender: (o, updateDirection) => {
        return <th onClick={() => updateDirection(o.index)} style={{fontWeight: 400, cursor: "pointer"}}>
            {o.label}
            <TableSortLabel active={o.sortDirection !== null} direction={o.sortDirection || ""}/>
        </th>;
    }

**Comment by ZeeshanSafdarZee** [comment]
@dandrei Thanks. I really need this.
