### ISSUE TITLE
Small Typo?

### ISSUE THREAD

**Issue by teadams** [gregnb/mui-datatables#55]
When I select a checkbox, it says "1 row deleted" and has a trash can on the right.

I believe this should say "1 row selected"  because the row is not actually deleted until you hit the trash can.
![deleted](https://user-images.githubusercontent.com/9733826/40095802-da1665d0-589b-11e8-9d0a-4a3bd7a41eff.JPG)

**Comment by gregnb** [comment]
Good catch, do you want to send a PR for this? This along the docs enhancements are some nice suggestions. Could be a good way for you to get started by adding value to the project
