### ISSUE TITLE
Detect before row deletion to prevent rows delete on some server condition.

### ISSUE THREAD

**Issue by mageshkumar1598** [gregnb/mui-datatables#557]
I am trying to prevent row deletion if the condition doesn't not meet. Now I can able to do that only after row deletion in onRowsDelete() method.Kindly help me with this.

**Comment by gabrielliwerant** [comment]
I've got a PR up that might help. The idea is that returning false from onRowsDelete will prevent a delete action from taking place. There will be an example in the code to demonstrate this as well.
