### ISSUE TITLE
Question: Can customRender be the name of a function?

### ISSUE THREAD

**Issue by teadams** [gregnb/mui-datatables#56]
Can customRender be the name of a function instead of the full function?

I tried and it did not work, but I may have the syntax wrong.

**Comment by gregnb** [comment]
Show me how you're implementing

**Comment by teadams** [comment]
}, {
      name: "b",
      options: {
        filter: true,
        customRender: handleRender (index, value, updateValue)
    }
  }

**Comment by gregnb** [comment]
If handleRender is a function you defined just simply change it to 

```
 {
name: "b",
options: {
filter: true,
customRender: handleRender
}
```
