### ISSUE TITLE
Search tooltip stays visible after closing search bar

### ISSUE THREAD

**Issue by jimdis** [gregnb/mui-datatables#561]
## Expected Behavior
In the [official example](https://codesandbox.io/s/wy2rl1nyzl) as well as my own code, there should be no tooltip visible after opening and then closing the search bar.

## Current Behavior

When closing the search bar by clicking the "X", the "Search" tooltip appears under the search icon and stays there until mouse hovers over the search icon again or mouse clicks anywhere.
## Steps to Reproduce (for bugs)

1. Goto: https://codesandbox.io/s/wy2rl1nyzl
2. Click search icon
3. Close search bar
4. See the tooltip showing up beneath search icon.

## Your Environment

Reproduced on Mac using latest versions of browsers (safari, chrome, firefox) and iOS 12.2 (safari).

**Comment by gabrielliwerant** [comment]
Nice catch. Looks like a nice, simple first issue if you'd like to add the fix!

**Comment by jimdis** [comment]
I'm still a n00b just starting to learn React! But I'll put it on my to learn-list and see if a fix is still needed when I get there..

**Comment by gabrielliwerant** [comment]
Closed via https://github.com/gregnb/mui-datatables/pull/606
