### ISSUE TITLE
Add Button in Table

### ISSUE THREAD

**Issue by mehuljariwala** [gregnb/mui-datatables#567]
Hello Team,
I really like this mui-datatables such a amazing feature but if add feature is have then it would be good to implement CRUD Operations.

**Comment by Beamanator** [comment]
1. How would you implement Create?
1. Same with Read? The table displays data you give it.
1. Update -> just add a link to the selected row via `customToolbarSelect`, and implement your own 'update' function
1. You can implement your own Delete function with `onRowsDelete`

**Comment by Legogris** [comment]
You can do this already using `customBodyRender`, just put whatever controls (e.g. Button(s)) there for each column.

**Comment by gabrielliwerant** [comment]
As others have said, you can do this via customizations already available. Have a look at the example here to get you started: https://github.com/gregnb/mui-datatables/blob/master/examples/custom-action-columns/index.js.

**Comment by eminence88th** [comment]
> As others have said, you can do this via customizations already available. Have a look at the example here to get you started: https://github.com/gregnb/mui-datatables/blob/master/examples/custom-action-columns/index.js.

Can I add more than 1 button in  a column?
