### ISSUE TITLE
CSV download data with selected columns

### ISSUE THREAD

**Issue by CristhianF7** [gregnb/mui-datatables#568]
Is there any way to download the csv just with the columns selected?

Columns: number | code | name
Selected Columns: number

CSV Output:
![Screenshot from 2019-04-18 18-23-32](https://user-images.githubusercontent.com/14883029/56396966-177ef480-6207-11e9-99a0-9e9f1b4fc818.png)

**Comment by CristhianF7** [comment]
Also, if it's something easy I can send you the PR

**Comment by gabrielliwerant** [comment]
You could do this in your own project now with a bit of effort by using the `customToolbarSelect` to add an option to download to CSV. You can try pulling in `createCSVDownload ` from the `utils.js` file and passing it the appropriate data.

Making it available out of the box as an option might be a good enhancement for the future depending on how @gregnb feels about it.

My proposal would be to have an option in `downloadOptions` like `selectedOnly` which when toggled to `true`, would automatically add the download icon to the selection toolbar.

**Comment by gregnb** [comment]
@gabrielliwerant So there are a couple of options people have wanted in re: to CSV downloads (ie: show filtered data only) we should try to group all the requests together then figure out what the options will look like

**Comment by gabrielliwerant** [comment]
This should eventually be closed by the PR open here: https://github.com/gregnb/mui-datatables/pull/440

**Comment by gabrielliwerant** [comment]
This functionality is now available in `2.7.0` (See release notes for more information).
