### ISSUE TITLE
Release of new npm package?

### ISSUE THREAD

**Issue by MBCSDave** [gregnb/mui-datatables#571]
Hi, 
is it possible to get a new release of the package, or is there some work which has to be done before?

Best regards
David

**Comment by gregnb** [comment]
I’ll do a release today sorry for delay

**Comment by MBCSDave** [comment]
No worries. Thank you for your effort.

**Comment by gregnb** [comment]
Ok released mui-datatables@2.0.0

**Comment by cpetit-sigma-fr** [comment]
Hello,

I found release 2.0.0 on https://yarnpkg.com/en/package/mui-datatables but it seems you forgot to tag the release on GitHub, cf. https://github.com/gregnb/mui-datatables/releases.

Thanks for that great work!
