### ISSUE TITLE
An option to remove delete icon?

### ISSUE THREAD

**Issue by schatterjee-erwin** [gregnb/mui-datatables#579]
Hello,

I would like to know whether mui-datatable has an option to remove the delete icon from the toolbar when selecting rows. 

Thanks,
Sourav

## Expected Behavior

Not exactly a bug, but basically on selecting rows I want the delete icon to be removed and have the toolbar say {number} rows selected.

## Current Behavior

The current behavior shows the delete icon along with how many rows selected
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gabrielliwerant** [comment]
Why yes you can! You can customize this toolbar with the following option:

![image](https://user-images.githubusercontent.com/1779564/56841233-758c8700-685a-11e9-8e6d-14e53dcd4e36.png)

The quickest way to remove the delete icon is to supply `customToolbarSelect: () => {}` to the options object.

**Comment by schatterjee-erwin** [comment]
Thanks @gabrielliwerant . I got it to work! 👍

**Comment by gabrielliwerant** [comment]
Glad to hear it! Closing this issue,

**Comment by gabrielliwerant** [comment]
@TKdevlop It looks like you are using React hooks, which is a feature introduced in react v16.8, but the mui-datatable library is not at this version yet. Until then, you may need to avoid using hooks with this library. Try your code without them, and see if it works then.

**Comment by ShqipognjaLL** [comment]
How to remove the header showing "selected rows" and row number?
