### ISSUE TITLE
Module not found: Can't resolve '@material-ui/icons/Clear' in V.2.0.0

### ISSUE THREAD

**Issue by matteo1976** [gregnb/mui-datatables#584]
when I compile I have this error:
Module not found: Can't resolve '@material-ui/icons/Clear' in '/myapp/node_modules/mui-datatables/dist'

I have :    
    "mui-datatables": "^2.0.0",
     "material-ui-icons": "^1.0.0-beta.36",
    "@material-ui/core": "^3.8.3",
    "react": "^16.0.0",

and I use Yarn to install packages
Thanks!

**Comment by matteo1976** [comment]
my mistake...
I had material-ui-icons": "^1.0.0-beta.36"...
and it doesn't work
I had installed @material-ui/icons  "@material-ui/icons": "^3.0.2",
with yarn add @material-ui/icons
and works now

**Comment by seta-hungDang** [comment]
Hi @matteo1976, I am having this same error. It happen when I use create-react-app as well as codesanbox. I also did the same things as you had done without any success. How did you resolve it?

**Comment by ivanemoje** [comment]
I deleted any .lock files, such as package-lock.json and yarn.lock, run `yarn install` and `yarn start`. Works now

**Comment by seta-hungDang** [comment]
What I did is to install Mui-datatables 2.0.0 with Material-UI 1.0.0. They work well for me
