### ISSUE TITLE
Always show select column (checkboxes) on a small viewport

### ISSUE THREAD

**Issue by kukuhsul** [gregnb/mui-datatables#593]
## Expected Behavior

I want the select column (checkboxes) is still shown eventhough on a small viewport. I dont find any configuration in the documentation to match those behaviour. Is there anything I'm missing?

## Current Behavior

In the current version, select column is hidden on a small viewport. 

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |3.9.3|
| MUI-datatables  |2.0.0|
| React        |16.8.4|
| browser      |Chrome|
| etc          |         |

Great work btw, thanks!

**Comment by gabrielliwerant** [comment]
This issue was fixed here https://github.com/gregnb/mui-datatables/pull/581 and will be in the next release, so stay tuned. If you want to experiment with it now, you can pull from `master`.

**Comment by kukuhsul** [comment]
That would be great. Thank!

**Comment by gabrielliwerant** [comment]
Closed via https://github.com/gregnb/mui-datatables/pull/581.
