### ISSUE TITLE
@material-ui/core 4.0.0-beta.1 Warning: Function components cannot be given refs.

### ISSUE THREAD

**Issue by dandrei** [gregnb/mui-datatables#595]
When using `@material-ui/core` `4.0.0-beta.1` & `mui-datatables` `2.0.0` I get the following warning:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Tooltip`.
    in ViewColumnIcon (created by Tooltip)
    in Tooltip (created by WithStyles(Tooltip))
    in WithStyles(Tooltip) (created by l)
    in span (created by ForwardRef(IconButton))
    in button (created by ButtonBase)
    in ButtonBase (created by ForwardRef(ButtonBase))
    in ForwardRef(ButtonBase) (created by WithStyles(ForwardRef(ButtonBase)))
    in WithStyles(ForwardRef(ButtonBase)) (created by ForwardRef(IconButton))
    in ForwardRef(IconButton) (created by WithStyles(ForwardRef(IconButton)))
    in WithStyles(ForwardRef(IconButton)) (created by l)
    in l (created by l)
    in div (created by l)
    in div (created by ForwardRef(Toolbar))
    in ForwardRef(Toolbar) (created by WithStyles(ForwardRef(Toolbar)))
    in WithStyles(ForwardRef(Toolbar)) (created by l)
    in l (created by t)
    in t (created by WithStyles(t))
    in WithStyles(t) (created by t)
    in t (created by t)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by t)
    in t (created by WithStyles(t))
```
I suspect it has something to do with the fact that the MUI team has changed their components to be functional and use Hooks.

**Comment by joziahg** [comment]
Having this issue aswell. `material-ui/core@4.0.0-beta.2` & `mui-datatables@2.0.0-beta.55`

**Comment by gabrielliwerant** [comment]
This library does not yet fully support versions of the material-ui library that are that high. The first step would be to take it up to the high 3's, which I've done some work on locally.

**Comment by dandrei** [comment]
I've recently had to add tooltips to functional components and looks like wrapping the exported component in `React.forwardRef(`, and adding a second parameter after the props (e.g. `ref: React.Ref<HTMLButtonElement>`) does the trick.

**Comment by shawnmitchell** [comment]
https://material-ui.com/guides/composition/#caveat-with-refs

**Comment by pfarnach** [comment]
Are there any plans to support v4 now that it's officially released?  Maybe a set of milestones for mui-datables v3 with associated issues would be a good start, and then people (like myself) could start picking them up if you're looking for help, @gabrielliwerant.

**Comment by gabrielliwerant** [comment]
@pfarnach Yes, support for v4 is part of the plan. That's not a bad idea about milestones and/or issues around upgrade necessities. Trying to review some PRs and fix some bugs at the moment, but when I get some time, I can start work on an upgrade roadmap.

**Comment by pgoforth** [comment]
A lot of v4 is already supported and just works OOTB. There are instances like here: https://github.com/gregnb/mui-datatables/blob/dc45413152bece974b4379182c68bb030770f860/src/components/TableToolbar.js#L214-L223
...where `gregnb/react-to-print` uses a cloned and ref injected component on `trigger` (https://github.com/gregnb/react-to-print/issues/131), so things like that are the only places where I'm seeing issues.

**Comment by lengband** [comment]
I Having this issue aswell. `material-ui/core@4.0.2` & `mui-datatables@2.5.1`
```
import React from 'react'
import MUIDataTable from 'mui-datatables'

const columns = [
  {
    name: 'name',
    label: 'Name',
    options: {
      filter: true,
      sort: true
    }
  },
  {
    name: 'company',
    label: 'Company',
    options: {
      filter: true,
      sort: false
    }
  },
  {
    name: 'city',
    label: 'City',
    options: {
      filter: true,
      sort: false
    }
  },
  {
    name: 'state',
    label: 'State',
    options: {
      filter: true,
      sort: false
    }
  }
]

const data = [
  { name: 'Joe James', company: 'Test Corp', city: 'Yonkers', state: 'NY' },
  { name: 'John Walsh', company: 'Test Corp', city: 'Hartford', state: 'CT' },
  { name: 'Bob Herm', company: 'Test Corp', city: 'Tampa', state: 'FL' },
  { name: 'James Houston', company: 'Test Corp', city: 'Dallas', state: 'TX' }
]

const options = {
  filterType: 'checkbox'
}

export default class ArticleList extends React.Component {
  render () {
    return (
      <MUIDataTable
        title={'Employee List'}
        data={data}
        columns={columns}
        options={options}
      />
    )
  }
}

```

**Comment by Captainlonate** [comment]
Yeah, still an issue with `"@material-ui/core": "^4.1.3"` and `"mui-datatables": "^2.5.1"` using simply the starter code from the documentation.
Is this days away from being fixed? Or should I find another Data Table?

**Comment by gabrielliwerant** [comment]
FYI, the upgrade roadmap is behind this issue in terms of priority: https://github.com/gregnb/mui-datatables/issues/679. When I get a good chunk of time, I can begin making progress on it, but for the near and mid future, I recommend not using the latest material ui versions.

**Comment by mib00038** [comment]
> A lot of v4 is already supported and just works OOTB. There are instances like here:
> 
> https://github.com/gregnb/mui-datatables/blob/dc45413152bece974b4379182c68bb030770f860/src/components/TableToolbar.js#L214-L223
> 
> ...where `gregnb/react-to-print` uses a cloned and ref injected component on `trigger` ([gregnb/react-to-print#131](https://github.com/gregnb/react-to-print/issues/131)), so things like that are the only places where I'm seeing issues.

Just wrap the ToolTip in a div.

**Comment by YoungCC2** [comment]
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

`<Form.Item label="Dragger">
                        <div className="dropbox">
                            {getFieldDecorator('dragger', {
                                rules: [{ required: true, message: 'Please select your country!' }],
                            })(
                                <Dragger {...props}>
                                    <p className="ant-upload-drag-icon">
                                        <Icon type="inbox" />
                                    </p>
                                    <p className="ant-upload-text">Click or drag file to this area to upload</p>
                                    <p className="ant-upload-hint">
                                        Support for a single or bulk upload. Strictly prohibit from uploading company data or other
                                        band files
                                    </p>
                                </Dragger>
                            )}
                        </div>
                    </Form.Item>`   
how to r it

**Comment by gabrielliwerant** [comment]
@YoungCC2 Can you give the versions of react, material, and this library that cause you to experience that error?

**Comment by YoungCC2** [comment]
> @YoungCC2 Can you give the versions of react, material, and this library that cause you to experience that error?
`"react": "^16.3.2",
    "react-dom": "^16.3.2",
"antd": "^3.22.2",`

`<Form.Item label="上传logo">
                        <div className="dropbox">
                            {getFieldDecorator('dragger', {
                                rules: [{ required: true, message: 'Please select your country!' }],
                            })(
                                <Dragger {...props}>
                                    <p className="ant-upload-drag-icon">
                                        <Icon type="inbox" />
                                    </p>
                                    <p className="ant-upload-text">点击上传logo</p>
                                    <p className="ant-upload-hint">
                                        
                                    </p>
                                </Dragger>
                            )}
                        </div>
                    </Form.Item>`

**Comment by gabrielliwerant** [comment]
@YoungCC2 Thanks, but I still need your '@material-ui/core' and 'mui-datatables' versions.

**Comment by YoungCC2** [comment]
@gabrielliwerant   i do`t  install @material-ui/core and mui-datatables

**Comment by gabrielliwerant** [comment]
@YoungCC2, I'm not sure I understand. This library is `mui-datatables`, so you must have this installed at all, unless you are posting on the wrong library!

**Comment by YoungCC2** [comment]
&nbsp;i rewrite this component. the question was reslove .........




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gabriel Liwerant"<notifications@github.com&gt;; 
发送时间: 2019年9月4日(星期三) 凌晨3:38
收件人: "gregnb/mui-datatables"<mui-datatables@noreply.github.com&gt;; 
抄送: "卯卯"<743472220@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [gregnb/mui-datatables] @material-ui/core 4.0.0-beta.1 Warning: Function components cannot be given refs. (#595)




@YoungCC2, I'm not sure I understand. This library is mui-datatables, so you must have this installed at all, unless you are posting on the wrong library!

**Comment by marcusjwhelan** [comment]
What if its not an IconButton and just an Icon. More specifically the icon is dynamically loaded as a functional method so I was pointed in the direction of creating a forward ref component but still nothing would pop up on hover. 

https://stackoverflow.com/questions/57527896/material-ui-tooltip-doesnt-display-on-custom-component-despite-spreading-props

**Comment by HarishRocks** [comment]
Wrapping the child component with a `div` worked for me!
