### ISSUE TITLE
Validation check on  onRowsSelect option

### ISSUE THREAD

**Issue by schatterjee-erwin** [gregnb/mui-datatables#596]
Hi, 
I would like to know whether I can set a validation check when deselecting rows.

## Expected Behavior

 On deselecting the rows should show an error message that says "Rows not selected"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gabrielliwerant** [comment]
The `onRowsSelect` option will fire both when a row is selected or deselected. Does this provide what you need?

**Comment by schatterjee-erwin** [comment]
@gabrielliwerant. I have found a way to handle the validation. Thanks :)
