### ISSUE TITLE
Show/Hide Options Filter, Print, Download

### ISSUE THREAD

**Issue by demoreno** [gregnb/mui-datatables#6]
Hi, I just implemented the library in my project and it's amazing! but I have a question with the props options, filter, print etc since I put the false boolean to hide them but in the same way render the icons

**Comment by gregnb** [comment]
Hey @demoreno thanks for the feedback! As for your question, if I'm understanding correctly you would like a way to disable the icons but still render them?

**Comment by demoreno** [comment]
Thanks for your answer, not the problem is that setting the props false to print, filter etc so that they do not show since in my logic they are not necessary but the same icons are shown in the same way

<MUIDataTable
      data={data}
      columns={columns}
      download={false}
      print={false}
      filter={false}
/>

**Comment by gregnb** [comment]
Could you paste what you are using for a config? In my example below

```
   const options = {
      filterType: "dropdown",
      responsive: "stacked",
      filter: false,
      download: false,
      print: false
    };
```

I do not see the filter, download, print icons anymore so it is working as expected. Example here:
https://codesandbox.io/s/lrl0361qpm


<img width="1225" alt="screen shot 2018-02-19 at 10 38 07 am" src="https://user-images.githubusercontent.com/19170080/36385641-0cd95e24-1561-11e8-9400-fb3a9c0e8b84.png">

**Comment by gregnb** [comment]
Hey @demoreno did you get a chance to see my reply?
