### ISSUE TITLE
Filter Table and View Columns icons are not working after upgrading to 2.1.0 (from 2.0.0)

### ISSUE THREAD

**Issue by hrmoller** [gregnb/mui-datatables#600]
## Expected Behavior
View columns and filter table as wanted.

## Current Behavior
When clicking the icon(`View Columns` & `Filter Table`) nothing happens. `Search` and `Download` icons works just fine.

Screenrecording:
https://www.dropbox.com/s/h9i449od9tlcowy/Screen%20Recording%202019-05-08%20at%2013.58.37.mov?dl=0

## Steps to reproduce
1. Upgrade `mui-datatables` to version 2.1.0
3. Start app
2. When `View Columns` selector and  `Filter Table` are clicked nothing happens

## Your Environment
I'm using a react app based on create-react-app running on node 10.15.3.

| Tech        	  | Version 		|
|-----------------|-----------------|
| Material-UI     | 3.9.3     		|
| MUI-datatables  | 2.1.0      		|
| React           | 16.8.1          |
| browser         |	Crome & Safari  |
| etc             | MacOS Latest	|

**Comment by cherukumilli** [comment]
I see the same error. Here is a link to codesandbox example for the same:
https://codesandbox.io/s/rj37ykw26m?fontsize=14

**Comment by gabrielliwerant** [comment]
Later versions of material-ui introduce breaking changes. I'm working on upgrading it, but it's complicated, so it may not be done for a bit.

In the mean time, I recommend using material packages that are no larger than the versions used by this library. In the code sandbox example above, if I change package versions to `@material-ui/core: 3.2.2` and `@material-ui/icon: 3.0.2`, the buttons work as expected.

**Comment by Flash619** [comment]
Same issue here on @material-ui/core@^3.2.0

[https://codesandbox.io/s/73v55m9250?fontsize=14](https://codesandbox.io/s/73v55m9250?fontsize=14)

**Comment by bndynet** [comment]
The same case, I have downgraded to version 2.0.0. Waiting for the newest version for fixing it.

**Comment by SkyTradeInc** [comment]
Same case here too

**Comment by gabrielliwerant** [comment]
There is a PR up that should fix this particular issue, so stay tuned.

**Comment by rodriigovieira** [comment]
Got the same error here, with the MaterialUI 4 beta. Made the downgrade to 2.0.0 and it worked.
