### ISSUE TITLE
Single filters have 50% width

### ISSUE THREAD

**Issue by nathancharles** [gregnb/mui-datatables#604]
Select filters are always given 50% width, regardless of the number of filters rendered. This causes single filters to render very poorly.

https://imgur.com/a/xdIih7K

## Expected Behavior
Select filter widths should be dynamic depending on the number. If only a single filter, full width. If > 1, 50% width.

It would be great to handle the odd case (3 filters, first 2 50%, last 100%)

## Current Behavior
Regardless of how many filters are rendered, they are given 50% width. This causes a poor experience for a single filter

## Steps to Reproduce (for bugs)
1. Render a table with a single select filter
2. Open filter menu, see small 50% width filter

Looks like the change was introduced in [65a8aa66abf520098049889a598f615b526ed386](https://github.com/gregnb/mui-datatables/commit/65a8aa66abf520098049889a598f615b526ed386#diff-93991f6e37cbe8ff55a6d6b46b1d44f1)

## Your Environment
| Tech         | Version |
|--------------|---------|
| Material-UI  |  3.9.3 |
| MUI-datatables  |  2.0.0 |
| React        |  16.8.6 |
| browser      |  Chrome - latest |

**Comment by gabrielliwerant** [comment]
@nathancharles Nice find! Would you be interested in opening up a PR to address the issue?

**Comment by TKdevlop** [comment]
tempfix 
```js
 const getMuiTheme = () =>
    createMuiTheme({
      overrides: {
        MuiGridListTile: {
          root: {
            width: "100% !important"
          }
        }
      }
    });
<MuiThemeProvider theme={getMuiTheme()}>
        <MUIDataTable
          title={props.title}
          data={rows}
          columns={columns}
          options={options}
        />
      </MuiThemeProvider>
```

**Comment by nathancharles** [comment]
Added a PR to handle the single filter case. Given that there are multiple filter types that can be shown at the same time, I didn't do anything to handle the case for an odd number of filters.

**Comment by nathancharles** [comment]
@gabrielliwerant any chance to take a look?

**Comment by gabrielliwerant** [comment]
@nathancharles Added it to my review list, will take a look when I get a chance which should be either tonight or tomorrow.

**Comment by 99uno** [comment]
It has been updated and now you should set {MUIDataTableFilter: {gridListTile: your_style_here}} instead of {MuiGridListTile: {root: your_style_here}}

**Comment by JvdWest** [comment]
If I understand you correctly, this is what you mean:

![image](https://user-images.githubusercontent.com/53224001/120067571-b8923780-c07c-11eb-8a31-c67a313cf25a.png)

To fix this issue, set the fullWidth property to true on the column options.

```
    const columns = [
      {
        name: "vehicle_ID",
        label: "Vehicle ID",
        options: {
          filter: true,
          sort: false,
          filterType: 'multiselect',
          filterList: vehicleFilter ? [vehicleFilter] : null,
          filterOptions: {
            names: vehicleList,
            fullWidth: true
          }
        }
      },
      {
        name: "record_type",
        label: "Record Type",
        options: {
          filter: true,
          sort: false,
          filterType: 'multiselect',
          filterList: serviceTypeFilter ? [serviceTypeFilter] : null,
          filterOptions: {
            names: serviceTypeList,
            fullWidth: true
          }
        }
      }
```

![image](https://user-images.githubusercontent.com/53224001/120067675-2179af80-c07d-11eb-8cb9-33af44412b92.png)
