### ISSUE TITLE
is it possible to customize search box ?

### ISSUE THREAD

**Issue by rushalipatel** [gregnb/mui-datatables#608]
![Screen Shot 2019-05-10 at 12 31 58 PM](https://user-images.githubusercontent.com/48195555/57508645-ad4a0300-731f-11e9-8436-6938f6099259.png)

I have to customize search-box like above screenshot..is It possible in MUI Datatable ??

**Comment by gabrielliwerant** [comment]
At the moment, it is not. This feature was requested a while ago here https://github.com/gregnb/mui-datatables/issues/91. If there is a lot of interest in this feature, I can take it on next, as it has languished quite a bit since it was initially opened.

**Comment by vnellore** [comment]
Hi @gabrielliwerant - I also would like some sort of customization or control over the search box. Currently it overlaps the title of the table when you type a query. Also the length of the search field seems very long. Thanks for your efforts on this project.

**Comment by elilondon** [comment]
@gabrielliwerant I am trying to override the color of the line (default black/ when focused blue) but cant seem to figure out how to call to this. Is this also not possible?

**Comment by gabrielliwerant** [comment]
@elilondon The only way to customize the search box at the moment is to use style overrides. You'll find examples for how to do this is the customize-styling example of this project. Also, the material-ui documentation will give you pointers about overriding styles.

**Comment by gabrielliwerant** [comment]
The ability to add a custom search bar is now available in `2.8.0`. See documentation or release notes for more information.
