### ISSUE TITLE
Sort icon wraps to a new line whenever table content width < header width

### ISSUE THREAD

**Issue by KasparasGud** [gregnb/mui-datatables#611]
Whenever the width of the content is less than that of the header for the column the sort icon wraps to a new line even though there is plenty of space to display it in the same row.

<img width="1176" alt="Screen Shot 2019-05-10 at 11 07 45" src="https://user-images.githubusercontent.com/21368701/57515874-e7150c80-7313-11e9-8f45-aa33f6907467.png">

![inspect](https://user-images.githubusercontent.com/21368701/57515986-217ea980-7314-11e9-964a-75d61216ef07.png)

## Expected Behavior

Sort icon stays in the same row if there is space available

## Current Behavior

Sort icon wrapping to a new row

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    ^3.9.3     |
| MUI-datatables  |    ^2.0.0-beta.59     |
| React        |   ^16.8.6      |
| browser      |    Chrome Version 74.0.3729.131 (Official Build) (64-bit)     |

**Comment by amacwhirter** [comment]
Temp fix I used for the same issue: 
```
  getMuiTheme = () => createMuiTheme({
    overrides: {
      MUIDataTableHeadRow: {
        root: {
          whiteSpace: 'nowrap'
        }
      }
    }
  });
```

**Comment by gabrielliwerant** [comment]
Closing as the merged PR here fixes the issue and this fix will be in the next release.
