### ISSUE TITLE
Responsive table, shows rows as stacked when printed

### ISSUE THREAD

**Issue by aramkoukia** [gregnb/mui-datatables#614]
I have a grid that is set as Responsive, Staked. but when I click Print on desktop, the preview is shown as stacked

But I need the print to look like what I see on the page.

I tried making it non-responsive, then the preview does not looks stacked, but then there is a vertical scroll bar and it does not print all the records

This is similar to this I guess: 526

**Comment by JReinhold** [comment]
> I tried making it non-responsive, then the preview does not looks stacked, but then there is a vertical scroll bar and it does not print all the records

That happens because when setting `responsive` to `scroll`, the table gets a `max-height` of, `499px`, which will make it "not print all the records", as they will be hidden.

See the following comment for a fix:
https://github.com/gregnb/mui-datatables/issues/378#issuecomment-458112410

**Comment by aramkoukia** [comment]
Thanks, that worked for me

**Comment by JReinhold** [comment]
As of [V2.10.0](https://github.com/gregnb/mui-datatables/tree/2.10.0) it is now possible to use the prop `responsive="scrollFullHeight"` to make the table full height and a scroll behavior at the same time. That should fix the issue.

See https://github.com/gregnb/mui-datatables/pull/867
