### ISSUE TITLE
Add onTableChange callback on table initialization

### ISSUE THREAD

**Issue by shawnmitchell** [gregnb/mui-datatables#617]
## Expected Behavior
I'm using a custom toolbar and using `onTableChange` to track the table state.

I have that state as soon as the user performs a sort or filter operation, but not before then. Adding a call to `onTableChange` on initialization will provide the client with the internal state to handle any custom actions on an unmodified table.

It is reasonable imo to fire the `onTableChange` callback on initialization as the table state has in fact changed from uninitialized to initialized. 

I created a pull request with my fix but some tests are not passing. If this is something the owners believe fits with the library I will be more than happy to work with them to fix the tests. 

My change is a one-liner to add a callback to the call to `setTableData` to call `setTableAction` after `setState` completes. `setTableAction` results in `onTableChange` being fired and the client receiving the initialized table state. 

```
initializeTable(props) {
    this.getDefaultOptions(props);
    this.setTableOptions(props);
    this.setTableData(props, TABLE_LOAD.INITIAL, () => {
      this.setTableAction('tableLoadInitial');
    });
  }
```

**Comment by shawnmitchell** [comment]
If there is interest, I'll also add the callback to 

```
componentDidUpdate(prevProps) {
    if (this.props.data !== prevProps.data || this.props.columns !== prevProps.columns) {
      this.setTableData(this.props, TABLE_LOAD.INITIAL, () => {
        this.setTableAction('tableLoadInitial');
      });
    }

    if (this.options.resizableColumns) {
      this.setHeadResizeable(this.headCellRefs, this.tableRef);
      this.updateDividers();
    }
  }
```

**Comment by gabrielliwerant** [comment]
Hm, how about a separate callback for initialization like `onTableInit` or something? I would accept something like that. I worry about combining with a change callback, as I might not expect that to fire on initial hydration.

**Comment by shawnmitchell** [comment]
@gabrielliwerant, that would also work. Would you be okay sending it on construction and componentDidUpdate where prevProps !== this.props? For me, sending new props is essentially reinitializing the table, so `onTableInit` would still be appropriate. 

Add setTableInitialized in the form of setTableAction...
```
  setTableAction = action => {
    if (typeof this.options.onTableChange === 'function') {
      this.options.onTableChange(action, this.state);
    }
  };

  setTableInit = action => {
    if (typeof this.options.onTableInit === 'function') {
      this.options.onTableInit(action, this.state);
    }
  };
```

add `setTableInit` callback in `initializeTable` 
```
  initializeTable(props) {
    this.getDefaultOptions(props);
    this.setTableOptions(props);
    this.setTableData(props, TABLE_LOAD.INITIAL, () => {
      this.setTableInit('tableLoadInitial');
    });
  }
```

add setTableInit callback on componentDidUpdate if `prevProps !== this.props`
```
  componentDidUpdate(prevProps) {
    if (this.props.data !== prevProps.data || this.props.columns !== prevProps.columns) {
      this.setTableData(this.props, TABLE_LOAD.INITIAL, () => {
        this.setTableInit('tablePropsUpdated');
      });
    }

    if (this.options.resizableColumns) {
      this.setHeadResizeable(this.headCellRefs, this.tableRef);
      this.updateDividers();
    }
  }
```

and change index.d.ts
```
    onColumnViewChange?: (changedColumn: string, action: string) => void;
    onTableChange?: (action: string, tableState: object) => void;
    onTableInit?: (action: string, tableState: object) => void;
    setRowProps?: (row: any[], rowIndex: number) => object;
```

and propTypes
```
...
      serverSide: PropTypes.bool,
      onTableChange: PropTypes.func,
      onTableInit: PropTypes.func,
      caseSensitive: PropTypes.bool,
...
```

**Comment by gabrielliwerant** [comment]
Interesting, I didn't realize that `onTableChange` wasn't firing on general prop updates. Thanks for pointing this out, by the way.

Looking through this, it seems to me like `onTableChange` should be firing whenever there is a prop update in `componentDidUpdate`, and `onTableInit` only as the callback here: https://github.com/gregnb/mui-datatables/blob/master/src/MUIDataTable.js#L206. I would expect an init to only fire once per component mounting, and this would avoid the need to add a wrapper function with different actions passed in, as well as ensuring that it will fire once the initial state has been successfully added.

It looks like the `TABLE_LOAD.INITIAL` sent in `componentDidUpdate` is a bit confusing, though there is a lot of behavior that currently relies on it.

Does that make sense? Let me know if you need more input, and if this would solve your problem.

**Comment by shawnmitchell** [comment]
Thanks @gabrielliwerant. I'm a bit swamped today but I will look at this and come up with a pull request for onTableInit - just for the initial mounting - and add the onTableChange callback for updated props. That's what you have in mind, yeah?

**Comment by gabrielliwerant** [comment]
@shawndibble Exactly. Thank you!

**Comment by gabrielliwerant** [comment]
This feature is now a part of version `2.3.0` thanks to @shawndibble!
