### ISSUE TITLE
Would like to have some data-testid attributes on ui components of the datatable

### ISSUE THREAD

**Issue by jdetle** [gregnb/mui-datatables#618]
Hi, I have a mui-datatable that has some custom search functionality that I'd like to test. I've gotten really into the react-testing-library approach of actually testing the component, and am running into issues with being able to select different elements of the datatable. If you'd be okay with it, I'd like to submit a PR to add `data-testid` props to key elements of the component.

**Comment by gabrielliwerant** [comment]
I think it's a good idea to add ids for testing, but maybe we should come up with a standard naming approach first for consistency? I like `data-test-id` as the attr, and something like `[component-name-element-name]`?

Do you have any thoughts on this? @gregnb

**Comment by jdetle** [comment]
> I think it's a good idea to add ids for testing, but maybe we should come up with a standard naming approach first for consistency? I like `data-test-id` as the attr, and something like `component-name-element-name`?

I am onboard with whatever approach you all agree on. The standard syntax is data-testid, which is useful to have for helper functions in react-testing-library, so thats the only hill I would die on. Thanks for your quick engagement.

**Comment by gabrielliwerant** [comment]
You're right, it looks like react native set the precedent for `data-testid`. Looking at that hurts my brain, but convention is convention! 😛 

Ok, I say go ahead with this, and lets see what you come up with as far as naming conventions for the actual ids.

**Comment by jdetle** [comment]
I got some work done on this, will be pushing it up on wednesday after I'm done giving a talk.

**Comment by gabrielliwerant** [comment]
Test ids added in `2.7.0`.
