### ISSUE TITLE
Show property from a complext object

### ISSUE THREAD

**Issue by diegooferreira** [gregnb/mui-datatables#625]
## Expected Behavior

I would like to display in the rows a property of a complex object. For example: object.name

## Current Behavior

Error in console, white in full screen. 
Console Error: Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {codigo, descricao, resumo, valor}). If you meant to render a collection of children, use an array instead.

I would like to show just one of these properties.

I've tried:
```
const columnsDetail = 
[{
    name: "sabor",
    label: "Sabor"
},      
{
    name: "quantidade",
    label: "Qtde."
}]
```

```
const columnsDetail = 
[{
    name: "sabor.descricao",
    label: "Sabor"
},      
{
    name: "quantidade",
    label: "Qtde."
}]
```

I tried use `customBodyRender` too, but no success.

Sample of my data:

```
[
      {
        "pedido":0,
        "quantidade":3,
        "sabor":{ "codigo":0,"descricao":"NICE CAKE","resumo":null,"valor":6.0 }
      }
]
```

Is It possible to do That?

**Comment by gabrielliwerant** [comment]
This functionality should be available in `2.5.0` thanks to https://github.com/gregnb/mui-datatables/pull/619.
