### ISSUE TITLE
Alias for Component

### ISSUE THREAD

**Issue by joziahg** [gregnb/mui-datatables#626]
Using components in the tables has been great, In my specific use case I use a react-router link components to link to a users profile. The issue comes when I want to pass multiple variables to the customBodyRender function. My table has a first name and last name field, among others. For the last name field I want to render a React-Router Link component that links to a users profile. I have to pass in both the first and last name of the user to link to their profile, therefore I have to set both as the value for the row object. The link component works great, however when it comes to filtering It has the full name as the value. Check out my code-sandbox link for a better understanding of what I am talking about.

## Expected Behavior

It technically works as you'd expect, If I had my way I would want some way to pass multiple variables to the customBodyRender function, but only have one string as the value for filtering and sorting. I guess I am posing this problem to the community to see what other people think, maybe its too much of an edge use case to support.
## Current Behavior

When I go to filter the last name column, it has both the first and last, which is 100% expected. I technically can make filtering work by putting the last name first.
## Steps to Reproduce (for bugs)

https://codesandbox.io/s/blue-surf-8se41
1. Try exporting to csv
2. Try filtering last name column
3.  Checkout the filter dialog for last name column
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |4.0.0|
| MUI-datatables  |2.2.0         |
| React        | 16.8.6        |
| browser      |    newest firefox     |
| etc          |         |

**Comment by gabrielliwerant** [comment]
If you're looking to customize what will be exported to csv, you can do this with the `onDownload` callback. You can see the example here https://github.com/gregnb/mui-datatables/blob/master/examples/on-download/index.js to get you started.

**Comment by gabrielliwerant** [comment]
Additionally, you can create custom filter names in the column options with `filterOptions`.

**Comment by joziahg** [comment]
I have been playing around with both of those thanks for the information.
