### ISSUE TITLE
Table height that's related to window height?

### ISSUE THREAD

**Issue by patorjk** [gregnb/mui-datatables#630]
Is there a way to set the table height so that it's related to the window height, and adjusts when the window is resized?

I thought I'd be able to do this by adjusting the theme, similar to what's mentioned in issue #411. Basically, on resize I update a state variable which is put into the theme property of the datatable. However, this update seems to have no effect on the rendered table. Is there something I'm missing? Is there a way to adjust the table height when the window is resized?

**Comment by patorjk** [comment]
Actually, I've figured out a way to do it. You need overrides that look like this:

    const myTheme = createMuiTheme({
      overrides: {
        MUIDataTable: {
          paper: {
            height: 'inherit',
          }
          responsiveScroll: {
            maxHeight: 'none',
            height: 'calc(100% - 128px)'
          }
        }
    });

Then you set the size of the div that encases the table, and on the resize event you update the size of that div.

**Comment by JReinhold** [comment]
As of [V2.10.0](https://github.com/gregnb/mui-datatables/tree/2.10.0) it is now possible to use the prop `responsive="scrollFullHeight"` to make the table full height and a scroll behavior at the same time. That should fix the issue.

See https://github.com/gregnb/mui-datatables/pull/867

**Comment by vlad-buzea-ullink** [comment]
`responsive="scrollFullHeight"` will make the columns overflow if on mobile device

**Comment by maxmann74** [comment]
None of these solutions work for me. Regardless of if I override the MUIDataTable, it always keeps that 499px height for the responsiveScrollMaxHeight div that is generated.  I have reponsive = "scrollMaxHeight".

**Comment by patorjk** [comment]
As of version 3, there is now a tableBodyHeight option that allows you to control the table height.

**Comment by fsmikedev** [comment]
Hi, are there any examples of 100% tableBodyHeight? I can't get the table to fill a parent at all with 3.7.1

**Comment by gsandorx** [comment]
Any word on getting tableBodyHeight/tableBodyMaxHeight = 100% and force the table to fill the parent and showing an "internal" scroll if necessary, without overflowing the parent container?
