### ISSUE TITLE
The Delete Handler Seems to be Called Twice

### ISSUE THREAD

**Issue by AlexThurston** [gregnb/mui-datatables#638]
It seems as though a registered `onRowsDelete` function is called twice whenever rows are selected and the trash icon is clicked from the toolbar.

## Expected Behaviour
It seems unusual that the callback would be called twice.

## Current Behaviour
The callback is called twice.  This becomes particularly troublesome when a delete is requested on a remote server for the same item.

## Steps to Reproduce (for bugs)
If I take the example directly from the README, but add a `onRowsDelete` handler (`console.log`), you can see it printed twice:
```
import React from 'react'

import MUIDataTable from "mui-datatables";

const columns = ["Name", "Company", "City", "State"];

const data = [
 ["Joe James", "Test Corp", "Yonkers", "NY"],
 ["John Walsh", "Test Corp", "Hartford", "CT"],
 ["Bob Herm", "Test Corp", "Tampa", "FL"],
 ["James Houston", "Test Corp", "Dallas", "TX"],
];

const options = {
  filterType: 'checkbox',
  onRowsDelete: console.log
};

export const Repro = () => (
    <MUIDataTable
        title={"Employee List"}
        data={data}
        columns={columns}
        options={options}
    />
)
```

Within the console, I'll see:
```
{lookup: {…}, data: Array(1)}
{lookup: {…}, data: Array(1)}
```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  | 3.9.3 |
| MUI-datatables  | 2.2.0 |
| React        |         |
| browser      | chrome |
| etc          |         |

**Comment by gabrielliwerant** [comment]
There is already a fix for this in a PR which will be in the next release, but thanks for taking the trouble to create the bug report!

**Comment by gabrielliwerant** [comment]
Closed via PR, and will be in next release. Until then, should be fixed in `master`.
