### ISSUE TITLE
Unable to change the row count via state after 2.1.0

### ISSUE THREAD

**Issue by pedroo21** [gregnb/mui-datatables#642]
Hello,

Since version 2.1.0, I noticed that providing the table count using state only reflects the initial value. Take the following example:

```
this.state = {
    count: 5
}
const options = {
            count: this.state.count,
            serverSide: true,
            rowsPerPage: 10,
            rowsPerPageOptions: [10, 25, 50]
}
```

After querying the server and modifying the state count, the row count on the bottom right will still show the old value of 5.

## Expected Behavior
```
this.setState({count: 100})
```

Expected to show the row count to 100 instead of 5.

## Steps to Reproduce (for bugs)
Please use the following link as a demonstration:
https://codesandbox.io/s/muidatatables-custom-toolbar-lwgog?fontsize=14

If you rollback the mui-datatables version to 2.0.0, the behavior will be as expected.

**Comment by SatorSquare** [comment]
I am also noticing a similar issue with other options such as column configuration.

**Comment by gabrielliwerant** [comment]
I believe this is a duplicate of https://github.com/gregnb/mui-datatables/issues/610#issuecomment-494701967.

**Comment by pedroo21** [comment]
It is. Thanks for pointing out. I couldn't find that issue when I opened this.
