### ISSUE TITLE
elevation option doesn't work

### ISSUE THREAD

**Issue by Akaike0** [gregnb/mui-datatables#644]
Edit: Okay, the evelation works AROUND the data table, but what about the toolbar? MUIDataTableToolbarSelect has also a MuiPaper element with evelation02. Is there a way to remove the shadow?

const options = {
            filter: false,
            elevation: 0,
            onRowsDelete: (rowsDeleted) => {
                for (var key in rowsDeleted.data) {
                    this.props.deleteLicence(this.props.licence[rowsDeleted.data[key].dataIndex].id);
                }
            },
            customToolbar: () => <CustomToolbar />,
            resizableColumns: false,
 };

## Expected Behavior
Changing elevation should change the Paper shadow, 0 means, no shadow.

## Current Behavior
Doesn't work at all, no matter what number you put in.

## Steps to Reproduce (for bugs)
Just use the option elevation, for example:
elevation: 0,

| Tech         | Version |
|--------------|---------|
| Material-UI  |   3.9.0    |
| MUI-datatables  |  2.2.0   |

**Comment by gabrielliwerant** [comment]
I'm unable to reproduce this issue. Can you open a codesandbox example of it not working?

**Comment by Akaike0** [comment]
> I'm unable to reproduce this issue. Can you open a codesandbox example of it not working?

Ok, I think I misunderstood it a little bit. I thought elevation applies also to the toolbar (table head), so for example, if I select something, the toolbar (MUIDataTableToolbarSelect) changes and there is some box-shadow I want to remove. Is there a way to do that? The MUIDataTableToolbarSelect has an MuiPaper element with evelation02.

**Comment by gabrielliwerant** [comment]
No problem! That is correct, the main option for elevation applies only to the primary table paper component.

If you want to override the select toolbar paper styles, you can use:

```
overrides: {
  MuiPaper: {
    elevation2: {
      // custom styles
    }
  }
}
```
