### ISSUE TITLE
Table not refresh with hooks

### ISSUE THREAD

**Issue by AlexCat** [gregnb/mui-datatables#649]
When I try to useState hook to manage "count" field in options, table not refreshing. Here is example - https://codesandbox.io/s/muidatatables-custom-toolbar-3gt7c

## Expected Behavior

Table should refresh because "count" state is changed
## Current Behavior

Table not refresh
## Steps to Reproduce (for bugs)

1. Please click on "Change count" to see the issue

## Your Environment

https://codesandbox.io/s/muidatatables-custom-toolbar-3gt7c

**Comment by shawnmitchell** [comment]
https://codesandbox.io/s/muidatatables-custom-toolbar-9u979

**Comment by AlexCat** [comment]
> https://codesandbox.io/s/muidatatables-custom-toolbar-9u979

Yeah, thanks, but we use "key" ability to force rerender whole component. I think it reduces performance. Is it right way to update mui-tables with hooks?

**Comment by gabrielliwerant** [comment]
Hooks are not yet officially supported by mui-datatables, so you use these new features at your own risk. You have to mind the peer dependency versions of this project.
