### ISSUE TITLE
Table only render first page of data after disable pagination

### ISSUE THREAD

**Issue by geohuz** [gregnb/mui-datatables#65]
I'm going to implement a table which doesn't use pagination, so I set pagination=false in option, but the table only render the first page. Is there anyway to make the table render whole data set? So, for example, rowsPerPage=10000 and we have a table height be set and just scroll the table straightly.

**Comment by geohuz** [comment]
sorry, my bad, didn't see the option in the doc

**Comment by gregnb** [comment]
If you set your rowsPerPage large enough it'll show the whole table. Did you try this?

**Comment by geohuz** [comment]
Yes, but how can I set the table height and allow scroll vertically

**Comment by gregnb** [comment]
Try wrapping MUIDataTable in a scrollable div that has a fixed height

**Comment by geohuz** [comment]
Yeah it works but the table lost Paper style, my code is like:
`<Paper style={{height: 500, overflowY: 'scroll'}}>
          <MUIDataTable
            title={"title"}
            data={flights.tableData}
            columns={columns}
            options={options}
          />
        </Paper>`
