### ISSUE TITLE
Typescript type error for filterTypes option

### ISSUE THREAD

**Issue by dzelge** [gregnb/mui-datatables#652]
When using mui-datatables with typescript you get a type error when attempting to set the 
filterType option-

## Expected Behavior

This shoudul work in typescript:

```typescript
const options = {
    filterType: 'checkbox',
};

<MUIDataTable
    title={"Employee List"}
    data={data}
     columns={columns}
     options={options}
/>

```

## Current Behavior

The above throws the following error:

```
Type 'string' is not assignable to type '"checkbox" | "textField" | "dropdown" | "multiselect" | undefined'.
```

## Steps to Reproduce (for bugs)

Use the above example.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Typescript Compiler | 3.4.5 |
| Material-UI  |     3.9.3    |
| MUI-datatables  |    2.2.0     |
| MUI-datatables types |    2.1.0     |
| React        |     16.9.0-alpha.0    |
| browser      |     Firefox Quantum (67.0)    |

**Comment by dzelge** [comment]
You need to create a type FilterOptions like so:
```typescript
export type FilterType = 'dropdown' | 'checkbox' | 'multiselect' | 'textField';
```

and then:

```typescript
filterType?: FilterType;
```

in ```class MUIDataTableColumnOptions```

Same for other types.

**Comment by sickyoon** [comment]
@dzelge Did you find any workaround to this issue?

**Comment by shawnmitchell** [comment]
I think that is the workaround. You need to specify a type that matches the union literal.

**Comment by shawnmitchell** [comment]
You can also use 

```
const options = {
    filterType: 'checkbox' as FilterType,
};

```

**Comment by dzelge** [comment]
Workaround is:

```
const options = {
    filterType: 'checkbox' as any,
};
```

**Comment by shawnmitchell** [comment]
I made this pull request to @types so I'll clean it up. I propose adding a type FilterType, Display, and SortDirection as well as fixing up selectableRows which is currently a boolean in the types definition when it should be a string literal union 'multiple' | 'single' | 'none' and I'll also add a type SelectableRows for that.

**Comment by shawnmitchell** [comment]
```
export type Display = 'true' | 'false' | 'excluded';
export type FilterType = 'dropdown' | 'checkbox' | 'multiselect' | 'textField';
export type SortDirection = 'asc' | 'desc';
export type Responsive = 'stacked' | 'scroll';
export type SelectableRows = 'multiple' | 'single' | 'none';
```

```
export interface MUIDataTableColumnOptions {
    
    [-] display?: 'true' | 'false' | 'excluded';
    [+] display?: Display;
    [-] filterType?: 'dropdown' | 'checkbox' | 'multiselect' | 'textField';	    
    [+] filterType?: FilterType;
    [-] sortDirection?: 'asc' | 'desc';	    
    [+] sortDirection?: SortDirection;
    
```

**Comment by dzelge** [comment]
Looks good to me. Thanx

**Comment by shawnmitchell** [comment]
https://github.com/shawnmitchell/DefinitelyTyped/pull/1

**Comment by FearlessHyena** [comment]
This seems to work fine

``` 
const options: MUIDataTableOptions = {
  filterType: "checkbox",
};
```

Can't this be closed?

**Comment by KrzysztofMadejski** [comment]
I sent a PR to DefinitelyTyped adding filterType to Column: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40941/files

**Comment by Laing-cloud** [comment]
> This seems to work fine
> 
> ```
> const options: MUIDataTableOptions = {
>   filterType: "checkbox",
> };
> ```
> 
> Can't this be closed?



> This seems to work fine
> 
> ```
> const options: MUIDataTableOptions = {
>   filterType: "checkbox",
> };
> ```
> 
> Can't this be closed?



> This seems to work fine
> 
> ```
> const options: MUIDataTableOptions = {
>   filterType: "checkbox",
> };
> ```
> 
> Can't this be closed?

Is there a PR to update the read me, the current example usage still shows:
`const options = {
  filterType: 'checkbox',
};`

**Comment by akpandeya** [comment]
For me 
```
const Options: Object = {
        filterType: 'checkbox'
      }
```

seems to work
