### ISSUE TITLE
searchText is lost when selecting rows

### ISSUE THREAD

**Issue by beerwin** [gregnb/mui-datatables#653]
## Expected Behavior
When selecting and deselecting rows, the search text should be kept in the search field.

## Current Behavior
Selecting and/or deselecting rows closes the search box and the search text is cleared.  (incorrect behavior)
However, the table remains filtered by the search text. (this works correctly)
Clicking on the clear button of the search field properly resets the table
So it seems, that only the search text gets cleared.

## Steps to Reproduce (for bugs)
1. The issue is reproducible with the selectable-rows example (https://github.com/gregnb/mui-datatables/blob/master/examples/selectable-rows/index.js)
2. Enter your search text into the search field
3. Select some rows
4. Deselect the selected rows
5. The search field is closed and if you reopen it, it is empty (the table is still filtered)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  any version  |
| MUI-datatables  | 2.1.0,  2.2.0  |
| React        |  any version  |
| browser      |  Google Chrome latest  |

## Notes
By testing with multiple versions, my conclusion is, that this never worked properly

**Comment by gabrielliwerant** [comment]
This is partly resolved by https://github.com/gregnb/mui-datatables/pull/647, and further aided by https://github.com/gregnb/mui-datatables/pull/654.

There is a remaining edge case where an open search bar with nothing entered will default to closed when switching back and forth with the selected toolbar. Fixing that requires a large refactor that changes how the different toolbars interact, so I'll put this issue on hold after the major problems have been resolved.

**Comment by gabrielliwerant** [comment]
Since the basic functionality for this exists, I will close this issue. If there is demand for the edge case mentioned here, it can be opened and tracked via a new issue.

**Comment by ariel-upstream** [comment]
version 4.2.2 when selecting rows the search bar disappear
