### ISSUE TITLE
Could not find dependency

### ISSUE THREAD

**Issue by seta-hungDang** [gregnb/mui-datatables#655]
I just import MUIdatatables to my create-react-app project and this error appears:
```
Module not found: Can't resolve 'mui-datatables' in '/home/hung/Playground/server-render-mui-datatables/src'
```
Even at codesandbox.io, this problem persists. I have tried all the solutions from #52 (jumping around serveral versions of mui-datatables and @material-ui/core) #515 (I couldn't even pass `npm cache clear --fource`).

## Expected Behavior
To run without an error

## Current Behavior
Not running with this error
```
Module not found: Can't resolve 'mui-datatables' in '/home/hung/Playground/server-render-mui-datatables/src'
```

## Steps to Reproduce (for bugs)
Use to example column-filters from the source code and try to run it at either create-react-app or codesandbox.io. 

[Reproduction example](https://codesandbox.io/s/long-bash-0w8c9)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.0.0   |
| MUI-datatables  |     2.2.0    |
| React        |    16.8.6     |
| browser      |    Chrome     |
| etc          |         |

**Comment by seta-hungDang** [comment]
MUI-datatables 2.2.0 work flawlessly with @material-ui/core 1.0.0 and @material-ui/icons 1.0.0. Quite a funny combination although I think @gregnb @gabrielliwerant wanna have a look at this. Thank you!

**Comment by gabrielliwerant** [comment]
You have to mind your peer dependency versions, as outlined in the `package.json` to this project. You don't need to go down to v1 for material, but you may not be able to go as high as you are now.

**Comment by seta-hungDang** [comment]
@gabrielliwerant You're right! It works well with version 3.0.0 as well. I'll close this issue. Thank you very much!
