### ISSUE TITLE
Total number of rows can't be updated asynchronously

### ISSUE THREAD

**Issue by seta-hungDang** [gregnb/mui-datatables#658]
At the beginning, there is no data so the total number of  rows is 0. After the page is loaded and I have a number for total number of rows, I still can't update my table with the new number. This issue doesn't appear in the earlier version like v2.0.0

## Expected Behavior
MUIdatatables update total number of rows asynchronously

## Current Behavior
MUIdatatables doesn't update total number of rows

## Steps to Reproduce (for bugs)
Link sandbox: https://codesandbox.io/s/compassionate-breeze-vyfqs

1. Set total number of rows 0 at the beginning
2. Make api call
3. Reset the total number with a bigger number

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    1.0.0     |
| MUI-datatables  |     2.2.0    |
| React        |    16.8.0     |
| browser      |     chrome    |
| etc          |         |

**Comment by karthick-vinod** [comment]
Related to https://github.com/gregnb/mui-datatables/issues/643

**Comment by gabrielliwerant** [comment]
In your example, it looks like you're updating the final count, but not the actual row data. To update the number of rows, you would have to also update the data to reflect the additional amount.

**Comment by seta-hungDang** [comment]
@gabrielliwerant Is there a way for me to overwrite this number because there is so much data at the server that I don't want to save in the browser.

**Comment by gabrielliwerant** [comment]
Update which number? If you're looking to load only some of your data at a time, you should implement pagination in your API, at which point you can load more with `onChangePage`.

**Comment by seta-hungDang** [comment]
Sorry I didn't make it clear. Like your previous comment I only want to update the total number of rows without adding more data to the browser like my example here https://codesandbox.io/s/compassionate-breeze-vyfqs

My current solution is to revert back to mui-datatables 2.0.0.

**Comment by gabrielliwerant** [comment]
Updating count issue sounds like a duplicate of this: https://github.com/gregnb/mui-datatables/issues/610

**Comment by seta-hungDang** [comment]
Yes it does.
