### ISSUE TITLE
Feature request: 'Select All' checkbox in thead should change to 'deselect all' icon when multiple selections are made

### ISSUE THREAD

**Issue by jkantr** [gregnb/mui-datatables#66]
## Expected Behavior
GIF example of behavior in gmail: https://i.imgur.com/qC7kuVt.gifv

The 'select all' checkbox should become a 'deselect all' checkbox (with appropriate icon change) when any selections are made.

## Current Behavior
When any selection is made, no changes happen to the 'select all' button

**Comment by gregnb** [comment]
Great catch. I will add it to the todo list

**Comment by jkantr** [comment]
Yep, I don't have time this week but I should be able to get to it in the near term.

**Comment by gregnb** [comment]
This feature is now added via #90 and merged in
