### ISSUE TITLE
How can change filter condition from equal to contain?

### ISSUE THREAD

**Issue by BingyuLiu** [gregnb/mui-datatables#660]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by BingyuLiu** [comment]
Like I have a filterOptions ['WA', 'CA'. 'NY'] with multiple select type,  the target column has a combination string, like "WA, NY", when I choise WA, the "WA, NY" is not returned as expected. Could you please help?

**Comment by BingyuLiu** [comment]
thank you~~ping!!

**Comment by gabrielliwerant** [comment]
You cannot do this at the moment, but the functionality is on its way, as this relates to an older issue: https://github.com/gregnb/mui-datatables/issues/430#issuecomment-493275272.

**Comment by BingyuLiu** [comment]
thanks Gabriel!

**Comment by gabrielliwerant** [comment]
This should be available as of `2.4.0` via `filterOptions` with the new `logic` option, which allows you to set custom filter logic. I can re-open if there's a different use case here.
