### ISSUE TITLE
has customSearch() been implemented?  I can't the function definition in  yours source code. Thanks!

### ISSUE THREAD

**Issue by BingyuLiu** [gregnb/mui-datatables#661]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gabrielliwerant** [comment]
Yes, it's there. You can find documentation in the README and an example in the examples section (`customize-search`).
