### ISSUE TITLE
Specifying Width of column

### ISSUE THREAD

**Issue by teadams** [gregnb/mui-datatables#67]
Is there a way to specify the width of a column?  Or tell it to be the size of the text, with a little bit of margin.

Use case
1. I've added Edit and Delete columns to my table with Edit/Delete Icons
2. I would like these column widths to be just a little bit bigger than the icons

Thanks,
Tracy

**Comment by gregnb** [comment]
So as it stands today there is styling support for columns in general but no styling support to target specific columns
