### ISSUE TITLE
Hint and Sort button are overlapping with eachother

### ISSUE THREAD

**Issue by jkeruzec** [gregnb/mui-datatables#672]
Using latest version of mui-datatable. I've seen that "hint" toolip is overlapping with "sort" button which was not the case before : 

Old version :
![image](https://user-images.githubusercontent.com/3499632/59019850-10f51c80-8849-11e9-92c5-4dfc4e86b8f2.png)

New version : 
![image](https://user-images.githubusercontent.com/3499632/59019869-181c2a80-8849-11e9-9495-f26d61dbbedd.png)

**Comment by gabrielliwerant** [comment]
Thank you for catching that. This is a regression caused from this fix: https://github.com/gregnb/mui-datatables/pull/629

**Comment by gabrielliwerant** [comment]
https://github.com/gregnb/mui-datatables/compare/bugfix/issue-672-more-robust-icon-fix?expand=1

**Comment by gabrielliwerant** [comment]
Closing, as this should be fixed in later versions via the PR mentioned here.
