### ISSUE TITLE
Enhancement: Allow for excluded, hidden, or 'never visible' columns

### ISSUE THREAD

**Issue by jkantr** [gregnb/mui-datatables#68]
### Add third column visibility option
Right now if you include a column of data and set `options: { display: false }` the column is hidden, but it's still available to be displayed via the "view columns" menu in the UI. Sometimes rows need related data that never needs to be displayed (nor should it be) but is necessary for things like calculations or end-user display customization.

#### Use Case
- John is creating a table to display a list of Users.
- This table includes a "Post Count" column which is the count (a number) of the total "Posts" belonging to a user.
- John would like to style this cell so that the number of posts is a link that navigates to a related table (the "Posts" table) filtered to only show posts from the User of that row. For instance, that table could be located at a path such as `/posts/?userId=${userId}`
- `userId` relates the Users and Posts data. John does not want to display the `userId` in a column or have it be selectable in 'view columns' menu, as it brings no value to be displayed for the user in the UI.
- John creates a mui-tables column definition for the userId in both the Users and Posts table and marks it as hidden or excluded, so that it is accessible to the `customRender` function, but does not clutter the UI.

#### Implementation
One clean way to implement is by adding an additional column option such as `excluded`, `hidden`, or `private` which is a bool that excludes it from the 'view columns' UI menu. This is similar to how the `filter: false` column setting excludes it from the filter menu. In that way, `display` would still control whether the column is showing or not, but this new option would affect **whether the user is allowed to change** the column showing or not via the 'view columns' menu. Coincidentally, this would allow for an *additional* use case, where you would like to display a column that a user can not hide.

Another possibility,  we could change `display` to a string type with `enum('true', 'false', 'excluded')` .. or possibly `hidden` instead of `excluded`. And then (to avoid a breaking change) just do a type check and, on boolean, use the old behavior.

**Comment by teadams** [comment]
Another way is to let data be a json and then only display the elements that are in columns.

**Comment by gregnb** [comment]
@jkantr I'm fine again making another breaking change considering this package is still in beta. My vote is for the string enum without doing a type check. 

```
enum('true', 'false', 'excluded')
```

**Comment by gregnb** [comment]
I will look to take this up next and go with the proposed enum solution listed above

**Comment by jmstein** [comment]
Can I put in another vote for this?

I'd really like to be able to able to get the index in the original list I passed in of a row (after being sorted). One way to do that would be to have a hidden index column, since "rowIndex" is currently the new index after sorting. What are your thoughts?

**Comment by gregnb** [comment]
This feature is now available in the latest published version

**Comment by jmstein** [comment]
Awesome, thanks! I'll take a look.

**Comment by tiagofernandez** [comment]
@gregnb should this work with Material UI 3.0? I'm trying [this example](https://github.com/gregnb/mui-datatables/blob/f1ba0be421177ce787ca0d1900c257cdc9c43c77/examples/customize-columns/index.js) but the excluded column keeps appearing in the UI.

**Comment by tiagofernandez** [comment]
Can't get it to work with Material UI 1.5.1 either.

**Comment by william-chu** [comment]
@gregnb Thanks so much for making this library, it's been a lifesaver! Just curious if there is any enum option for this other use case the original requester mentioned?

"display a column that a user can not hide."

I have a situation where I have a column that I render with my table, the display opt is set to true so it can't be hidden, but it still shows up in the column view toggle list.
