### ISSUE TITLE
How to set column width and row height?

### ISSUE THREAD

**Issue by emagombe** [gregnb/mui-datatables#681]

**Comment by roballsopp** [comment]
Apparently they aren't planning to support this: https://github.com/gregnb/mui-datatables/issues/92#issuecomment-403651830. There is at least one potential semi-hacky example of how to get around this in that thread. I'd just go for the native [material-ui tables](https://material-ui.com/components/tables/) if you have the flexibility.

**Comment by gabrielliwerant** [comment]
The way to do this is the same way you'd do it with material-ui, which is to override mui classes with the styles you want, or provide your own components/styles via the custom render options (`customBodyRender`, `customRowRender`). This library is based off of the material-ui tables, so generally speaking, anything you can do with that library, you can do with this one. See `customize-rows` and `customize-styling` for some examples.
