### ISSUE TITLE
Custom filter ranges for numbers and dates

### ISSUE THREAD

**Issue by Avd6977** [gregnb/mui-datatables#688]
## Expected Behavior
1. Filter Type can have new types called numberRange and dateRange
1. Number and Date Range can accept custom component tags to allow a custom date-picker
1. Two inputs appear for the column which are Start Date and End Date

## Current Behavior
Columns which have numbers or dates cannot be filtered to a user-input range with start and end. Possibly the new custom filter logic would allow a number range to work if the user types 1-10 and we parse the "-" out, but that's a lot of reliance on the user to do it properly. For date-ranges, a date picker would be preferable with two inputs.

**Comment by Avd6977** [comment]
@gabrielliwerant I should've looked more into that branch, but I have some work on this if you'd like to provide some input.
https://github.com/Avd6977/mui-datatables/tree/DateRangeFilter

Additionally, it might be a better route to just do a custom filter which allows JSX to be passed in.

**Comment by Avd6977** [comment]
@gabrielliwerant Any thoughts on this? Would definitely appreciate your input on how we would do something like this.

**Comment by gabrielliwerant** [comment]
So, I agree that what we need is a generic custom filter render which will allow users to specify whatever components they wish instead of the default options. If you'd like to take a swing at that and open up a PR, I will gladly take a look when I get a chance.

**Comment by gabrielliwerant** [comment]
Closing, as this feature should now be available in `2.6.0` via `filterOptions: { display: Component }` and `fitlerType: 'custom'`, thanks to @Avd6977!
