### ISSUE TITLE
Advice? -- Inline Updates

### ISSUE THREAD

**Issue by teadams** [gregnb/mui-datatables#69]
I've used customRender to do inline edits to data in individual cells.

It seems like I have these options for after i call the server
1. Visually, the value has changed in the table.  I can trust that the server updated the data correctly and continue with the same data array.
2. I can update the state of my data array, which will force a new render of MUIDataTable.  All my sorts go away.
3. If there are errors from the server, I can catch them and diplay a red "The update did not work" on the top of the screen.  The screen will still have the new value, but I've given a visual cue to the user that something went wrong.

I'm leaning toward 3, but would like to hear what people think.

**Comment by patorjk** [comment]
Closing due to age of issue. Problem described in #2 now resolved in later versions of the table (state, including sorting,  is no longer reset).
