### ISSUE TITLE
Custom Filter Logic / p[t].sort is not a function

### ISSUE THREAD

**Issue by DJLionheart** [gregnb/mui-datatables#696]
I am loving MUI-datatables so far. Thank you all for the work you've put into it!

I've been trying to add some custom filters to a Customer table I've been working on. When I include filterOptions as an array of strings (`filterOptions: ['Tag1', 'Tag2', 'Tag3']`), the table allows me to select each of the options as expected:

<img width="826" alt="FilterOptionsAsArray" src="https://user-images.githubusercontent.com/35812374/59469245-8042b180-8df1-11e9-83e7-56979a1758a8.png">

 However, when I try to include my custom logic, the page crashes and I am met with an empty white screen.

## Expected Behavior

I am passing down the full list of tags through props to use as filter options. In the actual cell data, I am passing down the list of tags associated to the customer as a string. My logic method is trying to account for multiple tags (say a user wanted to see all customers with the tags `'Automotive'` and `25 and Older`) by keeping a count of if the tags are included in the filters.

I am expecting the table to show customers with the selected tag filters, though the blank page issue may simply be a problem with my logic, or an unrelated react issue with some other part of my code base.

## Current Behavior

Instead of showing any data at all, I am met with a blank page (nothing renders).

## Steps to Reproduce (for bugs)

I can't include the full code as it includes proprietary information, but I will include the table and options I'm passing in:

### Column 
```
const customerColumns = [...
{
      name: "tags",
      label: "Tags",
      options: {
        filter: true,
        sort: false,
        filterType: 'multiselect',
        filterOptions: {
          names: this.props.customer_tags.map( tag => tag.name ),
          logic(tags, filters) {
            let show = false;
            let tagData = tags.split(', ');
            let count = 0;

            tagData.forEach( tag => {
              if(filters.indexOf(tag) >= 0) {
                count++;
              }
            });
            
            if(count === tagData.length) {
              show = true
            }
            return !show;
          }
        }
      },
    }
]
```
<img width="1439" alt="CustomLogic" src="https://user-images.githubusercontent.com/35812374/59469238-7b7dfd80-8df1-11e9-9b6e-69159ff5c143.png">

### Options
```
const options = {
  filterType: 'checkbox',
  responsive: 'stacked',
  selectableRows: false,
  }
```

### Table
```
<Table title="Customers"
                data={this.state.data}
                className="table"
                columns={customerColumns}
                options={options}/>
```

I believe my issue is coming from a few possible causes:

1. Issues with my logic method.
2. Issues with the format in which I wrote the logic.
3. Misunderstanding of the data type that will be included as the `'filters'` argument
4. Another issue that I'm not seeing that another set of eyes might notice

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    @material-ui/core: 3.9.3    |
| MUI-datatables  |    2.0.0     |
| React        |    16.4.0     |
| browser      |    Chrome     |

Thank you for being willing to read through this.

**Comment by DJLionheart** [comment]
On second thought, I'm starting to wonder if this is actually a bug.

With my code, I get this in the console along with the blank white screen:

```
react-dom.development.js:17212 Uncaught TypeError: p[t].sort is not a function
    at index.js:2542
    at Array.forEach (<anonymous>)
    at t.value (index.js:2522)
    at t.value (index.js:2457)
    at t.value (index.js:2437)
    at callComponentWillMount (react-dom.development.js:11829)
    at mountClassInstance (react-dom.development.js:11913)
    at updateClassComponent (react-dom.development.js:13571)
    at beginWork (react-dom.development.js:14272)
    at performUnitOfWork (react-dom.development.js:16505)
    at workLoop (react-dom.development.js:16545)
    at renderRoot (react-dom.development.js:16582)
    at performWorkOnRoot (react-dom.development.js:17229)
    at performWork (react-dom.development.js:17150)
    at performSyncWork (react-dom.development.js:17123)
    at interactiveUpdates$1 (react-dom.development.js:17406)
    at interactiveUpdates (react-dom.development.js:2248)
    at dispatchInteractiveEvent (react-dom.development.js:4744)
```

I tried swapping out my code for the example shown at [](https://github.com/gregnb/mui-datatables/blob/master/examples/customize-filter/index.js), and I'm seeing the exact same behavior: a white screen with the error listed above shown in the console.

**Comment by gabrielliwerant** [comment]
Try swapping out `this.props.customer_tags.map( tag => tag.name )` with a hard-coded array of values. I suspect you're having an issue with that line, but I'm not sure. It works as it should in the example in the project.

If it still does not work for you at that point, you can help us to isolate it by creating a minimal example in codesandbox that shows the broken behavior (something where switching one line will change it from working to not working, ideally).

**Comment by DJLionheart** [comment]
I found the issue. I wasn't using the most recent version of MUI Datatables. I updated to 2.4.0 and the page doesn't crash anymore.
 
It makes sense because it looks like the PR was just approved a few days ago.
