### ISSUE TITLE
Is there a way to disable default behavior for certain actions when providing callbacks? 

### ISSUE THREAD

**Issue by slomski** [gregnb/mui-datatables#70]
HI and thank you for you work on the component.
I would like to us this table in my project but i want the data to be requested from server every time i perform search or sort.
I can do this by providing my own callbacks and create new request, fetch data and populate table. 
But at the same time for example when searching the table rerenders with local data.
Is there a way to disable this when providing callbacks for actions like search or sort?
Thanks.

**Comment by gregnb** [comment]
@slomski Thanks for the feedback. Unfortunately a feature like you described above is out of scope for this project. Providing the data is your best option
