### ISSUE TITLE
filterOptions giving TypeError: s[a].sort is not a function

### ISSUE THREAD

**Issue by alielkhateeb** [gregnb/mui-datatables#701]
I have tried the [example](https://github.com/gregnb/mui-datatables/blob/master/examples/customize-filter/index.js#L35) with filterOptions but I keep getting

> TypeError: s[a].sort is not a function

if I type `filterOptions: ['Yes', 'No']` it works in displaying `Yes` and `No` in the filter list, but functionality is not working of course as the value is `true` and `false`

How can I achieve changing the labels in the filter but keeping the functionality unchanged?

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.0.1   |
| MUI-datatables  |    2.3.0    |
| React        |   16.8.6   |

**Comment by gabrielliwerant** [comment]
Hello @alielkhateeb! Make sure you're on the latest version before you try that feature. You've listed your environment as `2.3.0`, but this feature was introduced in `2.4.0`, so you may need to upgrade first.

If that still doesn't work for you, let me know, and we may need to step through your situation more carefully.

**Comment by alielkhateeb** [comment]
Oh sorry, I did not notice that this was a feature in `2.4.0`
Thank you!
