### ISSUE TITLE
customBodyRender won't update column style on state change

### ISSUE THREAD

**Issue by otaviobps** [gregnb/mui-datatables#707]
On changing the state of an object, data is rerendered with new data from the object state, however the `customBodyRender` in column options is not rerendered. I'm trying to style the column based on the object in component state. The `customBodyRender` functions is called in the first page render, however when the state changes with new data, the data is loaded fine, but the `customBodyRender` rerenders the previous state.

## Expected Behavior

Rerender the column `customBodyRender` with the updated state.

## Current Behavior

`customBodyRender` is rendered again with the previous (first) component state.

## Steps to Reproduce (for bugs)

1. Component renders and calls the api. The api returns a json and is stored in the components state
2. When selecting to change the currency, the api is called again and receives a new json object. The component's state is updated with this new data
3. The data is loaded in the table, however the `customBodyRender` rerenders with the previous object.

What I'm trying to do is this:

```
{
      name: "amount",
      label: t("Amount"),
      options: {
        filter: false,
        customBodyRender: (value, tableMeta, updateValue) => {
          if ("statementEur" in props.statement) {
            const nf = new Intl.NumberFormat("en-GB", {
              style: "currency",
              currency: "EUR",
              minimumFractionDigits: 2,
              maximumFractionDigits: 2
            });

            return nf.format(value);
          }
          if ("statementBtc" in props.statement) {
            const nf = new Intl.NumberFormat("en-GB", {
              style: "currency",
              currency: "XBT",
              minimumFractionDigits: 2,
              maximumFractionDigits: 6
            });
            return nf.format(value);
          }
        }
      }
    },
```
The `mui-datatables` is rendered when `props.statement` has `statementEur`. When `props.statement` is updated with new data and only has `statementBtc`, `customBodyRender` is called again, but is loads the previous state. I can see this because I tried to `console.log(props.statement)` inside the `customBodyRender` and outside the columns array. It always shows `statementEur` in `customBodyRender`, no matter what object is in `props.statement`

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  4.1.1       |
| MUI-datatables  |  2.4.0       |
| React        |  16.8.6       |

**Comment by gabrielliwerant** [comment]
This looks like a duplicate of https://github.com/gregnb/mui-datatables/issues/643, so I'll mark it as such.

**Comment by gabrielliwerant** [comment]
Try out `2.5.1` and see if it fixes your issue,

**Comment by otaviobps** [comment]
Hi @gabrielliwerant version `2.5.1` fix the issue. Thanks!
