### ISSUE TITLE
How to use it with "@material-ui/core": "1.0.0"

### ISSUE THREAD

**Issue by shubham81407** [gregnb/mui-datatables#71]

**Comment by gregnb** [comment]
I’m not sure what you’re asking? Do you have material-ui installed?

**Comment by shubham81407** [comment]
@gregnb mui-datatables use material-ui beta version now material-ui v1.0 has been came so how can i migrate it with v1.0

**Comment by gregnb** [comment]
Sure, so upgrade to the latest version of mui-datatables it also uses material-ui v1.0
