### ISSUE TITLE
Typescript error: option searchText is missing

### ISSUE THREAD

**Issue by skalma** [gregnb/mui-datatables#713]
mui-datatables v2.4
@types/mui-datatables: v2.1.2

Option searchText is missing from interface definition MUIDataTableOptions
I added it myself as:
searchText? :string;

**Comment by gabrielliwerant** [comment]
@skalma Thank you!

If you've added the definition, would it be safe to say that this issue is closed?

**Comment by skalma** [comment]
Sorry, I'm new to this: I meant to say that I've added it in my own codebase, just to be able to continue developing. Have no idea how to get that change into the standard?

**Comment by skalma** [comment]
Just discovered that also customFilterListRender definition is missing from MUIDataTableColumnOptions type definition. I locally set it as:
customFilterListRender?: (value: any) => string;

**Comment by gabrielliwerant** [comment]
Ah, so this isn't a typescript library, and at the present time, there aren't any plans to make it one, so if you want to add type definitions to intentionally and wonderfully loosely typed language, then you'll have to ad them yourself. :D

You can find some instructions on that here http://blog.wolksoftware.com/contributing-to-definitelytyped.

This is the project to add types to 3rd party packages: https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by skalma** [comment]
Thx for the links, i will look into it when i find the time

**Comment by skalma** [comment]
searchText has been added to MUIDataTableOptions and the value custom has been added to FilterType variable in the types definition for mui-datatables, see version 2.1.5 in [https://www.npmjs.com/package/@types/mui-datatables]
