### ISSUE TITLE
Filter Fields Are partially hidden

### ISSUE THREAD

**Issue by Nasseratic** [gregnb/mui-datatables#719]
The filter fields are partially hidden.

![Screenshot](https://i.ibb.co/9gMvRz4/Screenshot-from-2019-06-26-11-07-47.png)

## Expected Behavior
The fields should totally be visible.

## Current Behavior
Extra paddings or margin with the fixed height caused the filed to be partially hidden

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    ^3.9.0     |
| MUI-datatables  |      ^2.4.0  -> 2.5.1   |
| React        |    16.6.0     |
| browser      |   Chrome      |

**Comment by gabrielliwerant** [comment]
You're using currently unsupported functionality, as you are modifying the type of input field in the filters. Without official support (which may be coming in the next release), you are on your own here. You have the ability to override any styles provided to the table, so you should be able to fix it by doing that.

**Comment by gabrielliwerant** [comment]
You can keep an eye on this https://github.com/gregnb/mui-datatables/pull/708, as I believe it will fix your issue and provide you with a supported API to add custom rendered filers.

**Comment by Nasseratic** [comment]
Thanks a lot @gabrielliwerant
