### ISSUE TITLE
File download does not work in Edge

### ISSUE THREAD

**Issue by teadams** [gregnb/mui-datatables#72]
If you try to download with Edge, you get another window to open and then it is just blank.

I did some research, and it appears "Data URI link <a href="data: doesn't work in Microsoft Edge".
https://stackoverflow.com/questions/33154646/data-uri-link-a-href-data-doesnt-work-in-microsoft-edge

There are a bunch of similar solutions I found.

I tested one paralleling the solution amsterdamharu  posted and it worked in both Edge and Chrome.
     https://github.com/highcharts/export-csv/issues/76

Other examples solving the same problem:
- React-csv code
     https://github.com/abdennour/react-csv/blob/master/src/core.js
- Medium article
    https://medium.com/@danny.pule/export-json-to-csv-file-using-javascript-a0b7bc5b00d2

**Comment by gregnb** [comment]
Which version of edge are you using?

**Comment by teadams** [comment]
Google Chrome is up to date
Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by gregnb** [comment]
I made an update and it will be in this weeks release

**Comment by richardjzhang** [comment]
@gregnb Me again! Just been testing the download option on Internet Explorer 11, and it doesn't seem to work. Something to do with Blob?

**Comment by gregnb** [comment]
@richardjzhang I did borrow some from react-csv. Is edge no longer a problem? Just IE?

**Comment by richardjzhang** [comment]
@gregnb Yep works fine on Edge, but I run into issues on IE 11

**Comment by gregnb** [comment]
I’ve decided we will no longer support IE11
