### ISSUE TITLE
Typing in filter fields not working

### ISSUE THREAD

**Issue by Nasseratic** [gregnb/mui-datatables#720]
When typing in the text fields in filters the input value doesn't change and the typed latter is sent every time to `onFilterChange` function.

## Expected Behavior

User can type a word.
## Current Behavior

The filed don't respond to typing or respond with a bugyy behavior.
![gif](https://i.ibb.co/nQ1kYXB/ezgif-com-optimize.gif)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     3.9.0    |
| MUI-datatables  |     2.5.1    |
| React        |    16     |
| browser      |    Chrome     |

**Comment by gabrielliwerant** [comment]
I'm going to need a codesandbox example of this not working. Firstly, it looks like your material ui version is too high. But secondly, go ahead and run the library examples of using filters. You will see that those, as well as the tests, are running fine. That means there's likely something very specific you're doing that's breaking it, and without knowing what that is, it's impossible to fix.
