### ISSUE TITLE
rows click event

### ISSUE THREAD

**Issue by JoonHyunJeong** [gregnb/mui-datatables#73]
i'm trying to handle event when row clicked but it seems there is no such options in mui-datatables.
How can i implement it?

**Comment by gregnb** [comment]
I will address these shortly as a part of a larger improvement

**Comment by gregnb** [comment]
I am going to provide a callback named `onCellClick` which will look like so:

```
function(tableMeta) => void 

tableMeta: {
  rowIndex: number,
  columnIndex: number,
  columnData: array, // Columns Options object
  rowData: array, // Full row data
  tableData: array, Full table data
  tableState: {
    announceText: null|string,
    page: number,
    rowsPerPage: number,
    filterList: array,
    selectedRows: {
      data: array,
      lookup: object,
    },
    showResponsive: boolean,
    searchText: null|string,
  },
}

```

That will provide you every bit of information

**Comment by gregnb** [comment]
This is now available in the latest release. A callback function named `onCellClick`

**Comment by laxmikamala** [comment]
how to get particular row data onRowClick in mui-datatables
