### ISSUE TITLE
Table not acting Responsively - Extends Grid size

### ISSUE THREAD

**Issue by hassant4** [gregnb/mui-datatables#732]
## Expected Behavior

When using MUI Grids (or even without), the table should restrict its width to the size of the window/browser if using `responsive: 'scroll'`

## Current Behaviour
The table flows off screen when I add enough columns, Typography used for benchmark, if I used xs={8} the scroll behaviour works (but the remaining xs={4} still extends beyond the window size) but I need to use xs={12}

Before MUI-Datatables: [Imgur](https://i.imgur.com/5b29ZVx.png)
After MUI-Datatables: [Imgur](https://i.imgur.com/cT3AytS.png)

## Steps to Reproduce (for bugs)

```
const options = {
  filterType: 'checkbox',
  responsive: 'scroll',
};

function ProjectExperimentTable(props) {
  const { classes } = props;

  return (
    <div className={classes.root}>
      <Grid container spacing={24}>
        <Grid item xs={12}>
            <Typography variant="h4" component="h2">
              Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem Lorem 
            </Typography>
        </Grid>
        <Grid item xs={12}>
          <MUIDataTable
            title={"Experiments"}
            data={data}
            columns={columns}
            options={options}
          />
        </Grid>
      </Grid>
    </div>
  );
}
```

**Comment by gabrielliwerant** [comment]
I can't find anything wrong with the table display using your markup (though I don't know what you have in `classes.root`). This looks like a problem on your end with the way you're using the `Grid`. Maybe in a codesandbox you'd be able to demonstrate something wrong with the table?

**Comment by hassant4** [comment]
I managed to get past this by checking other parts of the code, I was wrapping the return above in another div (w/o any custom classes btw) but removing that fixed everything. It was hard to spot without rebuilding the code in codesandbox.

Also what would be cool is if we can have the option to `responsive: 'scroll'` in the horizontal direction only and not the vertical
