### ISSUE TITLE
Feature Request - Pass in initial filter values

### ISSUE THREAD

**Issue by teadams** [gregnb/mui-datatables#74]
Use case
1. User is viewing a list of items
2. Use clicks on one of the items, which takes the user to a MuiDatatable.
3. Ideally, the view would be filtered based on the item the user clicked.

Unless I am mistaken, there is no one to specify that MUIDatatable should have a specific filter displayed by default.  (I do see a way to pass in if the column should be displayed or not, which is a similar concept).

As a work around, I built another filter on the outside.
As similar request would be the ability to pass in search text.

Also to think about, if I have a filter or search active and then download a csv, the csv has all the rows instead of the what is visible in the table.

**Comment by gregnb** [comment]
https://github.com/gregnb/mui-datatables/blob/master/examples/serverside-options/index.js

You can pass in a filterList which is an array of arrays. Each inner array represents results to filter a column by. I think that is what you're looking for?

**Comment by teadams** [comment]
Wonderful, thanks!

**Comment by RUPAAK** [comment]
i want to set default value of a filter box. How do I do that, can you please help?

**Comment by codyng** [comment]
me2, how to set initially the filtered attributes on top of the table? I mean the UI not the request to the backend.
I need to put the selected filters shown with Mui Chips.

Also, as replied from gregnb in 2018, passing the column filters as the array of arrays is not code-friendly as in the backend it's not good to process.

My workaround is passing reserved keywords for page, itemsPerPage, sort and order using _page, _itemsPerPage, _sort and _order, and business logic query strings like name=cat, color=black.
?_page=1&_itemsPerPage=10&_sort=createdAt&_order=desc&name=cat&color=black

But how to set the selected filters shown with Mui Chips?

**Comment by codyng** [comment]
I found the answer. Just set the filterList from the column option, e.g. filterList: [ 'cat' ]
I have searched for some questions with this same question but I couldn't find any answers.
Why hasn't anyone addressed this question? :)
