### ISSUE TITLE
Invalid prop childreen - ForwardRef(TableCell)

### ISSUE THREAD

**Issue by Roberto4091** [gregnb/mui-datatables#743]
Hi! Help!
I'm using the example of a table they give on their website, but with the latest versions.
I have an error with the TableCell component, the error can be seen [here](https://codesandbox.io/embed/young-violet-2bl1q), could you help me?

| Tech         | Version |
|--------------|---------|
| Material-UI  |    ^4.1.1     |
| MUI-datatables  |    ^2.6.1     |
| React        |    ^16.8.6     |
| browser      |    chrome    |

**Comment by djheroez** [comment]
Interesting... if you get rid of the **sort: false** the error message does not longer appear.

**Comment by gabrielliwerant** [comment]
Yep, figured that out and am already on it.

**Comment by gabrielliwerant** [comment]
Should be resolved in `2.6.2`.
