### ISSUE TITLE
No applyfilter/applysearch event available on tableChange option (next to the filterChange and search event)

### ISSUE THREAD

**Issue by skalma** [gregnb/mui-datatables#747]
I'm using:
- mui-datatables 2.4.0
- material-ui/core 3.9.2
- react 16.8.1
- typescript 3.3.3
- vs2017 CE 15.9.12
- chrome 75.0.3770.100 

I handle pagination myself (serverSide = true) and use tableChange option to catch events and handle searching and filtering (for searchresults and filterresults i switch to serverside = false so mui-datatables handles pagination of those results). However: there are only filterChange and search events available that fire on every input of the user. I want to only search and filter (both backend actions that take time) if a user decides to press the search button or the apply filter button (last one is not available). Am i missing something?

Tried sofar: - I have put a console.log on the tableAction event, but see nothing when the search button is pressed or when i hit enter in the filter dialog.

## Expected Behavior
Fire an applysearch event that only fires when a user hits the search button. Same for filtering: add an applyfilter button and fire an applyfilter event when user hits it. 

## Current Behavior
on every character entered in the searchbox the search event fires, causing my search code to fetch search results, an expensive backend action i only want to perform when the user hits the search button. Same for filtering: every change in the filter dialog fires the filterchange event.
I just noticed that when pressing the remove search cross which empties the search box also the same search event is fired? Is it possible to change that also, it makes more fine-tuned control possible

**Comment by gabrielliwerant** [comment]
For search, there is an `onSearchOpen` callback.

Via custom filter logic and display, you should be able to change how filters work enough for you to get the control you want. See the `customize-filters` example. You are given access to the `onChange` method and can therefore decide when you want to fire it (like on a button click that "sets" the filter, if you so choose).

**Comment by skalma** [comment]
Checking in after holiday: i got the search part working using customSearchRender callback. For filters i still rely on having to update filter results on every filter change. I checked the examples but could not get it working. Is ok for now, search update on every char typed was my main concern. Closing this issue.

**Comment by gabrielliwerant** [comment]
I don't have a handle on precisely what you want to do, but I'm pretty sure it is possible with a bit of work, as there are many options for customizing behavior. A more recent example, `column-options-update` might be more helpful to you as it gives a way to change filters via button press.
