### ISSUE TITLE
Paging resets when serverside search and change page

### ISSUE THREAD

**Issue by Avd6977** [gregnb/mui-datatables#762]
## Expected Behavior
Page passed in as prop should be taken

## Current Behavior
Page prop is ignored when search is not null. This disables paging when search exists and done serverside with table reload

## Steps to Reproduce (for bugs)

1. Set serverside true and maintain state
2. Search for a value
3. Select Next Page
4. Page stays at 0

## Your Environment

| Tech         | Version |
|--------------|---------|
| MUI-datatables  |     2.6.1    |

**Comment by gabrielliwerant** [comment]
Thanks for finding this, there is a bug here, but it's a bit more subtle than it appears. We definitely need to override the page value the first time a search is entered. However, in subsequent page updates, we should allow the page to change. I put some notes in the PR. It's possible there won't be a fix without a state refactor overhaul for the whole table. :(

**Comment by gabrielliwerant** [comment]
Should be resolved in `2.8.0`.
