### ISSUE TITLE
selectableRowsOnClick overrides isRowSelectable

### ISSUE THREAD

**Issue by pbatleyGH** [gregnb/mui-datatables#764]
## Expected Behavior

selectableRowsOnClick seems to override isRowSelectable. A row with isRowSelectable that returns false can still be selected by clicking it. The checkbox appears greyed out suggesting that the isRowSelectable styling is being applied.

I would expect the behaviour to be that a row with isRowSelectable false should not be selectable at all. If isRowSelectable returns true, then the checkbox for selection should work, and if isRowSelectable returns true and selectableRowsOnClick is true then the row should be selectable by clicking anywhere within it.

## Current Behavior

(see previous paragraph)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.2.0    |
| MUI-datatables  |    2.6.2     |
| React        |     16.8.6    |
| browser      |   Chrome 74.0.3729.108      |

**Comment by gabrielliwerant** [comment]
Nice find, I can confirm this is a bug. Thank you!

**Comment by gabrielliwerant** [comment]
Should be fixed in `2.6.3`.
