### ISSUE TITLE
Update rows without changing sort?

### ISSUE THREAD

**Issue by patorjk** [gregnb/mui-datatables#770]
Consider this scenario: There is a column called "Status" that can be set to true/false. A user is able to select a row, push a button, and toggle the value of "Status" for that row. If the table is currently set to sort by the column "Status", the table will re-sort after the data change and the row the user was working on will no longer be in the same place. This can be disorienting.

Is there a way to modify the data of a particular row without causing the table to reorder its data?

I've put together a rather crude example here:

https://codesandbox.io/s/muidatatables-custom-toolbar-k9yds

Steps:
* Select the top entry and click "Change" in the toolbar.
* Notice that the table has resorted itself.

**Comment by gabrielliwerant** [comment]
Forgive me; trying to get a handle on the use case. It sounds like you want to both sort and not sort at the same time? If a column is set to sort, I would find it confusing if changing the data did not re-sort it. If I wanted it to then sort it after that, I'd have to sort twice to get back to that state, and it would be further confusing to me that the sort icon arrow is showing, indicating that the data should be sorted.

If what you want is an initial sorting, but not sorting after that point (on a given column), then I would not set a default sort through the table, and instead pre-sort my data before I fed it to the table. Then it can take whatever initial ordering you want, it won't re-sort automatically when the data changes, and the user can then opt into a sort at any point, as expected.

**Comment by gabrielliwerant** [comment]
Another way you can go is the full custom route, by creating `customHeadRender` with a new sort icon that will trigger as you want and/or the `customSort` function in the main options to determine when a column sorts.

**Comment by patorjk** [comment]
Sorry, it's is a little confusing. For context, I'm rewriting a jQuery/AngularJS app in React and in the existing app, there's a datatable where a user can sort and then perform operations on rows. Some users were getting upset that the rows would disappear after an operation was performed. In the jQuery Datatable component, you can update table entries without a resort, which is how we got around this issue (they would want to sort by this field, and perform their operations).

I think your suggestion of a full custom route may be the solution. I hadn't thought about overriding the column headers. That's basically what I'm looking for (only to sort when a column header is clicked). I actually think that may solve this issue, thanks!

**Comment by gabrielliwerant** [comment]
No problem, we've all been there. Ah, these kinds of UX issues are interesting. Good luck!
