### ISSUE TITLE
Sort arrows disappeared, in filters: no text is displayed(2.6.3)

### ISSUE THREAD

**Issue by alexeykush** [gregnb/mui-datatables#773]
## Expected Behavior
Before 2.6.3 it was possible to see sort arrows and written text in filters.

## Current Behavior
Sort arrows disappeared, in filters: no text is displayed and it rememebers only the first letter. It happens only when serverSide is enabled + passing onTableChange, but i need both these options. I've noticed that after updating to 2.6.3 from 2.4.0.
Also, if selectableRowsOnClick is enabled --> can't click on checkbox.
Please help, i'm having deploy today
## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.1.1     |
| MUI-datatables  |      2.6.3   |
| React        |    16.8.6     |
| browser      |    Chrome( 75.0.3770.100 )     |

**Comment by alexeykush** [comment]
Found out that there are many changes between these two versions, found solution

**Comment by gabrielliwerant** [comment]
Interesting, I was not aware it was ever possible to have sort arrows in filters. As far as I know, such a thing only recently became possible via custom filters in `2.6.0`.

**Comment by alexeykush** [comment]
Sorry, incorrectly expressed my thoughts. Sort arrows disappeared not in filters.They disappeared in the table heading. Previously i used version 2.4.0. in my project and i've had server side pagination, custom filtering and sorting. And before updating, table remembered filter text and which columns were sorted. After updating its disappeared. So, now every new request table forgets everything. Later I found this information and refactored these things(every column has option with sortDirecton and filterList). I needed update because there was a problem with selectableRowsOnClick: true and isRowSelectable(the first override the second one), and now this problem is gone , but if selectableRowsOnClick is enabled , you can't click on checkbox.Can it be fixed? Thank you

**Comment by gabrielliwerant** [comment]
Have you verified the select issue on `2.6.4`? I just fixed a bug there that may have been causing the selection problem.

**Comment by alexeykush** [comment]
not yet, I'll try

**Comment by alexeykush** [comment]
Yes, it fixed.Thank you
