### ISSUE TITLE
onDownload return false do not cancel download

### ISSUE THREAD

**Issue by mikenlanggio** [gregnb/mui-datatables#774]
I want to cancel download button.
I `return false` according to the docs. But it's not working.
It's still download.
Help me, please.
Thank you

**Comment by gabrielliwerant** [comment]
I'll need you to post a minimal example that demonstrates the issue in order to see what's happening. It works on my end and it passes the appropriate tests, so it is likely that there is something on your end that is causing the issue.

**Comment by mikenlanggio** [comment]
Here is my code sandbox.
https://codesandbox.io/s/muidatatables-custom-toolbar-mfut5
It's event don't go into function

**Comment by gabrielliwerant** [comment]
Ok, so it looks like your issue is that your version of this library is too low, at least according to the example you created. The feature that lets you skip download was added to this release https://github.com/gregnb/mui-datatables/releases/tag/2.6.0, so you need that version or higher.

**Comment by gabrielliwerant** [comment]
Closing as resolved.

**Comment by ronaiza-cardoso** [comment]
Hi, the version that I'm using is higher than `2.6.0` and the download button is not been disabled when returning false. Here is my sample: https://codesandbox.io/s/mui-datatables--snr7y

And I have one question about download external CSV, how could I do that?
