### ISSUE TITLE
does /examples/customize-filter/ Age form work?

### ISSUE THREAD

**Issue by hassant4** [gregnb/mui-datatables#775]
Seems like it isn't rendering the form as a custom filter display:
Literally copied and pasted the code into ProjectExperimentTable.js:

https://codesandbox.io/embed/mui-datatablesissue-usdoj

infact, getting rid of the Form imports doesn't even throw an error

**Comment by gabrielliwerant** [comment]
In your example, the library version is too low. The feature was added to this release: https://github.com/gregnb/mui-datatables/releases/tag/2.6.0. If you update the library, it will work.

**Comment by hassant4** [comment]
awesome, working, thanks!
