### ISSUE TITLE
Can Selected Rows Be Cleared From Another Component?

### ISSUE THREAD

**Issue by tony-molumby** [gregnb/mui-datatables#777]
I would like to be able to call the setSelectedRows() method available to customToolBarSelect from another component.  The user flow would look like this:

1) User selects a row and a dialog appears.
2) User closes the dialog and setSelectedRows is called which clears the row.

Is this possible in the current version?  Thank you.

Versions: 
react: 16.8.6
mui-datatables: 2.6.3

**Comment by tony-molumby** [comment]
Solved this out by using handleRowClick instead and changing selectableRows to 'none'

**Comment by gabrielliwerant** [comment]
If you are looking to dynamically determine what rows are selected based on some condition, you do not need any internal row handling functions, as you can manage this via `rowsSelected` in the main table options.
