### ISSUE TITLE
Props Not Updating from Parent State After onRowClick Function

### ISSUE THREAD

**Issue by tony-molumby** [gregnb/mui-datatables#780]
I am having difficulty getting props to update on a child mui-datatables component from a parent when I click a row on the child component.  Here is the code:

Parent:

    class ParentPage extends Component {
      constructor(props) {
        super(props);
        this.state = {
           columns: columns,
           data: [ ... data ]
           selectedRowIndex: null,

    handleRowClick = (rowData, rowMeta) => {
      this.setState({
        selectedRowIndex: rowMeta.dataIndex
     })
    
      
    render() {
      return (
        <ChildDataTable
          title='Child Table'
          onRowClick={this.handleRowClick}
          columns={this.state.columns}
          data={this.state.data}
          selectedRowIndex={this.state.selectedRowIndex}
        >
        </ChildDataTable
        )}
    }

Here is the ChildDataTable Component:

    const ChildDataTable = ({
      title,
      onRowClick,
      columns,
      data,
      selectedRowIndex,
      classes
       }) => (
        <DataTable
            title={title}
            columns={columns}
            data={data}
            options={{
            onRowClick: onRowClick,
            selectableRows: 'none',
            customToolbarSelect: (selectedRows, displayData, setselectedRows) => {},
            setRowProps: (row, dataIndex) => {
                console.log(selectedRowIndex)
            }    
          >
          </DataTable>
    )

## Expected Behavior
The console.log in the options.setRowProps function of the ChildDataData component will show the correct props.selectedRowIndex when a row is clicked.

## Current Behavior
The state.selectedRowIndex in the parent component is being updated on row click, but the child component's props.selectedRowIndex is not being updated.  So the console.log(props.selectedRowIndex) always shows the initial value of the parent component's state.selectedRowIndex which is null.

## Steps to Reproduce (for bugs)

Please see code above and click on any row and look at your console.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |  4.2.0   |
| MUI-datatables  |  2.6.3  |
| React        | 16.8.6  |
| browser      |  chrome  75.0.3770.10 |

**Comment by tottivega** [comment]
I have encountered this same exact bug, this is very strange!

**Comment by gabrielliwerant** [comment]
`onRowClick` is intentionally prevented from interacting with row selection because this leads to a number of bugs and confusing situations. The proper callback for hooking into row selections is `onRowsSelect`. Additionally, there was a bug here that was fixed in `2.6.4`, so see if upgrading to that also helps.

If you want to select rows on click, there is an options for it: `selectableRowsOnClick`. `onRowsSelect` is still the correct callback in that situation.

**Comment by gabrielliwerant** [comment]
Another thing is that you're going to run into problems sending in your columns as state. This will cause the table to refresh, so it's not recommended unless you are prepared to track the state of your table at every change. Unfortunately, things are not as simple as sending in whatever props you want and then just having everything change as you would expect. The table currently manages internal state, derived from props, so certain things will cause a refresh of the whole internal state, one of them being columns.

**Comment by tony-molumby** [comment]
@gabrielliwerant Thanks for the information on columns as state.  I changed my implementation to your suggestions above and I guess it will be workable for now.  I guess I wish there was an option to allow row selection with styling without displaying a checkbox.  It takes up horizontal screen space which can be crucial with larger tables / smaller screens.  Am I missing that option?

**Comment by gabrielliwerant** [comment]
@tony-molumby What you are describing isn't available as a default option, however, you can customize styling to create that experience if you wish. What you would need is to set `selectableRowsOnClick` and then override styles to hide the checkbox column.

**Comment by tony-molumby** [comment]
Excellent, I will try that out.  Thank you!
