### ISSUE TITLE
[Enhancement] Loading state when changing pagination

### ISSUE THREAD

**Issue by NoMercy235** [gregnb/mui-datatables#785]
I am facing an issue where I have to show some sort of loading state in the table while the data is requested from the server when the pagination changes (either page or items per page). 

I know this is possible by controlling each row separately and showing a different UI when the request happens, but I was wondering whether or not it would be possible to expose a property on the table which could accept a React component that will be displayed as an overlay (or in any other way you think it's appropriate) over the current rows (to prevent the user taking actions on them) while the request for data fetching is in progress.

I was thinking of something like this:

The normal state of the table:
![image](https://user-images.githubusercontent.com/24717857/61595102-ac74fd80-abfb-11e9-85c4-f9dbac52f4f9.png)

Table after the next page button (or anything else related to pagination) was preseed: 
![loading-state](https://user-images.githubusercontent.com/24717857/61595199-e72b6580-abfc-11e9-8169-3eb77fe6c8e4.png)

The loading state would be controlled from the outside so that it can disappear when the request ends.

Do you think something like this could be feasible?

**Comment by gabrielliwerant** [comment]
Hello, and thank you for your interest!

To me, it's less a question of feasibility, and more, is this something the table should be doing, or the implementer should be doing? I think the problem with adding specific implementations for a feature with something that often has a wide variety of tastes among different UI/UX people is that it will be difficult to accommodate everyone, but the feature will open the door for maintenance, and requests like "if it does this, why not this?" (which would be valid suggestions).

The way the library tends to handle aesthetics now is that it provides the ability to customize the appearance via custom render functions or style overrides.

I'm also more concerned with adding features that may not be possible in any other way (than to have them integrated into the table). I believe what you want is already doable without any changes in the library. You could place a loading div above the table, and then position it down over the table. Something like this (psuedocoded):

```
<div>
  <LoadingOverlay isLoading={this.state.isLoading} styles={{ height: '499px', z-index: '11', background: 'gray transparent 50%', marginTop: '499px' }} />
  <MUIDataTable data={this.state.data} columns={columns} options={options} />
</div>
```

I haven't tested the above, and the CSS isn't all there or entirely accurate, but hopefully it gives you the idea.

**Comment by NoMercy235** [comment]
Hello @gabrielliwerant ! You are right. The loading workflow may see hundreds of variations between various applications, so it might not be a good idea to implement it here. I'll try to do it your way and see how the results look. 👍 

Feel free to close this issue. 😁
