### ISSUE TITLE
Download the data based on filtered value

### ISSUE THREAD

**Issue by nuprakash** [gregnb/mui-datatables#786]
## Expected Behavior

    After the filter is done, by downloading the data only filtered value must download as CSV

## Current Behavior

   By downloading, all the data are download as CSV

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    0.19.4     |
| MUI-datatables  |   2.4.0      |
| React        |   16.1.1      |
| browser      |         |
| etc          |         |

**Comment by gabrielliwerant** [comment]
Marking as duplicate as this issue has been covered in a few places and there are PRs up to address it (though they need some work before they can merged/released). You can follow along in these places:

https://github.com/gregnb/mui-datatables/issues/568, https://github.com/gregnb/mui-datatables/pull/440, https://github.com/gregnb/mui-datatables/pull/725

**Comment by gabrielliwerant** [comment]
This functionality is now available in `2.7.0`.

**Comment by nuprakash** [comment]
Ya, It's working @gabrielliwerant
