### ISSUE TITLE
Reusable TablePagination for customFooter

### ISSUE THREAD

**Issue by patorjk** [gregnb/mui-datatables#789]
I'm looking to do a custom footer, though all I really want to do is add a "jump to page" option (maybe a dropdown or buttom that brings up a dialog, haven't decided yet). I was poking around to see if I could reuse the existing footer and just stick another component next to it, but I noticed two things:

* The footer options aren't passed to the customFooter callback. These options are needed for the TablePagination component (https://github.com/gregnb/mui-datatables/blob/master/src/components/TableFooter.js#L28).
* The TablePagination component starts with MuiTableFooter and MuiTableRow tags, so even if I had the options, I wouldn't be able to reuse this component (https://github.com/gregnb/mui-datatables/blob/master/src/components/TablePagination.js#L56).

I can recreate everything, but it would be nice to reuse what the table uses. Not sure if it would break anything, but spliting TablePagination into 2 components (a reusable BaseTablePagination component and the normal TablePagination component that has the MuiTableFooter/MuiTableRow tags wrapping BaseTablePagination), plus passing the pagination options to customFooter would seem to allow this in theory.

**Comment by gabrielliwerant** [comment]
Should be resolved via your PR for `customFooter` options in `2.9.0`.
