### ISSUE TITLE
select option in stacked mobile mode

### ISSUE THREAD

**Issue by RaySheikh** [gregnb/mui-datatables#79]
Hi Greg, 

Is there a way to override the style to allow selecting of the rows in mobile stacked version and display the toolbar on top with the buttons? sort of similar to the screenshot below.

![image](https://user-images.githubusercontent.com/35114618/41061518-baa26a8a-6987-11e8-9fdd-92cfff5a3cf7.png)

**Comment by gregnb** [comment]
As it stands today no. I will have to think about adding such a feature

**Comment by gabrielliwerant** [comment]
It looks like this functionality has been added since this issue was open, and exists in version `2.2.0`.
