### ISSUE TITLE
Width on custom filter component

### ISSUE THREAD

**Issue by pkmnct** [gregnb/mui-datatables#790]
## Expected Behavior
FormControl should allow components to fill width
![image](https://user-images.githubusercontent.com/8972556/61825467-0a852900-ae26-11e9-8268-ab142a2c299c.png)

## Current Behavior
FormControl limits the width of components
![image](https://user-images.githubusercontent.com/8972556/61825406-f17c7800-ae25-11e9-82df-a05fe53b4e46.png)

We are using React-Select within our project, and attempting to make a custom filter using it results in this.

**Comment by emil-alexandrescu** [comment]
@pkmnct How did you solve overflow issue?

**Comment by pkmnct** [comment]
@emil-alexandrescu https://github.com/gregnb/mui-datatables/pull/791#issuecomment-515504268
