### ISSUE TITLE
Toolbar style property has different object mapping compare to docs

### ISSUE THREAD

**Issue by syedabuthahirm** [gregnb/mui-datatables#8]
I want to add a bottom border to the toolbar. if I follow the documentation it's not working. the following one is worked for me.
## Config
This is my workaround for toolbar style issue.
```js
styles: {
        table: {
            toolbar: {
                root: {
                    borderBottom: '1px solid #e4e4e4'
                },
                search: {
                    searchText: {
                        color: 'red'
                    }
                }
            }
        }
}
```

**Comment by gregnb** [comment]
I will look into this thank you

**Comment by gregnb** [comment]
@syedabuthahirm so I'm trying to look for where I specify and example of changing the borderbottom color and I don't see it? can you point this out? Otherwise you're doing it correctly you need to target `root`
