### ISSUE TITLE
CustomRowRenderer using TableBodyRow

### ISSUE THREAD

**Issue by Fabbok1x** [gregnb/mui-datatables#804]
Trying to render rows as usual, but extending TableBodyRow at the same time.
Is there any example available utilizing TableBodyRow?
TableRow furthermore has options such as options.selectableRowsOnClick, 
which don't seem to be passed via customRowRender(data, dataIndex, rowIndex) => React Component.

Is there any way to achieve regular rendering using TableBodyRow via customRowRender?

**Comment by Fabbok1x** [comment]
Neverminded got it going.

**Comment by ntt2k** [comment]
@Fabbok1x Hey, how do you figure out this problem?
I'm trying to achieve regular rendering using TableBodyRow via customRowRender because only certain data requires custom render? Please advise?

**Comment by Fabbok1x** [comment]
using customRowRenderer in the options will work (basically), then you will need to extract the relevant parts (render) from TableBody and do some modifications to have the passed objects suit the class. What I didn't get working is however some bound functions as isRowSelected because the props in there won't be available in the class that you're gonna define it in.
There is for sure a fix possible but for time reasons I moved to cloning the repo and doing modifications directly to the MUIDataTable. That way you can also modify/extend the classes to your requirement.
