### ISSUE TITLE
Request: Allow custom buttons/functions for selected row(s)

### ISSUE THREAD

**Issue by dustingraves** [gregnb/mui-datatables#81]
I would like to be able to pass in another button next to the delete button that fires a callback I can work with. This would be useful if you want to trigger some other function for the selected row(s) other then delete.

This could be done through an `onRowsCustomFunction` function in the options object. The icon could be set this way through `onRowsCustomIcon`.

Additionally, this could be an array of functions.

**Comment by dustingraves** [comment]
just found `customToolbarSelect`

**Comment by gregnb** [comment]
I really need to finish the docs site and make this easier to navigate and find solutions. Sorry for the trouble
