### ISSUE TITLE
disable escape key behaviour

### ISSUE THREAD

**Issue by farodrig** [gregnb/mui-datatables#811]
Is there a way to avoid closing the search input when I press escape key?

I can't figure out a workaround to disable this behaviour.

**Comment by gabrielliwerant** [comment]
There isn't a way to disable this at the moment. Is there a good reason to disable this behavior? Seems like appropriate UX to me, but maybe I'm missing something.

**Comment by farodrig** [comment]
I'm customizing the search behaviour for my app and the escape key breaks it.

So I wanted to know if there is a way (workaround) to disable it.

I think it may be a appropriate UX in the general case but not necessarily in a customized scenario.

Anyway, thanks for your answer :)

**Comment by gabrielliwerant** [comment]
Sure, no problem. It's possible that such an option can be incorporated here https://github.com/gregnb/mui-datatables/pull/771. I will think on it.

**Comment by farodrig** [comment]
Thanks :)
