### ISSUE TITLE
Column rendering layout broken with small screen size

### ISSUE THREAD

**Issue by bennidi** [gregnb/mui-datatables#812]
When I reduce the screen size such that breakpoint `xs` is hit, then the table rendering seems broken. The column header renders into each row (see attached screenshot). This may be due to some CSS issue in my project (I have forked the project from an existing template and don't yet know my way around yet).
Still, I believe it is all fairly standard and such a behavior should not be caused by outer CSS. Also, other components of the app like `Tabs` handle the transition well.

This is what my theme preakpoint config looks like:

```js
{ "breakpoints": {
    "keys": ["xs", "sm", "md", "lg", "xl"],
    "values": { "xs": 0, "lg": 1280, "sm": 600, "xl": 1920, "md": 960 }
  }}

```

This is the screen I get before hitting the `xs` breakpoint.

![mui-datatables-renderproblem-expected](https://user-images.githubusercontent.com/1842420/62488713-4a082980-b7c5-11e9-86dd-0543286e6b9b.png)

And this is what it looks like when layout passes the breakpoint (and several components respond with layout changes).

![mui-datatables-renderproblem](https://user-images.githubusercontent.com/1842420/62488430-9141ea80-b7c4-11e9-9987-06485e1621ab.png)

Is this a bug in mui-datatables or more likely of my project layout?

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.2.1     |
| MUI-datatables  |    2.7.0     |
| React        |    16.8.6     |
| browser      |    firefox, chrome (Ubuntu)     |
| etc          |         |

**Comment by gabrielliwerant** [comment]
Hello @bennidi. It's hard to say at this point where the issue is, as I'd need to know more about your table options and code. Are you able to reproduce this issue from one of the examples in the project? You could take a simple example, add it to a codesandbox, and then progressively add features from your own project until it breaks. If you can do that, I would be happy to take a look.

**Comment by bennidi** [comment]
Yes, the code is taken from the example in main README.md. I just render it within the layout of my app. 

```js
import React from 'react';
import MUIDataTable from "mui-datatables";

const columns = [
  {
    name: "name",
    label: "Name",
    options: {
      filter: true,
      sort: true,
    }
  },
  {
    name: "company",
    label: "Company",
    options: {
      filter: true,
      sort: false,
    }
  },
  {
    name: "city",
    label: "City",
    options: {
      filter: true,
      sort: false,
    }
  },
  {
    name: "state",
    label: "State",
    options: {
      filter: true,
      sort: false,
    }
  },
];

const data = [
  { name: "Joe James", company: "Test Corp", city: "Yonkers", state: "NY" },
  { name: "John Walsh", company: "Test Corp", city: "Hartford", state: "CT" },
  { name: "Bob Herm", company: "Test Corp", city: "Tampa", state: "FL" },
  { name: "James Houston", company: "Test Corp", city: "Dallas", state: "TX" },
];

const options = {
  filterType: 'checkbox',
  resizableColumns:true
};

export default function CatalogueList(){

  return (<MUIDataTable
    title="Employee List"
    data={data}
    columns={columns}
    options={options}
  />)

}

```

**Comment by bennidi** [comment]
The same happens when exporting to pdf. Even with wide screen size and correct rendering in the browser, the generated pdf shows the same issue of column headers leaking into each row

**Comment by bennidi** [comment]
I don't think that I can isolate parts of my project setup and build a trace of when the app breaks the table. I wouldnt know where to start and it seems quite a bit of work. Have you ever seen this behavior before?

**Comment by gabrielliwerant** [comment]
Unfortunately, I can't be of much help without seeing and interacting with your code. There are too many possibilities. Unless you can show a simple example that breaks, there is a good chance that the issue is not specifically in the library, but in the way it is being utilized in your project.

**Comment by bennidi** [comment]
Understood. Was just giving it a try since it might have been a known issue.
