### ISSUE TITLE
rowsSelected does not work in version 2.7.0

### ISSUE THREAD

**Issue by PovilasSlekys** [gregnb/mui-datatables#817]
Updated from version 2.6.2 to 2.7.0 to find rowsSelected does not work as before.

## Expected Behavior
In 2.6.2 providing rowsSelected would select the provided rows when rendering the datatable.

## Current Behavior
In 2.7.0 the provided rowsSelected option is ignored and no rows are selected.

Minimal code example for reference:

https://codesandbox.io/s/muidatatables-example-1p637

**Comment by gabrielliwerant** [comment]
Yes, there is a regression here, thanks for point that out! I will work on a fix.

**Comment by gabrielliwerant** [comment]
The issue should be fixed here https://github.com/gregnb/mui-datatables/pull/818 and will be in the next release. Until then, if you want to upgrade to the latest version immediately but have working behavior with this feature, then you can supply the `selectableRows` option in your options object. The bug only exists when none is specified.
