### ISSUE TITLE
Unable to Scroll Smoothly 

### ISSUE THREAD

**Issue by kumargugloth** [gregnb/mui-datatables#820]
i have  one month data. for every day i was creating a New Table For that But  Iam unable to scroll smoothly 
Any idea is why is it happening like that?

**Comment by gabrielliwerant** [comment]
Hm, I haven't experienced that on my end, so in order to debug your situation, I'd need to see your code or a reproducible example, ideally in a codesandbox so I can be sure we're looking at the same thing.

**Comment by kumargugloth** [comment]
i have 30days data for that iam looping it so it is basically 30 tables  will it cause an issue ??

**Comment by gabrielliwerant** [comment]
It is 30 separate tables on the same page? If so, I've never attempted such a scenario, so it's difficult for me to say what might be happening. It may be that you have so many elements on the page (also depending on how much data each table has) that you're simply running into performance/memory constraints.

As a way to test this, I would try rendering only a few tables and see if the issue persists. You may need to be clever about how you present your data, utilizing some form of pagination or lazy loading.
