### ISSUE TITLE
Add button "create new row" in toolbar

### ISSUE THREAD

**Issue by jkeruzec** [gregnb/mui-datatables#83]
Hello,

I think someone already did this but I can't find documentation nor issues on that.. 
I'd like to add a "new" button on datatable's toolbar to create a new line on table (with custom form, rest call etc. reload on top on that and where I will handle it my-self).

I already saw customToolbarSelect but this does not fit to what I want to do...

If someone can give me some information or if I must add a button on top of grid myself... 

Please tell me :) 
Thanks,

**Comment by gregnb** [comment]
The option to customize the toolbar is not available as it stands today.  It is something I would need to think about. I will add it to the discussion list

**Comment by KaRkY** [comment]
If you decide to add functionality of adding buttons to toolbar it would be nice to be able to add buttons to rows too.

For now I have my own implementation of this where I can add Open, Edit, Delete etc.

**Comment by gregnb** [comment]
@KaRkY Could you post a screenshot of what that looks like?

**Comment by gregnb** [comment]
This has now been released and available for usage

**Comment by jkeruzec** [comment]
Thank you !

**Comment by NickToye** [comment]
Ok this isn't working for me.  I've copied your code example pretty much and the component just doesn't get rendered.  

These are my dependencies:

"mui-datatables": "^2.0.0-beta-12"

Getting no errors in the console either.

**Comment by gregnb** [comment]
@NickToye Try taking a look at this sandbox https://codesandbox.io/s/lx35x2pn8m

**Comment by chiran-subedi** [comment]
How can we have different tooltip popover to each of the column head at
hover? All of them have "sort" when we hover on them now ?

**Comment by NickToye** [comment]
@gregnb I wonder if its because I'm rendering without using ReactDOM.  I'll check.

**Comment by NickToye** [comment]
@gregnb ok found my issue.

I have this dependency set as:

`"mui-datatables": "^2.0.0-beta-12",`

rather than

`"mui-datatables": "2.0.0-beta-12",`

**Comment by gregnb** [comment]
Ok great @NickToye glad it's working for you

**Comment by KaRkY** [comment]
@gregnb Sorry I did not respond earlier but was very bussy. This is how my implementation looks.

![grid](https://user-images.githubusercontent.com/832289/42554621-dd64523a-84e5-11e8-98c3-fa250906c084.png)

**Comment by SoftwireTimC** [comment]
@KaRkY could you share your source for your inline buttons?

**Comment by asharafshahi** [comment]
When you select the checkbox on a row, it only shows the delete button on the toolbar.  Is it possible to allow other actions?

**Comment by asharafshahi** [comment]
@KaRkY  To get the inline buttons into the table, I simply passed the JSX into the data array: 
`<MUIDataTable .... data={[field1, field2, ..., <IconButton ... />]}`

**Comment by kevinglasson** [comment]
@asharafshahi Love your inline action buttons, how did you get a reference to the row to do something with it?

**Comment by asharafshahi** [comment]
@kevinglasson You pass the button component into the data prop of the MUIDataTable component.  So just like you'd pass a string content for a given cell, you can also pass a React component.

**Comment by arturoribes** [comment]
@asharafshahi do you know how could we implement a delete button with confirm? The only way I can think of is adding a custom component which also provides the alert dialog, but I think this is overkill.

**Comment by asharafshahi** [comment]
@arturoribes I would check out something like https://material-ui.com/demos/dialogs/#confirmation-dialogs

**Comment by paianoa** [comment]
How can I set the "new button" as first element of the toolbar instead of last? (As shown by @gregnb )

**Comment by kalyan542** [comment]
> How can I set the "new button" as first element of the toolbar instead of last? (As shown by @gregnb )

I am also facing same issue.Any update on this?

**Comment by janak-prajapati** [comment]
> > How can I set the "new button" as first element of the toolbar instead of last? (As shown by @gregnb )
> 
> I am also facing same issue.Any update on this?

Me too. Please let us know if there is a way.

**Comment by gabrielliwerant** [comment]
Reordering the toolbar should probably be a feature request in a new issue, so we can track it separately. We'd need a means to reorder all the options so that this doesn't end up overly specific. I'm open to PRs and suggestions on it.

**Comment by fouwst** [comment]
It would be nice if the custom toolbar icon received the same css classes as its siblings. In the codesandbox example posted by @gregnb above, the icon does not change color on rollover.

**Comment by petrkrejcik** [comment]
To put a button as a first in the toolbar you can use negative flex `order`.
```js
  const getMuiTheme = () =>
    createMuiTheme({
      overrides: {
        MUIDataTableToolbar: {
          actions: {
            display: 'flex',
            flexDirection: 'row',
            flex: 'initial',
          },
        },
      },
    });


  const options = {
    customToolbar: () => {
      return (
          <IconButton style={{ order: -1 }}>
            <AddIcon />
          </IconButton>
      );
    },
  };

  return (
    <MuiThemeProvider theme={getMuiTheme()}>
      <MUIDataTable options={options} />
    </MuiThemeProvider>
  );
```

**Comment by ShqipognjaLL** [comment]
It would be ideal if basically customToolBar hook passed the children props and allowed you to manipulate them accordingly and return whatever you wanted.

**Comment by hutber** [comment]
Just to ask, with the Add button, will this automatically handle the form fields too like material-table? Or are these custom?
Also nice throw back to the whole HOC pattern :O
