### ISSUE TITLE
When no data is provided, table is not displayed

### ISSUE THREAD

**Issue by jkeruzec** [gregnb/mui-datatables#84]
I notice that when table is empty and there are no data to display,  table component is not shown.

Could it be possible that table is shown and a customable message is displayed on table body.
Possible message : "No data to be displayed" or "Datatable is empty".

Thanks!

**Comment by gregnb** [comment]
hey @jkeruzec, as it stands today I am going to leave this up to the developer to implement outside of the library.  The component is expecting data otherwise nothing will render
