### ISSUE TITLE
[QUESTION]: Is there any way to set initial sort/page/filter?

### ISSUE THREAD

**Issue by MellowoO** [gregnb/mui-datatables#840]
I didn't find any way,  to set initial config in the table, except for the use of custom renderer. 
Is there more easy and clear solution ?

| Tech         | Version |
|--------------|---------|
| Material-UI  |      2.8.1    |
| React        |      16.9   |

**Comment by patorjk** [comment]
Look in the "Usage" second of the docs. It shows a column array you can use that has some of those parameters set (specificaly the "customize columns" part).

**Comment by gabrielliwerant** [comment]
@MellowoO I think you are looking for table options like these, correct?

![Capture_foo1](https://user-images.githubusercontent.com/1779564/63188608-d02b3800-c02f-11e9-8a04-165355d0efcc.PNG)
![Capture_foo](https://user-images.githubusercontent.com/1779564/63188612-d3262880-c02f-11e9-9307-b4234f0b73d4.PNG)

If so, have a look through the docs and see if it's missing something you need.

**Comment by MellowoO** [comment]
@gabrielliwerant hi!
Yes, you are right
But for example, if i need to specify initial sort column
```
const columns = [
 {
  name: "name",
  label: "Name",
  options: {
   filter: true,
   sort: true,
  }
 },
 {
  name: "company",
  label: "Company",
  options: {
   filter: true,
   sort: true,
  }
 },]
```
I want to display "sort arrow" icon on `name` column by default
Can i do this?

**Comment by MellowoO** [comment]
@gabrielliwerant or set any selected by default filters

**Comment by gabrielliwerant** [comment]
In that case, I think what you're looking for is this:

![image](https://user-images.githubusercontent.com/1779564/63200947-2ceb1a80-c051-11e9-9f09-4594cf5570f9.png)

**Comment by MellowoO** [comment]
Thank you)
