### ISSUE TITLE
Prevent table row from becoming more than one line no matter how much data, instead the overflow x just gets longer.

### ISSUE THREAD

**Issue by snsheth55** [gregnb/mui-datatables#842]
I am making a table where I need all the rows to remain in one line no matter how much data is in the cells. Right now if I extend my table across two screens ( the table has 12 columns with 30 characters per col) the row becomes one line, however when I have the window to only one screen the columns shrink and the data overflows causing the row to be 2 or more lines. I want to prevent this from happening because I need dense one line rows. 

## Expected Behavior

I expect that if I have the responsive option set to scroll then the horizontal scroll will allow all table rows to remain on one line by increasing the length of the scroll. I also set the maxWidth in responsiveScroll in MUIDatatable in getMuiTheme however it only adjusts the width of the inner cells but not the entire table with the search and pagination etc...
## Current Behavior

When I make my window smaller the table columns shrinks and the rows become multiple lines.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    0.20.2     |
| MUI-datatables  |     2.81    |
| React        |   16.9    |
| browser      |   Chrome 73      |
| etc          |         |

**Comment by patorjk** [comment]
I have this issue with one of my tables (I have 1 table that's 16 columns). I solved it by setting the styling for the cell in the customBodyRender method of each column's option object:

    customBodyRender: (value) => (<div style={{whiteSpace:'pre'}}>{value}</div>)

**Comment by snsheth55** [comment]
Thank you works perfect!
