### ISSUE TITLE
Custom Header Component 

### ISSUE THREAD

**Issue by snsheth55** [gregnb/mui-datatables#843]
I want to add one tiny adjustment to the header where, the label will not wrap around itself if its squeezed for space.  I want to keep all the other styles/features exactly the same (font size/color, sort etc...) . 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     0.20.2    |
| MUI-datatables  |    2.8.1     |
| React        |    16.9.0     |
| browser      |     Chrome    |
| etc          |         |

**Comment by gabrielliwerant** [comment]
Hello @snsheth55. Is this a request for a fix or about how to create a custom header? Also, I'm not sure which label wrapping you're referring to. Can you provide an example/screenshot?

**Comment by snsheth55** [comment]
Hello,

This is a question about how to create a custom header, I know I can use the custom header option but I'm having difficulty setting up the header component  which will be an exact copy of how it is in MUI-datatable except the headers are not wrapped.


![Header Component](https://user-images.githubusercontent.com/37764769/63364164-07a52780-c343-11e9-81bb-843cf10b6a9e.PNG)

**Comment by gabrielliwerant** [comment]
It's a bit complicated, but here is where the display code is internally for the table headers: https://github.com/gregnb/mui-datatables/blob/master/src/components/TableHeadCell.js#L101.

Do you want the headers to be wrapped or unwrapped? And which wrapping are you referring to?

**Comment by snsheth55** [comment]
I want them to be unwrapped, like how I set it up in custombodyrender

```
        let obj = {
          name: humanize(col),
          options: {
            filter: true,
            customBodyRender: (value) => (<div style={{whiteSpace:'pre'}}>{value}</div>)
          }
        }
```

**Comment by gabrielliwerant** [comment]
Unwrapped by what, the `span` that handles the sort?

**Comment by snsheth55** [comment]
I am not sure where the best place would be to unwrap it.

**Comment by gabrielliwerant** [comment]
Unfortunately, I'm still not sure what you mean by "wrapping." :/ I may not be able to help unless you can be more specific. For now, I would take a look at the file I linked above and try to recreate the styles and structure on your end as best as possible.

**Comment by snsheth55** [comment]
By wrapping I mean  the column header titles will remain in one line, not be split into multiple lines.

**Comment by gabrielliwerant** [comment]
Oh, you do not need to recreate the entire header to do that. Just customize the styling. Look into how to override theme styles with the `customize-styling` example. You'd need to add something like

```
MUIDataTableHeadCell: {
  data: {
    whiteSpace: 'pre'
  }
}
```

**Comment by snsheth55** [comment]
Works perfect, thank you!

**Comment by new-furry** [comment]
Hi
how can i customize header..
I would like to make header bottomBorder..

I tried this

    MUIDataTableHeadCell: {
      root: {},
      fixedHeaderOptions: {
        borderBottom: "#000"
      }
    },

but not work.. please help me!
