### ISSUE TITLE
Deprecated lifecycle method warnings with React 16.9

### ISSUE THREAD

**Issue by taylon** [gregnb/mui-datatables#844]
Hi,

The following warning is shown upon upgrading to React 16.9:

```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
      
      * Move code with side effects to componentDidMount, and set initial state in the constructor.
      * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
```

I guess a quick temporary fix would be to use the codemod to rename everything but I'm not sure if that has any other impact.

**Comment by gabrielliwerant** [comment]
Yes, I've been aware of this issue for a while, but might as well switch to the unsafe API now. I'd like to handle the actual removal in a different release to help isolate any breakage, but this will get us started: https://github.com/gregnb/mui-datatables/compare/enhancement/issue-844-deprecated-lifecycle?expand=1.

**Comment by codealchemy** [comment]
I noticed these warnings when using this library as well and am looking forward to the patch - might the version of `React` need to be bumped as a part of this (ie. in `peerDependencies`)?  It seems that these aliases [were introduced in React `16.3`](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html).

**Comment by gabrielliwerant** [comment]
`peerDependencies` could probably use a bump at some point, but the version in the lockfile is high enough, and new installations of the library will install what's specified in the lockfile, so we're good there.
