### ISSUE TITLE
Failed prop type: Invalid prop `children` supplied to `TableCell`, expected a ReactNode.

### ISSUE THREAD

**Issue by laurexas** [gregnb/mui-datatables#845]
## Expected Behavior

boolean type values converted to string type values should appear in table without error message
## Current Behavior

Hey, i get this problem whenever my table data prop loads data  from remote  API which contains boolean type values , i know that MUI datatable accepts only strings and numbers, so after i get data from API i convert all my boolean type values to string values so all the values can appear in table, but sometimes this error message appears in console, when fetching data without booleans type values no error appears. so this must be because of boolean types, but i'm not sure why error appears if i convert it to string at the same second data arrives, is there anything i can do, because mannualy i can't reach TableCell? any suggestions and thanks for help
## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     3.9.2    |
| MUI-datatables  |    ^2.6.4     |
| React        |         16.8.2|
| browser      |     chrome  |
| etc          |         |

**Comment by gabrielliwerant** [comment]
It sounds like it might be a timing issue with the data fetching. I would prevent rendering of the table until the data is finished fetching and being converted (so not just when the data loads, but after the transformation of the data).

I'm not sure if it's possible or desirable for you, but if you could change the values returned by the API to `0` and `1` for `false` and `true`, that should also work, but the above suggestion is probably best.

**Comment by laurexas** [comment]
its because of timing i have tested with timeouts just to make sure, although i can't find the right way to fix this issue without timeout,because i'm using redux and when value is converted to string i dispatch and action to store to load  data to table but for some reason it it's not enough and most of the times i still get the error.. i have very complex type coercion with  lots of mapping and callback functions because its wery deep nested object i get from api, so this must be the case

**Comment by laurexas** [comment]
@gabrielliwerant i made some mistakes in my coercion function, but with some help i managed to fix it, so basically boolean to string coercion function is working fine and i dont get any more warnings, thank you for your time
