### ISSUE TITLE
Enhance filter to have custom filter options render

### ISSUE THREAD

**Issue by jacklimwenjie** [gregnb/mui-datatables#846]
## Current Behavior

Sometimes developers need to deal with normalised data (referencing another data through ID), take for example the following table data: 
```
[
    {
        id: "1",
        name: "Josh",
        companyId: "a1-b2-c3-d4"
    }
]
``` 

And the companies data obtained through another means: 
```
[
    {
        id: "a1-b2-c3-d4",
        name: "Google Inc. "
    }
]
```

The requirement is to show "Google Inc. " for the table column "Company" for example, instead of the ID i.e. "a1-b2-c3-d4". 

There is a props to handle this when rendering in table `customBodyRender`, but when setting the column to be filterable, the filter options appear to display as the raw data, which is the ID "a1-b2-c3-d4". 

A means is needed to lookup the company name "Google Inc. " by using the `id` to render as the filter option label. 

We can use `filterOptions` `display` key to render a custom filter, but that is overkilled in this scenario, because we just want to change the filter options label.

## Expected Behavior

Add a means to customise the filter options label. 
For example, a function to return the filter option label based on the filter value, like this:

```
(filterValue) => <p>lookupTable[filterValue]</p>
```

Maybe add a key in the `filterOptions`, like `customNameRender`, or reuse the `names` key and make it accept function as well.

**Comment by gabrielliwerant** [comment]
Have you tried `filterOptions: { names: [] }`? Or is the request that you want `names` to accept a function in addition to an array? I am hesitant to complicate the API for this use case, as you can already choose to transform your data however you wish in your API resolutions. If you can do that, I'm not sure it makes sense to bundle generic functions in with this or most other table APIs that are intended to be cleaner.

You do also have the option of using the `onTableInit` callback in the main options which should let you run generic functions which change the data, though you'd be triggering a re-render, so the better option is to transform your data on your end before feeding it into the table.

**Comment by gabrielliwerant** [comment]
Marking as "wontfix" for now, as it sounds to me like the functionality required is available if you also transform your data pre-render, which is recommended.
