### ISSUE TITLE
Replace delete icon with other bulk operation icon

### ISSUE THREAD

**Issue by mwubgadeashish** [gregnb/mui-datatables#849]
Can we replace delete icon with some custom icon (like bulk operations)

## Current Behavior
In my current project we don't need delete option but we want to do few bulk operation. So is there is any example to do this?

**Comment by gabrielliwerant** [comment]
You can customize the whole toolbar to display whatever you wish. Check out the `customToolbarSelect` option in the main options, and the `customize-toolbarselect` in the examples.

**Comment by mwubgadeashish** [comment]
@gabrielliwerant Thanks for help... it worked.
