### ISSUE TITLE
How to handle the checked state when using selectable rows with the "multiple" option

### ISSUE THREAD

**Issue by GusRodriguezM** [gregnb/mui-datatables#854]
## Expected Behavior
If i choose a specific row or all the rows i want to see how it changes the status from selected to no selected. 

## Current Behavior
1. In the example provided of selectable-rows if all rows are selected and then deselected by the user the array is printed empty  but the rows still appears selected on the table. 
2. Sometimes when some rows are selected and i want to select another one it won't change the state, it changes the state of another row.

## Steps to Reproduce
1. Copy the example of selectable-rows into your own environment or on a sandbox proyect. 
2. Try first selecting all the rows and then deselecting with the same option. (For the first problem)
3. To the second behavior use only 5 rows, select the first then the third and then the fifth row. After that just select the first row and its visible how the third and the fifth row change its state but the state of the first row won't change.

## Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    3.9.2     |
| MUI-datatables  |   2.8.0      |
| React        |    16.8.5     |

How can i control the status of checked/unchecked of the rows in order to prevent the behavior explained above?

Here is the sandbox with the example of the repository:
https://codesandbox.io/embed/muidatatables-select-rows-fj93k

**Comment by GusRodriguezM** [comment]
First behavior:
![first-behavior](https://user-images.githubusercontent.com/35277967/63547374-a53e5980-c4f1-11e9-9042-79a63d399e42.gif)

Second behavior:
![second-behavior](https://user-images.githubusercontent.com/35277967/63547372-a53e5980-c4f1-11e9-8ae5-142b2587cba7.gif)

I hope the quality isn't too awful and allows to see how it works actually.

**Comment by gabrielliwerant** [comment]
This looks like an issue that was resolved in `2.8.1`. Upgrade your table version to that or the latest and see if it still occurs.

**Comment by GusRodriguezM** [comment]
Thanks for check the issue. The problem is gone after i updated the version.

**Comment by gabrielliwerant** [comment]
Closing this as resolved for now. We can consider re-opening if the issue returns.
