### ISSUE TITLE
Bug export CSV Chrome Mac OSX

### ISSUE THREAD

**Issue by benjaminbours** [gregnb/mui-datatables#86]
Hello, i got a bug when i use the export CSV feature in the toolbar of the table.
I'm with chrome on Mac OSX

## Expected Behavior

I need this kind of data 
<img width="207" alt="screen shot 2018-06-26 at 11 19 46" src="https://user-images.githubusercontent.com/8804297/41902091-e0040e68-7932-11e8-939c-fbde3e01ec20.png">

## Current Behavior

but data looks like
<img width="550" alt="screen shot 2018-06-26 at 11 17 39" src="https://user-images.githubusercontent.com/8804297/41901984-99228970-7932-11e8-9a79-b2c6f27e2c2f.png">

## Steps to Reproduce (for bugs)

1. Click on download CSV in the toolbar of the table
2.
3.
4.

## Your Environment

Like you can see in my screen, the bug is happening on the latest version of this repository. But i will complete this to be sure :)

| Tech         | Version |
|--------------|---------|
| Material-UI  |     1.0    |
| MUI-datatables  |   2.0.0-beta-9      |
| React        |     16.2    |
| browser      |   Chrome      |
| etc          |     Mac OSX    |

**Comment by gregnb** [comment]
So when you open the download in Excel all the data comes in on one line?

**Comment by benjaminbours** [comment]
Yep, and with a bad formatage or encodage, as you can see in the screenshot. I proposed a solution in a pull request, but between us, it's the fist time i contribute to something, so i hope it is good :)

**Comment by gregnb** [comment]
@benjaminbours Thank you! I was looking at making that same fix as well. I'm more than happy to accept it but before I do can you test it in other browsers to make sure things are fine?

**Comment by benjaminbours** [comment]
I checked on Chrome, Firefox, Safari on Mac OSX and Edge on a Windows and no problem. On IE11, I got a lot of bug but it happens at the loading, i don't think it is why I did which created the bug. And I tested on the webpack-dev-server, so maybe the code is not compiled down enought ( I mean like ES3) to match the required of IE11.

I can't test on other browser :)

**Comment by gregnb** [comment]
Ok great thank you
