### ISSUE TITLE
Add `setCellHeaderProps`

### ISSUE THREAD

**Issue by mikroware** [gregnb/mui-datatables#871]
Add `setCellHeaderProps` just like how `setCellProps` is there already. 

## Expected Behavior
`setCellHeaderProps` should work the same as `setCellProps`. It should be passing those props to the underlying `TableCell`. With this feature one can style the header cell just like the rest of the cells.

## Current Behavior
Does not exist for header cells (only for normal cells through `setCellProps`).

(feature request created as of discussion in #400)

**Comment by marek-jarab** [comment]
Hi. I would like to start working on that . Could you pls assign me to this issue?

**Comment by gabrielliwerant** [comment]
There is already a PR open for this feature, so I have to check on the status of that.

**Comment by shawnmitchell** [comment]
Would it not make sense for `align` to be a first-class column option? 

```
const columns = [
 {
  name: "Name",
  options: {
   filter: true,
   sort: false,
   align: 'right',
  }
 },
 ...
];
```

**Comment by austin557** [comment]
Has any progress been made on this?
I cannot get my column headers to center align while using the responsive: "scrollFullHeight" option.

**Comment by gabrielliwerant** [comment]
Yes, this feature has been added as of 2.13.0, but `align` on the th won't help you because the column name is wrapped in `flex` display mode when there is a sort button. So you'll actually need to override styles instead: `MUIDataTableHeadCell sortAction` and set `justify-content`.
