### ISSUE TITLE
Select all + select all when already selected

### ISSUE THREAD

**Issue by nadobando** [gregnb/mui-datatables#89]
## Expected Behavior
* Select All:
When select all rows it should select all rows in table or be able to choose the behavior.

* Select All rows when already selected rows in different pages:
When you already selected different rows in different pages when selecting all rows it should select all the rows

* Select All rows then change number of rows per page:
When selecting all rows and changing the number of rows should be showing all rows?

## Current Behavior
* Select all:
Just select the rows in the current page

* Select all when already selected rows:
It deselect the selected rows and selects the rows in the current page

* Select all then changing number of rows: 
Only selected rows from the last current page are selected
and also the select all button still checked

## Steps to Reproduce (for bugs)

* Select all:
1.  just select all rowsl and only the rows in the current page are selected

* Select all with already selected rows:
1. select many rows in different pages
2. select all it will remove the already selected rows in different pages and select all rows in the current page

* Select All then change number of rows per page:
1. Select All
2. Change rows per page number

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    1.0.0     |
| MUI-datatables  |    2.0.0-beta-7     |
| React        |      16.3.1   |
| browser      |  Chrome       |
| etc          |         |

**Comment by gregnb** [comment]
hey @nadobando thank you for filing this report. I am currently working on deselect and you are right as I worked through the feature enhancement I noticed this as well. The change I am going to provide will be the following:

Select All:
Clicking the 'Select All' checkbox will select all the data in the table. This then will display a checked checkbox

Selecting individual cells:
When selecting individual cells the 'Select all' checkbox up top will show a deselect or a "-" character inside to deselect all the rows. If a user manages to manually select all the rows individually and then the 'Select all' checkbox be checked
