### ISSUE TITLE
TypeError: Cannot read property 'noMatch' of undefined when in production

### ISSUE THREAD

**Issue by laurexas** [gregnb/mui-datatables#891]
## Expected Behavior
Table component should render correctly when i production mode

## Current Behavior
Hello, when i locally run my code everything works fine, but when i deploy in production mode when page loads with table component i suddenly get type error in console : 
1) TypeError: Cannot read property 'noMatch' of undefined when in production
  at t.value (VM150 0.81ac1b64.chunk.js:1)
2) TypeError: Cannot read property 'search' of undefined when in production
3) TypeError: Cannot read property 'rowsPerPage' of undefined when in production
is this problem may occur because of data that i get from API or because of columns names i get from API? any suggestions? 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |      "3.9.2"   |
| MUI-datatables  |     "^2.6.4"    |
| React        | "16.8.2"        |
| browser      |    chrome     |
| etc          |         |

**Comment by patorjk** [comment]
This looks like it may be related to https://github.com/gregnb/mui-datatables/issues/878, but that problem only appears as of 2.8.1 (there will be a fix for it later today: https://github.com/gregnb/mui-datatables/pull/890).

You may want to see if you can create a CodeSandbox to re-create the issue, ex: https://codesandbox.io/s/muidatatables-custom-toolbar-82ds7 (if you switch the MUI-Datatables version to 2.8.1 and hit the loading toggle, you'll see the same error you describe above)

**Comment by gabrielliwerant** [comment]
It does sound like it's related, but I'm unsure of why it would work locally and not in production, unless your production is using a different version of this library, which is possible.

**Comment by gabrielliwerant** [comment]
@laurexas See if you can verify what version of the library you have running in production. `2.10.1` is also now available, which may fix your issue.

**Comment by laurexas** [comment]
@gabrielliwerant package version is the same in production as in development mode, updated my mui-datatable package version to 2.10.1, i will push it to master branch and i will check it if its working and will let you know.

**Comment by laurexas** [comment]
updating to new version problem was solved, case closed.
