### ISSUE TITLE
Filter Icon 

### ISSUE THREAD

**Issue by krishnaUIDev** [gregnb/mui-datatables#9]
How can I change that Filter Icon on the right-hand side? And I want to remove some Items in the last filter. Is it possible in MUI Datatable??

| Tech         | Version |
|--------------|---------|
| mui-datatables  |         |
| node        |     8    |
| OS      |   Mac      |

**Comment by gregnb** [comment]
There's no option as of today to change the icons. That would be a feature request. Let me look into that. 

Second issue, removing some items in the last filter. Can you show me a screenshot of what you're talking about ?

**Comment by krishnaUIDev** [comment]
Please see the screenshot. I want to remove salary from the filter. But I need that salary on the table. Not in the filters. Is there any chance???
![screenshot 19 _li](https://user-images.githubusercontent.com/24648588/37248559-54ff1602-24a3-11e8-81ec-281e5a35e8a0.jpg)

**Comment by gregnb** [comment]
Ok I think this is a great idea. It goes along with some other changes users have requested. Currently I'm on vacation so I will not be able to get to this rigjt away but I will look to add this feature for more customization.

**Comment by gregnb** [comment]
So I have some initial work done that will allow for customization of columns. It'll also address #3 when it's complete. As it stands now you'll be able to define which columns you want filtering for or not.  But, as far as the icon replacement here's what I'm proposing: You'll be able to swap in custom icons but they must be React Components that return SVG much like how material-ui-icons works currently

**Comment by gregnb** [comment]
@krishnaUIDev In version 1.0.8 I've added the ability to customize columns. You can turn the filter on/off per column basis

**Comment by krishnaUIDev** [comment]
Thanks @gregnb. And if you have time can you look at removing columns from filters.

**Comment by gregnb** [comment]
@krishnaUIDev yea that's what I just posted lol. You can remove them now in version 1.0.8. Take a look at the new examples folder

**Comment by krishnaUIDev** [comment]
When click on Filter Icon or view column icon its getting error @gregnb 
![screenshot 21](https://user-images.githubusercontent.com/24648588/37549878-2f2005b0-295b-11e8-9fef-b64f9e2da99c.png)

**Comment by gregnb** [comment]
@krishnaUIDev looks like a warning. I think the current PR fixes it when we merge it in. But nothing is broken, correct ?

**Comment by krishnaUIDev** [comment]
Ya Nothing is broken and can you try to add functions to the rows (onClick events). Is there any chance to add onclick events to that rows? ?

**Comment by gregnb** [comment]
Ok, but I want to learn more about why. What's the use case first to binding an onClick event to the rows? Are you tracking something? Just curious

**Comment by krishnaUIDev** [comment]
I am trying to create a data table site. At that place, i need to click handlers for rows to show that row data.

**Comment by gregnb** [comment]
@krishnaUIDev Ok, I will try to work on expanding more options into this package. I'm still on vacation so nothing will get done right away so bare with me. If it makes sense after I look into it some more I'll put it on the feature board.  Some people have also asked for ability for selectable rows which sounds close to what you're asking for

**Comment by gregnb** [comment]
Selectable rows have been added in the latest version. It has two event callbacks that should help with this ticket.

**Comment by krishnaUIDev** [comment]
Is there any new features??

**Comment by gregnb** [comment]
Yes, in the latest version there are selectable rows and two callbacks you can read the README for more information

**Comment by krishnaUIDev** [comment]
Thanks. And is there any chance to change font icons??

**Comment by gregnb** [comment]
@krishnaUIDev I could do something on the column options. A property called 'icon' so the options available would look like:
```
const columns = [
 {
  name: "Name",
  options: {
   filter: true,
   sort: false
   icon: <some icon from material-ui-icons only>
  }
 },
 ...
]; 

```

But again, I would only allow icons from material-ui-icons

**Comment by gregnb** [comment]
Nevermind that, I wrote about the wrong section this is related to toolbar.  Let me think about this some more

**Comment by gregnb** [comment]
So I'm trying to find a good reason to do this but I'm struggling. The only icons I would allow are ones to be loaded from material-ui-icons package.  Take for example print, if you search https://material.io/icons/ there are only two available.  Were you going to try to load in your own SVG's?

**Comment by SiriLivtar** [comment]
hi @gregnb.
First of all, thank you very much for the component. I am trying to change the search icon. I am trying to load my own SVG. 
Is there any functionality to do this?

regards
luis

**Comment by Ciip1996** [comment]
Did any of you guys have any luck by changing the icons svg? 

> hi @gregnb.
> First of all, thank you very much for the component. I am trying to change the search icon. I am trying to load my own SVG.
> Is there any functionality to do this?
> 
> regards
> luis

**Comment by entozoon** [comment]
Is it still true that you can't conveniently change the filter button?

If it's helpful at all, I've managed to add text with some brutal CSS along the lines of
```css
[data-testid^="Filters"]::after {
  content: "Filters"
}
 ```
And you could even hide the SVG and replace it with a background-image.
