### ISSUE TITLE
Always show search field.

### ISSUE THREAD

**Issue by czellerdavid** [gregnb/mui-datatables#917]
I would like to customize the search field the way that it's always shown.

## Expected Behavior
The search field should be always open. So that way, you don't have to click on the search icon to open the search field. 

## Current Behavior
   Now you have to click on the search icon to open the search field. There should be a bool if it's always open or if you want the current behavior.

**Comment by gabrielliwerant** [comment]
@czellerdavid There is a PR open now that would add the option for this behavior, so feel free to watch it: https://github.com/gregnb/mui-datatables/pull/893.

**Comment by gabrielliwerant** [comment]
Should now be available via `searchOpen` in `2.12.0`.

**Comment by twpopcornchkn** [comment]
@gabrielliwerant thanks for the amazing table, this "searchOpen" option addressed half of my use case. 
When the filter (or any other toolbar) item was clicked, the searchBar would still be hidden. Is there a way to make this truly "always-on". thanks

**Comment by stijn-gravity** [comment]
Hi @gabrielliwerant, this isn't 'always open', just initially. I am very happy with this, however I do hope in the future you would consider a feature where the search bar is un-closable.  For now I can solve this with a custom render. Thank you.

**Comment by gabrielliwerant** [comment]
@stijn-gravity The problem with always open, is that it permanently replaces the title. It should be possible to see both if we're going always open, and so far, there hasn't been a solution for that.
