### ISSUE TITLE
responsive option of 'scroll' is missing in documentation

### ISSUE THREAD

**Issue by konrazem** [gregnb/mui-datatables#918]
responsive option of '**scroll**' is missing as an option of table in main documentation. Moreover this is only one option that is reasonable to make table responsive. When I have lots of columns and rows, data will go out of boundary on mobile if default or any other option than 'scroll' is selected.

![image](https://user-images.githubusercontent.com/19363700/64705156-c7534800-d4af-11e9-9532-9100b3496530.png)

**Comment by gabrielliwerant** [comment]
Hello @konrazem. I need more information about what you're looking for. Right now, the docs look like this:

![image](https://user-images.githubusercontent.com/1779564/64731239-c4a42300-d4ae-11e9-8d6d-f0157b7e9489.png)

So, the two scroll options are `scrollMaxHeight` and `scrollFullHeight`. Have you tried either of these?

Also, I'm not sure that the error in your screenshot is related to anything responsive. Can you provide the steps to reproduce it, or a minimal codesandbox example?

**Comment by konrazem** [comment]
@gabrielliwerant  yes exactly I was trying at first scrollMaxHeight and scrollFullHeight but those make no scroll. After I found somewhere in blog actual 'scroll' option was the case. I just wanted to notice that maybe it would save some time for newcomers to add '**scroll**' option to documentation with  'stacked', 'scrollFullHeight', 'scrollMaxHeight' ?

`  const options = {
    filterType: 'dropdown', 
    rowHover: false,
    responsive: 'scroll',
}`

**Comment by gabrielliwerant** [comment]
In the latest version of this project, `scroll` behavior is identical to `scrollMaxHeight`. It is also deprecated and will be replaced with `scrollMaxHeight` eventually. You must be on an older version of this library.

**Comment by BenjaOliva** [comment]
Hi, im dealing with same issue, so 'scroll' and 'scrollMaxHeight' are deprectaded but the new ones ( ["standard","vertical","verticalAlways","simple"] ) won't get the same result as im testing all this options. I'm missing sometging here or what happened to this option prop ?
