### ISSUE TITLE
how to set column width 

### ISSUE THREAD

**Issue by ifaungthiha** [gregnb/mui-datatables#92]
Hello,
how to set column width?

Thanks,

**Comment by gregnb** [comment]
Hello @ifaungthiha you can set a column width that will apply to all columns (there is no individual column support and no plans for it) like so via theme:

```
import React from "react";
import ReactDOM from "react-dom";
import MUIDataTable from "../../src/";
import { createMuiTheme, MuiThemeProvider, withStyles } from '@material-ui/core/styles';

class Example extends React.Component {

  getMuiTheme = () => createMuiTheme({
    overrides: {
      MUIDataTable: {
        root: {
          backgroundColor: "#FF000",
        },
        paper: {
          boxShadow: "none",
        }
      },
      MUIDataTableBodyCell: {
        root: {
          backgroundColor: "#FFF",
          width: "50px"
        }
      }
    }
  })

  render() {

    const columns = [
      {
        name: "Name",
        options: {
          filter: true,
        }
      },      
      {
        name: "Title",
        options: {
          filter: true,
        }
      },
      {
        name: "Location",
        options: {
          filter: false,
        }
      },
      {
        name: "Age",
        options: {
          filter: true,
        }
      },
      {
        name: "Salary",
        options: {
          filter: true,
          sort: false
        }
      }      
    ];

    const data = [
      ["Gabby George", "Business Analyst", "Minneapolis", 30, 100000],
      ["Aiden Lloyd", "Business Consultant", "Dallas",  55, 200000],
      ["Jaden Collins", "Attorney", "Santa Ana", 27, 500000],
      ["Franky Rees", "Business Analyst", "St. Petersburg", 22, 50000],
      ["Aaren Rose", "Business Consultant", "Toledo", 28, 75000],
      ["Blake Duncan", "Business Management Analyst", "San Diego", 65, 94000],
      ["Frankie Parry", "Agency Legal Counsel", "Jacksonville", 71, 210000],
      ["Lane Wilson", "Commercial Specialist", "Omaha", 19, 65000],
      ["Robin Duncan", "Business Analyst", "Los Angeles", 20, 77000],
      ["Mel Brooks", "Business Consultant", "Oklahoma City", 37, 135000],
      ["Harper White", "Attorney", "Pittsburgh", 52, 420000],
      ["Kris Humphrey", "Agency Legal Counsel", "Laredo", 30, 150000],
      ["Frankie Long", "Industrial Analyst", "Austin", 31, 170000],
      ["Brynn Robbins", "Business Analyst", "Norfolk", 22, 90000],
      ["Justice Mann", "Business Consultant", "Chicago", 24, 133000],
      ["Addison Navarro", "Business Management Analyst", "New York", 50, 295000],
      ["Jesse Welch", "Agency Legal Counsel", "Seattle", 28, 200000],
      ["Eli Mejia", "Commercial Specialist", "Long Beach", 65, 400000],
      ["Gene Leblanc", "Industrial Analyst", "Hartford", 34, 110000],
      ["Danny Leon", "Computer Scientist", "Newark", 60, 220000],
      ["Lane Lee", "Corporate Counselor", "Cincinnati", 52, 180000],
      ["Jesse Hall", "Business Analyst", "Baltimore", 44, 99000],
      ["Danni Hudson", "Agency Legal Counsel", "Tampa", 37, 90000],
      ["Terry Macdonald", "Commercial Specialist", "Miami", 39, 140000],
      ["Justice Mccarthy", "Attorney", "Tucson", 26, 330000],
      ["Silver Carey", "Computer Scientist", "Memphis", 47, 250000],
      ["Franky Miles", "Industrial Analyst", "Buffalo", 49, 190000],
      ["Glen Nixon", "Corporate Counselor", "Arlington", 44, 80000],
      ["Gabby Strickland", "Business Process Consultant", "Scottsdale", 26, 45000],
      ["Mason Ray", "Computer Scientist", "San Francisco", 39, 142000]
    ];

    const options = {
      filter: true,
      filterType: 'dropdown',
      responsive: 'stacked',
    };

    return (
      <MuiThemeProvider theme={this.getMuiTheme()}>
        <MUIDataTable title={"ACME Employee list"} data={data} columns={columns} options={options} />
      </MuiThemeProvider>
    );

  }
}

ReactDOM.render(<Example />, document.getElementById("app-root"));

```

**Comment by ifaungthiha** [comment]
:( 
thank you for reply

**Comment by igorRoog** [comment]
Hi,
I spotted similar issue during development and that's how I managed to set column width:

```
getMuiTheme = () => createMuiTheme({
  overrides: {
    MUIDataTableHeadCell: {
      root: {
        '&:nth-child(2)': {
          width: 70
        }
      }
    }
  }
})
```
Basically, you need to apply css rule to specfic column by using :nth-child(X) selector (or :first-child() selector). It's not a pretty solution, but what's important, it works.

**Comment by NickRadu** [comment]
Hi Igor,

I tried your solution but it's not working to resize the width, only the color is changed. Below is my code:
`import MUIDataTable from "mui-datatables";
import { createMuiTheme, MuiThemeProvider } from '@material-ui/core/styles';

const customTheme = createMuiTheme({
  overrides: {
    MUIDataTableHeadCell: {
      root: {
        '&:nth-child(4)': {
          width: 30,
          backgroundColor: "#FF0000"
        }
      }
    }
  },

  typography: {
    useNextVariants: true,
  },

}); 
class HomePage extends React.Component {

  /**
   * Class constructor.
   */
  constructor(props, context) {
    super(props, context);
  }


  /**
   * Render the component.
   */
  render() {
      return (
        <div className="container">
        <MuiThemeProvider theme={customTheme}>
             <MUIDataTable
                title={"locations"}
                data={data}
                columns={columns}
                options={options}
              />  
          </MuiThemeProvider>
        </div>
      );
    }
  }
}
`

Thank you.

**Comment by Edeph** [comment]
@NickRadu did you manage to fix the custom width issue ?

**Comment by ianmccaul** [comment]
Yea, I cant get that to work at all either.

**Comment by Edeph** [comment]
TBH What I did that helped in my case was just removing the padding by wrapping the Datatable into a customTheme that would overwrite MuiTableCell padding to 0px like this:
```
const customTheme = createMuiTheme({
        overrides: {
            MuiTableCell: {
                root: {
                    padding: '0px',
                },
            },
        },
    } as ThemeOptions);
```
I had to define it `as ThemeOptions` because TS was complaining since mui-datatables types are not defined into materialUI library.

**Comment by ToddHerron** [comment]
If the underlying problem you are really trying to solve is stopping content in a cell from wrapping, I recommend using a `customBodyRender` for the column and using the `noWrap` prop for the `<Typography>` component:


```
const columns = [
		{
			name    : 'myNoWrappingColumn',
			label   : 'Column with no wrapping',
			options : {
				customBodyRender : (value, tableMeta, updateValue) => {
					return (
						<Typography noWrap='true'>
							{value}
						</Typography>
					)
				}
			}
		},
		{
			name    : 'myOtherColumnThatWraps',
			label   : 'Column with wrapping',
			options : {
				customBodyRender : (value, tableMeta, updateValue) => {
					return (
						<Typography noWrap='false'>
							{value}
						</Typography>
					)
				}
			}
		}
]
```

**Comment by glowkeeper** [comment]
@ToddHerron customBodyRender works great for _noWrap_, but how to set column width? I tried adding _Grid_ components with breakpoints, and while that _appears_ to work for the row data, the table row header appears unaffected...

**Comment by glowkeeper** [comment]
Does `noWrap` work? I'm using a _customRender_ with `noWrap` on all my columns, but as you can see, it doesn't appear to work. 

![width](https://user-images.githubusercontent.com/9264929/121854396-01d3bf80-ccea-11eb-955f-978aa68911f4.png)

 In fact, the whole table then expands beyond the page width, which is annoying :( Er, help?

**Comment by DaniGB1** [comment]
The only thing that worked for me was adding a constant style as:

const columnStyleWidthSmall = {
        top: '0px',
        left: '0px',
        zIndex: '100',
        position: 'sticky',
        backgroundColor: '#fff',
        width: '100px',
}

Then in each column options add:
{
            name: 'name1',
            label: 'File Left',
            options: {
                filter: true,
                **customHeadRender: ({ index, ...column }) => {
                    return (
                        <TableCell key={index} style={columnStyleWidthMedium}>
                            {column.label}
                        </TableCell>
                    )
                },**
            },
            flex: 1,
 },

**Comment by alinoureldin707** [comment]
Wrap the MUIDataTable with a container and give it a style 
const DataTableContainer = styled('div')(() => ({
  background: 'red',
  '& .MuiTableCell-root': {
    '&:nth-child(1)': {
      width: '100px',
      paddingLeft: '1rem',
    },
  },
}));

**Comment by crucialfelix** [comment]
Simplest solution is to wrap your content in a span and style that:

```html
          <Cell><span class="clipText">{item.key}</span></Cell>
```

```css
  .clipText {
    display: inline-block;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    width: 20rem;
  }
```

**Comment by annavidaltur** [comment]
You can define width for specific column with `setCellHeaderProps`
```
const columns: MUIDataTableColumnDef[] = [
    { name: 'fixedWidth150', label: '150px', options: { filterType: 'textField', setCellHeaderProps: () => ({ style: { width: "150px" }})}},
    { name: 'fixedWidth300', label: '300px', options: { filterType: 'textField', setCellHeaderProps: () => ({ style: { width: "300px" }})}}
]
```

**Comment by joy271f** [comment]
Solved: Handling Ellipses in Column Text for Data Tables

I recently faced an issue with truncating long text in a data table column, where I needed to show ellipses (...) when the text exceeded a certain length. Here's the solution I came up with:

```
const truncateText = (text, length) => {
  if (typeof text !== 'string') {
    return '';
  }
  return text.length > length ? `${text.slice(0, length)}...` : text;
};

// Usage in component
<span className="ellipsis">
  {truncateText(value, 100)} {/* Adjust length as needed */}
</span>
```

![image](https://github.com/user-attachments/assets/a3092649-9ca0-4d27-9617-3a03db0fe2e8)

**Comment by joychandradas007** [comment]
**Solved: Handling Ellipses in Column Text for Data Tables**

I recently faced an issue with truncating long text in a data table column, where I needed to show ellipses (...) when the text exceeded a certain length. Here's the solution I came up with:

```
const truncateText = (text, length) => {
  return text.length > length ? `${text.slice(0, length)}...` : text;
};

// Usage in component
customBodyRender: (value) => ( <Box maxWidth={300}>{truncateText(value, 120)}</Box>),
```

![image](https://github.com/user-attachments/assets/7a886b77-d33f-4039-855b-f8131c01a80c)
