### ISSUE TITLE
examples/selectable-rows mistake

### ISSUE THREAD

**Issue by Yakitrak** [gregnb/mui-datatables#934]
In the "examples/selectable-rows". "onRowsSelect"function uses "dataIndex" instead of "index" causing issues with checkbox selection when the table is sorted. Current solution:

``` 
      onRowsSelect: (rowsSelected, allRows) => {
        console.log(rowsSelected, allRows);
        this.setState({ rowsSelected: allRows.map(row => row.dataIndex) });
      },
```

Fixed solution:

``` 
      onRowsSelect: (rowsSelected, allRows) => {
        console.log(rowsSelected, allRows);
        this.setState({ rowsSelected: allRows.map(row => row.index) });
      },
```

## Expected Behavior
Clicking a row should select that row

## Current Behavior
Click a row select a different row due to "dataIndex" and "index" mismatch.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.3.2   |
| MUI-datatables  |    2.8.1     |
| React        |    16.9.0      |

**Comment by gabrielliwerant** [comment]
Hm, not sure I understand. `dataIndex` was the intention, as this index does not change with sorting, meaning that the same data will be selected before and after.

**Comment by Yakitrak** [comment]
I see, sorry about the issue in that case. For me, the way I was keeping track of state, my method worked but the example didn't. I ended up removing mine in the end anyway. I'll close the issue now. Thanks for the great library (especially how customizable it is).
