### ISSUE TITLE
Styling after preventing sort action with `sort: false` in a column fails in 2.11.1

### ISSUE THREAD

**Issue by apercas** [gregnb/mui-datatables#935]
Unless the definition of a non sortable column has changed, when the column is provided with that option as false, it keeps displaying the name in the column header as clickable. Before this, providing said option didn't allow the user to click the column.

Hope this is an easy fix! Other than this 2.11.1 works like a charm! Thank for taking care of the old bugs, awesome work!

## Expected Behavior

Columns to follow the sorting true / false option as they did before, as non clickable text.
## Current Behavior
When a column is provided with the options `sort: false` the table still displays that column name as clickable. I'm guessing it shouldn't apply the CSS class with the `cursor: pointer` in it.

## Steps to Reproduce (for bugs)

1. Define a column object
2. Add an `options` object to it
3. Declare the attribute `sort` as `false` inside the object (as in https://github.com/gregnb/mui-datatables#usage)

```
{
  name: "city",
  label: "City",
  options: {
   filter: true,
   sort: false,
  }
},
```

## Your Environment
Chrome 76, MUI-datatables 2.11.1

**Comment by gabrielliwerant** [comment]
Thanks @apercas! However, this issue looks like a duplicate of https://github.com/gregnb/mui-datatables/pull/910, so marking it as such. Feel free to stay tuned on the PR for progress.

**Comment by apercas** [comment]
Ha, totally. I'm sorry I didn't see that. Closing this!
