### ISSUE TITLE
sorting issue in latest version

### ISSUE THREAD

**Issue by ketankanhasoft** [gregnb/mui-datatables#938]
Same issue again in latest version, Repeating same state again and again on click of column for sorting
https://github.com/gregnb/mui-datatables/issues/244

Here is sendbox link:
https://codesandbox.io/s/muidatatables-custom-toolbar-epfh8

Thanks

**Comment by gabrielliwerant** [comment]
See my comment in the old issue. I don't think this is a table problem.

**Comment by gabrielliwerant** [comment]
Should now be fixable via `sortDirection` in `2.12.0`.
