### ISSUE TITLE
Wrong page number when total count of items equils selected RowsPerPage value

### ISSUE THREAD

**Issue by MaksimKoniukhov** [gregnb/mui-datatables#942]
Hi, I'm backend developer, but work with frontend and I could be wrong. I'm using MUI-datatables and have issue. There is a function "changeRowsPerPage" in your code. When I have total count of items equils selected RowsPerPage value this function return wrong page number.

## Expected Behavior
When total count of items equils selected RowsPerPage value should return page number 0. Maybe to use: 
`const nextTotalPages = rowCount === rows ? 0 : Math.floor(rowCount / rows);`

## Current Behavior
When total count of items equils selected RowsPerPage value return page number 1.
Used: 
`const nextTotalPages = Math.floor(rowCount / rows);`

## Steps to Reproduce (for bugs)

1. You have 7 total items and rowsPerPageOptions: [3, 6, 7, 8]
2. First selected 3 rows per page. You click on last page (page - 2)
3. a) If after 2 step you select 6 rows per page all good (return page 1)
    b) If after 2 step you select 8 rows per page all good (return page 0)
    c) If after 2 step you select 7 rows per page you'll get 8-7 of 7 (return page 1, but must be page 0)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |   4.3.1     |
| MUI-datatables  |    2.10.1     |
| React        |    16.8.6     |

P.S. Sorry for my English

**Comment by gabrielliwerant** [comment]
I don't think I have enough information to reproduce this problem, as everything looks fine on my end:

![capture](https://user-images.githubusercontent.com/1779564/65275139-fe9aa800-daf2-11e9-9c95-0f7556b5b6df.gif)

However, I am not using material v4, as it is not yet supported by this library, as it has many breaking changes. Do you still see the issue if you reduce material versions? Or am I missing something?

**Comment by MaksimKoniukhov** [comment]
@gabrielliwerant Thanks for your reply! Really, when I reduce material-ui version to 3.9.3 all work fine. When I come back to version 4.3... or 4.4... this issue appears. How can I to use material-ui version 4 and avoid this issue? I found solution this problem is to use CustomFooter like here [https://github.com/gregnb/mui-datatables/blob/master/examples/customize-footer/index.js](https://github.com/gregnb/mui-datatables/blob/master/examples/customize-footer/index.js). In this case all work fine. But maybe there's a way not to use custom footer? Thanks

**Comment by gabrielliwerant** [comment]
@MaksimKoniukhov This library is striving to support v4 of material ui, so I added a fix for the next release. Please continue to open any issues with updating versions!

**Comment by MaksimKoniukhov** [comment]
@gabrielliwerant Ok. I'll be there. I'm happy to help you)
