### ISSUE TITLE
Is it possible to use inline update & create?

### ISSUE THREAD

**Issue by csyan5** [gregnb/mui-datatables#945]
Hi there,

I found this package extremely useful for viewing list of data with great flexibility. Thank for all your efforts!

But I do have a question about creating & updating a row. The material-table (https://material-table.com/#/docs/features/editable) has the feature of creating and updating rows in line. I'd like to know does mui-datatables offer similar function?

Thank you,
Changsheng

**Comment by gabrielliwerant** [comment]
Not out of the box, but you can create this for yourself by using columns with edit buttons and `customBodyRender` with input fields that switch on and off depending on whether or not you're pressing it.
