### ISSUE TITLE
Nested arrays in custom headers

### ISSUE THREAD

**Issue by MathiasTC** [gregnb/mui-datatables#946]
First of all hello there, and thank you for this wonderful project.
I want to access nested data in a nested array. I have like 30 custom headers in a separate file, where all of the headers work perfectly except 2. These two headers gets their value one more level down, than the other headers. 

An example could be this:
```
--------- THIS WORKS -------------
{
    name: 'value.fields.system.name',
    label: System,
    options: {
         filter: true,
         sort: true,
     }
}

------- THIS DOES NOT WORK --------
{
    name: 'value.fields.system.applications[0].name',
    label: 'App Types',
    options: {
         filter: true,
         sort: true,
     }
}
```
I dont know if there is any way I can loop over these or similar?
All I need is this array to be joined, so for example I have applications[0].name joined with the rest applications[rest].name.

Once again thank you for this great repo! It really solves a lot of problems and frustrations. :-)

## Your Environment
 

VS Code
TypeScript
Parcel

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.4.2    |
| MUI-datatables  |    2.11.1     |
| React        |    16.9.0     |
| React-DOM |    16.9.0       |
| browser      |    Chrome     |
| etc          |         |

**Comment by gabrielliwerant** [comment]
On behalf of the community, thank you, and you're welcome!

The table doesn't have any way to combine objects into arrays for you as it builds the table. This is something you would need to do with your data before you pass it in, using something like `reduce` to get the structure that you want. Also, be aware that array data is not well supported for cell individual cell contents. You may need to also use `customBodyRender` to get the kind of display you're looking for.

**Comment by MathiasTC** [comment]
Hi @gabrielliwerant,

Thank you for your response. That was also what I thought could be the case, but great to get it confirmed. I will look into the customBodyRender, as there are loads of individual and complex data being inserted into the table. However if it isn't well supported, I would like to say that it is only 'really' nested data that isn't showing correct for me, otherwise the Datatable handles the data quite good actually.

I will hereby close this issue. :-)
