### ISSUE TITLE
Double click on rows

### ISSUE THREAD

**Issue by crudnick** [gregnb/mui-datatables#950]
I'd like to get a double click event on rows, as i want . to edit the content then in a separate overlay or page. Is this somehow possible? So far i couldn't find anything about that

Thanks a lot

**Comment by gabrielliwerant** [comment]
There are lots of ways to do this aside from double click, just fyi. I've done this on a project before where just clicking on the row opens up an edit modal.

At this point, I'm not in favor of adding a double click event in the primary options as this is non-standard web UX, especially for material ui, on which this library is built (hence, I'd like not to stray too far from material recommendations). However, if you are intent on adding double click events, you can add them yourself in various ways, like by providing your own components for cells using either `customRowRender` or `customBodyRender`.

**Comment by patorjk** [comment]
Just to chime in with another way of adding double click events - you can take advantage of the setRowProps option and add them that way:

    const options = {
      responsive: "scroll",
      setRowProps: () => ({
        onDoubleClick: (row, dataIndex) => {
          alert("double click!");
        }
      })
    };

Ex: https://codesandbox.io/s/muidatatables-custom-toolbar-tyb2w

**Comment by crudnick** [comment]
Thank you vary much, this was the missing piece :)


On 22. September 2019 at 05:04:50, patorjk (notifications@github.com) wrote:

Just to chime in with another way of adding double click events - you can
take advantage of the setRowProps option and add them that way:

const options = {
  responsive: "scroll",
  setRowProps: () => ({
    onDoubleClick: (row, dataIndex) => {
      alert("double click!");
    }
  })
};

Ex: https://codesandbox.io/s/muidatatables-custom-toolbar-tyb2w

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gregnb/mui-datatables/issues/950?email_source=notifications&email_token=AANQN6R6HBBZTFQGCZLL3NDQK3OFFA5CNFSM4IY6BBK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7I5NUA#issuecomment-533845712>,
or mute the thread

**Comment by crudnick** [comment]
> Just to chime in with another way of adding double click events - you can take advantage of the setRowProps option and add them that way:
> 
> ```
> const options = {
>   responsive: "scroll",
>   setRowProps: () => ({
>     onDoubleClick: (row, dataIndex) => {
>       alert("double click!");
>     }
>   })
> };
> ```
> 
> Ex: https://codesandbox.io/s/muidatatables-custom-toolbar-tyb2w

Hi, i implemented it exactly the same way, but the dataIndex in 'Undefined'. Also 'row' equals the actual event. I'm sure there is a sulution or i did something wrong. Please help me again ;)

Best,
Christian

**Comment by patorjk** [comment]
Sorry about that, it’s the setRowProps method that takes those parameters. So adding them there and then removing them from the double click method should fix it.

**Comment by crudnick** [comment]
Yes, that was the solution. Thanks a lot for the quick response


On 28. September 2019 at 15:32:09, patorjk (notifications@github.com) wrote:

Sorry about that, it’s the setRowProps method that takes those parameters.
So adding them there and then removing them from the double click method
should fix it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gregnb/mui-datatables/issues/950?email_source=notifications&email_token=AANQN6QQN2Y5C6V4OKBEOK3QL5MFTA5CNFSM4IY6BBK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD72Z3PY#issuecomment-536190399>,
or mute the thread

**Comment by ruthwe** [comment]
> Sorry about that, it’s the setRowProps method that takes those parameters. So adding them there and then removing them from the double click method should fix it.

can you give an example for this please?

**Comment by patorjk** [comment]
@ruthwe in my example above just move the row and dataIndex parameters from onDoubleClick to setRowProps.

**Comment by ibarapascal** [comment]
By now it seems `setRowProps` is removed and `setCellProps` would work

```tsx
setCellProps: (item: any, idx: number) => ({
      onDoubleClick: () => {
        alert(data[idx]);
      }
    });
```

Refer to 

> node_modules/@types/mui-datatables/index.d.ts

MUIDataTableColumnOptions
```ts
setCellProps?: (cellValue: string, rowIndex: number, columnIndex: number) => object;
```

**Comment by kayoch1n** [comment]
The `setRowProps` still works for me on `"mui-datatables": "^2.6.4"`

**Comment by acroyear** [comment]
setRowProps is still there in the 3.x.  also, it returns the dataIndex (the row info is the raw cell react component, which isn't terribly useful) which may be better than setCellProps which returns the rowIndex, as that might be after sorting and you'll need the table metadata from somewhere to translate to the real index.

**Comment by buster95** [comment]
I solved this in a different way, I will left my code here just in case someone else tries to do this
```javascript
setRowProps: (row, dataIndex) => ({
  onDoubleClick: (evt) => {
    alert("Double click!");
  }
}),
```

**Comment by avichovatiya67** [comment]
> > Just to chime in with another way of adding double click events - you can take advantage of the setRowProps option and add them that way:
> > ```
> > const options = {
> >   responsive: "scroll",
> >   setRowProps: () => ({
> >     onDoubleClick: (row, dataIndex) => {
> >       alert("double click!");
> >     }
> >   })
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ex: https://codesandbox.io/s/muidatatables-custom-toolbar-tyb2w
> 
> Hi, i implemented it exactly the same way, but the dataIndex in 'Undefined'. Also 'row' equals the actual event. I'm sure there is a sulution or i did something wrong. Please help me again ;)
> 
> Best, Christian

You should try this
`setRowProps: (rowData, rowIndex) => ({
            onDoubleClick: () => {
              console.log(rowIndex, rowData);
            }
          })`
