### ISSUE TITLE
Localization not working in customFooter() function

### ISSUE THREAD

**Issue by janakprajapati** [gregnb/mui-datatables#959]
I am using the customFooter function in the Options. I have also defined the textLabels in the Options. I noticed that, the localization works in other parts of the data-table except the labels in the customFooter() where Pagination component is defined. I am not sure how to apply the textLabels for the Pagination component which is part of the customFooter(), to apply localization for the "Rows per page" text.

Here is my code sample for the Options section:

```
const options = {
      rowsPerPage: 20,
      responsive: "scroll",
      selectableRows: "none",
      print: false,
      customFooter: (
        count,
        page,
        rowsPerPage,
        changeRowsPerPage,
        changePage
      ) => {
        return (
          <TableFooter>
            <TableRow>
                // some code for extra row
            </TableRow>
            <TableRow>
              <TablePagination
                count={count}
                rowsPerPage={rowsPerPage}
                page={page}
                onChangePage={(_, page) => changePage(page)}
                onChangeRowsPerPage={event =>
                  changeRowsPerPage(event.target.value)
                }
                rowsPerPageOptions={[20, 50, 100]}
              />
            </TableRow>
          </TableFooter>
        );
      },
      textLabels: {
        body: {
          noMatch: t("Sorry, no matching records found"),
          toolTip: t("Sort"),
          columnHeaderTooltip: column => `Sort for ${column.label}`
        },
        pagination: {
          next: t("Next Page"),
          previous: t("Previous Page"),
          rowsPerPage: `${t("Rows per page")}:`,
          displayRows: "of"
        },
        toolbar: {
          search: t("Search"),
          downloadCsv: t("Download CSV"),
          print: "Print",
          viewColumns: t("View Columns"),
          filterTable: t("Filter Table")
        },
        filter: {
          all: t("All"),
          title: t("FILTERS"),
          reset: t("RESET")
        },
        viewColumns: {
          title: t("Show Columns"),
          titleAria: t("Show/Hide Table Columns")
        },
        selectedRows: {
          text: t("row(s) selected"),
          delete: t("Delete"),
          deleteAria: t("Delete Selected Rows")
        }
      }
    };
```

**Comment by gabrielliwerant** [comment]
The localization options for the `customFooter` is the last argument, after `changePage`. So you need

```
customFooter: (
  count,
  page,
  rowsPerPage,
  changeRowsPerPage,
  changePage,
  paginationLocalization
) => {}
```

**Comment by janakprajapati** [comment]
@gabrielliwerant Thanks for the quick reply. 

However, can you please tell me what I need to pass as "paginationLocalization" considering my sample above? I checked by passing the same textLabels object paginationLocalization but, it is not working.

Thanks

**Comment by janakprajapati** [comment]
> The localization options for the `customFooter` is the last argument, after `changePage`. So you need
> 
> ```
> customFooter: (
>   count,
>   page,
>   rowsPerPage,
>   changeRowsPerPage,
>   changePage,
>   paginationLocalization
> ) => {}
> ```

@gabrielliwerant Thanks for the quick reply.

However, can you please tell me what I need to pass as "paginationLocalization" considering my sample above? I checked by passing the same textLabels object as paginationLocalization but, it is not working.

Thanks

**Comment by gabrielliwerant** [comment]
Whatever you put in `textLabels: { pagination }` will be in that argument. You just declare it and it's there for use in your custom footer however you want.

**Comment by janakprajapati** [comment]
> Whatever you put in `textLabels: { pagination }` will be in that argument. You just declare it and it's there for use in your custom footer however you want. Have a look at and play around with `customize-footer` in the examples for more information.
> 
> (psuedocode):
> 
> ```
> const options = {
>   textLabels: { pagination: { rowsPerPage: "foo", ... } ... },
>   customFooter: (
>     count,
>     page,
>     rowsPerPage,
>     changeRowsPerPage,
>     changePage,
>     paginationLocalization
>   ) => <TablePagination labelRowsPerPage={paginationLocalization.rowsPerPage} ... />
> };
> ```

@gabrielliwerant That worked. Thanks.
