### ISSUE TITLE
customization on the column's head

### ISSUE THREAD

**Issue by chiran-subedi** [gregnb/mui-datatables#96]
Firstly i'd like to thank-you for this awesome project.
I want to add code snippet beside the column name and sort icon (for eg. div tag) at thead>tr>th. How can i add this piece of code in each of the column's head ? 
The image attached herewith describes more..

<img width="953" alt="screen shot 2018-07-10 at 9 12 51 pm" src="https://user-images.githubusercontent.com/4115132/42526424-7eb7fe08-8495-11e8-8373-3677cf41e040.png">

Thankyou in advance. :)

**Comment by gregnb** [comment]
Ok I just published `2.0.0-beta-18` this will allow you to overwrite the column header and render whatever you like. I put some information in the README

**Comment by chiran-subedi** [comment]
Hey @gregnb,
Thankyou so much for the update. This looks awesome. 👍 
Can you please add an example for customHeadRender like its there for the customBodyRender?
