### ISSUE TITLE
Filter Popover goes away when filtering on server side

### ISSUE THREAD

**Issue by Avd6977** [gregnb/mui-datatables#961]
## Expected Behavior
Filter popover stays open until the user is done filtering.

## Current Behavior
When filtering on client side, the filter popover stays open until the user is done filtering. When filtering server side, the table re-renders because new data, but that hides the filter window.

## Steps to Reproduce (for bugs)
Only reproducible on server side

1. Must be server side
2. Pass in data
3. Filter data to a smaller subset
4. See the filter popover goes away

## Your Environment

| Tech         | Version |
|--------------|---------|
| MUI-datatables  |    2.11.1     |

**Comment by gabrielliwerant** [comment]
There is work already being done to add options to serverside filtering, so marking this as duplicate. You can see this issue https://github.com/gregnb/mui-datatables/issues/857 or this PR https://github.com/gregnb/mui-datatables/pull/913 for more information.

**Comment by Avd6977** [comment]
Thanks! I saw that and am looking forward to it. Looking through the code for the PR, how would we tell the filter to stay open?

**Comment by gabrielliwerant** [comment]
The filter dialog? It won't close until the user clicks outside of it, like normal. In the example in the PR, there is a demonstration adding a button to the filter dialog to set the filters outside of the usual client side process. Then it's closed as usual by clicking outside of it. Direct control over closing won't be available in that PR as it's a lot more work, but possibly in the future. However, the PR should provide enough to make server side filters more serviceable.

**Comment by Avd6977** [comment]
Currently, the filter dialog closes when new rows get passed in from the server side. That's why I was making the issue of being able to have it open on load or some better way of controlling when it was closed because it's not just when the user clicks outside of it.

**Comment by gabrielliwerant** [comment]
I haven't written a serverside example outside of that PR, but in that PR, the dialog does not close when changing the table data, so I don't think that will be an issue.

**Comment by gabrielliwerant** [comment]
@Avd6977 Let me know if you still have this issue in `2.12.0`.

**Comment by Avd6977** [comment]
Nope, issue is resolved and the function is working. Thanks!
