### ISSUE TITLE
Using download option useDisplayedRowsOnly is causing issues with non-react objects like arrays

### ISSUE THREAD

**Issue by gabrielliwerant** [gregnb/mui-datatables#963]
Originally brought up here https://github.com/gregnb/mui-datatables/issues/709#issuecomment-535637754

**Comment by GuyShaanan** [comment]
Thanks.
I think I could sort it out by setting `dataIndex: index` in https://github.com/gregnb/mui-datatables/blob/f0ea9e58d82839c57a4dfd4a342b6649932660a7/src/MUIDataTable.js#L791
Some tests failed but I think they need to be changed as well.
(Not sure what are the side effects of this, but from skimming the examples they all seem to work fine).

**Comment by gabrielliwerant** [comment]
I've got a PR open that closes the issue (linked here) so I don't think we need to worry about potentially breaking tests with a different fix.
