### ISSUE TITLE
Improve accessbility

### ISSUE THREAD

**Issue by michalica** [gregnb/mui-datatables#969]
Allow user to "tab" among rows and allow him to open and close expandable row with Space or enter 

## Expected Behavior
    We should allow user tabbing among rows.
    We should wrap SVG icon which opens expandable row with HTML element button:
`<button><svg></svg></button>
`
## Current Behavior
It in not wrapped -> tabbing doesnt work.

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.0.1    |
| MUI-datatables  |     2.1.2    |
| React        |    latest      |
| browser      |    all     |

**Comment by gabrielliwerant** [comment]
Available in `2.12.0`!
