### ISSUE TITLE
Expandable rows do not expand full width

### ISSUE THREAD

**Issue by danipralea** [gregnb/mui-datatables#976]
First of all I want to thank you for the amazing library. I can tell that there's been so much work put into it.
I'm guessing maybe I'm missing anything?

## Expected Behavior
The `renderExpandableRow` rendering should go full width

## Current Behavior
The `renderExpandableRow` method expands only for the expand icon's width
<img width="1372" alt="Screenshot 2019-10-03 09 51 54" src="https://user-images.githubusercontent.com/768893/66105188-707af300-e5c3-11e9-908a-fc17615814d8.png">

## Steps to Reproduce (for bugs)
```renderExpandableRow: () => <div style={{backgroundColor: 'red', height: '200px', width: '100%'}}></div>```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |      4.3.2   |
| MUI-datatables  |    2.10.3     |
| React        |    16.10.1     |
| browser      |    Chrome 77.0.3865.90     |

**Comment by PovilasSlekys** [comment]
You might find this helpful https://github.com/gregnb/mui-datatables/issues/735

**Comment by danipralea** [comment]
@PovilasSlekys thank you so much. you are amazing!
