### ISSUE TITLE
selecting half of rows indicates full selection

### ISSUE THREAD

**Issue by danipralea** [gregnb/mui-datatables#979]
## Expected Behavior
The check box in the header toggles to selected should be marked as checked only when all the rows have been selected.

## Current Behavior

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/768893/66131955-f5363300-e5fc-11e9-841a-4e7bb2df0f6b.gif)

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |      4.3.2   |
| MUI-datatables  |    2.10.3     |
| React        |    16.10.1     |
| browser      |    Chrome 77.0.3865.90     |

**Comment by gabrielliwerant** [comment]
I can't reproduce this in `2.12.0` with material-ui v3. Can you confirm this by raising your mui-datatables version and lowering your material-ui version (separately to determine which, if any, is causing the problem for you).

![capture](https://user-images.githubusercontent.com/1779564/66153364-581dcf00-e5e9-11e9-8eed-e9b2a1c1e5f9.gif)

**Comment by danipralea** [comment]
@gabrielliwerant thank you for your reply. My `mui-datatables` version is already `2.12.0`. I'm going to try lowering the material-ui version. Can you point me to your specific version?

**Comment by gabrielliwerant** [comment]
Glad it works for you!

mui v4 has a lot of breaking changes and there are still a lot of sore spots in this library around it, so if you are able to track any issues pertaining to your material version, it would be great if you could open those with steps.
