### ISSUE TITLE
filter or search issue

### ISSUE THREAD

**Issue by eramax** [gregnb/mui-datatables#98]
when there isn't a matched value from filter or search the table disappears.

## Steps to Reproduce (for bugs)
<!---
search with any value not matched with the table contents.

**Comment by apercas** [comment]
I'm having the same issue, thought it was my code but I saw it's happening on the demo as well https://codesandbox.io/s/wy2rl1nyzl

**Comment by gregnb** [comment]
Upgrade to the latest version just put out a fix

**Comment by apercas** [comment]
Great! Thanks, is it already on NPM?

**Comment by gregnb** [comment]
Yep!

**Comment by eramax** [comment]
I checked but it is still not fixed 
I used 
`    "mui-datatables": "latest",
`
you can check this link https://codesandbox.io/s/0p3k65qx9v

Regards

**Comment by gregnb** [comment]
Try -16 just published

**Comment by gregnb** [comment]
did that help @eramax  ?

**Comment by eramax** [comment]
Yes thanks so much for your help.

Regards
