### ISSUE TITLE
problemin with table size using scrollFullHeight option

### ISSUE THREAD

**Issue by laurexas** [gregnb/mui-datatables#980]
In mui datatable supposed to fit all columns

If i use responsive option with scrollFullheight value, my table's width depends on screen width but not by columns  length and in that case where i have more columns and scroll to right appears but  table columns goes beyond table borders in x-axis.. any ideas why this may be happening? 

## Steps to Reproduce (for bugs)
I tried to replicate bug in codesandbox , but unsuccessfully, bug happens only in my table with columns that requires scroll to right

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |         |
| MUI-datatables  |         |
| React        |         |
| browser      |         |
| etc          |         |

**Comment by gabrielliwerant** [comment]
Unfortunately, if I can't reproduce the issue, then I won't be able to solve it, and it's possible this is something related to your code and not the library. Everything looks good on my end. Without being able to reproduce it, I'll have to close the issue, and there are too many un-reproducible issues to keep track of easily.

![capture](https://user-images.githubusercontent.com/1779564/66154332-3291c500-e5eb-11e9-9c76-9a446eb3028f.gif)

**Comment by laurexas** [comment]
maybe it have something with my page layout, for now i'll stick with 'stacked' functionality, thanks for quick response.
