### ISSUE TITLE
i need helo guys how can do column count

### ISSUE THREAD

**Issue by zilkenberg22** [gregnb/mui-datatables#988]
![43293418-2d86659a-9108-11e8-886e-36a89f59a62e](https://user-images.githubusercontent.com/33345651/66379001-32c50280-e9e7-11e9-9bc0-f81f0e96654f.png)

like that i need example ty
`

**Comment by wdh2100** [comment]
https://github.com/gregnb/mui-datatables/blob/master/examples/customize-footer/index.js

**Comment by zilkenberg22** [comment]
@wdh2100 how do count age column ?

**Comment by wdh2100** [comment]
https://jsfiddle.net/akvnbs2u/19/

did u mean this?

**Comment by zilkenberg22** [comment]
@wdh2100 no age column all rows total count

**Comment by gabrielliwerant** [comment]
`customFooter` is the closest you can get to this behavior at this time. Data tables don't really function like spread sheets, in that they're not designed to total columns. When you pass in data, it's expected that all of it can be treated the same way, i.e. they will all be affected by sorting, filtering, searching, pagination, etc. So there is no special consideration given to a "final" row.

Another approach you might take to hack this together is to have a separate table, stripped of everything but one row which tallies from your data in the other, and then put them right up against each other in the DOM. I'm pretty sure you could get that to look and work the way you want, but it might require quite a bit of work.
