### ISSUE TITLE
Add tabs on row click in muidatatable

### ISSUE THREAD

**Issue by PratyushaTN** [gregnb/mui-datatables#993]
is it possible to open the row related data as a new tab with the table?

## Expected Behavior
On clicking a row in MUIDatatable using React I would like to display the content related to the row in a tab(within the same page and not another chrome/IE tab) or as a table within this row.

## Current Behavior
I have implemented a functionality where on rowClick I am navigating to another view and displaying the row related details there in another table.

   

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |    0.20.2     |
| MUI-datatables  |     2.0.0-beta.58    |
| React        |    16.8.2     |
| browser      |         |
| etc          |         |

**Comment by gabrielliwerant** [comment]
If you've found a successful approach, please add it here so others can benefit from your solutions!
