### ISSUE TITLE
Current page doesn't reset when data changes

### ISSUE THREAD

**Issue by jlucier** [gregnb/mui-datatables#994]
When you're on say page 3 of some current data, and the data then changes (most importantly changes size) the current page doesn't reset. This is especially a problem for times when your data shrinks by a lot, because it seems like the data is now gone until you page backwards. This is a bug that seems to be related to how Material UI v4 handles paging because it only appeared when I upped my `@material-ui/core` dependency >= 4.0.0. I checked and there is no issue with `@material-ui/core`==3.9.3. 

-- Edit: here is the relevant [MUI doc](https://material-ui.com/guides/migration-v3/#table) that explains why this appears.

If support for MUI v4 isn't targeted until future releases, so be it I suppose, but I'll put this out there.

## Expected Behavior

What should happen, I think, is whenever the data changes, the current page is reset (which I verified occurs when you switch `@material-ui/core` to 3.9.3 and use my same sandbox below, [live one](https://codesandbox.io/s/mui-datatables-page-bug-98j01)).

## Current Behavior

The current page doesn't reset when data changes.

## Steps to Reproduce
1. See simple example: [playground](https://codesandbox.io/embed/mui-datatables-page-bug-9upfc)
2. Page past the initial page with the page arrow.
3. Click "Change Data" in the top right, this will shorten the list of data.
4. Observe that you are not reset to the initial page, but if you page back you can now see the shrunken list.
5. Click change data again to reset to the original and repeat if desired.

Here's the playground environment: (had to up React version to comply with MUI)

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.0.0     |
| MUI-datatables  |    2.12.0     |
| React        |    16.9.0     |
| browser      |    Chrome     |

My environment where I discovered it:

| Tech         | Version |
|--------------|---------|
| Material-UI  |    4.4.1     |
| MUI-datatables  |    >=2.10.2     |
| React        |    16.9.0     |
| browser      |    Chrome     |

**Comment by gabrielliwerant** [comment]
Thank you @jlucier for reporting this and for the information in reproducing it. I can tie it to the material-ui version and the change made by material-ui. I'll be adding a fix to https://github.com/gregnb/mui-datatables/pull/948 as it solves the same issue, only in a different use of the library. So a more general fix is needed.

It is the goal to support material-ui v4, but it requires fixing issues just like these, so your help is greatly appreciated.

**Comment by jlucier** [comment]
Verified the fix in 2.12.1, excellent! Thanks!

Possibly worth discussion: I don't know if this is intended behavior, nor do I think I have strong opinions on the whether it should or should not be this way, but now when you revert back to the original data the page goes back to the page you were on before the data change occurred. Make sense? You can bump the version in the sandboxes linked above and check it out.

I gather this is a detail of the implementation (clipping the currentPage as it's passed into the MUI layer rather than storing a clipped value), but I figured I'd let the posterity know this is a thing.

**Comment by jlucier** [comment]
Something wasn't sitting right so I did more digging, sadly the plot thickens.

New [sandbox](https://codesandbox.io/s/mui-datatables-page-bug-0y638).

The values of `data.length` and `rowsPerPage` seem to determine different behavior. I thought all was fixed because when the data changes such that `data.length <= rowsPerPage`, to the observer it looks like it resets the page to 0.

However, the following can be observed by playing with the number on line 14 of the new sandbox to change what the modified `data` array's length will be:
1. `data.length > rowsPerPage` -> the component will switch to the largest valid page, not the first page or something. Arguably not a bug, but a feature.
2. `data.length === N * rowsPerPage` where `N > 1`, and `N` is an integer -> the bug will reappear, no records shown because the page passed to MUI is out of bounds.

I hope this is helpful. Still very grateful for the fix as it stands!

**Comment by patorjk** [comment]
I ran into the same issue today. In one of my tables I have a button that manually adds a filter to the table. I noticed when I was one the second page of the table and pushed the button I got the weird empty table message.

I believe this issue to due to how totalPages is calculated in the getPageValue function [1]:

```
function getPageValue(count, rowsPerPage, page) {
  const totalPages = count === rowsPerPage ? 0 : Math.floor(count / rowsPerPage);

  return page > totalPages ? totalPages : page;
}
```

If you have 30 items, and 10 rows per page, that function will tell you that you should be on page 3 (the 4th page since it's 0-indexed). But you should really be on page 2 (the 3rd page). I think the calculation is wrong, I think it should be this:

`  const totalPages = count <= rowsPerPage ? 0 : Math.floor( (count-1) / rowsPerPage);`

Making that change seems to fix the problem for me.

[1] https://github.com/gregnb/mui-datatables/blob/master/src/utils.js#L9

**Comment by gabrielliwerant** [comment]
Nice catch @patorjk, `totalPages` is 1-indexed and page is 0-indexed, and I'm not accounting for that. Will fix.
